var anyList = [
	{
		1: {
			word: 'natis',
			full: 'natus, nati, m',
			translation: 'son',
			type: 'datp',
		},
		2: {
			word: 'agnis',
			full: 'agnus, agni, m',
			translation: 'lamb',
			type: 'datp',
		},
		3: {
			word: 'letis',
			full: 'letum, leti, n',
			translation: 'death',
			type: 'datp',
		},
		4: {
			word: 'lupis',
			full: 'lupus, lupi, m',
			translation: 'wolf',
			type: 'datp',
		},
		5: {
			word: 'toris',
			full: 'torus, tori, m',
			translation: 'bed, couch, marriage',
			type: 'datp',
		},
		6: {
			word: 'fatis',
			full: 'fatum, fati, n',
			translation: 'fate',
			type: 'datp',
		},
		7: {
			word: 'arvis',
			full: 'arvum, arvi , n',
			translation: 'field, land',
			type: 'datp',
		},
		8: {
			word: 'rivis',
			full: 'rivus, rivi, m',
			translation: 'stream',
			type: 'datp',
		},
		9: {
			word: 'divis',
			full: 'divus, divi, m',
			translation: 'god',
			type: 'datp',
		},
		10: {
			word: 'iugis',
			full: 'iugum, iugi, n',
			translation: 'yoke, mountain ridge',
			type: 'datp',
		},
		11: {
			word: 'polis',
			full: 'polus, poli, m',
			translation: 'pole, sky, heaven',
			type: 'datp',
		},
		12: {
			word: 'votis',
			full: 'votum, voti, n',
			translation: 'vow, prayer, hope',
			type: 'datp',
		},
		13: {
			word: 'feris',
			full: 'fera, ferae, f',
			translation: 'wild beast',
			type: 'datp',
		},
		14: {
			word: 'rogis',
			full: 'rogus, rogi, m',
			translation: 'funeral pyre, pyre',
			type: 'datp',
		},
		15: {
			word: 'casis',
			full: 'casa, casae, f',
			translation: 'hut, cottage',
			type: 'datp',
		},
		16: {
			word: 'lucis',
			full: 'lucus, luci, m',
			translation: 'wood, grove',
			type: 'datp',
		},
		17: {
			word: 'meris',
			full: 'merum, meri, n',
			translation: 'wine',
			type: 'datp',
		},
		18: {
			word: 'remis',
			full: 'remus, remi, m',
			translation: 'oar',
			type: 'datp',
		},
		19: {
			word: 'rosis',
			full: 'rosa, rosae, f',
			translation: 'rose',
			type: 'datp',
		},
		20: {
			word: 'noxis',
			full: 'noxa, noxae, f',
			translation: 'harm, injury',
			type: 'datp',
		},
		21: {
			word: 'odiis',
			full: 'odium, odii, n',
			translation: 'hatred',
			type: 'datp',
		},
		22: {
			word: 'minis',
			full: 'mina, minae, f',
			translation: 'threat',
			type: 'datp',
		},
		23: {
			word: 'fanis',
			full: 'fanum, fani, n',
			translation: 'temple, shrine',
			type: 'datp',
		},
		24: {
			word: 'tubis',
			full: 'tuba, tubae, f',
			translation: 'trumpet',
			type: 'datp',
		},
		25: {
			word: 'aevis',
			full: 'aevum, aevi, n',
			translation: 'time, life, age',
			type: 'datp',
		},
		26: {
			word: 'togis',
			full: 'toga, togae, f',
			translation: 'toga',
			type: 'datp',
		},
		27: {
			word: 'velis',
			full: 'velum, veli, n',
			translation: 'sail',
			type: 'datp',
		},
		28: {
			word: 'omina',
			full: 'omen, ominis, n',
			translation: 'sign, omen',
			type: 'nomp',
		},
		29: {
			word: 'rotis',
			full: 'rota, rotae, f',
			translation: 'wheel, chariot',
			type: 'datp',
		},
		30: {
			word: 'astro',
			full: 'astrum, astri, n',
			translation: 'star, constellation',
			type: 'dats',
		},
		31: {
			word: 'dicto',
			full: 'dictum, dicti, n',
			translation: 'word',
			type: 'dats',
		},
		32: {
			word: 'freto',
			full: 'fretum, freti, n',
			translation: 'strait, sea',
			type: 'dats',
		},
		33: {
			word: 'lecto',
			full: 'lectus, lecti, m',
			translation: 'bed, couch',
			type: 'dats',
		},
		34: {
			word: 'penna',
			full: 'penna, pennae, f',
			translation: 'feather, (pl.) wing',
			type: 'vocs',
		},
		35: {
			word: 'puppe',
			full: 'puppis, puppis, f',
			translation: 'stern, ship',
			type: 'abls',
		},
		36: {
			word: 'tauro',
			full: 'taurus, tauri, m',
			translation: 'bull',
			type: 'dats',
		},
		37: {
			word: 'crine',
			full: 'crinis, crinis, m',
			translation: 'hair',
			type: 'abls',
		},
		38: {
			word: 'umero',
			full: 'umerus, umeri, m',
			translation: 'shoulder',
			type: 'dats',
		},
		39: {
			word: 'aestu',
			full: 'aestus, aestus, m',
			translation: 'heat, sea, passion',
			type: 'abls',
		},
		40: {
			word: 'prole',
			full: 'proles, prolis',
			translation: 'offspring, child, descendant, flock',
			type: 'abls',
		},
		41: {
			word: 'amica',
			full: 'amica, amicae, f',
			translation: 'girlfriend',
			type: 'vocs',
		},
		42: {
			word: 'forma',
			full: 'forma, formae, f',
			translation: 'beauty',
			type: 'vocs',
		},
		43: {
			word: 'regia',
			full: 'regia, regiae, f',
			translation: 'palace',
			type: 'vocs',
		},
		44: {
			word: 'sacro',
			full: 'sacrum, sacri, n',
			translation: 'rite, ceremony, religious rite',
			type: 'dats',
		},
		45: {
			word: 'sorte',
			full: 'sors, sortis, f',
			translation: 'lot, fortune',
			type: 'abls',
		},
		46: {
			word: 'imbre',
			full: 'imber, imbris, m',
			translation: 'rain',
			type: 'abls',
		},
		47: {
			word: 'ponto',
			full: 'pontus, ponti, m',
			translation: 'sea',
			type: 'dats',
		},
		48: {
			word: 'corde',
			full: 'cor, cordis, n',
			translation: 'heart, mind',
			type: 'abls',
		},
		49: {
			word: 'herba',
			full: 'herba, herbae, f',
			translation: 'grass, herb',
			type: 'vocs',
		},
		50: {
			word: 'ruina',
			full: 'ruina, ruinae, f',
			translation: 'ruin, destruction',
			type: 'vocs',
		},
		51: {
			word: 'fletu',
			full: 'fletus, fletus, m',
			translation: 'weeping, tears',
			type: 'abls',
		},
		52: {
			word: 'flore',
			full: 'flos, floris, m',
			translation: 'flower',
			type: 'abls',
		},
		53: {
			word: 'gemma',
			full: 'gemma, gemmae, f',
			translation: 'jewel',
			type: 'vocs',
		},
		54: {
			word: 'crure',
			full: 'crus, cruris, n',
			translation: 'leg',
			type: 'abls',
		},
		55: {
			word: 'curru',
			full: 'currus, currus, m',
			translation: 'chariot',
			type: 'abls',
		},
		56: {
			word: 'grege',
			full: 'grex, gregis, m',
			translation: 'flock, herd',
			type: 'abls',
		},
		57: {
			word: 'prora',
			full: 'prora, prorae, f',
			translation: 'prow, ship',
			type: 'vocs',
		},
		58: {
			word: 'virga',
			full: 'virga, virgae, f',
			translation: 'stick, wand',
			type: 'vocs',
		},
		59: {
			word: 'clivo',
			full: 'clivus, clivi, m',
			translation: 'slope, hill',
			type: 'dats',
		},
		60: {
			word: 'pisce',
			full: 'piscis, piscis, m',
			translation: 'fish',
			type: 'abls',
		},
		61: {
			word: 'prato',
			full: 'pratum, prati, n',
			translation: 'meadow',
			type: 'dats',
		},
		62: {
			word: 'anima',
			full: 'anima, animae, f',
			translation: 'breath, soul, life',
			type: 'vocs',
		},
		63: {
			word: 'antro',
			full: 'antrum, antri, n',
			translation: 'cave',
			type: 'dats',
		},
		64: {
			word: 'cerva',
			full: 'cerva, cervae, f',
			translation: 'deer, hind',
			type: 'vocs',
		},
		65: {
			word: 'forte',
			full: 'fors, fortis, f',
			translation: 'chance, luck, fortune',
			type: 'abls',
		},
		66: {
			word: 'sensu',
			full: 'sensus, sensus, m',
			translation: 'sense, feeling',
			type: 'abls',
		},
		67: {
			word: 'ungue',
			full: 'unguis, unguis, m',
			translation: 'nail, claw, talon',
			type: 'abls',
		},
		68: {
			word: 'vulgo',
			full: 'vulgus, vulgi, n',
			translation: 'crowd, common people',
			type: 'dats',
		},
		69: {
			word: 'copia',
			full: 'copia, copiae, f',
			translation: 'abundance, plenty, riches',
			type: 'vocs',
		},
		70: {
			word: 'facto',
			full: 'factum, facti, n',
			translation: 'deed, action',
			type: 'dats',
		},
		71: {
			word: 'gradu',
			full: 'gradus, gradus, m',
			translation: 'step, position, rank',
			type: 'abls',
		},
		72: {
			word: 'peste',
			full: 'pestis, pestis, f',
			translation: 'plague, disease',
			type: 'abls',
		},
		73: {
			word: 'turri',
			full: 'turris, turris, f',
			translation: 'tower, siege tower',
			type: 'dats',
		},
		74: {
			word: 'cornu',
			full: 'cornu, cornus, n',
			translation: 'horn, wing (of an army)',
			type: 'vocs',
		},
		75: {
			word: 'cursu',
			full: 'cursus, cursus, m',
			translation: 'course, running',
			type: 'abls',
		},
		76: {
			word: 'exitu',
			full: 'exitus, exitus, m',
			translation: 'way out, end, death',
			type: 'abls',
		},
		77: {
			word: 'statu',
			full: 'status, status, m',
			translation: 'position, state',
			type: 'abls',
		},
		78: {
			word: 'aditu',
			full: 'aditus, aditus, m',
			translation: 'entrance, approach, access',
			type: 'abls',
		},
		79: {
			word: 'collo',
			full: 'collum, colli, n',
			translation: 'neck',
			type: 'dats',
		},
		80: {
			word: 'laude',
			full: 'laus, laudis, f',
			translation: 'praise, glory',
			type: 'abls',
		},
		81: {
			word: 'anulo',
			full: 'anulus, anuli, m',
			translation: 'ring',
			type: 'dats',
		},
		82: {
			word: 'atrio',
			full: 'atrium, atrii, n',
			translation: 'hallway',
			type: 'dats',
		},
		83: {
			word: 'vallo',
			full: 'vallum, valli, n',
			translation: 'rampart',
			type: 'dats',
		},
		84: {
			word: 'curia',
			full: 'curia, curiae, f',
			translation: 'senate house',
			type: 'vocs',
		},
		85: {
			word: 'dubio',
			full: 'dubium, dubii, n',
			translation: 'doubt',
			type: 'dats',
		},
		86: {
			word: 'luctu',
			full: 'luctus, luctus, m',
			translation: 'grief',
			type: 'abls',
		},
		87: {
			word: 'arena',
			full: 'arena, arenae, f',
			translation: 'arena, sand, amphitheatre',
			type: 'vocs',
		},
		88: {
			word: 'colle',
			full: 'collis, collis, m',
			translation: 'hill',
			type: 'abls',
		},
		89: {
			word: 'fonte',
			full: 'fons, fontis, m',
			translation: 'fountain, spring',
			type: 'abls',
		},
		90: {
			word: 'tribu',
			full: 'tribus, tribus, m',
			translation: 'tribe',
			type: 'abls',
		},
		91: {
			word: 'cultu',
			full: 'cultus, cultus, m',
			translation: 'worship, culture, splendour',
			type: 'abls',
		},
		92: {
			word: 'fundo',
			full: 'fundo, fundere, fudi, fusus',
			translation: 'pour, rout, put to flight',
			type: 'pracind1s',
		},
		93: {
			word: 'ligno',
			full: 'lignum, ligni, n',
			translation: 'wood, firewood',
			type: 'dats',
		},
		94: {
			word: 'umbra',
			full: 'umbra, umbrae, f',
			translation: 'shade, shadow',
			type: 'vocs',
		},
		95: {
			word: 'damno',
			full: 'damno, damnare, damnavi, damnatus',
			translation: 'condemn',
			type: 'pracind1s',
		},
		96: {
			word: 'saltu',
			full: 'saltus, saltus, m',
			translation: 'mountain pass',
			type: 'abls',
		},
		97: {
			word: 'furto',
			full: 'furtum, furti, n',
			translation: 'theft, deception',
			type: 'dats',
		},
		98: {
			word: 'nummo',
			full: 'nummus, nummi, m',
			translation: 'coin, money',
			type: 'dats',
		},
		99: {
			word: 'venia',
			full: 'venia, veniae, f',
			translation: 'pardon, favour',
			type: 'vocs',
		},
		100: {
			word: 'victu',
			full: 'victus, victus, m',
			translation: 'food, livelihood',
			type: 'abls',
		},
		101: {
			word: 'aeres',
			full: 'aer, aeris, m',
			translation: 'air',
			type: 'vocp',
		},
		102: {
			word: 'astra',
			full: 'astrum, astri, n',
			translation: 'star, constellation',
			type: 'vocp',
		},
		103: {
			word: 'comas',
			full: 'coma, comae, f',
			translation: 'hair',
			type: 'accp',
		},
		104: {
			word: 'dicta',
			full: 'dictum, dicti, n',
			translation: 'word',
			type: 'vocp',
		},
		105: {
			word: 'enses',
			full: 'ensis, ensis, m',
			translation: 'sword',
			type: 'vocp',
		},
		106: {
			word: 'freta',
			full: 'fretum, freti, n',
			translation: 'strait, sea',
			type: 'vocp',
		},
		107: {
			word: 'natas',
			full: 'nata, natae, f',
			translation: 'daughter',
			type: 'accp',
		},
		108: {
			word: 'natos',
			full: 'natus, nati, m',
			translation: 'son',
			type: 'accp',
		},
		109: {
			word: 'nubes',
			full: 'nubes, nubis, f',
			translation: 'cloud',
			type: 'vocs',
		},
		110: {
			word: 'orbes',
			full: 'orbis, orbis',
			translation: 'sphere, world, country, eye',
			type: 'vocp',
		},
		111: {
			word: 'agnas',
			full: 'agna, agnae, f',
			translation: 'lamb',
			type: 'accp',
		},
		112: {
			word: 'agnos',
			full: 'agnus, agni, m',
			translation: 'lamb',
			type: 'accp',
		},
		113: {
			word: 'lupas',
			full: 'lupa, lupae, f',
			translation: 'she-wolf',
			type: 'accp',
		},
		114: {
			word: 'lupos',
			full: 'lupus, lupi, m',
			translation: 'wolf',
			type: 'accp',
		},
		115: {
			word: 'toros',
			full: 'torus, tori, m',
			translation: 'bed, couch, marriage',
			type: 'accp',
		},
		116: {
			word: 'arcus',
			full: 'arcus, arcus, m',
			translation: 'bow, curve',
			type: 'vocs',
		},
		117: {
			word: 'rates',
			full: 'ratis, ratis, f',
			translation: 'boat, raft',
			type: 'vocp',
		},
		118: {
			word: 'rivos',
			full: 'rivus, rivi, m',
			translation: 'stream',
			type: 'accp',
		},
		119: {
			word: 'sacra',
			full: 'sacrum, sacri, n',
			translation: 'rite, ceremony, religious rite',
			type: 'vocp',
		},
		120: {
			word: 'divas',
			full: 'diva, divae, f',
			translation: 'goddess',
			type: 'accp',
		},
		121: {
			word: 'divos',
			full: 'divus, divi, m',
			translation: 'god',
			type: 'accp',
		},
		122: {
			word: 'boves',
			full: 'bos, bovis, m/f',
			translation: 'ox, cow, cattle',
			type: 'vocp',
		},
		123: {
			word: 'corda',
			full: 'cor, cordis, n',
			translation: 'heart, mind',
			type: 'vocp',
		},
		124: {
			word: 'polos',
			full: 'polus, poli, m',
			translation: 'pole, sky, heaven',
			type: 'accp',
		},
		125: {
			word: 'sites',
			full: 'sitis, sitis, (acc. sitim) f',
			translation: 'thirst',
			type: 'vocp',
		},
		126: {
			word: 'artus',
			full: 'artus, artus, m',
			translation: 'limb',
			type: 'vocs',
		},
		127: {
			word: 'feras',
			full: 'fera, ferae, f',
			translation: 'wild beast',
			type: 'accp',
		},
		128: {
			word: 'rogos',
			full: 'rogus, rogi, m',
			translation: 'funeral pyre, pyre',
			type: 'accp',
		},
		129: {
			word: 'crura',
			full: 'crus, cruris, n',
			translation: 'leg',
			type: 'vocp',
		},
		130: {
			word: 'faces',
			full: 'fax, facis, f',
			translation: 'torch, fire',
			type: 'vocp',
		},
		131: {
			word: 'nives',
			full: 'nix, nivis, f',
			translation: 'snow',
			type: 'vocp',
		},
		132: {
			word: 'amnes',
			full: 'amnis, amnis, m',
			translation: 'river',
			type: 'vocp',
		},
		133: {
			word: 'casas',
			full: 'casa, casae, f',
			translation: 'hut, cottage',
			type: 'accp',
		},
		134: {
			word: 'lucos',
			full: 'lucus, luci, m',
			translation: 'wood, grove',
			type: 'accp',
		},
		135: {
			word: 'remos',
			full: 'remus, remi, m',
			translation: 'oar',
			type: 'accp',
		},
		136: {
			word: 'dapes',
			full: 'daps, dapis, f',
			translation: 'feast, meast',
			type: 'vocp',
		},
		137: {
			word: 'gelua',
			full: 'gelu, gelus, n',
			translation: 'ice',
			type: 'vocp',
		},
		138: {
			word: 'ortus',
			full: 'ortus, ortus, m',
			translation: 'rising, east',
			type: 'vocs',
		},
		139: {
			word: 'prata',
			full: 'pratum, prati, n',
			translation: 'meadow',
			type: 'vocp',
		},
		140: {
			word: 'rosas',
			full: 'rosa, rosae, f',
			translation: 'rose',
			type: 'accp',
		},
		141: {
			word: 'vates',
			full: 'vates, vatis, m',
			translation: 'prophet, poet',
			type: 'vocs',
		},
		142: {
			word: 'aedes',
			full: 'aedes, aedis, f',
			translation: 'house (pl.), temple',
			type: 'vocs',
		},
		143: {
			word: 'antra',
			full: 'antrum, antri, n',
			translation: 'cave',
			type: 'vocp',
		},
		144: {
			word: 'rupes',
			full: 'rupes, rupis, f',
			translation: 'rock',
			type: 'vocs',
		},
		145: {
			word: 'arces',
			full: 'arx, arcis, f',
			translation: 'stronghold, citadel',
			type: 'vocp',
		},
		146: {
			word: 'facta',
			full: 'factum, facti, n',
			translation: 'deed, action',
			type: 'vocp',
		},
		147: {
			word: 'motus',
			full: 'motus, motus, m',
			translation: 'movement, disturbance, uprising',
			type: 'vocs',
		},
		148: {
			word: 'noxas',
			full: 'noxa, noxae, f',
			translation: 'harm, injury',
			type: 'accp',
		},
		149: {
			word: 'fames',
			full: 'fames, famis, f',
			translation: 'hunger',
			type: 'vocs',
		},
		150: {
			word: 'colla',
			full: 'collum, colli, n',
			translation: 'neck',
			type: 'vocp',
		},
		151: {
			word: 'minas',
			full: 'mina, minae, f',
			translation: 'threat',
			type: 'accp',
		},
		152: {
			word: 'atria',
			full: 'atrium, atrii, n',
			translation: 'hallway',
			type: 'vocp',
		},
		153: {
			word: 'valla',
			full: 'vallum, valli, n',
			translation: 'rampart',
			type: 'vocp',
		},
		154: {
			word: 'dubia',
			full: 'dubium, dubii, n',
			translation: 'doubt',
			type: 'vocp',
		},
		155: {
			word: 'tubas',
			full: 'tuba, tubae, f',
			translation: 'trumpet',
			type: 'accp',
		},
		156: {
			word: 'ictus',
			full: 'ictus, ictus, m',
			translation: 'blow, strike',
			type: 'vocs',
		},
		157: {
			word: 'moles',
			full: 'moles, molis, f',
			translation: 'size, weight, mass, block',
			type: 'vocs',
		},
		158: {
			word: 'ligna',
			full: 'lignum, ligni, n',
			translation: 'wood, firewood',
			type: 'vocp',
		},
		159: {
			word: 'togas',
			full: 'toga, togae, f',
			translation: 'toga',
			type: 'accp',
		},
		160: {
			word: 'damna',
			full: 'damnum, damni, n',
			translation: 'loss, damage',
			type: 'vocp',
		},
		161: {
			word: 'fures',
			full: 'fur, furis, m/f',
			translation: 'thief',
			type: 'vocp',
		},
		162: {
			word: 'furta',
			full: 'furtum, furti, n',
			translation: 'theft, deception',
			type: 'vocp',
		},
		163: {
			word: 'rotas',
			full: 'rota, rotae, f',
			translation: 'wheel, chariot',
			type: 'accp',
		},
		164: {
			word: 'aerem',
			full: 'aer, aeris, m',
			translation: 'air',
			type: 'accs',
		},
		165: {
			word: 'comam',
			full: 'coma, comae, f',
			translation: 'hair',
			type: 'accs',
		},
		166: {
			word: 'ensem',
			full: 'ensis, ensis, m',
			translation: 'sword',
			type: 'accs',
		},
		167: {
			word: 'lumen',
			full: 'lumen, luminis, n',
			translation: 'light, eye',
			type: 'vocs',
		},
		168: {
			word: 'natam',
			full: 'nata, natae, f',
			translation: 'daughter',
			type: 'accs',
		},
		169: {
			word: 'natum',
			full: 'natus, nati, m',
			translation: 'son',
			type: 'accs',
		},
		170: {
			word: 'nubem',
			full: 'nubes, nubis, f',
			translation: 'cloud',
			type: 'accs',
		},
		171: {
			word: 'orbem',
			full: 'orbis, orbis',
			translation: 'sphere, world, country, eye',
			type: 'accs',
		},
		172: {
			word: 'agnam',
			full: 'agna, agnae, f',
			translation: 'lamb',
			type: 'accs',
		},
		173: {
			word: 'agnum',
			full: 'agnus, agni, m',
			translation: 'lamb',
			type: 'accs',
		},
		174: {
			word: 'letum',
			full: 'letum, leti, n',
			translation: 'death',
			type: 'vocs',
		},
		175: {
			word: 'lupam',
			full: 'lupa, lupae, f',
			translation: 'she-wolf',
			type: 'accs',
		},
		176: {
			word: 'lupum',
			full: 'lupus, lupi, m',
			translation: 'wolf',
			type: 'accs',
		},
		177: {
			word: 'torum',
			full: 'torus, tori, m',
			translation: 'bed, couch, marriage',
			type: 'accs',
		},
		178: {
			word: 'arcum',
			full: 'arcus, arcus, m',
			translation: 'bow, curve',
			type: 'accs',
		},
		179: {
			word: 'fatum',
			full: 'fatum, fati, n',
			translation: 'fate',
			type: 'vocs',
		},
		180: {
			word: 'numen',
			full: 'numen, numinis, n',
			translation: 'divinity, divine power, god',
			type: 'vocs',
		},
		181: {
			word: 'ratem',
			full: 'ratis, ratis, f',
			translation: 'boat, raft',
			type: 'accs',
		},
		182: {
			word: 'arvum',
			full: 'arvum, arvi , n',
			translation: 'field, land',
			type: 'vocs',
		},
		183: {
			word: 'rivum',
			full: 'rivus, rivi, m',
			translation: 'stream',
			type: 'accs',
		},
		184: {
			word: 'divam',
			full: 'diva, divae, f',
			translation: 'goddess',
			type: 'accs',
		},
		185: {
			word: 'divum',
			full: 'divus, divi, m',
			translation: 'god',
			type: 'accs',
		},
		186: {
			word: 'bovem',
			full: 'bos, bovis, m/f',
			translation: 'ox, cow, cattle',
			type: 'accs',
		},
		187: {
			word: 'funus',
			full: 'funus, funeris, n',
			translation: 'burial, funeral, death',
			type: 'vocs',
		},
		188: {
			word: 'iugum',
			full: 'iugum, iugi, n',
			translation: 'yoke, mountain ridge',
			type: 'vocs',
		},
		189: {
			word: 'polum',
			full: 'polus, poli, m',
			translation: 'pole, sky, heaven',
			type: 'accs',
		},
		190: {
			word: 'sitim',
			full: 'sitis, sitis, (acc. sitim) f',
			translation: 'thirst',
			type: 'accs',
		},
		191: {
			word: 'votum',
			full: 'votum, voti, n',
			translation: 'vow, prayer, hope',
			type: 'vocs',
		},
		192: {
			word: 'artum',
			full: 'artus, artus, m',
			translation: 'limb',
			type: 'accs',
		},
		193: {
			word: 'feram',
			full: 'fera, ferae, f',
			translation: 'wild beast',
			type: 'accs',
		},
		194: {
			word: 'rogum',
			full: 'rogus, rogi, m',
			translation: 'funeral pyre, pyre',
			type: 'accs',
		},
		195: {
			word: 'facem',
			full: 'fax, facis, f',
			translation: 'torch, fire',
			type: 'accs',
		},
		196: {
			word: 'nivem',
			full: 'nix, nivis, f',
			translation: 'snow',
			type: 'accs',
		},
		197: {
			word: 'robur',
			full: 'robur, roboris',
			translation: 'oak, strength, manpower',
			type: 'vocs',
		},
		198: {
			word: 'semen',
			full: 'semen, seminis, n',
			translation: 'seed',
			type: 'vocs',
		},
		199: {
			word: 'amnem',
			full: 'amnis, amnis, m',
			translation: 'river',
			type: 'accs',
		},
		200: {
			word: 'casam',
			full: 'casa, casae, f',
			translation: 'hut, cottage',
			type: 'accs',
		},
		201: {
			word: 'decus',
			full: 'decus, decoris, n',
			translation: 'glory, dignity, beauty',
			type: 'vocs',
		},
		202: {
			word: 'lucum',
			full: 'lucus, luci, m',
			translation: 'wood, grove',
			type: 'accs',
		},
		203: {
			word: 'merum',
			full: 'merum, meri, n',
			translation: 'wine',
			type: 'vocs',
		},
		204: {
			word: 'remum',
			full: 'remus, remi, m',
			translation: 'oar',
			type: 'accs',
		},
		205: {
			word: 'dapem',
			full: 'daps, dapis, f',
			translation: 'feast, meast',
			type: 'accs',
		},
		206: {
			word: 'ortum',
			full: 'ortus, ortus, m',
			translation: 'rising, east',
			type: 'accs',
		},
		207: {
			word: 'rosam',
			full: 'rosa, rosae, f',
			translation: 'rose',
			type: 'accs',
		},
		208: {
			word: 'sidus',
			full: 'sidus, sideris, n',
			translation: 'star, constellation, weather',
			type: 'vocs',
		},
		209: {
			word: 'vatem',
			full: 'vates, vatis, m',
			translation: 'prophet, poet',
			type: 'accs',
		},
		210: {
			word: 'aedem',
			full: 'aedes, aedis, f',
			translation: 'house (pl.), temple',
			type: 'accs',
		},
		211: {
			word: 'limen',
			full: 'limen, liminis, n',
			translation: 'entrance, threshold, house',
			type: 'vocs',
		},
		212: {
			word: 'nemus',
			full: 'nemus, nemoris, n',
			translation: 'wood, forest',
			type: 'vocs',
		},
		213: {
			word: 'rupem',
			full: 'rupes, rupis, f',
			translation: 'rock',
			type: 'accs',
		},
		214: {
			word: 'arcem',
			full: 'arx, arcis, f',
			translation: 'stronghold, citadel',
			type: 'accs',
		},
		215: {
			word: 'motum',
			full: 'motus, motus, m',
			translation: 'movement, disturbance, uprising',
			type: 'accs',
		},
		216: {
			word: 'noxam',
			full: 'noxa, noxae, f',
			translation: 'harm, injury',
			type: 'accs',
		},
		217: {
			word: 'odium',
			full: 'odium, odii, n',
			translation: 'hatred',
			type: 'vocs',
		},
		218: {
			word: 'famem',
			full: 'fames, famis, f',
			translation: 'hunger',
			type: 'accs',
		},
		219: {
			word: 'minam',
			full: 'mina, minae, f',
			translation: 'threat',
			type: 'accs',
		},
		220: {
			word: 'fanum',
			full: 'fanum, fani, n',
			translation: 'temple, shrine',
			type: 'vocs',
		},
		221: {
			word: 'munus',
			full: 'munus, muneris, n',
			translation: 'office, duty, gift',
			type: 'vocs',
		},
		222: {
			word: 'tubam',
			full: 'tuba, tubae, f',
			translation: 'trumpet',
			type: 'accs',
		},
		223: {
			word: 'ictum',
			full: 'ictus, ictus, m',
			translation: 'blow, strike',
			type: 'accs',
		},
		224: {
			word: 'aevum',
			full: 'aevum, aevi, n',
			translation: 'time, life, age',
			type: 'vocs',
		},
		225: {
			word: 'molem',
			full: 'moles, molis, f',
			translation: 'size, weight, mass, block',
			type: 'accs',
		},
		226: {
			word: 'togam',
			full: 'toga, togae, f',
			translation: 'toga',
			type: 'accs',
		},
		227: {
			word: 'velum',
			full: 'velum, veli, n',
			translation: 'sail',
			type: 'vocs',
		},
		228: {
			word: 'furem',
			full: 'fur, furis, m/f',
			translation: 'thief',
			type: 'accs',
		},
		229: {
			word: 'rotam',
			full: 'rota, rotae, f',
			translation: 'wheel, chariot',
			type: 'accs',
		},
		230: {
			word: 'comis',
			full: 'coma, comae, f',
			translation: 'hair',
			type: 'datp',
		},
		231: {
			word: 'comae',
			full: 'coma, comae, f',
			translation: 'hair',
			type: 'vocp',
		},
		232: {
			word: 'natae',
			full: 'nata, natae, f',
			translation: 'daughter',
			type: 'vocp',
		},
		233: {
			word: 'puppi',
			full: 'puppis, puppis, f',
			translation: 'stern, ship',
			type: 'dats',
		},
		234: {
			word: 'agnae',
			full: 'agna, agnae, f',
			translation: 'lamb',
			type: 'vocp',
		},
		235: {
			word: 'crini',
			full: 'crinis, crinis, m',
			translation: 'hair',
			type: 'dats',
		},
		236: {
			word: 'lupae',
			full: 'lupa, lupae, f',
			translation: 'she-wolf',
			type: 'vocp',
		},
		237: {
			word: 'arcui',
			full: 'arcus, arcus, m',
			translation: 'bow, curve',
			type: 'dats',
		},
		238: {
			word: 'proli',
			full: 'proles, prolis',
			translation: 'offspring, child, descendant, flock',
			type: 'dats',
		},
		239: {
			word: 'sorti',
			full: 'sors, sortis, f',
			translation: 'lot, fortune',
			type: 'dats',
		},
		240: {
			word: 'divae',
			full: 'diva, divae, f',
			translation: 'goddess',
			type: 'vocp',
		},
		241: {
			word: 'imbri',
			full: 'imber, imbris, m',
			translation: 'rain',
			type: 'dats',
		},
		242: {
			word: 'cordi',
			full: 'cor, cordis, n',
			translation: 'heart, mind',
			type: 'dats',
		},
		243: {
			word: 'artui',
			full: 'artus, artus, m',
			translation: 'limb',
			type: 'dats',
		},
		244: {
			word: 'ferae',
			full: 'fera, ferae, f',
			translation: 'wild beast',
			type: 'vocp',
		},
		245: {
			word: 'flori',
			full: 'flos, floris, m',
			translation: 'flower',
			type: 'dats',
		},
		246: {
			word: 'cruri',
			full: 'crus, cruris, n',
			translation: 'leg',
			type: 'dats',
		},
		247: {
			word: 'gregi',
			full: 'grex, gregis, m',
			translation: 'flock, herd',
			type: 'dats',
		},
		248: {
			word: 'casae',
			full: 'casa, casae, f',
			translation: 'hut, cottage',
			type: 'vocp',
		},
		249: {
			word: 'ortui',
			full: 'ortus, ortus, m',
			translation: 'rising, east',
			type: 'dats',
		},
		250: {
			word: 'pisci',
			full: 'piscis, piscis, m',
			translation: 'fish',
			type: 'dats',
		},
		251: {
			word: 'rosae',
			full: 'rosa, rosae, f',
			translation: 'rose',
			type: 'vocp',
		},
		252: {
			word: 'forti',
			full: 'fors, fortis, f',
			translation: 'chance, luck, fortune',
			type: 'dats',
		},
		253: {
			word: 'ungui',
			full: 'unguis, unguis, m',
			translation: 'nail, claw, talon',
			type: 'dats',
		},
		254: {
			word: 'motui',
			full: 'motus, motus, m',
			translation: 'movement, disturbance, uprising',
			type: 'dats',
		},
		255: {
			word: 'noxae',
			full: 'noxa, noxae, f',
			translation: 'harm, injury',
			type: 'vocp',
		},
		256: {
			word: 'pesti',
			full: 'pestis, pestis, f',
			translation: 'plague, disease',
			type: 'dats',
		},
		257: {
			word: 'laudi',
			full: 'laus, laudis, f',
			translation: 'praise, glory',
			type: 'dats',
		},
		258: {
			word: 'minae',
			full: 'mina, minae, f',
			translation: 'threat',
			type: 'vocp',
		},
		259: {
			word: 'tubae',
			full: 'tuba, tubae, f',
			translation: 'trumpet',
			type: 'vocp',
		},
		260: {
			word: 'ictui',
			full: 'ictus, ictus, m',
			translation: 'blow, strike',
			type: 'dats',
		},
		261: {
			word: 'colli',
			full: 'collum, colli, n',
			translation: 'neck',
			type: 'gens',
		},
		262: {
			word: 'fonti',
			full: 'fons, fontis, m',
			translation: 'fountain, spring',
			type: 'dats',
		},
		263: {
			word: 'togae',
			full: 'toga, togae, f',
			translation: 'toga',
			type: 'vocp',
		},
		264: {
			word: 'omini',
			full: 'omen, ominis, n',
			translation: 'sign, omen',
			type: 'dats',
		},
		265: {
			word: 'rotae',
			full: 'rota, rotae, f',
			translation: 'wheel, chariot',
			type: 'vocp',
		},
		266: {
			word: 'abdam',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'pracsuj1s',
		},
		267: {
			word: 'flebo',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'ftacind1s',
		},
		268: {
			word: 'fluam',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'pracsuj1s',
		},
		269: {
			word: 'gemam',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'pracsuj1s',
		},
		270: {
			word: 'cedam',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'pracsuj1s',
		},
		271: {
			word: 'dedam',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'pracsuj1s',
		},
		272: {
			word: 'figam',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'pracsuj1s',
		},
		273: {
			word: 'arabo',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'ftacind1s',
		},
		274: {
			word: 'colam',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'pracsuj1s',
		},
		275: {
			word: 'nubam',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'pracsuj1s',
		},
		276: {
			word: 'seram',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'pracsuj1s',
		},
		277: {
			word: 'visam',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'pracsuj1s',
		},
		278: {
			word: 'abdes',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'ftacind2s',
		},
		279: {
			word: 'flues',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'ftacind2s',
		},
		280: {
			word: 'gemes',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'ftacind2s',
		},
		281: {
			word: 'cedes',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'ftacind2s',
		},
		282: {
			word: 'dedes',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'ftacind2s',
		},
		283: {
			word: 'figes',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'ftacind2s',
		},
		284: {
			word: 'coles',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'ftacind2s',
		},
		285: {
			word: 'seres',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'ftacind2s',
		},
		286: {
			word: 'vises',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'ftacind2s',
		},
		287: {
			word: 'urent',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'ftacind3pl',
		},
		288: {
			word: 'edent',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'ftacind3pl',
		},
		289: {
			word: 'ruent',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'ftacind3pl',
		},
		290: {
			word: 'alent',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'ftacind3pl',
		},
		291: {
			word: 'abdet',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'ftacind3s',
		},
		292: {
			word: 'fluet',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'ftacind3s',
		},
		293: {
			word: 'gemet',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'ftacind3s',
		},
		294: {
			word: 'cedet',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'ftacind3s',
		},
		295: {
			word: 'dedet',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'ftacind3s',
		},
		296: {
			word: 'figet',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'ftacind3s',
		},
		297: {
			word: 'colet',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'ftacind3s',
		},
		298: {
			word: 'nubet',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'ftacind3s',
		},
		299: {
			word: 'seret',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'ftacind3s',
		},
		300: {
			word: 'viset',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'ftacind3s',
		},
		301: {
			word: 'abdar',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'prpasuj1s',
		},
		302: {
			word: 'fluar',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'prpasuj1s',
		},
		303: {
			word: 'gemar',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'prpasuj1s',
		},
		304: {
			word: 'cedar',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'prpasuj1s',
		},
		305: {
			word: 'dedar',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'prpasuj1s',
		},
		306: {
			word: 'figar',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'prpasuj1s',
		},
		307: {
			word: 'colar',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'prpasuj1s',
		},
		308: {
			word: 'nubar',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'prpasuj1s',
		},
		309: {
			word: 'serar',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'prpasuj1s',
		},
		310: {
			word: 'visar',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'prpasuj1s',
		},
		311: {
			word: 'aerum',
			full: 'aes, aeris, n',
			translation: 'bronze, money',
			type: 'genp',
		},
		312: {
			word: 'axium',
			full: 'axis, axis, m',
			translation: 'vault of heaven, axle, chariot',
			type: 'genp',
		},
		313: {
			word: 'ovium',
			full: 'ovis, ovis, f',
			translation: 'sheep',
			type: 'genp',
		},
		314: {
			word: 'bovum',
			full: 'bos, bovis, m/f',
			translation: 'ox, cow, cattle',
			type: 'genp',
		},
		315: {
			word: 'facum',
			full: 'fax, facis, f',
			translation: 'torch, fire',
			type: 'genp',
		},
		316: {
			word: 'nivum',
			full: 'nix, nivis, f',
			translation: 'snow',
			type: 'genp',
		},
		317: {
			word: 'dapum',
			full: 'daps, dapis, f',
			translation: 'feast, meast',
			type: 'genp',
		},
		318: {
			word: 'vatum',
			full: 'vates, vatis, m',
			translation: 'prophet, poet',
			type: 'genp',
		},
		319: {
			word: 'verum',
			full: 'ver, veris, n',
			translation: 'spring (season)',
			type: 'genp',
		},
		320: {
			word: 'aedum',
			full: 'aedes, aedis, f',
			translation: 'house (pl.), temple',
			type: 'genp',
		},
		321: {
			word: 'rupum',
			full: 'rupes, rupis, f',
			translation: 'rock',
			type: 'genp',
		},
		322: {
			word: 'usuum',
			full: 'usus, usus, m',
			translation: 'use, value, experience',
			type: 'genp',
		},
		323: {
			word: 'molum',
			full: 'moles, molis, f',
			translation: 'size, weight, mass, block',
			type: 'genp',
		},
		324: {
			word: 'furum',
			full: 'fur, furis, m/f',
			translation: 'thief',
			type: 'genp',
		},
		325: {
			word: 'aeris',
			full: 'aes, aeris, n',
			translation: 'bronze, money',
			type: 'gens',
		},
		326: {
			word: 'astri',
			full: 'astrum, astri, n',
			translation: 'star, constellation',
			type: 'gens',
		},
		327: {
			word: 'dicti',
			full: 'dictum, dicti, n',
			translation: 'word',
			type: 'gens',
		},
		328: {
			word: 'ensis',
			full: 'ensis, ensis, m',
			translation: 'sword',
			type: 'vocs',
		},
		329: {
			word: 'freti',
			full: 'fretum, freti, n',
			translation: 'strait, sea',
			type: 'gens',
		},
		330: {
			word: 'lecti',
			full: 'lectus, lecti, m',
			translation: 'bed, couch',
			type: 'vocp',
		},
		331: {
			word: 'nubis',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'pracind2s',
		},
		332: {
			word: 'orbis',
			full: 'orbis, orbis',
			translation: 'sphere, world, country, eye',
			type: 'vocs',
		},
		333: {
			word: 'tauri',
			full: 'taurus, tauri, m',
			translation: 'bull',
			type: 'vocp',
		},
		334: {
			word: 'umeri',
			full: 'umerus, umeri, m',
			translation: 'shoulder',
			type: 'vocp',
		},
		335: {
			word: 'ratis',
			full: 'ratis, ratis, f',
			translation: 'boat, raft',
			type: 'vocs',
		},
		336: {
			word: 'sacri',
			full: 'sacrum, sacri, n',
			translation: 'rite, ceremony, religious rite',
			type: 'gens',
		},
		337: {
			word: 'ponti',
			full: 'pontus, ponti, m',
			translation: 'sea',
			type: 'vocp',
		},
		338: {
			word: 'bovis',
			full: 'bos, bovis, m/f',
			translation: 'ox, cow, cattle',
			type: 'gens',
		},
		339: {
			word: 'sitis',
			full: 'sitis, sitis, (acc. sitim) f',
			translation: 'thirst',
			type: 'vocs',
		},
		340: {
			word: 'facis',
			full: 'fax, facis, f',
			translation: 'torch, fire',
			type: 'gens',
		},
		341: {
			word: 'nivis',
			full: 'nix, nivis, f',
			translation: 'snow',
			type: 'gens',
		},
		342: {
			word: 'amnis',
			full: 'amnis, amnis, m',
			translation: 'river',
			type: 'vocs',
		},
		343: {
			word: 'clivi',
			full: 'clivus, clivi, m',
			translation: 'slope, hill',
			type: 'vocp',
		},
		344: {
			word: 'dapis',
			full: 'daps, dapis, f',
			translation: 'feast, meast',
			type: 'gens',
		},
		345: {
			word: 'gelus',
			full: 'gelu, gelus, n',
			translation: 'ice',
			type: 'gens',
		},
		346: {
			word: 'prati',
			full: 'pratum, prati, n',
			translation: 'meadow',
			type: 'gens',
		},
		347: {
			word: 'vatis',
			full: 'vates, vatis, m',
			translation: 'prophet, poet',
			type: 'gens',
		},
		348: {
			word: 'veris',
			full: 'ver, veris, n',
			translation: 'spring (season)',
			type: 'gens',
		},
		349: {
			word: 'aedis',
			full: 'aedes, aedis, f',
			translation: 'house (pl.), temple',
			type: 'gens',
		},
		350: {
			word: 'antri',
			full: 'antrum, antri, n',
			translation: 'cave',
			type: 'gens',
		},
		351: {
			word: 'rupis',
			full: 'rupes, rupis, f',
			translation: 'rock',
			type: 'gens',
		},
		352: {
			word: 'vulgi',
			full: 'vulgus, vulgi, n',
			translation: 'crowd, common people',
			type: 'vocp',
		},
		353: {
			word: 'arcis',
			full: 'arx, arcis, f',
			translation: 'stronghold, citadel',
			type: 'gens',
		},
		354: {
			word: 'facti',
			full: 'factum, facti, n',
			translation: 'deed, action',
			type: 'gens',
		},
		355: {
			word: 'famis',
			full: 'fames, famis, f',
			translation: 'hunger',
			type: 'gens',
		},
		356: {
			word: 'anuli',
			full: 'anulus, anuli, m',
			translation: 'ring',
			type: 'vocp',
		},
		357: {
			word: 'atrii',
			full: 'atrium, atrii, n',
			translation: 'hallway',
			type: 'gens',
		},
		358: {
			word: 'valli',
			full: 'vallum, valli, n',
			translation: 'rampart',
			type: 'gens',
		},
		359: {
			word: 'dubii',
			full: 'dubium, dubii, n',
			translation: 'doubt',
			type: 'gens',
		},
		360: {
			word: 'molis',
			full: 'moles, molis, f',
			translation: 'size, weight, mass, block',
			type: 'gens',
		},
		361: {
			word: 'fundi',
			full: 'fundus, fundi, m',
			translation: 'farm, estate',
			type: 'vocp',
		},
		362: {
			word: 'ligni',
			full: 'lignum, ligni, n',
			translation: 'wood, firewood',
			type: 'gens',
		},
		363: {
			word: 'damni',
			full: 'damnum, damni, n',
			translation: 'loss, damage',
			type: 'gens',
		},
		364: {
			word: 'furis',
			full: 'fur, furis, m/f',
			translation: 'thief',
			type: 'gens',
		},
		365: {
			word: 'furti',
			full: 'furtum, furti, n',
			translation: 'theft, deception',
			type: 'gens',
		},
		366: {
			word: 'nummi',
			full: 'nummus, nummi, m',
			translation: 'coin, money',
			type: 'vocp',
		},
		367: {
			word: 'urite',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'imppl',
		},
		368: {
			word: 'flete',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'imppl',
		},
		369: {
			word: 'arate',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'imppl',
		},
		370: {
			word: 'edite',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'imppl',
		},
		371: {
			word: 'ruite',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'imppl',
		},
		372: {
			word: 'alite',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'imppl',
		},
		373: {
			word: 'lania',
			full: 'lanio, laniare, laniavi, laniatus',
			translation: 'tear, mutilate',
			type: 'imps',
		},
		374: {
			word: 'perde',
			full: 'perdo, perdere, perdidi, perditus',
			translation: 'destroy, ruin, lose, waste',
			type: 'imps',
		},
		375: {
			word: 'spira',
			full: 'spiro, spirare, spiravi, spiratus',
			translation: 'breathe, blow, be alive',
			type: 'imps',
		},
		376: {
			word: 'tende',
			full: 'tendo, tendere, tetendi, tensus',
			translation: 'stretch, extend, aim for, march',
			type: 'imps',
		},
		377: {
			word: 'caede',
			full: 'caedo, caedere, cecidi, caesus',
			translation: 'slaughter, kill',
			type: 'imps',
		},
		378: {
			word: 'carpe',
			full: 'carpo, carpere, carpsi, carptus',
			translation: 'pluck, take',
			type: 'imps',
		},
		379: {
			word: 'iacta',
			full: 'iacto, iactare, iactavi, iactatus',
			translation: 'throw, hurl, boast',
			type: 'imps',
		},
		380: {
			word: 'lassa',
			full: 'lasso, lassare, lassavi, lassatus',
			translation: 'tire, exhaust, wear out',
			type: 'imps',
		},
		381: {
			word: 'preme',
			full: 'premo, premere, pressi, pressus',
			translation: 'press, curb, overpower',
			type: 'imps',
		},
		382: {
			word: 'cerne',
			full: 'cerno, cernere, crevi, cretus',
			translation: 'perceive, deceive',
			type: 'imps',
		},
		383: {
			word: 'misce',
			full: 'misceo, miscere, miscui, mixtum',
			translation: 'mix, stir up',
			type: 'imps',
		},
		384: {
			word: 'cinge',
			full: 'cingo, cingere, cinxi, cinctus',
			translation: 'surround',
			type: 'imps',
		},
		385: {
			word: 'hauri',
			full: 'haurio, haurire, hausi, haustum',
			translation: 'drain, drink',
			type: 'imps',
		},
		386: {
			word: 'pinge',
			full: 'pingo, pingere, pinxi, pictum',
			translation: 'paint',
			type: 'imps',
		},
		387: {
			word: 'surge',
			full: 'surgo, surgere, surrexi, surrectus',
			translation: 'rise, rise up',
			type: 'imps',
		},
		388: {
			word: 'turba',
			full: 'turbo, turbare, turbavi, turbatum',
			translation: 'disturb, throw into confusion',
			type: 'imps',
		},
		389: {
			word: 'cessa',
			full: 'cesso, cessare, cessavi, cessatus',
			translation: 'delay, do nothing, leave off',
			type: 'imps',
		},
		390: {
			word: 'merge',
			full: 'mergo, mergere, mersi, mersus',
			translation: 'sink, submerge',
			type: 'imps',
		},
		391: {
			word: 'finge',
			full: 'fingo, fingere, finxi, fictum',
			translation: 'fabricate, invent',
			type: 'imps',
		},
		392: {
			word: 'mulce',
			full: 'mulceo, mulcere, mulsi, mulsus',
			translation: 'soothe, appease',
			type: 'imps',
		},
		393: {
			word: 'placa',
			full: 'placo, placare, placavi, placatum',
			translation: 'calm, soothe, placate',
			type: 'imps',
		},
		394: {
			word: 'adime',
			full: 'adimo, adimere, ademi, ademptus',
			translation: 'take away',
			type: 'imps',
		},
		395: {
			word: 'conde',
			full: 'condo, condere, condidi, conditus',
			translation: 'build, found, establish',
			type: 'imps',
		},
		396: {
			word: 'laede',
			full: 'laedo, laedere, laesi, laesus',
			translation: 'hurt, harm',
			type: 'imps',
		},
		397: {
			word: 'morde',
			full: 'mordeo, mordere, momordi, morsus',
			translation: 'bite, hurt, distress',
			type: 'imps',
		},
		398: {
			word: 'prode',
			full: 'prodo, prodere, prodidi, proditus',
			translation: 'betray',
			type: 'imps',
		},
		399: {
			word: 'strue',
			full: 'struo, struere, struxi, structus',
			translation: 'arrange, construct, draw up',
			type: 'imps',
		},
		400: {
			word: 'evade',
			full: 'evado, evadere, evasi, evasus',
			translation: 'escape',
			type: 'imps',
		},
		401: {
			word: 'erige',
			full: 'erigo, erigere, erexi, erectus',
			translation: 'raise, build, rouse',
			type: 'imps',
		},
		402: {
			word: 'funde',
			full: 'fundus, fundi, m',
			translation: 'farm, estate',
			type: 'vocs',
		},
		403: {
			word: 'iunge',
			full: 'iungo, iungere, iunxi, iunctus',
			translation: 'join',
			type: 'imps',
		},
		404: {
			word: 'eveni',
			full: 'evenio, evenire, eveni, eventus',
			translation: 'come out, happen, result',
			type: 'pfacind1s',
		},
		405: {
			word: 'obrue',
			full: 'obruo, obruere, obrui, obrutus',
			translation: 'overwhelm, cover',
			type: 'imps',
		},
		406: {
			word: 'perge',
			full: 'pergo, pergere, perrexi, perrectus',
			translation: 'proceed, march, go on',
			type: 'imps',
		},
		407: {
			word: 'proba',
			full: 'probo, probare, probavi, probatus',
			translation: 'approve, test, prove',
			type: 'imps',
		},
		408: {
			word: 'elude',
			full: 'eludo, eludere, elusi, elusus',
			translation: 'ward off, escape, mock',
			type: 'imps',
		},
		409: {
			word: 'haere',
			full: 'haereo, haerere, haesi, haesum',
			translation: 'stick, cling',
			type: 'imps',
		},
		410: {
			word: 'obice',
			full: 'obicio, obicere, obieci, obiectus',
			translation: 'throw in the way of, expose',
			type: 'imps',
		},
		411: {
			word: 'adice',
			full: 'adicio, adicere, adieci, adiectus',
			translation: 'throw to, add',
			type: 'imps',
		},
		412: {
			word: 'aequa',
			full: 'aequo, aequare, aequavi, aequatus',
			translation: 'equal, match, liken, compare',
			type: 'imps',
		},
		413: {
			word: 'argue',
			full: 'arguo, arguere, argui, argutus',
			translation: 'prove, accuse, denounce',
			type: 'imps',
		},
		414: {
			word: 'manda',
			full: 'mando, mandare, mandavi, mandatum',
			translation: 'commit, entrust, command',
			type: 'imps',
		},
		415: {
			word: 'operi',
			full: 'operio, operire, operui, opertum',
			translation: 'cover',
			type: 'imps',
		},
		416: {
			word: 'vasta',
			full: 'vasto, vastare, vastavi, vastatum',
			translation: 'ravage, lay waste',
			type: 'imps',
		},
		417: {
			word: 'agita',
			full: 'agito, agitare, agitavi, agitatum',
			translation: 'drive, agitate, disturb, consider',
			type: 'imps',
		},
		418: {
			word: 'firma',
			full: 'firmo, firmare, firmavi, firmatum',
			translation: 'strengthen',
			type: 'imps',
		},
		419: {
			word: 'nosce',
			full: 'nosco, noscere, novi, notum',
			translation: 'know',
			type: 'imps',
		},
		420: {
			word: 'parce',
			full: 'parco, parcere, peperci, parsum (+ dat.)',
			translation: 'spare',
			type: 'imps',
		},
		421: {
			word: 'adige',
			full: 'adigo, adigere, adegi, adactum',
			translation: 'thrust, drive, stab',
			type: 'imps',
		},
		422: {
			word: 'bella',
			full: 'bello, bellare, bellavi, belatum',
			translation: 'wage war, fight',
			type: 'imps',
		},
		423: {
			word: 'indue',
			full: 'induo, induere, indui, indutum',
			translation: 'put on, dress in',
			type: 'imps',
		},
		424: {
			word: 'trade',
			full: 'trado, tradere, tradidi, traditum',
			translation: 'hand over, record',
			type: 'imps',
		},
		425: {
			word: 'vinci',
			full: 'vincio, vincire, vinxi, vinctum',
			translation: 'tie up, bind',
			type: 'imps',
		},
		426: {
			word: 'minue',
			full: 'minuo, minuere, minui, minutum',
			translation: 'lessen, diminish',
			type: 'imps',
		},
		427: {
			word: 'salta',
			full: 'salto, saltare, saltavi, saltatum',
			translation: 'dance',
			type: 'imps',
		},
		428: {
			word: 'suade',
			full: 'suadeo, suadere, suasi, suasum',
			translation: 'urge, recommend, persuade, force',
			type: 'imps',
		},
		429: {
			word: 'cense',
			full: 'censeo, censere, censui, censum',
			translation: 'fight, compete',
			type: 'imps',
		},
		430: {
			word: 'dirue',
			full: 'diruo, diruere, dirui, dirutum',
			translation: 'demolish',
			type: 'imps',
		},
		431: {
			word: 'saevi',
			full: 'saevio, saevire, saevii, saevitum',
			translation: 'be fierce, in a rage',
			type: 'imps',
		},
		432: {
			word: 'verte',
			full: 'verto, vertere, verti, versum',
			translation: 'turn, overthrow, destroy',
			type: 'imps',
		},
		433: {
			word: 'viola',
			full: 'violo, violare, violavi, violatum',
			translation: 'violate, defile',
			type: 'imps',
		},
		434: {
			word: 'reice',
			full: 'reicio, reicere, reieci, reiectum',
			translation: 'reject, refuse',
			type: 'imps',
		},
		435: {
			word: 'servi',
			full: 'servio, servire, servii, servitum',
			translation: 'be a slave, serve',
			type: 'imps',
		},
		436: {
			word: 'urere',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'infpr',
		},
		437: {
			word: 'flere',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'infpr',
		},
		438: {
			word: 'arare',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'infpr',
		},
		439: {
			word: 'edere',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'infpr',
		},
		440: {
			word: 'ruere',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'infpr',
		},
		441: {
			word: 'alere',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'infpr',
		},
		442: {
			word: 'color',
			full: 'color, coloris, m',
			translation: 'colour, complexion',
			type: 'vocs',
		},
		443: {
			word: 'natus',
			full: 'natus, nati, m',
			translation: 'son',
			type: 'noms',
		},
		444: {
			word: 'agnus',
			full: 'agnus, agni, m',
			translation: 'lamb',
			type: 'noms',
		},
		445: {
			word: 'lupus',
			full: 'lupus, lupi, m',
			translation: 'wolf',
			type: 'noms',
		},
		446: {
			word: 'seges',
			full: 'seges, segetis, f',
			translation: 'crop, (corn) field',
			type: 'vocs',
		},
		447: {
			word: 'torus',
			full: 'torus, tori, m',
			translation: 'bed, couch, marriage',
			type: 'noms',
		},
		448: {
			word: 'limes',
			full: 'limes, limitis, m',
			translation: 'boundary, track',
			type: 'vocs',
		},
		449: {
			word: 'rivus',
			full: 'rivus, rivi, m',
			translation: 'stream',
			type: 'noms',
		},
		450: {
			word: 'divus',
			full: 'divus, divi, m',
			translation: 'god',
			type: 'noms',
		},
		451: {
			word: 'frons',
			full: 'frons, frontis, f',
			translation: 'forehead, brow, front',
			type: 'vocs',
		},
		452: {
			word: 'imago',
			full: 'imago, imaginis, f',
			translation: 'image, statue, idea',
			type: 'vocs',
		},
		453: {
			word: 'imber',
			full: 'imber, imbris, m',
			translation: 'rain',
			type: 'vocs',
		},
		454: {
			word: 'vomer',
			full: 'vomer, vomeris, n',
			translation: 'plough, ploughshare',
			type: 'vocs',
		},
		455: {
			word: 'polus',
			full: 'polus, poli, m',
			translation: 'pole, sky, heaven',
			type: 'noms',
		},
		456: {
			word: 'rogus',
			full: 'rogus, rogi, m',
			translation: 'funeral pyre, pyre',
			type: 'noms',
		},
		457: {
			word: 'lucus',
			full: 'lucus, luci, m',
			translation: 'wood, grove',
			type: 'noms',
		},
		458: {
			word: 'pudor',
			full: 'pudor, pudoris, m',
			translation: 'shame, modesty',
			type: 'vocs',
		},
		459: {
			word: 'remus',
			full: 'remus, remi, m',
			translation: 'oar',
			type: 'noms',
		},
		460: {
			word: 'cruor',
			full: 'cruor, cruoris, m',
			translation: 'blood',
			type: 'vocs',
		},
		461: {
			word: 'aetas',
			full: 'aetas, aetatis, f',
			translation: 'age',
			type: 'vocs',
		},
		462: {
			word: 'sermo',
			full: 'sermo, sermonis, m',
			translation: 'speech, conversation',
			type: 'vocs',
		},
		463: {
			word: 'ardor',
			full: 'ardor, ardoris, m',
			translation: 'burning, heart, love, passion',
			type: 'vocs',
		},
		464: {
			word: 'furor',
			full: 'furor, furoris, m',
			translation: 'madness, frenzy',
			type: 'vocs',
		},
		465: {
			word: 'quies',
			full: 'quies, quietis, f',
			translation: 'calmness, quiet',
			type: 'vocs',
		},
		466: {
			word: 'exsul',
			full: 'exsul, exsulis, m',
			translation: 'exile (person)',
			type: 'vocs',
		},
		467: {
			word: 'fraus',
			full: 'fraus, fraudis, f',
			translation: 'deceit, lie',
			type: 'vocs',
		},
		468: {
			word: 'natio',
			full: 'natio, nationis, f',
			translation: 'race, nation, people',
			type: 'vocs',
		},
		469: {
			word: 'pavor',
			full: 'pavor, pavoris, m',
			translation: 'terror',
			type: 'vocs',
		},
		470: {
			word: 'regio',
			full: 'regio, regionis, f',
			translation: 'region',
			type: 'vocs',
		},
		471: {
			word: 'vigor',
			full: 'vigor, vigoris, m',
			translation: 'force, energy',
			type: 'vocs',
		},
		472: {
			word: 'nepos',
			full: 'nepos, nepotis, m',
			translation: 'grandson',
			type: 'vocs',
		},
		473: {
			word: 'obses',
			full: 'obses, obsidis, m',
			translation: 'hostage',
			type: 'vocs',
		},
		474: {
			word: 'latro',
			full: 'latro, latronis, m',
			translation: 'robber',
			type: 'vocs',
		},
		475: {
			word: 'sopor',
			full: 'sopor, soporis, m',
			translation: 'sleep',
			type: 'vocs',
		},
		476: {
			word: 'agger',
			full: 'agger, aggeris, n',
			translation: 'mound, rampart',
			type: 'vocs',
		},
		477: {
			word: 'dicio',
			full: 'dicio, dicionis, f',
			translation: 'power, sway, rule',
			type: 'vocs',
		},
		478: {
			word: 'heres',
			full: 'heres, heredis, m/f',
			translation: 'heir, heiress',
			type: 'vocs',
		},
		479: {
			word: 'cinis',
			full: 'cinis, cineris, m',
			translation: 'ash',
			type: 'vocs',
		},
		480: {
			word: 'lapis',
			full: 'lapis, lapidis, m',
			translation: 'stone',
			type: 'vocs',
		},
		481: {
			word: 'urens',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'pap',
		},
		482: {
			word: 'flens',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'pap',
		},
		483: {
			word: 'arans',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'pap',
		},
		484: {
			word: 'edens',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'pap',
		},
		485: {
			word: 'ruens',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'pap',
		},
		486: {
			word: 'alens',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'pap',
		},
		487: {
			word: 'crevi',
			full: 'cresco, crescere, crevi, cretus',
			translation: 'grow, increase, arise',
			type: 'pfacind1s',
		},
		488: {
			word: 'salui',
			full: 'salio, salire, salui, saltus',
			translation: 'jump',
			type: 'pfacind1s',
		},
		489: {
			word: 'tonui',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'pfacind1s',
		},
		490: {
			word: 'merui',
			full: 'mereo, merere, merui, meritum',
			translation: 'deserve, earn',
			type: 'pfacind1s',
		},
		491: {
			word: 'domui',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'pfacind1s',
		},
		492: {
			word: 'cinxi',
			full: 'cingo, cingere, cinxi, cinctus',
			translation: 'surround',
			type: 'pfacind1s',
		},
		493: {
			word: 'hausi',
			full: 'haurio, haurire, hausi, haustum',
			translation: 'drain, drink',
			type: 'pfacind1s',
		},
		494: {
			word: 'pinxi',
			full: 'pingo, pingere, pinxi, pictum',
			translation: 'paint',
			type: 'pfacind1s',
		},
		495: {
			word: 'flexi',
			full: 'flecto, flectere, flexi, flexus',
			translation: 'turn, bend',
			type: 'pfacind1s',
		},
		496: {
			word: 'flevi',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'pfacind1s',
		},
		497: {
			word: 'fluxi',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'pfacind1s',
		},
		498: {
			word: 'gemui',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'pfacind1s',
		},
		499: {
			word: 'mersi',
			full: 'mergo, mergere, mersi, mersus',
			translation: 'sink, submerge',
			type: 'pfacind1s',
		},
		500: {
			word: 'finxi',
			full: 'fingo, fingere, finxi, fictum',
			translation: 'fabricate, invent',
			type: 'pfacind1s',
		},
		501: {
			word: 'mulsi',
			full: 'mulceo, mulcere, mulsi, mulsus',
			translation: 'soothe, appease',
			type: 'pfacind1s',
		},
		502: {
			word: 'ademi',
			full: 'adimo, adimere, ademi, ademptus',
			translation: 'take away',
			type: 'pfacind1s',
		},
		503: {
			word: 'cessi',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'pfacind1s',
		},
		504: {
			word: 'laesi',
			full: 'laedo, laedere, laesi, laesus',
			translation: 'hurt, harm',
			type: 'pfacind1s',
		},
		505: {
			word: 'evasi',
			full: 'evado, evadere, evasi, evasus',
			translation: 'escape',
			type: 'pfacind1s',
		},
		506: {
			word: 'erexi',
			full: 'erigo, erigere, erexi, erectus',
			translation: 'raise, build, rouse',
			type: 'pfacind1s',
		},
		507: {
			word: 'iunxi',
			full: 'iungo, iungere, iunxi, iunctus',
			translation: 'join',
			type: 'pfacind1s',
		},
		508: {
			word: 'obrui',
			full: 'obruo, obruere, obrui, obrutus',
			translation: 'overwhelm, cover',
			type: 'pfacind1s',
		},
		509: {
			word: 'elusi',
			full: 'eludo, eludere, elusi, elusus',
			translation: 'ward off, escape, mock',
			type: 'pfacind1s',
		},
		510: {
			word: 'haesi',
			full: 'haereo, haerere, haesi, haesum',
			translation: 'stick, cling',
			type: 'pfacind1s',
		},
		511: {
			word: 'omisi',
			full: 'omitto, omittere, omisi, omissus',
			translation: 'abandon, leave',
			type: 'pfacind1s',
		},
		512: {
			word: 'argui',
			full: 'arguo, arguere, argui, argutus',
			translation: 'prove, accuse, denounce',
			type: 'pfacind1s',
		},
		513: {
			word: 'aravi',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'pfacind1s',
		},
		514: {
			word: 'adegi',
			full: 'adigo, adigere, adegi, adactum',
			translation: 'thrust, drive, stab',
			type: 'pfacind1s',
		},
		515: {
			word: 'colui',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'pfacind1s',
		},
		516: {
			word: 'indui',
			full: 'induo, induere, indui, indutum',
			translation: 'put on, dress in',
			type: 'pfacind1s',
		},
		517: {
			word: 'tacui',
			full: 'taceo, tacere, tacui, tacitum',
			translation: 'be silent',
			type: 'pfacind1s',
		},
		518: {
			word: 'vinxi',
			full: 'vincio, vincire, vinxi, vinctum',
			translation: 'tie up, bind',
			type: 'pfacind1s',
		},
		519: {
			word: 'minui',
			full: 'minuo, minuere, minui, minutum',
			translation: 'lessen, diminish',
			type: 'pfacind1s',
		},
		520: {
			word: 'nupsi',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'pfacind1s',
		},
		521: {
			word: 'suasi',
			full: 'suadeo, suadere, suasi, suasum',
			translation: 'urge, recommend, persuade, force',
			type: 'pfacind1s',
		},
		522: {
			word: 'dirui',
			full: 'diruo, diruere, dirui, dirutum',
			translation: 'demolish',
			type: 'pfacind1s',
		},
		523: {
			word: 'serui',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'pfacind1s',
		},
		524: {
			word: 'verti',
			full: 'verto, vertere, verti, versum',
			translation: 'turn, overthrow, destroy',
			type: 'pfacind1s',
		},
		525: {
			word: 'ussit',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'pfacind3s',
		},
		526: {
			word: 'iuvit',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'pfacind3s',
		},
		527: {
			word: 'arsit',
			full: 'ardeo, ardere, arsi, arsus',
			translation: 'blaze, be on fire, be on fire',
			type: 'pfacind3s',
		},
		528: {
			word: 'fudit',
			full: 'fundo, fundere, fudi, fusus',
			translation: 'pour, rout, put to flight',
			type: 'pfacind3s',
		},
		529: {
			word: 'fixit',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'pfacind3s',
		},
		530: {
			word: 'novit',
			full: 'nosco, noscere, novi, notum',
			translation: 'know',
			type: 'pfacind3s',
		},
		531: {
			word: 'fodit',
			full: 'fodio, fodere, fodi, fossum',
			translation: 'dig',
			type: 'pracind3s',
		},
		532: {
			word: 'fovit',
			full: 'foveo, fovere, fovi, fotum',
			translation: 'warm, cherish',
			type: 'pfacind3s',
		},
		533: {
			word: 'aluit',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'pfacind3s',
		},
		534: {
			word: 'lavit',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'pfacind3s',
		},
		535: {
			word: 'visit',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'pracind3s',
		},
		536: {
			word: 'ustus',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'ppp',
		},
		537: {
			word: 'iutus',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'ppp',
		},
		538: {
			word: 'arsus',
			full: 'ardeo, ardere, arsi, arsus',
			translation: 'blaze, be on fire, be on fire',
			type: 'ppp',
		},
		539: {
			word: 'fusus',
			full: 'fundo, fundere, fudi, fusus',
			translation: 'pour, rout, put to flight',
			type: 'ppp',
		},
		540: {
			word: 'fixus',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'ppp',
		},
		541: {
			word: 'notus',
			full: 'nosco, noscere, novi, notum',
			translation: 'know',
			type: 'ppp',
		},
		542: {
			word: 'essus',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'ppp',
		},
		543: {
			word: 'fotus',
			full: 'foveo, fovere, fovi, fotum',
			translation: 'warm, cherish',
			type: 'ppp',
		},
		544: {
			word: 'rutus',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'ppp',
		},
		545: {
			word: 'altus',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'ppp',
		},
		546: {
			word: 'visus',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'ppp',
		},
		547: {
			word: 'lanio',
			full: 'lanio, laniare, laniavi, laniatus',
			translation: 'tear, mutilate',
			type: 'pracind1s',
		},
		548: {
			word: 'perdo',
			full: 'perdo, perdere, perdidi, perditus',
			translation: 'destroy, ruin, lose, waste',
			type: 'pracind1s',
		},
		549: {
			word: 'salio',
			full: 'salio, salire, salui, saltus',
			translation: 'jump',
			type: 'pracind1s',
		},
		550: {
			word: 'spiro',
			full: 'spiro, spirare, spiravi, spiratus',
			translation: 'breathe, blow, be alive',
			type: 'pracind1s',
		},
		551: {
			word: 'tendo',
			full: 'tendo, tendere, tetendi, tensus',
			translation: 'stretch, extend, aim for, march',
			type: 'pracind1s',
		},
		552: {
			word: 'caedo',
			full: 'caedo, caedere, cecidi, caesus',
			translation: 'slaughter, kill',
			type: 'pracind1s',
		},
		553: {
			word: 'carpo',
			full: 'carpo, carpere, carpsi, carptus',
			translation: 'pluck, take',
			type: 'pracind1s',
		},
		554: {
			word: 'iacto',
			full: 'iacto, iactare, iactavi, iactatus',
			translation: 'throw, hurl, boast',
			type: 'pracind1s',
		},
		555: {
			word: 'lasso',
			full: 'lasso, lassare, lassavi, lassatus',
			translation: 'tire, exhaust, wear out',
			type: 'pracind1s',
		},
		556: {
			word: 'premo',
			full: 'premo, premere, pressi, pressus',
			translation: 'press, curb, overpower',
			type: 'pracind1s',
		},
		557: {
			word: 'cerno',
			full: 'cerno, cernere, crevi, cretus',
			translation: 'perceive, deceive',
			type: 'pracind1s',
		},
		558: {
			word: 'mereo',
			full: 'mereo, merere, merui, meritum',
			translation: 'deserve, earn',
			type: 'pracind1s',
		},
		559: {
			word: 'cingo',
			full: 'cingo, cingere, cinxi, cinctus',
			translation: 'surround',
			type: 'pracind1s',
		},
		560: {
			word: 'pingo',
			full: 'pingo, pingere, pinxi, pictum',
			translation: 'paint',
			type: 'pracind1s',
		},
		561: {
			word: 'surgo',
			full: 'surgo, surgere, surrexi, surrectus',
			translation: 'rise, rise up',
			type: 'pracind1s',
		},
		562: {
			word: 'turbo',
			full: 'turbo, turbare, turbavi, turbatum',
			translation: 'disturb, throw into confusion',
			type: 'pracind1s',
		},
		563: {
			word: 'cesso',
			full: 'cesso, cessare, cessavi, cessatus',
			translation: 'delay, do nothing, leave off',
			type: 'pracind1s',
		},
		564: {
			word: 'mergo',
			full: 'mergo, mergere, mersi, mersus',
			translation: 'sink, submerge',
			type: 'pracind1s',
		},
		565: {
			word: 'ardeo',
			full: 'ardeo, ardere, arsi, arsus',
			translation: 'blaze, be on fire, be on fire',
			type: 'pracind1s',
		},
		566: {
			word: 'fingo',
			full: 'fingo, fingere, finxi, fictum',
			translation: 'fabricate, invent',
			type: 'pracind1s',
		},
		567: {
			word: 'placo',
			full: 'placo, placare, placavi, placatum',
			translation: 'calm, soothe, placate',
			type: 'pracind1s',
		},
		568: {
			word: 'adimo',
			full: 'adimo, adimere, ademi, ademptus',
			translation: 'take away',
			type: 'pracind1s',
		},
		569: {
			word: 'condo',
			full: 'condo, condere, condidi, conditus',
			translation: 'build, found, establish',
			type: 'pracind1s',
		},
		570: {
			word: 'laedo',
			full: 'laedo, laedere, laesi, laesus',
			translation: 'hurt, harm',
			type: 'pracind1s',
		},
		571: {
			word: 'prodo',
			full: 'prodo, prodere, prodidi, proditus',
			translation: 'betray',
			type: 'pracind1s',
		},
		572: {
			word: 'struo',
			full: 'struo, struere, struxi, structus',
			translation: 'arrange, construct, draw up',
			type: 'pracind1s',
		},
		573: {
			word: 'evado',
			full: 'evado, evadere, evasi, evasus',
			translation: 'escape',
			type: 'pracind1s',
		},
		574: {
			word: 'erigo',
			full: 'erigo, erigere, erexi, erectus',
			translation: 'raise, build, rouse',
			type: 'pracind1s',
		},
		575: {
			word: 'iungo',
			full: 'iungo, iungere, iunxi, iunctus',
			translation: 'join',
			type: 'pracind1s',
		},
		576: {
			word: 'obruo',
			full: 'obruo, obruere, obrui, obrutus',
			translation: 'overwhelm, cover',
			type: 'pracind1s',
		},
		577: {
			word: 'pergo',
			full: 'pergo, pergere, perrexi, perrectus',
			translation: 'proceed, march, go on',
			type: 'pracind1s',
		},
		578: {
			word: 'probo',
			full: 'probo, probare, probavi, probatus',
			translation: 'approve, test, prove',
			type: 'pracind1s',
		},
		579: {
			word: 'eludo',
			full: 'eludo, eludere, elusi, elusus',
			translation: 'ward off, escape, mock',
			type: 'pracind1s',
		},
		580: {
			word: 'aequo',
			full: 'aequo, aequare, aequavi, aequatus',
			translation: 'equal, match, liken, compare',
			type: 'pracind1s',
		},
		581: {
			word: 'arguo',
			full: 'arguo, arguere, argui, argutus',
			translation: 'prove, accuse, denounce',
			type: 'pracind1s',
		},
		582: {
			word: 'mando',
			full: 'mando, mandare, mandavi, mandatum',
			translation: 'commit, entrust, command',
			type: 'pracind1s',
		},
		583: {
			word: 'vasto',
			full: 'vasto, vastare, vastavi, vastatum',
			translation: 'ravage, lay waste',
			type: 'pracind1s',
		},
		584: {
			word: 'agito',
			full: 'agito, agitare, agitavi, agitatum',
			translation: 'drive, agitate, disturb, consider',
			type: 'pracind1s',
		},
		585: {
			word: 'firmo',
			full: 'firmo, firmare, firmavi, firmatum',
			translation: 'strengthen',
			type: 'pracind1s',
		},
		586: {
			word: 'nosco',
			full: 'nosco, noscere, novi, notum',
			translation: 'know',
			type: 'pracind1s',
		},
		587: {
			word: 'parco',
			full: 'parco, parcere, peperci, parsum (+ dat.)',
			translation: 'spare',
			type: 'pracind1s',
		},
		588: {
			word: 'adigo',
			full: 'adigo, adigere, adegi, adactum',
			translation: 'thrust, drive, stab',
			type: 'pracind1s',
		},
		589: {
			word: 'bello',
			full: 'bello, bellare, bellavi, belatum',
			translation: 'wage war, fight',
			type: 'pracind1s',
		},
		590: {
			word: 'fodio',
			full: 'fodio, fodere, fodi, fossum',
			translation: 'dig',
			type: 'pracind1s',
		},
		591: {
			word: 'foveo',
			full: 'foveo, fovere, fovi, fotum',
			translation: 'warm, cherish',
			type: 'pracind1s',
		},
		592: {
			word: 'induo',
			full: 'induo, induere, indui, indutum',
			translation: 'put on, dress in',
			type: 'pracind1s',
		},
		593: {
			word: 'taceo',
			full: 'taceo, tacere, tacui, tacitum',
			translation: 'be silent',
			type: 'pracind1s',
		},
		594: {
			word: 'trado',
			full: 'trado, tradere, tradidi, traditum',
			translation: 'hand over, record',
			type: 'pracind1s',
		},
		595: {
			word: 'minuo',
			full: 'minuo, minuere, minui, minutum',
			translation: 'lessen, diminish',
			type: 'pracind1s',
		},
		596: {
			word: 'salto',
			full: 'salto, saltare, saltavi, saltatum',
			translation: 'dance',
			type: 'pracind1s',
		},
		597: {
			word: 'diruo',
			full: 'diruo, diruere, dirui, dirutum',
			translation: 'demolish',
			type: 'pracind1s',
		},
		598: {
			word: 'verto',
			full: 'verto, vertere, verti, versum',
			translation: 'turn, overthrow, destroy',
			type: 'pracind1s',
		},
		599: {
			word: 'violo',
			full: 'violo, violare, violavi, violatum',
			translation: 'violate, defile',
			type: 'pracind1s',
		},
		600: {
			word: 'creas',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'pracind2s',
		},
		601: {
			word: 'salis',
			full: 'salio, salire, salui, saltus',
			translation: 'jump',
			type: 'pracind2s',
		},
		602: {
			word: 'tonas',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'pracind2s',
		},
		603: {
			word: 'velas',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'pracind2s',
		},
		604: {
			word: 'volas',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'pracind2s',
		},
		605: {
			word: 'meres',
			full: 'mereo, merere, merui, meritum',
			translation: 'deserve, earn',
			type: 'pracind2s',
		},
		606: {
			word: 'domas',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'pracind2s',
		},
		607: {
			word: 'iuvas',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'pracind2s',
		},
		608: {
			word: 'optas',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'pracind2s',
		},
		609: {
			word: 'sonas',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'pracind2s',
		},
		610: {
			word: 'abdis',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'pracind2s',
		},
		611: {
			word: 'fluis',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'pracind2s',
		},
		612: {
			word: 'gemis',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'pracind2s',
		},
		613: {
			word: 'donas',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'pracind2s',
		},
		614: {
			word: 'iuras',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'pracind2s',
		},
		615: {
			word: 'ardes',
			full: 'ardeo, ardere, arsi, arsus',
			translation: 'blaze, be on fire, be on fire',
			type: 'pracind2s',
		},
		616: {
			word: 'cedis',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'pracind2s',
		},
		617: {
			word: 'citas',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'pracind2s',
		},
		618: {
			word: 'dedis',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'pracind2s',
		},
		619: {
			word: 'locas',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'pracind2s',
		},
		620: {
			word: 'figis',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'pracind2s',
		},
		621: {
			word: 'levas',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'pracind2s',
		},
		622: {
			word: 'colis',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'pracind2s',
		},
		623: {
			word: 'fodis',
			full: 'fodio, fodere, fodi, fossum',
			translation: 'dig',
			type: 'pracind2s',
		},
		624: {
			word: 'foves',
			full: 'foveo, fovere, fovi, fotum',
			translation: 'warm, cherish',
			type: 'pracind2s',
		},
		625: {
			word: 'taces',
			full: 'taceo, tacere, tacui, tacitum',
			translation: 'be silent',
			type: 'pracind2s',
		},
		626: {
			word: 'cenas',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'pracind2s',
		},
		627: {
			word: 'lavas',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'pracind2s',
		},
		628: {
			word: 'nudas',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'pracind2s',
		},
		629: {
			word: 'pacas',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'pracind2s',
		},
		630: {
			word: 'duras',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'pracind2s',
		},
		631: {
			word: 'fugas',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'pracind2s',
		},
		632: {
			word: 'secas',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'pracind2s',
		},
		633: {
			word: 'seris',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'pracind2s',
		},
		634: {
			word: 'vexas',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'pracind2s',
		},
		635: {
			word: 'visis',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'pracind2s',
		},
		636: {
			word: 'urunt',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'pracind3pl',
		},
		637: {
			word: 'flent',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'pracind3pl',
		},
		638: {
			word: 'arant',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'pracind3pl',
		},
		639: {
			word: 'edunt',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'pracind3pl',
		},
		640: {
			word: 'ruunt',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'pracind3pl',
		},
		641: {
			word: 'alunt',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'pracind3pl',
		},
		642: {
			word: 'creat',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'pracind3s',
		},
		643: {
			word: 'salit',
			full: 'salio, salire, salui, saltus',
			translation: 'jump',
			type: 'pracind3s',
		},
		644: {
			word: 'tonat',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'pracind3s',
		},
		645: {
			word: 'velat',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'pracind3s',
		},
		646: {
			word: 'volat',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'pracind3s',
		},
		647: {
			word: 'meret',
			full: 'mereo, merere, merui, meritum',
			translation: 'deserve, earn',
			type: 'pracind3s',
		},
		648: {
			word: 'domat',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'pracind3s',
		},
		649: {
			word: 'iuvat',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'pracind3s',
		},
		650: {
			word: 'optat',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'pracind3s',
		},
		651: {
			word: 'sonat',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'pracind3s',
		},
		652: {
			word: 'abdit',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'pracind3s',
		},
		653: {
			word: 'fluit',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'pracind3s',
		},
		654: {
			word: 'gemit',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'pracind3s',
		},
		655: {
			word: 'donat',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'pracind3s',
		},
		656: {
			word: 'iurat',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'pracind3s',
		},
		657: {
			word: 'ardet',
			full: 'ardeo, ardere, arsi, arsus',
			translation: 'blaze, be on fire, be on fire',
			type: 'pracind3s',
		},
		658: {
			word: 'cedit',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'pracind3s',
		},
		659: {
			word: 'citat',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'pracind3s',
		},
		660: {
			word: 'dedit',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'pracind3s',
		},
		661: {
			word: 'locat',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'pracind3s',
		},
		662: {
			word: 'figit',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'pracind3s',
		},
		663: {
			word: 'levat',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'pracind3s',
		},
		664: {
			word: 'colit',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'pracind3s',
		},
		665: {
			word: 'fovet',
			full: 'foveo, fovere, fovi, fotum',
			translation: 'warm, cherish',
			type: 'pracind3s',
		},
		666: {
			word: 'tacet',
			full: 'taceo, tacere, tacui, tacitum',
			translation: 'be silent',
			type: 'pracind3s',
		},
		667: {
			word: 'cenat',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'pracind3s',
		},
		668: {
			word: 'lavat',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'pracind3s',
		},
		669: {
			word: 'nubit',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'pracind3s',
		},
		670: {
			word: 'nudat',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'pracind3s',
		},
		671: {
			word: 'pacat',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'pracind3s',
		},
		672: {
			word: 'durat',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'pracind3s',
		},
		673: {
			word: 'fugat',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'pracind3s',
		},
		674: {
			word: 'secat',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'pracind3s',
		},
		675: {
			word: 'serit',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'pracind3s',
		},
		676: {
			word: 'vexat',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'pracind3s',
		},
		677: {
			word: 'creem',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'pracsuj1s',
		},
		678: {
			word: 'tonem',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'pracsuj1s',
		},
		679: {
			word: 'velem',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'pracsuj1s',
		},
		680: {
			word: 'volem',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'pracsuj1s',
		},
		681: {
			word: 'domem',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'pracsuj1s',
		},
		682: {
			word: 'iuvem',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'pracsuj1s',
		},
		683: {
			word: 'optem',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'pracsuj1s',
		},
		684: {
			word: 'sonem',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'pracsuj1s',
		},
		685: {
			word: 'fleam',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'pracsuj1s',
		},
		686: {
			word: 'donem',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'pracsuj1s',
		},
		687: {
			word: 'iurem',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'pracsuj1s',
		},
		688: {
			word: 'citem',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'pracsuj1s',
		},
		689: {
			word: 'locem',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'pracsuj1s',
		},
		690: {
			word: 'levem',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'pracsuj1s',
		},
		691: {
			word: 'cenem',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'pracsuj1s',
		},
		692: {
			word: 'lavem',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'pracsuj1s',
		},
		693: {
			word: 'nudem',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'pracsuj1s',
		},
		694: {
			word: 'pacem',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'pracsuj1s',
		},
		695: {
			word: 'durem',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'pracsuj1s',
		},
		696: {
			word: 'fugem',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'pracsuj1s',
		},
		697: {
			word: 'secem',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'pracsuj1s',
		},
		698: {
			word: 'vexem',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'pracsuj1s',
		},
		699: {
			word: 'crees',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'pracsuj2s',
		},
		700: {
			word: 'tones',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'pracsuj2s',
		},
		701: {
			word: 'veles',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'pracsuj2s',
		},
		702: {
			word: 'voles',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'pracsuj2s',
		},
		703: {
			word: 'domes',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'pracsuj2s',
		},
		704: {
			word: 'iuves',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'pracsuj2s',
		},
		705: {
			word: 'optes',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'pracsuj2s',
		},
		706: {
			word: 'sones',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'pracsuj2s',
		},
		707: {
			word: 'abdas',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'pracsuj2s',
		},
		708: {
			word: 'fleas',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'pracsuj2s',
		},
		709: {
			word: 'fluas',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'pracsuj2s',
		},
		710: {
			word: 'gemas',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'pracsuj2s',
		},
		711: {
			word: 'dones',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'pracsuj2s',
		},
		712: {
			word: 'iures',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'pracsuj2s',
		},
		713: {
			word: 'cedas',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'pracsuj2s',
		},
		714: {
			word: 'cites',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'pracsuj2s',
		},
		715: {
			word: 'dedas',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'pracsuj2s',
		},
		716: {
			word: 'loces',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'pracsuj2s',
		},
		717: {
			word: 'figas',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'pracsuj2s',
		},
		718: {
			word: 'leves',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'pracsuj2s',
		},
		719: {
			word: 'colas',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'pracsuj2s',
		},
		720: {
			word: 'cenes',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'pracsuj2s',
		},
		721: {
			word: 'laves',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'pracsuj2s',
		},
		722: {
			word: 'nubas',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'pracsuj2s',
		},
		723: {
			word: 'nudes',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'pracsuj2s',
		},
		724: {
			word: 'paces',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'pracsuj2s',
		},
		725: {
			word: 'dures',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'pracsuj2s',
		},
		726: {
			word: 'fuges',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'pracsuj2s',
		},
		727: {
			word: 'seces',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'pracsuj2s',
		},
		728: {
			word: 'seras',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'pracsuj2s',
		},
		729: {
			word: 'vexes',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'pracsuj2s',
		},
		730: {
			word: 'visas',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'pracsuj2s',
		},
		731: {
			word: 'urant',
			full: 'uro, urere, ussi, ustus',
			translation: 'burning, heart, love, passion',
			type: 'pracsuj3pl',
		},
		732: {
			word: 'arent',
			full: 'aro, arare, aravi, aratum',
			translation: 'plough',
			type: 'pracsuj3pl',
		},
		733: {
			word: 'edant',
			full: 'edo, edere, edidi, editum',
			translation: 'put forth, produce, utter, proclaim',
			type: 'pracsuj3pl',
		},
		734: {
			word: 'ruant',
			full: 'ruo, ruere, rui, rutum',
			translation: 'rush, charge, collapse, fall in ruin',
			type: 'pracsuj3pl',
		},
		735: {
			word: 'alant',
			full: 'alo, alere, alui, alitum',
			translation: 'nourish, bring up',
			type: 'pracsuj3pl',
		},
		736: {
			word: 'creet',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'pracsuj3s',
		},
		737: {
			word: 'tonet',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'pracsuj3s',
		},
		738: {
			word: 'velet',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'pracsuj3s',
		},
		739: {
			word: 'volet',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'pracsuj3s',
		},
		740: {
			word: 'domet',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'pracsuj3s',
		},
		741: {
			word: 'iuvet',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'pracsuj3s',
		},
		742: {
			word: 'optet',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'pracsuj3s',
		},
		743: {
			word: 'sonet',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'pracsuj3s',
		},
		744: {
			word: 'abdat',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'pracsuj3s',
		},
		745: {
			word: 'fleat',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'pracsuj3s',
		},
		746: {
			word: 'fluat',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'pracsuj3s',
		},
		747: {
			word: 'gemat',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'pracsuj3s',
		},
		748: {
			word: 'donet',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'pracsuj3s',
		},
		749: {
			word: 'iuret',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'pracsuj3s',
		},
		750: {
			word: 'cedat',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'pracsuj3s',
		},
		751: {
			word: 'citet',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'pracsuj3s',
		},
		752: {
			word: 'dedat',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'pracsuj3s',
		},
		753: {
			word: 'locet',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'pracsuj3s',
		},
		754: {
			word: 'figat',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'pracsuj3s',
		},
		755: {
			word: 'levet',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'pracsuj3s',
		},
		756: {
			word: 'colat',
			full: 'colo, colere, colui, cultum',
			translation: 'cultivate, worship, honour',
			type: 'pracsuj3s',
		},
		757: {
			word: 'cenet',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'pracsuj3s',
		},
		758: {
			word: 'lavet',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'pracsuj3s',
		},
		759: {
			word: 'nubat',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'pracsuj3s',
		},
		760: {
			word: 'nudet',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'pracsuj3s',
		},
		761: {
			word: 'pacet',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'pracsuj3s',
		},
		762: {
			word: 'duret',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'pracsuj3s',
		},
		763: {
			word: 'fuget',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'pracsuj3s',
		},
		764: {
			word: 'secet',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'pracsuj3s',
		},
		765: {
			word: 'serat',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'pracsuj3s',
		},
		766: {
			word: 'vexet',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'pracsuj3s',
		},
		767: {
			word: 'visat',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'pracsuj3s',
		},
		768: {
			word: 'creor',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'prpaind1s',
		},
		769: {
			word: 'tonor',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'prpaind1s',
		},
		770: {
			word: 'velor',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'prpaind1s',
		},
		771: {
			word: 'volor',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'prpaind1s',
		},
		772: {
			word: 'domor',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'prpaind1s',
		},
		773: {
			word: 'iuvor',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'prpaind1s',
		},
		774: {
			word: 'optor',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'prpaind1s',
		},
		775: {
			word: 'sonor',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'prpaind1s',
		},
		776: {
			word: 'abdor',
			full: 'abdo, abdere, abdidi, abditus',
			translation: 'hide',
			type: 'prpaind1s',
		},
		777: {
			word: 'fleor',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'prpaind1s',
		},
		778: {
			word: 'fluor',
			full: 'fluo, fluere, fluxi, fluctus',
			translation: 'flow',
			type: 'prpaind1s',
		},
		779: {
			word: 'gemor',
			full: 'gemo, gemere, gemui, gemitum',
			translation: 'moan, groan',
			type: 'prpaind1s',
		},
		780: {
			word: 'donor',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'prpaind1s',
		},
		781: {
			word: 'iuror',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'prpaind1s',
		},
		782: {
			word: 'cedor',
			full: 'cedo, cedere, cessi, cessus',
			translation: 'yield',
			type: 'prpaind1s',
		},
		783: {
			word: 'citor',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'prpaind1s',
		},
		784: {
			word: 'dedor',
			full: 'dedo, dedere, dedidi, deditus',
			translation: 'surrender',
			type: 'prpaind1s',
		},
		785: {
			word: 'locor',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'prpaind1s',
		},
		786: {
			word: 'figor',
			full: 'figo, figere, fixi, fixus',
			translation: 'fix, attach',
			type: 'prpaind1s',
		},
		787: {
			word: 'levor',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'prpaind1s',
		},
		788: {
			word: 'cenor',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'prpaind1s',
		},
		789: {
			word: 'lavor',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'prpaind1s',
		},
		790: {
			word: 'nubor',
			full: 'nubo, nubere, nupsi, nuptum',
			translation: 'marry (a husband)',
			type: 'prpaind1s',
		},
		791: {
			word: 'nudor',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'prpaind1s',
		},
		792: {
			word: 'pacor',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'prpaind1s',
		},
		793: {
			word: 'duror',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'prpaind1s',
		},
		794: {
			word: 'fugor',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'prpaind1s',
		},
		795: {
			word: 'secor',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'prpaind1s',
		},
		796: {
			word: 'seror',
			full: 'sero, serere, sevi, satum',
			translation: 'sow, plant, beget',
			type: 'prpaind1s',
		},
		797: {
			word: 'vexor',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'prpaind1s',
		},
		798: {
			word: 'visor',
			full: 'viso, visere, visi, visum',
			translation: 'visit, look at',
			type: 'prpaind1s',
		},
		799: {
			word: 'creer',
			full: 'creo, creare, creavi, creatum',
			translation: 'create, make, elect',
			type: 'prpasuj1s',
		},
		800: {
			word: 'toner',
			full: 'tono, tonare, tonui, tonitus',
			translation: 'thunder',
			type: 'prpasuj1s',
		},
		801: {
			word: 'veler',
			full: 'velo, velare, velavi, velatus',
			translation: 'cover, clothe, conceal',
			type: 'prpasuj1s',
		},
		802: {
			word: 'voler',
			full: 'volo, volare, volavi, volatum',
			translation: 'fly',
			type: 'prpasuj1s',
		},
		803: {
			word: 'domer',
			full: 'domo, domare, domui, domitus',
			translation: 'subdue, overcome',
			type: 'prpasuj1s',
		},
		804: {
			word: 'iuver',
			full: 'iuvo, iuvare, iuvi, iutus',
			translation: 'help, am pleasing, be pleasing',
			type: 'prpasuj1s',
		},
		805: {
			word: 'opter',
			full: 'opto, optare, optavi, optatum',
			translation: 'wish for, choose',
			type: 'prpasuj1s',
		},
		806: {
			word: 'soner',
			full: 'sono, sonare, sonui, sonitum',
			translation: 'make a noise',
			type: 'prpasuj1s',
		},
		807: {
			word: 'flear',
			full: 'fleo, flere, flevi, fletum',
			translation: 'weep, lament',
			type: 'prpasuj1s',
		},
		808: {
			word: 'doner',
			full: 'dono, donare, donavi, donatus',
			translation: 'present, gift, bestow',
			type: 'prpasuj1s',
		},
		809: {
			word: 'iurer',
			full: 'iuro, iurare, iuravi, iuratum',
			translation: 'swear',
			type: 'prpasuj1s',
		},
		810: {
			word: 'citer',
			full: 'cito, citare, citavi, citatus',
			translation: 'summon, stir up',
			type: 'prpasuj1s',
		},
		811: {
			word: 'locer',
			full: 'loco, locare, locavi, locatus',
			translation: 'place, station',
			type: 'prpasuj1s',
		},
		812: {
			word: 'lever',
			full: 'levo, levare, levavi, levatus',
			translation: 'raise, lift',
			type: 'prpasuj1s',
		},
		813: {
			word: 'cener',
			full: 'ceno, cenare, cenavi, cenatum',
			translation: 'dine, have dinner',
			type: 'prpasuj1s',
		},
		814: {
			word: 'laver',
			full: 'lavo, lavare, lavi, lautus',
			translation: 'bathe, wash',
			type: 'prpasuj1s',
		},
		815: {
			word: 'nuder',
			full: 'nudo, nudare, nudavi, nudatum',
			translation: 'strip, plunder',
			type: 'prpasuj1s',
		},
		816: {
			word: 'pacer',
			full: 'paco, pacare, pacavi, pacatum',
			translation: 'bring under control, subdue',
			type: 'prpasuj1s',
		},
		817: {
			word: 'durer',
			full: 'duro, durare, duravi, duratum',
			translation: 'make hard, endure',
			type: 'prpasuj1s',
		},
		818: {
			word: 'fuger',
			full: 'fugo, fugare, fugavi, fugatum',
			translation: 'fruit, crops',
			type: 'prpasuj1s',
		},
		819: {
			word: 'secer',
			full: 'seco, secare, secui, sectum',
			translation: 'cut, cut off',
			type: 'prpasuj1s',
		},
		820: {
			word: 'vexer',
			full: 'vexo, vexare, vexavi, vexatum',
			translation: 'disturb, annoy, upset',
			type: 'prpasuj1s',
		},
		821: {
			word: 'lecte',
			full: 'lectus, lecti, m',
			translation: 'bed, couch',
			type: 'vocs',
		},
		822: {
			word: 'taure',
			full: 'taurus, tauri, m',
			translation: 'bull',
			type: 'vocs',
		},
		823: {
			word: 'umere',
			full: 'umerus, umeri, m',
			translation: 'shoulder',
			type: 'vocs',
		},
		824: {
			word: 'ponte',
			full: 'pontus, ponti, m',
			translation: 'sea',
			type: 'vocs',
		},
		825: {
			word: 'clive',
			full: 'clivus, clivi, m',
			translation: 'slope, hill',
			type: 'vocs',
		},
		826: {
			word: 'vulge',
			full: 'vulgus, vulgi, n',
			translation: 'crowd, common people',
			type: 'vocs',
		},
		827: {
			word: 'anule',
			full: 'anulus, anuli, m',
			translation: 'ring',
			type: 'vocs',
		},
		828: {
			word: 'omine',
			full: 'omen, ominis, n',
			translation: 'sign, omen',
			type: 'vocs',
		},
		829: {
			word: 'numme',
			full: 'nummus, nummi, m',
			translation: 'coin, money',
			type: 'vocs',
		},
	},
];
