var gcseList = [
	{
		1: {
			word: 'agant',
			full: 'ago, agere, egi, actus',
			translation: 'do, act, drive',
			type: 'pracsuj3pl',
		},
		2: {
			word: 'dabis',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'ftacind2s',
		},
		3: {
			word: 'duxit',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'pfacind3s',
		},
		4: {
			word: 'vocat',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'pracind3s',
		},
		5: {
			word: 'narra',
			full: 'narro, narrare, narravi, narratus',
			translation: 'tell, relate',
			type: 'imps',
		},
		6: {
			word: 'orare',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'infpr',
		},
		7: {
			word: 'parui',
			full: 'pareo, parere, parui + dat',
			translation: 'obey',
			type: 'pfacind1s',
		},
		8: {
			word: 'geram',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'pracsuj1s',
		},
		9: {
			word: 'vinco',
			full: 'vinco, vincere, vici, victus',
			translation: 'conquer, win, be victorious',
			type: 'pracind1s',
		},
		10: {
			word: 'ponet',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'ftacind3s',
		},
		11: {
			word: 'cibos',
			full: 'cibus, cibi, m.',
			translation: 'food',
			type: 'accp',
		},
		12: {
			word: 'serve',
			full: 'servus, servi, m.',
			translation: 'slave',
			type: 'vocs',
		},
		13: {
			word: 'servo',
			full: 'servus, servi, m.',
			translation: 'slave',
			type: 'dats',
		},
		14: {
			word: 'amans',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'pap',
		},
		15: {
			word: 'ement',
			full: 'emo, emere, emi, emptus',
			translation: 'buy',
			type: 'ftacind3pl',
		},
		16: {
			word: 'cogar',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'prpasuj1s',
		},
		17: {
			word: 'legio',
			full: 'legio, legionis, f.',
			translation: 'legion',
			type: 'vocs',
		},
		18: {
			word: 'puffl',
			full: 'a, ab + abl (also used as prefix with verbs)',
			translation: 'from, by, away',
			type: 'noms',
		},
		19: {
			word: 'dicis',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'pracind2s',
		},
		20: {
			word: 'annum',
			full: 'annus, anni, m.',
			translation: 'year',
			type: 'accs',
		},
		21: {
			word: 'celor',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'prpaind1s',
		},
		22: {
			word: 'videt',
			full: 'video, videre, vidi, visus',
			translation: 'see',
			type: 'pracind3s',
		},
		23: {
			word: 'audio',
			full: 'audio, audire, audivi, auditus',
			translation: 'hear, listen to',
			type: 'pracind1s',
		},
		24: {
			word: 'cenas',
			full: 'cena, cenae, f.',
			translation: 'dinner, meal',
			type: 'accp',
		},
		25: {
			word: 'modum',
			full: 'modus, modi, m.',
			translation: 'manner, way, kind',
			type: 'accs',
		},
		26: {
			word: 'mater',
			full: 'mater, matris, f.',
			translation: 'mother',
			type: 'vocs',
		},
		27: {
			word: 'emere',
			full: 'emo, emere, emi, emptus',
			translation: 'buy',
			type: 'infpr',
		},
		28: {
			word: 'misit',
			full: 'mitto, mittere, misi, missus',
			translation: 'send',
			type: 'pfacind3s',
		},
		29: {
			word: 'cenis',
			full: 'cena, cenae, f.',
			translation: 'dinner, meal',
			type: 'datp',
		},
		30: {
			word: 'bella',
			full: 'bellum, belli, n.',
			translation: 'war',
			type: 'vocp',
		},
		31: {
			word: 'curam',
			full: 'cura, curae, f.',
			translation: 'care, worry',
			type: 'accs',
		},
		32: {
			word: 'dicam',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'pracsuj1s',
		},
		33: {
			word: 'caput',
			full: 'caput, capitis, n.',
			translation: 'head',
			type: 'vocs',
		},
		34: {
			word: 'cibum',
			full: 'cibus, cibi, m.',
			translation: 'food',
			type: 'accs',
		},
		35: {
			word: 'darem',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'impacsuj1s',
		},
		36: {
			word: 'pacum',
			full: 'pax, pacis, f.',
			translation: 'peace',
			type: 'genp',
		},
		37: {
			word: 'amico',
			full: 'amicus, amici, m.',
			translation: 'friend',
			type: 'dats',
		},
		38: {
			word: 'iacit',
			full: 'iacio, iacere, ieci, iactus',
			translation: 'throw',
			type: 'pracind3s',
		},
		39: {
			word: 'cogat',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'pracsuj3s',
		},
		40: {
			word: 'agent',
			full: 'ago, agere, egi, actus',
			translation: 'do, act, drive',
			type: 'ftacind3pl',
		},
		41: {
			word: 'paces',
			full: 'pax, pacis, f.',
			translation: 'peace',
			type: 'vocp',
		},
		42: {
			word: 'forum',
			full: 'forum, fori, n.',
			translation: 'forum, market place, marketplace',
			type: 'vocs',
		},
		43: {
			word: 'ponit',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'pracind3s',
		},
		44: {
			word: 'caelo',
			full: 'caelum, caeli, n.',
			translation: 'sky, heaven',
			type: 'dats',
		},
		45: {
			word: 'maria',
			full: 'mare, maris, n.',
			translation: 'sea',
			type: 'vocp',
		},
		46: {
			word: 'filia',
			full: 'filia, filiae, f.',
			translation: 'daughter',
			type: 'vocs',
		},
		47: {
			word: 'cogor',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'prpaind1s',
		},
		48: {
			word: 'modus',
			full: 'modus, modi, m.',
			translation: 'manner, way, kind',
			type: 'noms',
		},
		49: {
			word: 'vivam',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'pracsuj1s',
		},
		50: {
			word: 'putem',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'pracsuj1s',
		},
		51: {
			word: 'taceo',
			full: 'taceo, tacere, tacui, tacitus',
			translation: 'be silent, be quiet',
			type: 'pracind1s',
		},
		52: {
			word: 'manet',
			full: 'maneo, manere, mansi',
			translation: 'remain, stay',
			type: 'pracind3s',
		},
		53: {
			word: 'horam',
			full: 'hora, horae, f.',
			translation: 'hour',
			type: 'accs',
		},
		54: {
			word: 'aquis',
			full: 'aqua, aquae, f.',
			translation: 'water',
			type: 'datp',
		},
		55: {
			word: 'legam',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'pracsuj1s',
		},
		56: {
			word: 'agens',
			full: 'ago, agere, egi, actus',
			translation: 'do, act, drive',
			type: 'pap',
		},
		57: {
			word: 'vivis',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'pracind2s',
		},
		58: {
			word: 'crede',
			full: 'credo, credere, credidi, creditus + dat',
			translation: 'believe, trust, have faith in',
			type: 'imps',
		},
		59: {
			word: 'ignem',
			full: 'ignis, ignis, m.',
			translation: 'fire',
			type: 'accs',
		},
		60: {
			word: 'agite',
			full: 'ago, agere, egi, actus',
			translation: 'do, act, drive',
			type: 'imppl',
		},
		61: {
			word: 'clamo',
			full: 'clamo, clamare, clamavi, clamatus',
			translation: 'shout',
			type: 'pracind1s',
		},
		62: {
			word: 'virum',
			full: 'vir, viri, m.',
			translation: 'man',
			type: 'accs',
		},
		63: {
			word: 'habui',
			full: 'habeo, habere, habui, habitus',
			translation: 'have',
			type: 'pfacind1s',
		},
		64: {
			word: 'datis',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'pracind2pl',
		},
		65: {
			word: 'vivit',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'pracind3s',
		},
		66: {
			word: 'scies',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'ftacind2s',
		},
		67: {
			word: 'habeo',
			full: 'habeo, habere, habui, habitus',
			translation: 'have',
			type: 'pracind1s',
		},
		68: {
			word: 'orant',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'pracind3pl',
		},
		69: {
			word: 'petam',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'pracsuj1s',
		},
		70: {
			word: 'regum',
			full: 'rex, regis, m.',
			translation: 'king',
			type: 'genp',
		},
		71: {
			word: 'datur',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'prpaind3s',
		},
		72: {
			word: 'paras',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'pracind2s',
		},
		73: {
			word: 'geres',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'ftacind2s',
		},
		74: {
			word: 'muros',
			full: 'murus, muri, m.',
			translation: 'wall',
			type: 'accp',
		},
		75: {
			word: 'emens',
			full: 'emo, emere, emi, emptus',
			translation: 'buy',
			type: 'pap',
		},
		76: {
			word: 'celes',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'pracsuj2s',
		},
		77: {
			word: 'datus',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'ppp',
		},
		78: {
			word: 'dabor',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'ftpaind1s',
		},
		79: {
			word: 'cadat',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'pracsuj3s',
		},
		80: {
			word: 'vixit',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'pfacind3s',
		},
		81: {
			word: 'parem',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'pracsuj1s',
		},
		82: {
			word: 'fiant',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'prpasuj3pl',
		},
		83: {
			word: 'ignes',
			full: 'ignis, ignis, m.',
			translation: 'fire',
			type: 'vocp',
		},
		84: {
			word: 'caeli',
			full: 'caelum, caeli, n.',
			translation: 'sky, heaven',
			type: 'gens',
		},
		85: {
			word: 'maneo',
			full: 'maneo, manere, mansi',
			translation: 'remain, stay',
			type: 'pracind1s',
		},
		86: {
			word: 'labor',
			full: 'labor, laboris, m.',
			translation: 'work',
			type: 'vocs',
		},
		87: {
			word: 'reddo',
			full: 'reddo, reddere, reddidi, redditus',
			translation: 'give back, restore',
			type: 'pracind1s',
		},
		88: {
			word: 'rogat',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'pracind3s',
		},
		89: {
			word: 'petet',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'ftacind3s',
		},
		90: {
			word: 'pedis',
			full: 'pes, pedis, m.',
			translation: 'foot, paw',
			type: 'gens',
		},
		91: {
			word: 'celat',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'pracind3s',
		},
		92: {
			word: 'rapis',
			full: 'rapio, rapere, rapui, raptus',
			translation: 'seize, grab',
			type: 'pracind2s',
		},
		93: {
			word: 'necat',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'pracind3s',
		},
		94: {
			word: 'murum',
			full: 'murus, muri, m.',
			translation: 'wall',
			type: 'accs',
		},
		95: {
			word: 'naves',
			full: 'navis, navis, f.',
			translation: 'ship',
			type: 'vocp',
		},
		96: {
			word: 'tollo',
			full: 'tollo, tollere, sustuli, sublatus',
			translation: 'raise, lift up',
			type: 'pracind1s',
		},
		97: {
			word: 'sciam',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'pracsuj1s',
		},
		98: {
			word: 'monti',
			full: 'mons, montis, m.',
			translation: 'mountain',
			type: 'dats',
		},
		99: {
			word: 'aufer',
			full: 'aufero, auferre, abstuli, ablatus',
			translation: 'take away, carry off, steal',
			type: 'imps',
		},
		100: {
			word: 'dives',
			full: 'dives, divitis',
			translation: 'rich',
			type: 'vocs',
		},
		101: {
			word: 'vocor',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'prpaind1s',
		},
		102: {
			word: 'tacet',
			full: 'taceo, tacere, tacui, tacitus',
			translation: 'be silent, be quiet',
			type: 'pracind3s',
		},
		103: {
			word: 'modos',
			full: 'modus, modi, m.',
			translation: 'manner, way, kind',
			type: 'accp',
		},
		104: {
			word: 'capis',
			full: 'capio, capere, cepi, captus',
			translation: 'take, catch, capture, adopt, adopt (a plan)',
			type: 'pracind2s',
		},
		105: {
			word: 'horas',
			full: 'hora, horae, f.',
			translation: 'hour',
			type: 'accp',
		},
		106: {
			word: 'dicas',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'pracsuj2s',
		},
		107: {
			word: 'necet',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'pracsuj3s',
		},
		108: {
			word: 'cenae',
			full: 'cena, cenae, f.',
			translation: 'dinner, meal',
			type: 'vocp',
		},
		109: {
			word: 'rapit',
			full: 'rapio, rapere, rapui, raptus',
			translation: 'seize, grab',
			type: 'pracind3s',
		},
		110: {
			word: 'orent',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'pracsuj3pl',
		},
		111: {
			word: 'rogas',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'pracind2s',
		},
		112: {
			word: 'venio',
			full: 'venio, venire, veni',
			translation: 'come',
			type: 'pracind1s',
		},
		113: {
			word: 'facis',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'pracind2s',
		},
		114: {
			word: 'horte',
			full: 'hortus, horti, m.',
			translation: 'garden',
			type: 'vocs',
		},
		115: {
			word: 'canis',
			full: 'canis, canis, m.',
			translation: 'dog',
			type: 'vocs',
		},
		116: {
			word: 'geras',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'pracsuj2s',
		},
		117: {
			word: 'civem',
			full: 'civis, civis, m.f.',
			translation: 'citizen',
			type: 'accs',
		},
		118: {
			word: 'caela',
			full: 'caelum, caeli, n.',
			translation: 'sky, heaven',
			type: 'vocp',
		},
		119: {
			word: 'parte',
			full: 'pars, partis, f.',
			translation: 'part',
			type: 'abls',
		},
		120: {
			word: 'necor',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'prpaind1s',
		},
		121: {
			word: 'vocem',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'pracsuj1s',
		},
		122: {
			word: 'navem',
			full: 'navis, navis, f.',
			translation: 'ship',
			type: 'accs',
		},
		123: {
			word: 'vultu',
			full: 'vultus, vultus, m.',
			translation: 'expression, face',
			type: 'abls',
		},
		124: {
			word: 'urbis',
			full: 'urbs, urbis, f.',
			translation: 'city',
			type: 'gens',
		},
		125: {
			word: 'iacis',
			full: 'iacio, iacere, ieci, iactus',
			translation: 'throw',
			type: 'pracind2s',
		},
		126: {
			word: 'cives',
			full: 'civis, civis, m.f.',
			translation: 'citizen',
			type: 'vocp',
		},
		127: {
			word: 'aquae',
			full: 'aqua, aquae, f.',
			translation: 'water',
			type: 'vocp',
		},
		128: {
			word: 'manui',
			full: 'manus, manus, f.',
			translation: 'hand, group of people',
			type: 'dats',
		},
		129: {
			word: 'cepit',
			full: 'capio, capere, cepi, captus',
			translation: 'take, catch, capture, adopt, adopt (a plan)',
			type: 'pfacind3s',
		},
		130: {
			word: 'sedeo',
			full: 'sedeo, sedere, sedi',
			translation: 'sit',
			type: 'pracind1s',
		},
		131: {
			word: 'legas',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'pracsuj2s',
		},
		132: {
			word: 'luces',
			full: 'lux, lucis, f.',
			translation: 'light, daylight',
			type: 'vocp',
		},
		133: {
			word: 'horti',
			full: 'hortus, horti, m.',
			translation: 'garden',
			type: 'vocp',
		},
		134: {
			word: 'aquam',
			full: 'aqua, aquae, f.',
			translation: 'water',
			type: 'accs',
		},
		135: {
			word: 'lauda',
			full: 'laudo, laudare, laudavi, laudatus',
			translation: 'praise',
			type: 'imps',
		},
		136: {
			word: 'venis',
			full: 'venio, venire, veni',
			translation: 'come',
			type: 'pracind2s',
		},
		137: {
			word: 'petar',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'prpasuj1s',
		},
		138: {
			word: 'stent',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'pracsuj3pl',
		},
		139: {
			word: 'locum',
			full: 'locus, loci, m.',
			translation: 'place',
			type: 'accs',
		},
		140: {
			word: 'ponis',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'pracind2s',
		},
		141: {
			word: 'cogas',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'pracsuj2s',
		},
		142: {
			word: 'lucis',
			full: 'lux, lucis, f.',
			translation: 'light, daylight',
			type: 'gens',
		},
		143: {
			word: 'monte',
			full: 'mons, montis, m.',
			translation: 'mountain',
			type: 'abls',
		},
		144: {
			word: 'puter',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'prpasuj1s',
		},
		145: {
			word: 'iacio',
			full: 'iacio, iacere, ieci, iactus',
			translation: 'throw',
			type: 'pracind1s',
		},
		146: {
			word: 'detis',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'pracsuj2pl',
		},
		147: {
			word: 'canem',
			full: 'canis, canis, m.',
			translation: 'dog',
			type: 'accs',
		},
		148: {
			word: 'coegi',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'pfacind1s',
		},
		149: {
			word: 'donis',
			full: 'donum, doni, n.',
			translation: 'gift, present',
			type: 'datp',
		},
		150: {
			word: 'visus',
			full: 'video, videre, vidi, visus',
			translation: 'see',
			type: 'ppp',
		},
		151: {
			word: 'celer',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'prpasuj1s',
		},
		152: {
			word: 'celas',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'pracind2s',
		},
		153: {
			word: 'curro',
			full: 'curro, currere, cucurri, cursus',
			translation: 'run',
			type: 'pracind1s',
		},
		154: {
			word: 'ianua',
			full: 'ianua, ianuae, f.',
			translation: 'door',
			type: 'vocs',
		},
		155: {
			word: 'nocte',
			full: 'nox, noctis, f.',
			translation: 'night',
			type: 'abls',
		},
		156: {
			word: 'reges',
			full: 'rex, regis, m.',
			translation: 'king',
			type: 'vocp',
		},
		157: {
			word: 'ponat',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'pracsuj3s',
		},
		158: {
			word: 'nocti',
			full: 'nox, noctis, f.',
			translation: 'night',
			type: 'dats',
		},
		159: {
			word: 'petor',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'prpaind1s',
		},
		160: {
			word: 'annos',
			full: 'annus, anni, m.',
			translation: 'year',
			type: 'accp',
		},
		161: {
			word: 'signa',
			full: 'signum, signi, n.',
			translation: 'sign, signal, seal',
			type: 'vocp',
		},
		162: {
			word: 'risus',
			full: 'rideo, ridere, risi',
			translation: 'laugh, smile',
			type: 'ppp',
		},
		163: {
			word: 'vocet',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'pracsuj3s',
		},
		164: {
			word: 'dedit',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'pfacind3s',
		},
		165: {
			word: 'verba',
			full: 'verbum, verbi, n.',
			translation: 'word',
			type: 'vocp',
		},
		166: {
			word: 'feres',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'ftacind2s',
		},
		167: {
			word: 'taces',
			full: 'taceo, tacere, tacui, tacitus',
			translation: 'be silent, be quiet',
			type: 'pracind2s',
		},
		168: {
			word: 'iubes',
			full: 'iubeo, iubere, iussi, iussus',
			translation: 'order',
			type: 'pracind2s',
		},
		169: {
			word: 'tulit',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'pfacind3s',
		},
		170: {
			word: 'canum',
			full: 'canis, canis, m.',
			translation: 'dog',
			type: 'genp',
		},
		171: {
			word: 'gerit',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'pracind3s',
		},
		172: {
			word: 'pater',
			full: 'pater, patris, m.',
			translation: 'father',
			type: 'vocs',
		},
		173: {
			word: 'vitas',
			full: 'vita, vitae, f.',
			translation: 'life',
			type: 'accp',
		},
		174: {
			word: 'uxori',
			full: 'uxor, uxoris, f.',
			translation: 'wife',
			type: 'dats',
		},
		175: {
			word: 'aperi',
			full: 'aperio, aperire, aperui, apertus',
			translation: 'open',
			type: 'imps',
		},
		176: {
			word: 'hoste',
			full: 'hostis, hostis, m.',
			translation: 'enemy',
			type: 'abls',
		},
		177: {
			word: 'dabam',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'impacind1s',
		},
		178: {
			word: 'stare',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'infpr',
		},
		179: {
			word: 'canes',
			full: 'canis, canis, m.',
			translation: 'dog',
			type: 'vocp',
		},
		180: {
			word: 'sedet',
			full: 'sedeo, sedere, sedi',
			translation: 'sit',
			type: 'pracind3s',
		},
		181: {
			word: 'legat',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'pracsuj3s',
		},
		182: {
			word: 'ducor',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'prpaind1s',
		},
		183: {
			word: 'amabo',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'ftacind1s',
		},
		184: {
			word: 'sensi',
			full: 'sentio, sentire, sensi, sensus',
			translation: 'feel, notice',
			type: 'pfacind1s',
		},
		185: {
			word: 'ferat',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'pracsuj3s',
		},
		186: {
			word: 'cadit',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'pracind3s',
		},
		187: {
			word: 'cibus',
			full: 'cibus, cibi, m.',
			translation: 'food',
			type: 'noms',
		},
		188: {
			word: 'nunti',
			full: 'nuntius, nuntii, m.',
			translation: 'messenger, message, news',
			type: 'vocs',
		},
		189: {
			word: 'legar',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'prpasuj1s',
		},
		190: {
			word: 'offer',
			full: 'offero, offerre, obtuli, oblatus',
			translation: 'offer',
			type: 'imps',
		},
		191: {
			word: 'manus',
			full: 'manus, manus, f.',
			translation: 'hand, group of people',
			type: 'vocs',
		},
		192: {
			word: 'filio',
			full: 'filius, filii, m.',
			translation: 'son',
			type: 'dats',
		},
		193: {
			word: 'ponar',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'prpasuj1s',
		},
		194: {
			word: 'murus',
			full: 'murus, muri, m.',
			translation: 'wall',
			type: 'noms',
		},
		195: {
			word: 'dabar',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'imppaind1s',
		},
		196: {
			word: 'celet',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'pracsuj3s',
		},
		197: {
			word: 'mitto',
			full: 'mitto, mittere, misi, missus',
			translation: 'send',
			type: 'pracind1s',
		},
		198: {
			word: 'pacem',
			full: 'pax, pacis, f.',
			translation: 'peace',
			type: 'accs',
		},
		199: {
			word: 'vitis',
			full: 'vita, vitae, f.',
			translation: 'life',
			type: 'datp',
		},
		200: {
			word: 'pedem',
			full: 'pes, pedis, m.',
			translation: 'foot, paw',
			type: 'accs',
		},
		201: {
			word: 'ducum',
			full: 'dux, ducis, m.',
			translation: 'leader',
			type: 'genp',
		},
		202: {
			word: 'geror',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'prpaind1s',
		},
		203: {
			word: 'cogam',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'pracsuj1s',
		},
		204: {
			word: 'hosti',
			full: 'hostis, hostis, m.',
			translation: 'enemy',
			type: 'dats',
		},
		205: {
			word: 'putet',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'pracsuj3s',
		},
		206: {
			word: 'aquas',
			full: 'aqua, aquae, f.',
			translation: 'water',
			type: 'accp',
		},
		207: {
			word: 'putes',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'pracsuj2s',
		},
		208: {
			word: 'cogit',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'pracind3s',
		},
		209: {
			word: 'vinis',
			full: 'vinum, vini, n.',
			translation: 'wine',
			type: 'datp',
		},
		210: {
			word: 'horto',
			full: 'hortus, horti, m.',
			translation: 'garden',
			type: 'dats',
		},
		211: {
			word: 'feret',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'ftacind3s',
		},
		212: {
			word: 'dicat',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'pracsuj3s',
		},
		213: {
			word: 'vidit',
			full: 'video, videre, vidi, visus',
			translation: 'see',
			type: 'pfacind3s',
		},
		214: {
			word: 'locos',
			full: 'locus, loci, m.',
			translation: 'place',
			type: 'accp',
		},
		215: {
			word: 'video',
			full: 'video, videre, vidi, visus',
			translation: 'see',
			type: 'pracind1s',
		},
		216: {
			word: 'fugis',
			full: 'fugio, fugere, fugi',
			translation: 'run away, flee',
			type: 'pracind2s',
		},
		217: {
			word: 'tacui',
			full: 'taceo, tacere, tacui, tacitus',
			translation: 'be silent, be quiet',
			type: 'pfacind1s',
		},
		218: {
			word: 'amate',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'imppl',
		},
		219: {
			word: 'signi',
			full: 'signum, signi, n.',
			translation: 'sign, signal, seal',
			type: 'gens',
		},
		220: {
			word: 'fimus',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'prpaind1pl',
		},
		221: {
			word: 'narro',
			full: 'narro, narrare, narravi, narratus',
			translation: 'tell, relate',
			type: 'pracind1s',
		},
		222: {
			word: 'filii',
			full: 'filius, filii, m.',
			translation: 'son',
			type: 'vocp',
		},
		223: {
			word: 'fiunt',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'prpaind3pl',
		},
		224: {
			word: 'pueri',
			full: 'puer, pueri, m.',
			translation: 'boy',
			type: 'vocp',
		},
		225: {
			word: 'credo',
			full: 'credo, credere, credidi, creditus + dat',
			translation: 'believe, trust, have faith in',
			type: 'pracind1s',
		},
		226: {
			word: 'silva',
			full: 'silva, silvae, f.',
			translation: 'wood',
			type: 'vocs',
		},
		227: {
			word: 'scivi',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'pfacind1s',
		},
		228: {
			word: 'cogis',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'pracind2s',
		},
		229: {
			word: 'modis',
			full: 'modus, modi, m.',
			translation: 'manner, way, kind',
			type: 'datp',
		},
		230: {
			word: 'ducem',
			full: 'dux, ducis, m.',
			translation: 'leader',
			type: 'vocs',
		},
		231: {
			word: 'morti',
			full: 'mors, mortis, f.',
			translation: 'death',
			type: 'dats',
		},
		232: {
			word: 'patri',
			full: 'pater, patris, m.',
			translation: 'father',
			type: 'dats',
		},
		233: {
			word: 'turba',
			full: 'turba, turbae, f.',
			translation: 'crowd',
			type: 'vocs',
		},
		234: {
			word: 'putas',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'pracind2s',
		},
		235: {
			word: 'damur',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'prpaind1pl',
		},
		236: {
			word: 'dixit',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'pfacind3s',
		},
		237: {
			word: 'ducar',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'prpasuj1s',
		},
		238: {
			word: 'voces',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'pracsuj2s',
		},
		239: {
			word: 'navis',
			full: 'navis, navis, f.',
			translation: 'ship',
			type: 'vocs',
		},
		240: {
			word: 'locis',
			full: 'locus, loci, m.',
			translation: 'place',
			type: 'datp',
		},
		241: {
			word: 'urbes',
			full: 'urbs, urbis, f.',
			translation: 'city',
			type: 'vocp',
		},
		242: {
			word: 'fient',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'ftpaind3pl',
		},
		243: {
			word: 'porto',
			full: 'porto, portare, portavi, portatus',
			translation: 'carry',
			type: 'pracind1s',
		},
		244: {
			word: 'cenam',
			full: 'cena, cenae, f.',
			translation: 'dinner, meal',
			type: 'accs',
		},
		245: {
			word: 'cibis',
			full: 'cibus, cibi, m.',
			translation: 'food',
			type: 'datp',
		},
		246: {
			word: 'tenet',
			full: 'teneo, tenere, tenui, tentus',
			translation: 'hold, keep, possess',
			type: 'pracind3s',
		},
		247: {
			word: 'pugno',
			full: 'pugno, pugnare, pugnavi',
			translation: 'fight',
			type: 'pracind1s',
		},
		248: {
			word: 'petas',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'pracsuj2s',
		},
		249: {
			word: 'iecit',
			full: 'iacio, iacere, ieci, iactus',
			translation: 'throw',
			type: 'pfacind3s',
		},
		250: {
			word: 'ducis',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'pracind2s',
		},
		251: {
			word: 'rebus',
			full: 'res, rei, f.',
			translation: 'thing, business, matter',
			type: 'datp',
		},
		252: {
			word: 'maris',
			full: 'mare, maris, n.',
			translation: 'sea',
			type: 'gens',
		},
		253: {
			word: 'tenes',
			full: 'teneo, tenere, tenui, tentus',
			translation: 'hold, keep, possess',
			type: 'pracind2s',
		},
		254: {
			word: 'traxi',
			full: 'traho, trahere, traxi, tractus',
			translation: 'drag, draw, pull',
			type: 'pfacind1s',
		},
		255: {
			word: 'senti',
			full: 'sentio, sentire, sensi, sensus',
			translation: 'feel, notice',
			type: 'imps',
		},
		256: {
			word: 'dares',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'impacsuj2s',
		},
		257: {
			word: 'soror',
			full: 'soror, sororis, f.',
			translation: 'sister',
			type: 'vocs',
		},
		258: {
			word: 'audit',
			full: 'audio, audire, audivi, auditus',
			translation: 'hear, listen to',
			type: 'pracind3s',
		},
		259: {
			word: 'vitae',
			full: 'vita, vitae, f.',
			translation: 'life',
			type: 'vocp',
		},
		260: {
			word: 'cadam',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'pracsuj1s',
		},
		261: {
			word: 'mansi',
			full: 'maneo, manere, mansi',
			translation: 'remain, stay',
			type: 'pfacind1s',
		},
		262: {
			word: 'dicar',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'prpasuj1s',
		},
		263: {
			word: 'regem',
			full: 'rex, regis, m.',
			translation: 'king',
			type: 'accs',
		},
		264: {
			word: 'ducit',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'pracind3s',
		},
		265: {
			word: 'equus',
			full: 'equus, equi, m.',
			translation: 'horse',
			type: 'noms',
		},
		266: {
			word: 'paror',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'prpaind1s',
		},
		267: {
			word: 'sciar',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'prpasuj1s',
		},
		268: {
			word: 'cupit',
			full: 'cupio, cupere, cupivi',
			translation: 'want, desire',
			type: 'pracind3s',
		},
		269: {
			word: 'putat',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'pracind3s',
		},
		270: {
			word: 'comes',
			full: 'comes, comitis, m.f.',
			translation: 'comrade, companion',
			type: 'vocs',
		},
		271: {
			word: 'vocas',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'pracind2s',
		},
		272: {
			word: 'necer',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'prpasuj1s',
		},
		273: {
			word: 'locus',
			full: 'locus, loci, m.',
			translation: 'place',
			type: 'noms',
		},
		274: {
			word: 'parti',
			full: 'pars, partis, f.',
			translation: 'part',
			type: 'dats',
		},
		275: {
			word: 'horae',
			full: 'hora, horae, f.',
			translation: 'hour',
			type: 'vocp',
		},
		276: {
			word: 'porta',
			full: 'porta, portae, f.',
			translation: 'gate',
			type: 'vocs',
		},
		277: {
			word: 'nesci',
			full: 'nescio, nescire, nescivi',
			translation: 'not know',
			type: 'imps',
		},
		278: {
			word: 'curre',
			full: 'curro, currere, cucurri, cursus',
			translation: 'run',
			type: 'imps',
		},
		279: {
			word: 'demus',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'pracsuj1pl',
		},
		280: {
			word: 'amare',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'infpr',
		},
		281: {
			word: 'agere',
			full: 'ago, agere, egi, actus',
			translation: 'do, act, drive',
			type: 'infpr',
		},
		282: {
			word: 'legit',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'pracind3s',
		},
		283: {
			word: 'scior',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'prpaind1s',
		},
		284: {
			word: 'lucum',
			full: 'lux, lucis, f.',
			translation: 'light, daylight',
			type: 'genp',
		},
		285: {
			word: 'parer',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'prpasuj1s',
		},
		286: {
			word: 'darer',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'imppasuj1s',
		},
		287: {
			word: 'patre',
			full: 'pater, patris, m.',
			translation: 'father',
			type: 'abls',
		},
		288: {
			word: 'manes',
			full: 'maneo, manere, mansi',
			translation: 'remain, stay',
			type: 'pracind2s',
		},
		289: {
			word: 'trahe',
			full: 'traho, trahere, traxi, tractus',
			translation: 'drag, draw, pull',
			type: 'imps',
		},
		290: {
			word: 'belli',
			full: 'bellum, belli, n.',
			translation: 'war',
			type: 'gens',
		},
		291: {
			word: 'villa',
			full: 'villa, villae, f.',
			translation: 'house, country house',
			type: 'vocs',
		},
		292: {
			word: 'vides',
			full: 'video, videre, vidi, visus',
			translation: 'see',
			type: 'pracind2s',
		},
		293: {
			word: 'fitis',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'prpaind2pl',
		},
		294: {
			word: 'vitam',
			full: 'vita, vitae, f.',
			translation: 'life',
			type: 'accs',
		},
		295: {
			word: 'dicor',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'prpaind1s',
		},
		296: {
			word: 'legor',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'prpaind1s',
		},
		297: {
			word: 'trade',
			full: 'trado, tradere, tradidi, traditus',
			translation: 'hand over',
			type: 'imps',
		},
		298: {
			word: 'vince',
			full: 'vinco, vincere, vici, victus',
			translation: 'conquer, win, be victorious',
			type: 'imps',
		},
		299: {
			word: 'vivet',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'ftacind3s',
		},
		300: {
			word: 'audis',
			full: 'audio, audire, audivi, auditus',
			translation: 'hear, listen to',
			type: 'pracind2s',
		},
		301: {
			word: 'roger',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'prpasuj1s',
		},
		302: {
			word: 'scite',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'imppl',
		},
		303: {
			word: 'cades',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'ftacind2s',
		},
		304: {
			word: 'pacis',
			full: 'pax, pacis, f.',
			translation: 'peace',
			type: 'gens',
		},
		305: {
			word: 'amori',
			full: 'amor, amoris, m.',
			translation: 'love',
			type: 'dats',
		},
		306: {
			word: 'fugio',
			full: 'fugio, fugere, fugi',
			translation: 'run away, flee',
			type: 'pracind1s',
		},
		307: {
			word: 'ament',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'pracsuj3pl',
		},
		308: {
			word: 'fugit',
			full: 'fugio, fugere, fugi',
			translation: 'run away, flee',
			type: 'pracind3s',
		},
		309: {
			word: 'habes',
			full: 'habeo, habere, habui, habitus',
			translation: 'have',
			type: 'pracind2s',
		},
		310: {
			word: 'petis',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'pracind2s',
		},
		311: {
			word: 'vivat',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'pracsuj3s',
		},
		312: {
			word: 'mitte',
			full: 'mitto, mittere, misi, missus',
			translation: 'send',
			type: 'imps',
		},
		313: {
			word: 'coget',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'ftacind3s',
		},
		314: {
			word: 'vives',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'ftacind2s',
		},
		315: {
			word: 'dicet',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'ftacind3s',
		},
		316: {
			word: 'emant',
			full: 'emo, emere, emi, emptus',
			translation: 'buy',
			type: 'pracsuj3pl',
		},
		317: {
			word: 'cupis',
			full: 'cupio, cupere, cupivi',
			translation: 'want, desire',
			type: 'pracind2s',
		},
		318: {
			word: 'rerum',
			full: 'res, rei, f.',
			translation: 'thing, business, matter',
			type: 'genp',
		},
		319: {
			word: 'damus',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'pracind1pl',
		},
		320: {
			word: 'signo',
			full: 'signum, signi, n.',
			translation: 'sign, signal, seal',
			type: 'dats',
		},
		321: {
			word: 'cadis',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'pracind2s',
		},
		322: {
			word: 'iubeo',
			full: 'iubeo, iubere, iussi, iussus',
			translation: 'order',
			type: 'pracind1s',
		},
		323: {
			word: 'verbi',
			full: 'verbum, verbi, n.',
			translation: 'word',
			type: 'gens',
		},
		324: {
			word: 'necem',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'pracsuj1s',
		},
		325: {
			word: 'rides',
			full: 'rideo, ridere, risi',
			translation: 'laugh, smile',
			type: 'pracind2s',
		},
		326: {
			word: 'traho',
			full: 'traho, trahere, traxi, tractus',
			translation: 'drag, draw, pull',
			type: 'pracind1s',
		},
		327: {
			word: 'bello',
			full: 'bellum, belli, n.',
			translation: 'war',
			type: 'dats',
		},
		328: {
			word: 'curis',
			full: 'cura, curae, f.',
			translation: 'care, worry',
			type: 'datp',
		},
		329: {
			word: 'dabat',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'impacind3s',
		},
		330: {
			word: 'parat',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'pracind3s',
		},
		331: {
			word: 'celem',
			full: 'celo, celare, celavi, celatus',
			translation: 'hide',
			type: 'pracsuj1s',
		},
		332: {
			word: 'equum',
			full: 'equus, equi, m.',
			translation: 'horse',
			type: 'accs',
		},
		333: {
			word: 'amice',
			full: 'amicus, amici, m.',
			translation: 'friend',
			type: 'vocs',
		},
		334: {
			word: 'teneo',
			full: 'teneo, tenere, tenui, tentus',
			translation: 'hold, keep, possess',
			type: 'pracind1s',
		},
		335: {
			word: 'dabit',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'ftacind3s',
		},
		336: {
			word: 'uxore',
			full: 'uxor, uxoris, f.',
			translation: 'wife',
			type: 'abls',
		},
		337: {
			word: 'facit',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'pracind3s',
		},
		338: {
			word: 'capio',
			full: 'capio, capere, cepi, captus',
			translation: 'take, catch, capture, adopt, adopt (a plan)',
			type: 'pracind1s',
		},
		339: {
			word: 'ignis',
			full: 'ignis, ignis, m.',
			translation: 'fire',
			type: 'vocs',
		},
		340: {
			word: 'feror',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'prpaind1s',
		},
		341: {
			word: 'pones',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'ftacind2s',
		},
		342: {
			word: 'petes',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'ftacind2s',
		},
		343: {
			word: 'duces',
			full: 'dux, ducis, m.',
			translation: 'leader',
			type: 'vocp',
		},
		344: {
			word: 'animi',
			full: 'animus, animi, m.',
			translation: 'spirit, soul, mind',
			type: 'vocp',
		},
		345: {
			word: 'emite',
			full: 'emo, emere, emi, emptus',
			translation: 'buy',
			type: 'imppl',
		},
		346: {
			word: 'muris',
			full: 'murus, muri, m.',
			translation: 'wall',
			type: 'datp',
		},
		347: {
			word: 'ponor',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'prpaind1s',
		},
		348: {
			word: 'curas',
			full: 'cura, curae, f.',
			translation: 'care, worry',
			type: 'accp',
		},
		349: {
			word: 'rogor',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'prpaind1s',
		},
		350: {
			word: 'roget',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'pracsuj3s',
		},
		351: {
			word: 'scire',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'infpr',
		},
		352: {
			word: 'petit',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'pracind3s',
		},
		353: {
			word: 'ponas',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'pracsuj2s',
		},
		354: {
			word: 'ridet',
			full: 'rideo, ridere, risi',
			translation: 'laugh, smile',
			type: 'pracind3s',
		},
		355: {
			word: 'deris',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'prpasuj2s',
		},
		356: {
			word: 'animo',
			full: 'animus, animi, m.',
			translation: 'spirit, soul, mind',
			type: 'dats',
		},
		357: {
			word: 'pedum',
			full: 'pes, pedis, m.',
			translation: 'foot, paw',
			type: 'genp',
		},
		358: {
			word: 'matri',
			full: 'mater, matris, f.',
			translation: 'mother',
			type: 'dats',
		},
		359: {
			word: 'cadar',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'prpasuj1s',
		},
		360: {
			word: 'sciat',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'pracsuj3s',
		},
		361: {
			word: 'gerat',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'pracsuj3s',
		},
		362: {
			word: 'geris',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'pracind2s',
		},
		363: {
			word: 'stans',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'pap',
		},
		364: {
			word: 'sciet',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'ftacind3s',
		},
		365: {
			word: 'rapio',
			full: 'rapio, rapere, rapui, raptus',
			translation: 'seize, grab',
			type: 'pracind1s',
		},
		366: {
			word: 'orans',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'pap',
		},
		367: {
			word: 'amant',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'pracind3pl',
		},
		368: {
			word: 'stabo',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'ftacind1s',
		},
		369: {
			word: 'annus',
			full: 'annus, anni, m.',
			translation: 'year',
			type: 'noms',
		},
		370: {
			word: 'horis',
			full: 'hora, horae, f.',
			translation: 'hour',
			type: 'datp',
		},
		371: {
			word: 'foris',
			full: 'forum, fori, n.',
			translation: 'forum, market place, marketplace',
			type: 'datp',
		},
		372: {
			word: 'paret',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'pracsuj3s',
		},
		373: {
			word: 'ponam',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'pracsuj1s',
		},
		374: {
			word: 'ducas',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'pracsuj2s',
		},
		375: {
			word: 'petat',
			full: 'peto, petere, petivi, petitus',
			translation: 'make for, attack, seek, beg, ask for',
			type: 'pracsuj3s',
		},
		376: {
			word: 'demur',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'prpasuj1pl',
		},
		377: {
			word: 'putor',
			full: 'puto, putare, putavi, putatus',
			translation: 'think',
			type: 'prpaind1s',
		},
		378: {
			word: 'fregi',
			full: 'frango, frangere, fregi, fractus',
			translation: 'break',
			type: 'pfacind1s',
		},
		379: {
			word: 'vivor',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'prpaind1s',
		},
		380: {
			word: 'daret',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'impacsuj3s',
		},
		381: {
			word: 'morte',
			full: 'mors, mortis, f.',
			translation: 'death',
			type: 'abls',
		},
		382: {
			word: 'habet',
			full: 'habeo, habere, habui, habitus',
			translation: 'have',
			type: 'pracind3s',
		},
		383: {
			word: 'orate',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'imppl',
		},
		384: {
			word: 'tolle',
			full: 'tollo, tollere, sustuli, sublatus',
			translation: 'raise, lift up',
			type: 'imps',
		},
		385: {
			word: 'neces',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'pracsuj2s',
		},
		386: {
			word: 'servi',
			full: 'servus, servi, m.',
			translation: 'slave',
			type: 'vocp',
		},
		387: {
			word: 'vende',
			full: 'vendo, vendere, vendidi, venditus',
			translation: 'sell',
			type: 'imps',
		},
		388: {
			word: 'scias',
			full: 'scio, scire, scivi, scitus',
			translation: 'know',
			type: 'pracsuj2s',
		},
		389: {
			word: 'ferte',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'imppl',
		},
		390: {
			word: 'sedes',
			full: 'sedeo, sedere, sedi',
			translation: 'sit',
			type: 'pracind2s',
		},
		391: {
			word: 'facio',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'pracind1s',
		},
		392: {
			word: 'cupio',
			full: 'cupio, cupere, cupivi',
			translation: 'want, desire',
			type: 'pracind1s',
		},
		393: {
			word: 'curae',
			full: 'cura, curae, f.',
			translation: 'care, worry',
			type: 'vocp',
		},
		394: {
			word: 'amavi',
			full: 'amo, amare, amavi, amatus',
			translation: 'love, like',
			type: 'pfacind1s',
		},
		395: {
			word: 'trado',
			full: 'trado, tradere, tradidi, traditus',
			translation: 'hand over',
			type: 'pracind1s',
		},
		396: {
			word: 'donum',
			full: 'donum, doni, n.',
			translation: 'gift, present',
			type: 'vocs',
		},
		397: {
			word: 'viris',
			full: 'vir, viri, m.',
			translation: 'man',
			type: 'datp',
		},
		398: {
			word: 'pareo',
			full: 'pareo, parere, parui + dat',
			translation: 'obey',
			type: 'pracind1s',
		},
		399: {
			word: 'lucem',
			full: 'lux, lucis, f.',
			translation: 'light, daylight',
			type: 'accs',
		},
		400: {
			word: 'sedit',
			full: 'sedeo, sedere, sedi',
			translation: 'sit',
			type: 'pfacind3s',
		},
		401: {
			word: 'state',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'imppl',
		},
		402: {
			word: 'geret',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'ftacind3s',
		},
		403: {
			word: 'feram',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'pracsuj1s',
		},
		404: {
			word: 'ferre',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'infpr',
		},
		405: {
			word: 'risit',
			full: 'rideo, ridere, risi',
			translation: 'laugh, smile',
			type: 'pfacind3s',
		},
		406: {
			word: 'laudo',
			full: 'laudo, laudare, laudavi, laudatus',
			translation: 'praise',
			type: 'pracind1s',
		},
		407: {
			word: 'venit',
			full: 'venio, venire, veni',
			translation: 'come',
			type: 'pracind3s',
		},
		408: {
			word: 'posui',
			full: 'pono, ponere, posui, positus',
			translation: 'put, place, put up',
			type: 'pfacind1s',
		},
		409: {
			word: 'dabas',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'impacind2s',
		},
		410: {
			word: 'ducet',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'ftacind3s',
		},
		411: {
			word: 'daris',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'prpaind2s',
		},
		412: {
			word: 'vicit',
			full: 'vinco, vincere, vici, victus',
			translation: 'conquer, win, be victorious',
			type: 'pfacind3s',
		},
		413: {
			word: 'vivar',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'prpasuj1s',
		},
		414: {
			word: 'vivas',
			full: 'vivo, vivere, vixi',
			translation: 'live, be alive',
			type: 'pracsuj2s',
		},
		415: {
			word: 'pares',
			full: 'paro, parare, paravi, paratus',
			translation: 'prepare',
			type: 'pracsuj2s',
		},
		416: {
			word: 'rogem',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'pracsuj1s',
		},
		417: {
			word: 'cadas',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'pracsuj2s',
		},
		418: {
			word: 'anime',
			full: 'animus, animi, m.',
			translation: 'spirit, soul, mind',
			type: 'vocs',
		},
		419: {
			word: 'cador',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'prpaind1s',
		},
		420: {
			word: 'ducat',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'pracsuj3s',
		},
		421: {
			word: 'viros',
			full: 'vir, viri, m.',
			translation: 'man',
			type: 'accp',
		},
		422: {
			word: 'pugna',
			full: 'pugno, pugnare, pugnavi',
			translation: 'fight',
			type: 'imps',
		},
		423: {
			word: 'leges',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'ftacind2s',
		},
		424: {
			word: 'vinum',
			full: 'vinum, vini, n.',
			translation: 'wine',
			type: 'vocs',
		},
		425: {
			word: 'vendo',
			full: 'vendo, vendere, vendidi, venditus',
			translation: 'sell',
			type: 'pracind1s',
		},
		426: {
			word: 'amici',
			full: 'amicus, amici, m.',
			translation: 'friend',
			type: 'vocp',
		},
		427: {
			word: 'place',
			full: 'placeo, placere, placui + dat',
			translation: 'please',
			type: 'imps',
		},
		428: {
			word: 'dices',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'ftacind2s',
		},
		429: {
			word: 'clama',
			full: 'clamo, clamare, clamavi, clamatus',
			translation: 'shout',
			type: 'imps',
		},
		430: {
			word: 'amore',
			full: 'amor, amoris, m.',
			translation: 'love',
			type: 'abls',
		},
		431: {
			word: 'nauta',
			full: 'nauta, nautae, m.',
			translation: 'sailor',
			type: 'vocs',
		},
		432: {
			word: 'equis',
			full: 'equus, equi, m.',
			translation: 'horse',
			type: 'datp',
		},
		433: {
			word: 'dormi',
			full: 'dormio, dormire, dormivi',
			translation: 'sleep',
			type: 'imps',
		},
		434: {
			word: 'civis',
			full: 'civis, civis, m.f.',
			translation: 'citizen',
			type: 'vocs',
		},
		435: {
			word: 'ferar',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'prpasuj1s',
		},
		436: {
			word: 'feras',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'pracsuj2s',
		},
		437: {
			word: 'detur',
			full: 'do, dare, dedi, datus',
			translation: 'give',
			type: 'prpasuj3s',
		},
		438: {
			word: 'equos',
			full: 'equus, equi, m.',
			translation: 'horse',
			type: 'accp',
		},
		439: {
			word: 'fecit',
			full: 'facio, facere, feci, factus',
			translation: 'make, do',
			type: 'pfacind3s',
		},
		440: {
			word: 'latus',
			full: 'fero, ferre, tuli, latus',
			translation: 'bring, carry, bear',
			type: 'ppp',
		},
		441: {
			word: 'leget',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'ftacind3s',
		},
		442: {
			word: 'ducam',
			full: 'duco, ducere, duxi, ductus',
			translation: 'lead, take',
			type: 'pracsuj1s',
		},
		443: {
			word: 'gerar',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'prpasuj1s',
		},
		444: {
			word: 'cadet',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'ftacind3s',
		},
		445: {
			word: 'regis',
			full: 'rex, regis, m.',
			translation: 'king',
			type: 'gens',
		},
		446: {
			word: 'gessi',
			full: 'gero, gerere, gessi, gestus',
			translation: 'wear (clothes), wage (war)',
			type: 'pfacind1s',
		},
		447: {
			word: 'manum',
			full: 'manus, manus, f.',
			translation: 'hand, group of people',
			type: 'accs',
		},
		448: {
			word: 'pedes',
			full: 'pes, pedis, m.',
			translation: 'foot, paw',
			type: 'vocp',
		},
		449: {
			word: 'necas',
			full: 'neco, necare, necavi, necatus',
			translation: 'kill',
			type: 'pracind2s',
		},
		450: {
			word: 'emunt',
			full: 'emo, emere, emi, emptus',
			translation: 'buy',
			type: 'pracind3pl',
		},
		451: {
			word: 'terra',
			full: 'terra, terrae, f.',
			translation: 'ground, land',
			type: 'vocs',
		},
		452: {
			word: 'stant',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'pracind3pl',
		},
		453: {
			word: 'coges',
			full: 'cogo, cogere, coegi, coactus',
			translation: 'force, compel',
			type: 'ftacind2s',
		},
		454: {
			word: 'vocer',
			full: 'voco, vocare, vocavi, vocatus',
			translation: 'call',
			type: 'prpasuj1s',
		},
		455: {
			word: 'matre',
			full: 'mater, matris, f.',
			translation: 'mother',
			type: 'abls',
		},
		456: {
			word: 'casus',
			full: 'cado, cadere, cecidi, casus',
			translation: 'fall',
			type: 'ppp',
		},
		457: {
			word: 'annis',
			full: 'annus, anni, m.',
			translation: 'year',
			type: 'datp',
		},
		458: {
			word: 'tenui',
			full: 'teneo, tenere, tenui, tentus',
			translation: 'hold, keep, possess',
			type: 'pfacind1s',
		},
		459: {
			word: 'rideo',
			full: 'rideo, ridere, risi',
			translation: 'laugh, smile',
			type: 'pracind1s',
		},
		460: {
			word: 'agunt',
			full: 'ago, agere, egi, actus',
			translation: 'do, act, drive',
			type: 'pracind3pl',
		},
		461: {
			word: 'capit',
			full: 'capio, capere, cepi, captus',
			translation: 'take, catch, capture, adopt, adopt (a plan)',
			type: 'pracind3s',
		},
		462: {
			word: 'redde',
			full: 'reddo, reddere, reddidi, redditus',
			translation: 'give back, restore',
			type: 'imps',
		},
		463: {
			word: 'poena',
			full: 'poena, poenae, f.',
			translation: 'punishment',
			type: 'vocs',
		},
		464: {
			word: 'orabo',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'ftacind1s',
		},
		465: {
			word: 'verbo',
			full: 'verbum, verbi, n.',
			translation: 'word',
			type: 'dats',
		},
		466: {
			word: 'roges',
			full: 'rogo, rogare, rogavi, rogatus',
			translation: 'ask, ask for',
			type: 'pracsuj2s',
		},
		467: {
			word: 'steti',
			full: 'sto, stare, steti',
			translation: 'stand',
			type: 'pfacind1s',
		},
		468: {
			word: 'legis',
			full: 'lego, legere, legi, lectus',
			translation: 'read, choose',
			type: 'pracind2s',
		},
		469: {
			word: 'miles',
			full: 'miles, militis, m.',
			translation: 'soldier',
			type: 'vocs',
		},
		470: {
			word: 'dicit',
			full: 'dico, dicere, dixi, dictus',
			translation: 'say',
			type: 'pracind3s',
		},
		471: {
			word: 'oravi',
			full: 'oro, orare, oravi, oratus',
			translation: 'beg, beg for',
			type: 'pfacind1s',
		},
		472: {
			word: 'rapui',
			full: 'rapio, rapere, rapui, raptus',
			translation: 'seize, grab',
			type: 'pfacind1s',
		},
		473: {
			word: 'iubet',
			full: 'iubeo, iubere, iussi, iussus',
			translation: 'order',
			type: 'pracind3s',
		},
		474: {
			word: 'urbem',
			full: 'urbs, urbis, f.',
			translation: 'city',
			type: 'accs',
		},
		475: {
			word: 'puero',
			full: 'puer, pueri, m.',
			translation: 'boy',
			type: 'dats',
		},
		476: {
			word: 'iussi',
			full: 'iubeo, iubere, iussi, iussus',
			translation: 'order',
			type: 'pfacind1s',
		},
	},
];
