var vocab = [
	{
		word: 'a, ab + abl',
		category: 'prep',
		translation: 'from, by',
		asked: false,
	},
	{
		word: 'absum, abesse, afui',
		category: 'verb irreg',
		translation: 'be absent, be away, be distant',
		asked: false,
	},
	{
		word: 'ac, atque',
		category: 'conjunction',
		translation: 'and',
		asked: false,
	},
	{
		word: 'accido, accidere, accidi',
		category: 'verb 3',
		translation: 'happen',
		asked: false,
	},
	{
		word: 'accipio, accipere, accepi, acceptus',
		category: 'verb 3',
		translation: 'accept, take in, receive, hear',
		asked: false,
	},
	{
		word: 'acer, acris, acre',
		category: 'adj',
		translation: 'keen, sharp, fierce',
		asked: false,
	},
	{
		word: 'acies, aciei, f',
		category: 'noun 5',
		translation: 'line, battle line, army',
		asked: false,
	},
	{
		word: 'ad + acc',
		category: 'prep',
		translation: 'to, towards, at, about, near',
		asked: false,
	},
	{
		word: 'addo, addere, addidi, additus',
		category: 'verb 3',
		translation: 'add, join',
		asked: false,
	},
	{
		word: 'adeo',
		category: 'adverb',
		translation: 'so much, so greatly, to such an extent',
		asked: false,
	},
	{
		word: 'adhuc',
		category: 'adverb',
		translation: 'till now, still',
		asked: false,
	},
	{
		word: 'adimo, adimere, ademi, ademptus',
		category: 'verb 3',
		translation: 'take away, remove',
		asked: false,
	},
	{
		word: 'adipiscor, adipisci, adeptus sum',
		category: 'verb 3 dep',
		translation: 'obtain',
		asked: false,
	},
	{
		word: 'adiuvo, adiuvare, adiuvi, adiutus',
		category: 'verb 1',
		translation: 'help',
		asked: false,
	},
	{
		word: 'adsum, adesse, adfui',
		category: 'verb irreg',
		translation: 'be here, be present',
		asked: false,
	},
	{
		word: 'adulescens, adulescentis, m',
		category: 'noun 3',
		translation: 'youth, young man',
		asked: false,
	},
	{
		word: 'advenio, advenire, adveni',
		category: 'verb 4',
		translation: 'arrive',
		asked: false,
	},
	{
		word: 'adversus + acc',
		category: 'prep',
		translation: 'against, towards',
		asked: false,
	},
	{
		word: 'adversus',
		category: 'adverb',
		translation: 'against, opposite',
		asked: false,
	},
	{
		word: 'aedificium, aedificii, n',
		category: 'noun 2',
		translation: 'building',
		asked: false,
	},
	{
		word: 'aedifico, aedificare, aedificavi, aedificatus',
		category: 'verb 1',
		translation: 'build',
		asked: false,
	},
	{
		word: 'aequus, aequa, aequum',
		category: 'adj',
		translation: 'equal, fair, favourable, calm',
		asked: false,
	},
	{
		word: 'ager, agri, m',
		category: 'noun 2',
		translation: 'field, land, territory',
		asked: false,
	},
	{
		word: 'aggredior, aggredi, aggressus sum',
		category: 'verb 3 dep',
		translation: 'attack, approach',
		asked: false,
	},
	{
		word: 'agmen, agminis, n',
		category: 'noun 3',
		translation: 'column of men, army',
		asked: false,
	},
	{
		word: 'ago, agere, egi, actus',
		category: 'verb 3',
		translation: 'do, act, drive',
		asked: false,
	},
	{
		word: 'aliquis, aliquid',
		category: 'pron',
		translation: 'someone, something, anyone, anything',
		asked: false,
	},
	{
		word: 'alius, alia, aliud',
		category: 'pron and adj',
		translation: 'other, one, another, else',
		asked: false,
	},
	{
		word: 'alter, altera, alterum',
		category: 'pron and adj',
		translation: 'the other, one (of two), another, a second',
		asked: false,
	},
	{
		word: 'altus, alta, altum',
		category: 'adj',
		translation: 'high, deep',
		asked: false,
	},
	{
		word: 'ambulo, ambulare, ambulavi',
		category: 'verb 1',
		translation: 'walk',
		asked: false,
	},
	{
		word: 'amica, amicae f',
		category: 'noun 1',
		translation: 'girl-friend, female friend',
		asked: false,
	},
	{
		word: 'amicus, amici m',
		category: 'noun 2',
		translation: 'friend',
		asked: false,
	},
	{
		word: 'amitto, amittere, amisi, amissus',
		category: 'verb 3',
		translation: 'lose',
		asked: false,
	},
	{
		word: 'amo, amare, amavi, amatus',
		category: 'verb 1',
		translation: 'love, like',
		asked: false,
	},
	{
		word: 'amor, amoris, m',
		category: 'noun 3',
		translation: 'love',
		asked: false,
	},
	{
		word: 'an',
		category: 'conjunction',
		translation: 'or',
		asked: false,
	},
	{
		word: 'ancilla, ancillae, f',
		category: 'noun 1',
		translation: 'slave-girl, slave-woman',
		asked: false,
	},
	{
		word: 'angustus, angusta, angustum',
		category: 'adj',
		translation: 'narrow, confined',
		asked: false,
	},
	{
		word: 'animadverto, animadvertere, animadverti, animadversus',
		category: 'verb 3',
		translation: 'notice, observe',
		asked: false,
	},
	{
		word: 'animus, animi, m',
		category: 'noun 2',
		translation: 'spirit, soul, mind, courage',
		asked: false,
	},
	{
		word: 'annus, anni, m',
		category: 'noun 2',
		translation: 'year',
		asked: false,
	},
	{
		word: 'ante + acc',
		category: 'prep',
		translation: 'before, in front of',
		asked: false,
	},
	{
		word: 'antea',
		category: 'adverb',
		translation: 'before, previously',
		asked: false,
	},
	{
		word: 'antequam',
		category: 'conjunction',
		translation: 'before',
		asked: false,
	},
	{
		word: 'aperio, aperire, aperui, apertus',
		category: 'verb 4',
		translation: 'open, reveal, disclose',
		asked: false,
	},
	{
		word: 'appareo, apparere, apparui',
		category: 'verb 2',
		translation: 'appear',
		asked: false,
	},
	{
		word: 'appropinquo, appropinquare, appropinquavi + dat',
		category: 'verb 1',
		translation: 'approach, come near to',
		asked: false,
	},
	{
		word: 'apud + acc',
		category: 'prep',
		translation: 'among, at the house of, according to, in the opinion of',
		asked: false,
	},
	{
		word: 'aqua, aquae, f',
		category: 'noun 1',
		translation: 'water',
		asked: false,
	},
	{
		word: 'aquila, aquilae, f',
		category: 'noun 1',
		translation: 'eagle, standard',
		asked: false,
	},
	{
		word: 'ara, arae, f',
		category: 'noun 1',
		translation: 'altar',
		asked: false,
	},
	{
		word: 'arbor, arboris, f',
		category: 'noun 3',
		translation: 'tree',
		asked: false,
	},
	{
		word: 'arcesso, arcessere, arcessivi, arcessitus',
		category: 'verb 3',
		translation: 'summon, send for',
		asked: false,
	},
	{
		word: 'argentum, argenti, n',
		category: 'noun 2',
		translation: 'silver, money',
		asked: false,
	},
	{
		word: 'arma, armorum, n pl',
		category: 'noun 2',
		translation: 'arms, weapons, armour',
		asked: false,
	},
	{
		word: 'ars, artis, f',
		category: 'noun 3',
		translation: 'art, skill',
		asked: false,
	},
	{
		word: 'ascendo, ascendere, ascendi, ascensus',
		category: 'verb 3',
		translation: 'climb, go up',
		asked: false,
	},
	{
		word: 'at',
		category: 'conjunction',
		translation: 'but',
		asked: false,
	},
	{
		word: 'attonitus, attonita, attonitum',
		category: 'adj',
		translation: 'astonished, thunder-struck',
		asked: false,
	},
	{
		word: 'audax, audacis',
		category: 'adj',
		translation: 'bold, daring',
		asked: false,
	},
	{
		word: 'audeo, audere, ausus sum',
		category: 'verb semi-dep.',
		translation: 'dare',
		asked: false,
	},
	{
		word: 'audio, audire, audivi, auditus',
		category: 'verb 4',
		translation: 'hear, listen to',
		asked: false,
	},
	{
		word: 'aufero, auferre, abstuli, ablatus',
		category: 'verb 3',
		translation: 'take away, carry off, steal',
		asked: false,
	},
	{
		word: 'augeo, augere, auxi, auctus',
		category: 'verb 2',
		translation: 'increase, exaggerate',
		asked: false,
	},
	{
		word: 'aut',
		category: 'conjunction',
		translation: 'or, either',
		asked: false,
	},
	{
		word: 'autem',
		category: 'conjunction',
		translation: 'but, however',
		asked: false,
	},
	{
		word: 'auxilium, auxilii, n',
		category: 'noun 2',
		translation: 'help; (pl ) (auxiliary) troops',
		asked: false,
	},
	{
		word: 'bellum, belli, n',
		category: 'noun 2',
		translation: 'war',
		asked: false,
	},
	{
		word: 'bene',
		category: 'adverb',
		translation: 'well',
		asked: false,
	},
	{
		word: 'beneficium, beneficii, n',
		category: 'noun 2',
		translation: 'kindness, service, favour',
		asked: false,
	},
	{
		word: 'bibo, bibere, bibi',
		category: 'verb 3',
		translation: 'drink',
		asked: false,
	},
	{
		word: 'bis',
		category: 'adverb',
		translation: 'twice',
		asked: false,
	},
	{
		word: 'bona, bonorum, n pl',
		category: 'noun 2',
		translation: 'goods, possessions, property',
		asked: false,
	},
	{
		word: 'bonus, bona, bonum',
		category: 'adj',
		translation: 'good',
		asked: false,
	},
	{
		word: 'brevis, breve',
		category: 'adj',
		translation: 'short, brief',
		asked: false,
	},
	{
		word: 'cado, cadere, cecidi, casus',
		category: 'verb 3',
		translation: 'fall, perish',
		asked: false,
	},
	{
		word: 'caedes, caedis, f',
		category: 'noun 3',
		translation: 'slaughter, killing, murder',
		asked: false,
	},
	{
		word: 'caelum, caeli, n',
		category: 'noun 2',
		translation: 'sky, heaven',
		asked: false,
	},
	{
		word: 'campus, campi, m',
		category: 'noun 2',
		translation: 'plain, field',
		asked: false,
	},
	{
		word: 'canis, canis, m and f',
		category: 'noun 3',
		translation: 'dog',
		asked: false,
	},
	{
		word: 'cano, canere, cecini, cantus',
		category: 'verb 3',
		translation: 'sing, sound, play (of trumpets etc.)',
		asked: false,
	},
	{
		word: 'capio, capere, cepi, captus (in compounds -icio)',
		category: 'verb 3',
		translation: 'take, catch, capture',
		asked: false,
	},
	{
		word: 'captivus, captivi, m',
		category: 'noun 2',
		translation: 'captive, prisoner',
		asked: false,
	},
	{
		word: 'caput, capitis, n',
		category: 'noun 3',
		translation: 'head, person, life, capital',
		asked: false,
	},
	{
		word: 'carus, cara, carum',
		category: 'adj',
		translation: 'dear',
		asked: false,
	},
	{
		word: 'castra, castrorum, n pl',
		category: 'noun 2',
		translation: 'camp',
		asked: false,
	},
	{
		word: 'causa, causae, f',
		category: 'noun 1',
		translation: 'cause, reason, case',
		asked: false,
	},
	{
		word: 'causa + gen',
		category: 'noun 1',
		translation: 'for the sake of',
		asked: false,
	},
	{
		word: 'caveo, cavere, cavi, cautus',
		category: 'verb 2',
		translation: 'beware (of), take care',
		asked: false,
	},
	{
		word: 'cedo, cedere, cessi, cessus',
		category: 'verb 3',
		translation: 'yield, give up; (in compounds) go',
		asked: false,
	},
	{
		word: 'celer, celeris, celere',
		category: 'adj',
		translation: 'quick',
		asked: false,
	},
	{
		word: 'celo, celare, celavi, celatus',
		category: 'verb 1',
		translation: 'hide, conceal',
		asked: false,
	},
	{
		word: 'cena, cenae, f',
		category: 'noun 1',
		translation: 'dinner, meal',
		asked: false,
	},
	{
		word: 'centurio, centurionis, m',
		category: 'noun 3',
		translation: 'centurion',
		asked: false,
	},
	{
		word: 'cerno, cernere, crevi, cretus',
		category: 'verb 3',
		translation: 'see, perceive, decree',
		asked: false,
	},
	{
		word: 'certamen, certaminis, n',
		category: 'noun 3',
		translation: 'contest, battle, struggle',
		asked: false,
	},
	{
		word: 'certus, certa, certum',
		category: 'adj',
		translation: 'certain, sure, fixed',
		asked: false,
	},
	{
		word: 'certiorem facere',
		category: 'verb phrase',
		translation: 'inform',
		asked: false,
	},
	{
		word: 'ceteri, ceterae, cetera',
		category: 'adj',
		translation: 'the rest, the other',
		asked: false,
	},
	{
		word: 'cibus, cibi, m',
		category: 'noun 2',
		translation: 'food',
		asked: false,
	},
	{
		word: 'cingo, cingere, cinxi, cinctus',
		category: 'verb 3',
		translation: 'surround, enclose, gird',
		asked: false,
	},
	{
		word: 'circum, circa + acc',
		category: 'prep',
		translation: 'around, about',
		asked: false,
	},
	{
		word: 'civis, civis, m and f',
		category: 'noun 3',
		translation: 'citizen',
		asked: false,
	},
	{
		word: 'civitas, civitatis, f',
		category: 'noun 3',
		translation: 'citizenship, state, city, tribe',
		asked: false,
	},
	{
		word: 'clades, cladis, f',
		category: 'noun 3',
		translation: 'disaster, loss, defeat',
		asked: false,
	},
	{
		word: 'clam',
		category: 'adverb',
		translation: 'secretly',
		asked: false,
	},
	{
		word: 'clamo, clamare, clamavi, clamatus',
		category: 'verb 1',
		translation: 'shout, exclaim, proclaim',
		asked: false,
	},
	{
		word: 'clamor, clamoris, m',
		category: 'noun 3',
		translation: 'shout, uproar, noise',
		asked: false,
	},
	{
		word: 'clarus, clara, clarum',
		category: 'adj',
		translation: 'clear, famous, distinguished',
		asked: false,
	},
	{
		word: 'coepi, coepisse, coeptus',
		category: 'verb defective',
		translation: 'began',
		asked: false,
	},
	{
		word: 'cogito, cogitare, cogitavi, cogitatus',
		category: 'verb 1',
		translation: 'think, consider',
		asked: false,
	},
	{
		word: 'cognosco, cognoscere, cognovi, cognitus',
		category: 'verb 3',
		translation: 'get to know, find out, learn',
		asked: false,
	},
	{
		word: 'cogo, cogere, coegi, coactus',
		category: 'verb 3',
		translation: 'force, compel, drive, assemble',
		asked: false,
	},
	{
		word: 'cohors, cohortis, f',
		category: 'noun 3',
		translation: 'cohort, company',
		asked: false,
	},
	{
		word: 'colo, colere, colui, cultus',
		category: 'verb 3',
		translation: 'cultivate, worship, honour',
		asked: false,
	},
	{
		word: 'comes, comitis, m and f',
		category: 'noun 3',
		translation: 'comrade, companion',
		asked: false,
	},
	{
		word: 'committo, committere, commisi, commissus',
		category: 'verb 3',
		translation: 'commit, fight, begin (battle)',
		asked: false,
	},
	{
		word: 'comparo, comparare, comparavi, comparatus',
		category: 'verb 1',
		translation: 'prepare, provide, obtain, compare',
		asked: false,
	},
	{
		word: 'condemno, condemnare, condemnavi, condemnatus',
		category: 'verb 1',
		translation: 'convict, condemn',
		asked: false,
	},
	{
		word: 'condo, condere, condidi, conditus',
		category: 'verb 3',
		translation: 'found, establish, hide',
		asked: false,
	},
	{
		word: 'confero, conferre, contuli, conlatus',
		category: 'verb irreg',
		translation: 'collect, compare, contribute, bestow',
		asked: false,
	},
	{
		word: 'conficio, conficere, confeci, confectus',
		category: 'verb 3',
		translation: 'complete, wear out',
		asked: false,
	},
	{
		word: 'confido, confidere, confisus sum + dat',
		category: 'verb semi-dep',
		translation: 'trust, believe, have confidence (in)',
		asked: false,
	},
	{
		word: 'coniunx, coniugis, m and f',
		category: 'noun 3',
		translation: 'husband, wife, spouse',
		asked: false,
	},
	{
		word: 'conor, conari, conatus sum',
		category: 'verb 1 dep',
		translation: 'try',
		asked: false,
	},
	{
		word: 'consilium, consilii, n',
		category: 'noun 2',
		translation: 'council, plan, advice, prudence',
		asked: false,
	},
	{
		word: 'consisto, consistere, constiti, constitus',
		category: 'verb 3',
		translation: 'halt, stand, stand firm',
		asked: false,
	},
	{
		word: 'conspicio, conspicere, conspexi, conspectus',
		category: 'verb 3',
		translation: 'notice, observe, see',
		asked: false,
	},
	{
		word: 'constituo, constituere, constitui, constitutus',
		category: 'verb 3',
		translation: 'decide, establish',
		asked: false,
	},
	{
		word: 'consul, consulis, m',
		category: 'noun 3',
		translation: 'consul',
		asked: false,
	},
	{
		word: 'consulo, consulere, consului, consultus',
		category: 'verb 3',
		translation: 'consult, consider, advise',
		asked: false,
	},
	{
		word: 'consumo, consumere, consumpsi, consumptus',
		category: 'verb 3',
		translation: 'eat, consume, spend',
		asked: false,
	},
	{
		word: 'contendo, contendere, contendi, contentus',
		category: 'verb 3',
		translation: 'hurry, march, contend, fight',
		asked: false,
	},
	{
		word: 'contra + acc',
		category: 'prep',
		translation: 'against',
		asked: false,
	},
	{
		word: 'copiae, copiarum, f pl',
		category: 'noun 1',
		translation: 'troops, forces, supplies',
		asked: false,
	},
	{
		word: 'corpus, corporis, n',
		category: 'noun 3',
		translation: 'body',
		asked: false,
	},
	{
		word: 'corripio, corripere, corripui, correptus',
		category: 'verb 3',
		translation: 'seize, carry off',
		asked: false,
	},
	{
		word: 'cotidie',
		category: 'adverb',
		translation: 'every day, daily',
		asked: false,
	},
	{
		word: 'cras',
		category: 'adverb',
		translation: 'tomorrow',
		asked: false,
	},
	{
		word: 'credo, credere, credidi, creditus + dat',
		category: 'verb 3',
		translation: 'believe, trust, entrust',
		asked: false,
	},
	{
		word: 'crimen, criminis, n',
		category: 'noun 3',
		translation: 'accusation, charge, crime',
		asked: false,
	},
	{
		word: 'crudelis, crudele',
		category: 'adj',
		translation: 'cruel',
		asked: false,
	},
	{
		word: 'culpa, culpae, f',
		category: 'noun 1',
		translation: 'fault, blame',
		asked: false,
	},
	{
		word: 'cum',
		category: 'conjunction',
		translation: 'when, since, although',
		asked: false,
	},
	{
		word: 'cum + abl',
		category: 'prep',
		translation: 'with',
		asked: false,
	},
	{
		word: 'cunctus, cuncta, cunctum',
		category: 'adj',
		translation: 'all, whole',
		asked: false,
	},
	{
		word: 'cupidus, cupida, cupidum + gen',
		category: 'adj',
		translation: 'eager (for), greedy',
		asked: false,
	},
	{
		word: 'cupio, cupere, cupivi, cupitus',
		category: 'verb 3',
		translation: 'desire, wish, want',
		asked: false,
	},
	{
		word: 'cur?',
		category: 'adverb',
		translation: 'why?',
		asked: false,
	},
	{
		word: 'cura, curae, f',
		category: 'noun 1',
		translation: 'care, charge, anxiety',
		asked: false,
	},
	{
		word: 'curo, curare, curavi, curatus',
		category: 'verb 1',
		translation: 'care for, cure; with gerundive = get something done',
		asked: false,
	},
	{
		word: 'curro, currere, cucurri, cursus',
		category: 'verb 3',
		translation: 'run',
		asked: false,
	},
	{
		word: 'custodio, custodire, custodivi, custoditus',
		category: 'verb 4',
		translation: 'guard',
		asked: false,
	},
	{
		word: 'custos, custodis, m and f',
		category: 'noun 3',
		translation: 'guard',
		asked: false,
	},
	{
		word: 'de + abl',
		category: 'prep',
		translation: 'about, from, down from',
		asked: false,
	},
	{
		word: 'dea, deae, f',
		category: 'noun 1',
		translation: 'goddess',
		asked: false,
	},
	{
		word: 'debeo, debere, debui, debitus',
		category: 'verb 2',
		translation: 'owe, ought',
		asked: false,
	},
	{
		word: 'decipio, decipere, decepi, deceptus',
		category: 'verb 3',
		translation: 'deceive',
		asked: false,
	},
	{
		word: 'defendo, defendere, defendi, defensus',
		category: 'verb 3',
		translation: 'defend',
		asked: false,
	},
	{
		word: 'defessus, defessa, defessum',
		category: 'adj',
		translation: 'tired',
		asked: false,
	},
	{
		word: 'deinde, dein',
		category: 'adverb',
		translation: 'then, next, afterwards',
		asked: false,
	},
	{
		word: 'deleo, delere, delevi, deletus',
		category: 'verb 2',
		translation: 'destroy',
		asked: false,
	},
	{
		word: 'denique',
		category: 'adverb',
		translation: 'at last, finally, in short',
		asked: false,
	},
	{
		word: 'descendo, descendere, descendi, descensus',
		category: 'verb 3',
		translation: 'descend, come down',
		asked: false,
	},
	{
		word: 'desino, desinere, desii, desitus',
		category: 'verb 3',
		translation: 'cease',
		asked: false,
	},
	{
		word: 'despero, desperare, desperavi, desperatus',
		category: 'verb 1',
		translation: 'despair',
		asked: false,
	},
	{
		word: 'deus, dei, m',
		category: 'noun 2',
		translation: 'god',
		asked: false,
	},
	{
		word: 'dexter, dextra, dextrum',
		category: 'adj',
		translation: 'right, on the right, right hand',
		asked: false,
	},
	{
		word: 'dextra, dextrae, f',
		category: 'noun 1',
		translation: 'right hand, right side',
		asked: false,
	},
	{
		word: 'dico, dicere, dixi, dictus',
		category: 'verb 3',
		translation: 'say, speak, tell',
		asked: false,
	},
	{
		word: 'dies, diei, m, occasionally f',
		category: 'noun 5',
		translation: 'day',
		asked: false,
	},
	{
		word: 'difficilis, difficile',
		category: 'adj',
		translation: 'difficult',
		asked: false,
	},
	{
		word: 'dignitas, dignitatis, f',
		category: 'noun 3',
		translation: 'rank, dignity, importance, honour',
		asked: false,
	},
	{
		word: 'dignus, digna, dignum + abl',
		category: 'adj',
		translation: 'worthy (of), deserving (of)',
		asked: false,
	},
	{
		word: 'diligens, diligentis',
		category: 'adj',
		translation: 'careful, diligent',
		asked: false,
	},
	{
		word: 'dimitto, dimittere, dimisi, dimissus',
		category: 'verb 3',
		translation: 'dismiss, scatter',
		asked: false,
	},
	{
		word: 'dirus, dira, dirum',
		category: 'adj',
		translation: 'dreadful',
		asked: false,
	},
	{
		word: 'discedo, discedere, discessi',
		category: 'verb 3',
		translation: 'depart, leave',
		asked: false,
	},
	{
		word: 'disco, discere, didici',
		category: 'verb 3',
		translation: 'learn',
		asked: false,
	},
	{
		word: 'dissimilis, dissimile',
		category: 'adj',
		translation: 'different',
		asked: false,
	},
	{
		word: 'diu',
		category: 'adverb',
		translation: 'for a long time',
		asked: false,
	},
	{
		word: 'dives, divitis',
		category: 'adj',
		translation: 'rich',
		asked: false,
	},
	{
		word: 'divitiae, divitiarum, f pl',
		category: 'noun 1',
		translation: 'riches, wealth',
		asked: false,
	},
	{
		word: 'divido, dividere, divisi, divisus',
		category: 'verb 3',
		translation: 'divide, separate',
		asked: false,
	},
	{
		word: 'do, dare, dedi, datus',
		category: 'verb 1',
		translation: 'give',
		asked: false,
	},
	{
		word: 'doceo, docere, docui, doctus',
		category: 'verb 2',
		translation: 'teach, inform',
		asked: false,
	},
	{
		word: 'doleo, dolere, dolui',
		category: 'verb 2',
		translation: 'hurt, be in pain, lament',
		asked: false,
	},
	{
		word: 'dolor, doloris, m',
		category: 'noun 3',
		translation: 'pain, sorrow, anger',
		asked: false,
	},
	{
		word: 'dolus, doli, m',
		category: 'noun 2',
		translation: 'trick, fraud',
		asked: false,
	},
	{
		word: 'domina, dominae, f',
		category: 'noun 2',
		translation: 'mistress',
		asked: false,
	},
	{
		word: 'dominus, domini, m',
		category: 'noun 2',
		translation: 'master',
		asked: false,
	},
	{
		word: 'domus, domus, f',
		category: 'noun 4',
		translation: 'house, home',
		asked: false,
	},
	{
		word: 'donum, doni, n',
		category: 'noun 2',
		translation: 'gift, present',
		asked: false,
	},
	{
		word: 'dormio, dormire, dormivi',
		category: 'verb 4',
		translation: 'sleep',
		asked: false,
	},
	{
		word: 'dubito, dubitare, dubitavi, dubitatus',
		category: 'verb 1',
		translation: 'doubt, hesitate',
		asked: false,
	},
	{
		word: 'dubius, dubia, dubium',
		category: 'adj',
		translation: 'doubtful, wavering, uncertain',
		asked: false,
	},
	{
		word: 'duco, ducere, duxi, ductus',
		category: 'verb 3',
		translation: 'lead, take, marry, consider',
		asked: false,
	},
	{
		word: 'dum',
		category: 'conjunction',
		translation: 'while, until, provided that',
		asked: false,
	},
	{
		word: 'durus, dura, durum',
		category: 'adj',
		translation: 'hard, harsh, rough',
		asked: false,
	},
	{
		word: 'dux, ducis, m',
		category: 'noun 3',
		translation: 'leader, general, ruler',
		asked: false,
	},
	{
		word: 'e, ex + abl',
		category: 'prep',
		translation: 'from, out of; (in compounds) out',
		asked: false,
	},
	{
		word: 'efficio, efficere, effeci, effectus',
		category: 'verb 3',
		translation: 'carry out, accomplish',
		asked: false,
	},
	{
		word: 'effugio, effugere, effugi',
		category: 'verb 3',
		translation: 'escape',
		asked: false,
	},
	{
		word: 'egeo, egere, egui + gen or abl',
		category: 'verb 2',
		translation: 'need, be in want of, lack',
		asked: false,
	},
	{
		word: 'ego, mei',
		category: 'pron',
		translation: 'I, me',
		asked: false,
	},
	{
		word: 'egredior, egredi, egressus sum',
		category: 'verb 3 dep',
		translation: 'go out, come out',
		asked: false,
	},
	{
		word: 'emo, emere, emi, emptus',
		category: 'verb 3',
		translation: 'buy',
		asked: false,
	},
	{
		word: 'enim',
		category: 'conjunction',
		translation: 'for',
		asked: false,
	},
	{
		word: 'eo',
		category: 'adverb',
		translation: 'thither',
		asked: false,
	},
	{
		word: 'eo, ire, i(v)i',
		category: 'verb irreg',
		translation: 'go',
		asked: false,
	},
	{
		word: 'epistula, epistulae, f',
		category: 'noun 1',
		translation: 'letter',
		asked: false,
	},
	{
		word: 'eques, equitis, m',
		category: 'noun 3',
		translation: 'knight, horseman, (pl) cavalry',
		asked: false,
	},
	{
		word: 'equus, equi, m',
		category: 'noun 2',
		translation: 'horse',
		asked: false,
	},
	{
		word: 'erga + acc',
		category: 'prep',
		translation: 'towards',
		asked: false,
	},
	{
		word: 'ergo',
		category: 'adverb',
		translation: 'therefore',
		asked: false,
	},
	{
		word: 'erro, errare, erravi, erratus',
		category: 'verb 1',
		translation: 'wander, make a mistake',
		asked: false,
	},
	{
		word: 'et',
		category: 'conjunction',
		translation: 'and, both',
		asked: false,
	},
	{
		word: 'etiam',
		category: 'adverb',
		translation: 'also, even, still',
		asked: false,
	},
	{
		word: 'etsi',
		category: 'conjunction',
		translation: 'although',
		asked: false,
	},
	{
		word: 'excipio, excipere, excepi, exceptus',
		category: 'verb 3',
		translation: 'receive, take, welcome',
		asked: false,
	},
	{
		word: 'excito, excitare, excitavi, excitatus',
		category: 'verb 1',
		translation: 'wake, rouse, excite',
		asked: false,
	},
	{
		word: 'exemplum, exempli, n',
		category: 'noun 2',
		translation: 'example, precedent',
		asked: false,
	},
	{
		word: 'exercitus, exercitus, m',
		category: 'noun 4',
		translation: 'army',
		asked: false,
	},
	{
		word: 'exilium, exilii, n',
		category: 'noun 2',
		translation: 'exile',
		asked: false,
	},
	{
		word: 'exitium, exitii, n',
		category: 'noun 2',
		translation: 'ruin, destruction',
		asked: false,
	},
	{
		word: 'exspecto, exspectare, exspectavi, exspectatus',
		category: 'verb 1',
		translation: 'wait for, expect',
		asked: false,
	},
	{
		word: 'extra + acc',
		category: 'prep & adverb',
		translation: 'outside, beyond',
		asked: false,
	},
	{
		word: 'facilis, facile',
		category: 'adj',
		translation: 'easy',
		asked: false,
	},
	{
		word: 'facinus, facinoris, n',
		category: 'noun 3',
		translation: 'crime, outrage, deed',
		asked: false,
	},
	{
		word: 'facio, facere, feci, factus (in compounds -ficio',
		category: 'verb 3',
		translation: 'make, do',
		asked: false,
	},
	{
		word: 'fallo, fallere, fefelli, falsus',
		category: 'verb 3',
		translation: 'deceive, cheat',
		asked: false,
	},
	{
		word: 'fama, famae, f',
		category: 'noun 1',
		translation: 'rumour, fame, glory',
		asked: false,
	},
	{
		word: 'familia, familiae, f',
		category: 'noun 1',
		translation: 'family, household',
		asked: false,
	},
	{
		word: 'faveo, favere, favi, + dat',
		category: 'verb 2',
		translation: 'favour, support',
		asked: false,
	},
	{
		word: 'felix, felicis',
		category: 'adj',
		translation: 'fortunate, happy, prosperous',
		asked: false,
	},
	{
		word: 'femina, feminae, f',
		category: 'noun 1',
		translation: 'woman',
		asked: false,
	},
	{
		word: 'fere',
		category: 'adverb',
		translation: 'nearly, about',
		asked: false,
	},
	{
		word: 'fero, ferre, tuli, latus',
		category: 'verb irreg',
		translation: 'bear, carry, bring, say',
		asked: false,
	},
	{
		word: 'ferox, ferocis',
		category: 'adj',
		translation: 'fierce, cruel, brave',
		asked: false,
	},
	{
		word: 'ferrum, ferri, n',
		category: 'noun 2',
		translation: 'iron, sword',
		asked: false,
	},
	{
		word: 'festino, festinare, festinavi',
		category: 'verb 1',
		translation: 'hurry',
		asked: false,
	},
	{
		word: 'fidelis, fidele',
		category: 'adj',
		translation: 'trustworthy, faithful, loyal',
		asked: false,
	},
	{
		word: 'fides, fidei, f',
		category: 'noun 5',
		translation: 'trust, faith, confidence, loyalty',
		asked: false,
	},
	{
		word: 'fido, fidere, fisus sum + dat or abl',
		category: 'verb 3 semi-dep',
		translation: 'trust, rely upon',
		asked: false,
	},
	{
		word: 'filia, filiae, f',
		category: 'noun 1',
		translation: 'daughter',
		asked: false,
	},
	{
		word: 'filius, filii, m',
		category: 'noun 2',
		translation: 'son',
		asked: false,
	},
	{
		word: 'finis, finis, m',
		category: 'noun 3',
		translation: 'end, boundary, pl territory',
		asked: false,
	},
	{
		word: 'fio, fieri, factus sum',
		category: 'verb irreg',
		translation: 'become, be made, happen',
		asked: false,
	},
	{
		word: 'flamma, flammae, f',
		category: 'noun 1',
		translation: 'blaze, flame, passion',
		asked: false,
	},
	{
		word: 'flumen, fluminis, n',
		category: 'noun 3',
		translation: 'river',
		asked: false,
	},
	{
		word: 'foedus, foederis, n',
		category: 'noun 3',
		translation: 'treaty, agreement',
		asked: false,
	},
	{
		word: 'fortasse',
		category: 'adverb',
		translation: 'perhaps',
		asked: false,
	},
	{
		word: 'forte',
		category: 'adverb',
		translation: 'by chance',
		asked: false,
	},
	{
		word: 'fortis, forte',
		category: 'adj',
		translation: 'brave, strong, bold',
		asked: false,
	},
	{
		word: 'fortuna, fortunae, f',
		category: 'noun 1',
		translation: 'fate, luck, fortune (good or bad)',
		asked: false,
	},
	{
		word: 'forum, fori, n',
		category: 'noun 2',
		translation: 'forum, market place',
		asked: false,
	},
	{
		word: 'frango, frangere, fregi, fractus',
		category: 'verb 3',
		translation: 'break, crush',
		asked: false,
	},
	{
		word: 'frater, fratris, m',
		category: 'noun 3',
		translation: 'brother',
		asked: false,
	},
	{
		word: 'frigus, frigoris, n',
		category: 'noun 3',
		translation: 'cold',
		asked: false,
	},
	{
		word: 'frumentum, frumenti, n',
		category: 'noun 2',
		translation: 'corn, grain',
		asked: false,
	},
	{
		word: 'frustra',
		category: 'adverb',
		translation: 'in vain',
		asked: false,
	},
	{
		word: 'fuga, fugae, f',
		category: 'noun 1',
		translation: 'flight, escape',
		asked: false,
	},
	{
		word: 'fugio, fugere, fugi',
		category: 'verb 3',
		translation: 'flee, run away (from), avoid',
		asked: false,
	},
	{
		word: 'fundo, fundere, fudi, fusus',
		category: 'verb 3',
		translation: 'pour, shed, rout',
		asked: false,
	},
	{
		word: 'furor, furoris, m',
		category: 'noun 3',
		translation: 'rage, fury, madness, passion',
		asked: false,
	},
	{
		word: 'gaudeo, gaudere, gavisus sum',
		category: 'verb 2 semi-dep',
		translation: 'rejoice',
		asked: false,
	},
	{
		word: 'gaudium, gaudii, n',
		category: 'noun 2',
		translation: 'joy, delight',
		asked: false,
	},
	{
		word: 'gens, gentis, f',
		category: 'noun 3',
		translation: 'race, people, family, tribe, nation',
		asked: false,
	},
	{
		word: 'genus, generis, n',
		category: 'noun 3',
		translation: 'race, descent, birth, kind',
		asked: false,
	},
	{
		word: 'gero, gerere, gessi, gestus',
		category: 'verb 3',
		translation: 'bear, wear, wage war, manage',
		asked: false,
	},
	{
		word: 'gladius, gladii, m',
		category: 'noun 2',
		translation: 'sword',
		asked: false,
	},
	{
		word: 'gratia, gratiae, f',
		category: 'noun 1',
		translation: 'favour, thanks, esteem',
		asked: false,
	},
	{
		word: 'gratias ago',
		category: 'verb phrase',
		translation: 'thank, give thanks',
		asked: false,
	},
	{
		word: 'gravis, grave',
		category: 'adj',
		translation: 'heavy, serious, painful, important',
		asked: false,
	},
	{
		word: 'habeo, habere, habui, habitus',
		category: 'verb 2',
		translation: 'have, hold, consider',
		asked: false,
	},
	{
		word: 'habito, habitare, habitavi, habitatus',
		category: 'verb 1',
		translation: 'live, dwell',
		asked: false,
	},
	{
		word: 'hasta, hastae, f',
		category: 'noun 1',
		translation: 'spear',
		asked: false,
	},
	{
		word: 'haud',
		category: 'adverb',
		translation: 'not',
		asked: false,
	},
	{
		word: 'heri',
		category: 'adverb',
		translation: 'yesterday',
		asked: false,
	},
	{
		word: 'hic, haec, hoc',
		category: 'pron',
		translation: 'this',
		asked: false,
	},
	{
		word: 'hic',
		category: 'adverb',
		translation: 'here',
		asked: false,
	},
	{
		word: 'hiems, hiemis, f',
		category: 'noun 3',
		translation: 'winter, storm',
		asked: false,
	},
	{
		word: 'hinc',
		category: 'adverb',
		translation: 'from here, hence, henceforth',
		asked: false,
	},
	{
		word: 'hodie',
		category: 'adverb',
		translation: 'today',
		asked: false,
	},
	{
		word: 'homo, hominis, m',
		category: 'noun 3',
		translation: 'man, person',
		asked: false,
	},
	{
		word: 'honor, honoris, m',
		category: 'noun 3',
		translation: 'honour, esteem, glory',
		asked: false,
	},
	{
		word: 'hora, horae, f',
		category: 'noun 1',
		translation: 'hour',
		asked: false,
	},
	{
		word: 'hortor, hortari, hortatus sum',
		category: 'verb 1 dep',
		translation: 'urge, encourage',
		asked: false,
	},
	{
		word: 'hortus, horti, m',
		category: 'noun 2',
		translation: 'garden',
		asked: false,
	},
	{
		word: 'hospes, hospitis, m',
		category: 'noun 3',
		translation: 'guest, host',
		asked: false,
	},
	{
		word: 'hostis, hostis, m',
		category: 'noun 3',
		translation: 'enemy',
		asked: false,
	},
	{
		word: 'huc',
		category: 'adverb',
		translation: 'here, to this place',
		asked: false,
	},
	{
		word: 'humus, humi, f',
		category: 'noun 2',
		translation: 'ground, earth',
		asked: false,
	},
	{
		word: 'iaceo, iacere, iacui',
		category: 'verb 2',
		translation: 'lie (down)',
		asked: false,
	},
	{
		word: 'iacio, iacere, ieci, iactus (in compounds -icio)',
		category: 'verb 3',
		translation: 'throw',
		asked: false,
	},
	{
		word: 'iam',
		category: 'adverb',
		translation: 'now, already',
		asked: false,
	},
	{
		word: 'non iam (indeclinable)',
		category: 'adverb',
		translation: 'no longer',
		asked: false,
	},
	{
		word: 'ibi',
		category: 'adverb',
		translation: 'there, then',
		asked: false,
	},
	{
		word: 'idem, eadem, idem',
		category: 'pron',
		translation: 'the same',
		asked: false,
	},
	{
		word: 'idoneus, idonea, idoneum',
		category: 'adj',
		translation: 'suitable, convenient',
		asked: false,
	},
	{
		word: 'igitur',
		category: 'adverb',
		translation: 'therefore, and so',
		asked: false,
	},
	{
		word: 'ignis, ignis, m',
		category: 'noun 3',
		translation: 'fire',
		asked: false,
	},
	{
		word: 'ignoro, ignorare, ignoravi, ignoratus',
		category: 'verb 1',
		translation: 'do not know, be ignorant, misunderstand',
		asked: false,
	},
	{
		word: 'ille, illa, illud',
		category: 'pron',
		translation: 'that, he, she, it',
		asked: false,
	},
	{
		word: 'illic',
		category: 'adverb',
		translation: 'there',
		asked: false,
	},
	{
		word: 'impedio, impedire, impedivi, impeditus',
		category: 'verb 4',
		translation: 'delay, hinder, prevent, hamper',
		asked: false,
	},
	{
		word: 'imperator, imperatoris, m',
		category: 'noun 3',
		translation: 'emperor, general, leader',
		asked: false,
	},
	{
		word: 'imperium, imperii, n',
		category: 'noun 2',
		translation: 'command, power, empire',
		asked: false,
	},
	{
		word: 'impero, imperare, imperavi, imperatus +dat',
		category: 'verb 1',
		translation: 'order, command',
		asked: false,
	},
	{
		word: 'impetus, impetus, m',
		category: 'noun 4',
		translation: 'attack, impulse',
		asked: false,
	},
	{
		word: 'in + abl',
		category: 'prep',
		translation: 'in, on',
		asked: false,
	},
	{
		word: 'in + acc',
		category: 'prep',
		translation: 'into, onto, against, towards',
		asked: false,
	},
	{
		word: 'incendium, incendii, n',
		category: 'noun 2',
		translation: 'fire',
		asked: false,
	},
	{
		word: 'incendo, incendere, incendi, incensus',
		category: 'verb 3',
		translation: 'burn, set on fire, inflame, rouse',
		asked: false,
	},
	{
		word: 'incipio, incipere, incepi, inceptus',
		category: 'verb 3',
		translation: 'begin',
		asked: false,
	},
	{
		word: 'incito, incitare, incitavi, incitatus',
		category: 'verb 1',
		translation: 'urge on, arouse, encourage',
		asked: false,
	},
	{
		word: 'inde',
		category: 'adverb',
		translation: 'from there, thereupon, next',
		asked: false,
	},
	{
		word: 'infero, inferre, intuli, illatus/inlatus',
		category: 'verb irreg',
		translation: 'inflict, bring to, cause, carry against',
		asked: false,
	},
	{
		word: 'signa inferre',
		category: 'verb phrase',
		translation: 'attack, charge',
		asked: false,
	},
	{
		word: 'bellum inferre + dat',
		category: 'verb phrase',
		translation: 'make war on',
		asked: false,
	},
	{
		word: 'infra + acc',
		category: 'prep & adverb',
		translation: 'below, beneath',
		asked: false,
	},
	{
		word: 'ingenium, ingenii, n',
		category: 'noun 2',
		translation: 'character, ability',
		asked: false,
	},
	{
		word: 'ingens, ingentis',
		category: 'adj',
		translation: 'huge',
		asked: false,
	},
	{
		word: 'ingredior, ingredi, ingressus sum',
		category: 'verb 3 dep',
		translation: 'enter, undertake',
		asked: false,
	},
	{
		word: 'inimicus, inimici, m',
		category: 'noun 2',
		translation: '(personal) enemy',
		asked: false,
	},
	{
		word: 'iniquus, iniqua, iniquum',
		category: 'adj',
		translation: 'unfair, unjust, unfavourable',
		asked: false,
	},
	{
		word: 'initium, initii, n',
		category: 'noun 2',
		translation: 'beginning',
		asked: false,
	},
	{
		word: 'iniuria, iniuriae, f',
		category: 'noun 1',
		translation: 'injustice, injury, wrong',
		asked: false,
	},
	{
		word: 'inopia, inopiae, f',
		category: 'noun 1',
		translation: 'shortage, lack, poverty',
		asked: false,
	},
	{
		word: 'inquam, inquit, inquiunt',
		category: 'verb irreg',
		translation: 'say',
		asked: false,
	},
	{
		word: 'insidiae, insidiarum, f pl',
		category: 'noun 1',
		translation: 'ambush, trap, trick',
		asked: false,
	},
	{
		word: 'insignis, insigne',
		category: 'adj',
		translation: 'distinguished, glorious',
		asked: false,
	},
	{
		word: 'inspicio, inspicere, inspexi, inspectus',
		category: 'verb 3',
		translation: 'look at, inspect, examine',
		asked: false,
	},
	{
		word: 'instruo, instruere, instruxi, instructus',
		category: 'verb 3',
		translation: 'draw up, prepare, equip, supply',
		asked: false,
	},
	{
		word: 'insula, insulae, f',
		category: 'noun 1',
		translation: 'island, block (of apartments)',
		asked: false,
	},
	{
		word: 'intellego, intellegere, intellexi, intellectus',
		category: 'verb 3',
		translation: 'understand, perceive, realise',
		asked: false,
	},
	{
		word: 'inter + acc',
		category: 'prep',
		translation: 'between, among',
		asked: false,
	},
	{
		word: 'interea, interim',
		category: 'adverb',
		translation: 'meanwhile, in the meantime',
		asked: false,
	},
	{
		word: 'interficio, interficere, interfeci, interfectus',
		category: 'verb 3',
		translation: 'kill',
		asked: false,
	},
	{
		word: 'intra + acc',
		category: 'prep',
		translation: 'inside, within',
		asked: false,
	},
	{
		word: 'intro, intrare, intravi, intratus',
		category: 'verb 1',
		translation: 'enter',
		asked: false,
	},
	{
		word: 'invenio, invenire, inveni, inventus',
		category: 'verb 4',
		translation: 'find, discover',
		asked: false,
	},
	{
		word: 'invito, invitare, invitavi, invitatus',
		category: 'verb 1',
		translation: 'invite',
		asked: false,
	},
	{
		word: 'invitus, invita, invitum',
		category: 'adj',
		translation: 'unwillling, reluctant',
		asked: false,
	},
	{
		word: 'ipse, ipsa, ipsum',
		category: 'pron',
		translation: '-self',
		asked: false,
	},
	{
		word: 'ira, irae, f',
		category: 'noun 1',
		translation: 'anger',
		asked: false,
	},
	{
		word: 'iratus, irata, iratum',
		category: 'adj',
		translation: 'angry',
		asked: false,
	},
	{
		word: 'is, ea, id',
		category: 'pron',
		translation: 'this, that, he, she, it',
		asked: false,
	},
	{
		word: 'ita',
		category: 'adverb',
		translation: 'in this way, so, thus',
		asked: false,
	},
	{
		word: 'ita vero',
		category: 'adverb',
		translation: 'yes',
		asked: false,
	},
	{
		word: 'itaque',
		category: 'adverb',
		translation: 'and so, therefore',
		asked: false,
	},
	{
		word: 'iter, itineris, n',
		category: 'noun 3',
		translation: 'journey, march, way',
		asked: false,
	},
	{
		word: 'iterum',
		category: 'adverb',
		translation: 'again',
		asked: false,
	},
	{
		word: 'iubeo, iubere, iussi, iussus',
		category: 'verb 2',
		translation: 'order, command',
		asked: false,
	},
	{
		word: 'iudex, iudicis, m and f',
		category: 'noun 3',
		translation: 'judge, juror',
		asked: false,
	},
	{
		word: 'iungo, iungere, iunxi, iunctus',
		category: 'verb 3',
		translation: 'join, unite, fasten',
		asked: false,
	},
	{
		word: 'iustus, iusta, iustum',
		category: 'adj',
		translation: 'right, just, lawful, complete',
		asked: false,
	},
	{
		word: 'iuvenis, iuvenis m or adj',
		category: 'noun & adj',
		translation: 'young man, young',
		asked: false,
	},
	{
		word: 'iuvo, iuvare, iuvi, iutus',
		category: 'verb 1',
		translation: 'help, please',
		asked: false,
	},
	{
		word: 'labor, labi, lapsus sum',
		category: 'verb 3 dep',
		translation: 'glide, slip, fall',
		asked: false,
	},
	{
		word: 'labor, laboris, m',
		category: 'noun 3',
		translation: 'work, toil, trouble',
		asked: false,
	},
	{
		word: 'laboro, laborare, laboravi',
		category: 'verb 1',
		translation: 'work, toil, be in difficulty',
		asked: false,
	},
	{
		word: 'laedo, laedere, laesi, laesus',
		category: 'verb 3',
		translation: 'hurt, injure, harm',
		asked: false,
	},
	{
		word: 'laetus, laeta, laetum',
		category: 'adj',
		translation: 'happy, glad',
		asked: false,
	},
	{
		word: 'latus, lata, latum',
		category: 'adj',
		translation: 'wide, broad',
		asked: false,
	},
	{
		word: 'latus, lateris, n',
		category: 'noun 3',
		translation: 'side, wing',
		asked: false,
	},
	{
		word: 'laudo, laudare, laudavi, laudatus',
		category: 'verb 1',
		translation: 'praise',
		asked: false,
	},
	{
		word: 'laus, laudis, f',
		category: 'noun 3',
		translation: 'praise, honour, credit',
		asked: false,
	},
	{
		word: 'legatus, legati, m',
		category: 'noun 2',
		translation: '(legionary) commander, ambassador, envoy',
		asked: false,
	},
	{
		word: 'legio, legionis, f',
		category: 'noun 3',
		translation: 'legion',
		asked: false,
	},
	{
		word: 'lego, legere, legi, lectus',
		category: 'verb 3',
		translation: 'read, choose',
		asked: false,
	},
	{
		word: 'lentus, lenta, lentum',
		category: 'adj',
		translation: 'slow',
		asked: false,
	},
	{
		word: 'levis, leve',
		category: 'adj',
		translation: 'light, slight',
		asked: false,
	},
	{
		word: 'lex, legis, f',
		category: 'noun 3',
		translation: 'law',
		asked: false,
	},
	{
		word: 'libens, libentis',
		category: 'adj',
		translation: 'willing, glad',
		asked: false,
	},
	{
		word: 'liber, libera, liberum',
		category: 'adj',
		translation: 'free',
		asked: false,
	},
	{
		word: 'liber, libri, m',
		category: 'noun 2',
		translation: 'book',
		asked: false,
	},
	{
		word: 'liberi, liberorum, m pl',
		category: 'noun 2',
		translation: 'children',
		asked: false,
	},
	{
		word: 'libero, liberare, liberavi, liberatus',
		category: 'verb 1',
		translation: 'set free',
		asked: false,
	},
	{
		word: 'libertas, libertatis, f',
		category: 'noun 3',
		translation: 'freedom',
		asked: false,
	},
	{
		word: 'libertus, liberti, m',
		category: 'noun 2',
		translation: 'freedman, ex-slave',
		asked: false,
	},
	{
		word: 'licet, licere, licuit + dat',
		category: 'verb impersonal',
		translation: 'it is allowed',
		asked: false,
	},
	{
		word: 'littera, litterae, f (usually pl. with sg. meaning)',
		category: 'noun 1',
		translation: 'letter',
		asked: false,
	},
	{
		word: 'litus, litoris, n',
		category: 'noun 3',
		translation: 'sea-shore, beach',
		asked: false,
	},
	{
		word: 'locus, loci, m',
		category: 'noun 2',
		translation: 'place, position, situation, opportunity',
		asked: false,
	},
	{
		word: 'longus, longa, longum',
		category: 'adj',
		translation: 'long',
		asked: false,
	},
	{
		word: 'loquor, loqui, locutus sum',
		category: 'verb 3 dep',
		translation: 'speak, talk',
		asked: false,
	},
	{
		word: 'lux, lucis, f',
		category: 'noun 3',
		translation: 'light, daylight',
		asked: false,
	},
	{
		word: 'magister, magistri, m',
		category: 'noun 2',
		translation: 'teacher, master',
		asked: false,
	},
	{
		word: 'magnus, magna, magnum',
		category: 'adj',
		translation: 'big, large, great',
		asked: false,
	},
	{
		word: 'magnopere',
		category: 'adverb',
		translation: 'very much, greatly',
		asked: false,
	},
	{
		word: 'magis',
		category: 'adverb comp',
		translation: 'more, rather',
		asked: false,
	},
	{
		word: 'malo, malle, malui',
		category: 'verb irreg',
		translation: 'prefer',
		asked: false,
	},
	{
		word: 'malus, mala, malum',
		category: 'adj',
		translation: 'evil, bad',
		asked: false,
	},
	{
		word: 'mando, mandare, mandavi, mandatus',
		category: 'verb 1',
		translation: 'commit, entrust, command',
		asked: false,
	},
	{
		word: 'mane',
		category: 'adverb',
		translation: 'in the morning, early',
		asked: false,
	},
	{
		word: 'maneo, manere, mansi',
		category: 'verb 2',
		translation: 'remain, stay',
		asked: false,
	},
	{
		word: 'manus, manus, f',
		category: 'noun 4',
		translation: 'hand, band',
		asked: false,
	},
	{
		word: 'mare, maris, n',
		category: 'noun 3',
		translation: 'sea',
		asked: false,
	},
	{
		word: 'maritus, mariti, m',
		category: 'noun 2',
		translation: 'husband',
		asked: false,
	},
	{
		word: 'mater, matris, f',
		category: 'noun 3',
		translation: 'mother',
		asked: false,
	},
	{
		word: 'medius, media, medium',
		category: 'adj',
		translation: 'middle (of)',
		asked: false,
	},
	{
		word: 'mens, mentis, f',
		category: 'noun 3',
		translation: 'mind',
		asked: false,
	},
	{
		word: 'mensis, mensis, m',
		category: 'noun 3',
		translation: 'month',
		asked: false,
	},
	{
		word: 'mercator, mercatoris, m',
		category: 'noun 3',
		translation: 'merchant',
		asked: false,
	},
	{
		word: 'metus, metus, m',
		category: 'noun 4',
		translation: 'fear',
		asked: false,
	},
	{
		word: 'meus, mea, meum',
		category: 'adj',
		translation: 'my',
		asked: false,
	},
	{
		word: 'miles, militis, m',
		category: 'noun 3',
		translation: 'soldier',
		asked: false,
	},
	{
		word: 'minor, minari, minatus sum + dat',
		category: 'verb 1 dep',
		translation: 'threaten',
		asked: false,
	},
	{
		word: 'mirabilis, mirabile',
		category: 'adj',
		translation: 'strange, wonderful',
		asked: false,
	},
	{
		word: 'miror, mirari, miratus sum',
		category: 'verb 1 dep',
		translation: 'wonder at, admire',
		asked: false,
	},
	{
		word: 'miser, misera, miserum',
		category: 'adj',
		translation: 'miserable, wretched, sad',
		asked: false,
	},
	{
		word: 'mitto, mittere, misi, missus',
		category: 'verb 3',
		translation: 'send, throw, let go',
		asked: false,
	},
	{
		word: 'modo',
		category: 'adverb',
		translation: 'just now, only',
		asked: false,
	},
	{
		word: 'modus, modi, m',
		category: 'noun 2',
		translation: 'manner, way, kind',
		asked: false,
	},
	{
		word: 'moenia, moenium, n pl',
		category: 'noun 3',
		translation: 'city walls, city',
		asked: false,
	},
	{
		word: 'moneo, monere, monui, monitus',
		category: 'verb 2',
		translation: 'warn, advise, teach',
		asked: false,
	},
	{
		word: 'mons, montis, m',
		category: 'noun 3',
		translation: 'mountain',
		asked: false,
	},
	{
		word: 'monstro, monstrare, monstravi, monstratus',
		category: 'verb 1',
		translation: 'show, point out, indicate, instruct',
		asked: false,
	},
	{
		word: 'morbus, morbi, m',
		category: 'noun 2',
		translation: 'sickness, disease',
		asked: false,
	},
	{
		word: 'morior, mori, mortuus sum',
		category: 'verb 3 dep',
		translation: 'die',
		asked: false,
	},
	{
		word: 'mors, mortis, f',
		category: 'noun 3',
		translation: 'death',
		asked: false,
	},
	{
		word: 'moror, morari, moratus sum',
		category: 'verb 1 dep',
		translation: 'delay, linger',
		asked: false,
	},
	{
		word: 'mora, morae, f',
		category: 'noun 1',
		translation: 'delay',
		asked: false,
	},
	{
		word: 'mos, moris, m',
		category: 'noun 3',
		translation: 'habit, custom, (pl) character, morals',
		asked: false,
	},
	{
		word: 'moveo, movere, movi, motus',
		category: 'verb 2',
		translation: 'move',
		asked: false,
	},
	{
		word: 'mox',
		category: 'adverb',
		translation: 'soon',
		asked: false,
	},
	{
		word: 'mulier, mulieris, f',
		category: 'noun 3',
		translation: 'woman',
		asked: false,
	},
	{
		word: 'multitudo, multitudinis, f',
		category: 'noun 3',
		translation: 'crowd, multitude',
		asked: false,
	},
	{
		word: 'multus, multa, multum',
		category: 'adj',
		translation: 'much, many',
		asked: false,
	},
	{
		word: 'munio, munire, munivi, munitus',
		category: 'verb 4',
		translation: 'fortify, defend, guard',
		asked: false,
	},
	{
		word: 'munus, muneris, n',
		category: 'noun 3',
		translation: 'service, duty, present',
		asked: false,
	},
	{
		word: 'murus, muri, m',
		category: 'noun 2',
		translation: 'wall, rampart',
		asked: false,
	},
	{
		word: 'muto, mutare, mutavi, mutatus',
		category: 'verb 1',
		translation: 'change, alter',
		asked: false,
	},
	{
		word: 'nam',
		category: 'conjunction',
		translation: 'for',
		asked: false,
	},
	{
		word: 'narro, narrare, narravi, narratus',
		category: 'verb 1',
		translation: 'tell, relate',
		asked: false,
	},
	{
		word: 'nascor, nasci, natus sum',
		category: 'verb 3 dep',
		translation: 'am born',
		asked: false,
	},
	{
		word: 'natura, naturae, f',
		category: 'noun 1',
		translation: 'nature',
		asked: false,
	},
	{
		word: 'nauta, nautae, m',
		category: 'noun 1',
		translation: 'sailor',
		asked: false,
	},
	{
		word: 'navigo, navigare, navigavi',
		category: 'verb 1',
		translation: 'sail',
		asked: false,
	},
	{
		word: 'navis, navis, f',
		category: 'noun 3',
		translation: 'ship',
		asked: false,
	},
	{
		word: 'navis longa',
		category: null,
		translation: 'warship',
		asked: false,
	},
	{
		word: 'navis oneraria',
		category: null,
		translation: 'merchant ship',
		asked: false,
	},
	{
		word: '-ne',
		category: 'particle',
		translation: '(introduces question)',
		asked: false,
	},
	{
		word: 'ne',
		category: 'conjunction',
		translation: 'lest, that not',
		asked: false,
	},
	{
		word: 'nec, neque',
		category: 'conjunction',
		translation: 'and not, nor, neither',
		asked: false,
	},
	{
		word: 'necesse',
		category: 'adj',
		translation: 'necessary',
		asked: false,
	},
	{
		word: 'neco, necare, necavi, necatus',
		category: 'verb 1',
		translation: 'kill',
		asked: false,
	},
	{
		word: 'neglego, neglegere, neglexi, neglectus',
		category: 'verb 3',
		translation: 'neglect, disregard',
		asked: false,
	},
	{
		word: 'nego, negare, negavi, negatus',
		category: 'verb 1',
		translation: 'say no, deny, refuse, say that ...not',
		asked: false,
	},
	{
		word: 'negotium, negotii, n',
		category: 'noun 2',
		translation: 'business',
		asked: false,
	},
	{
		word: 'nemo, nullius',
		category: 'noun irreg',
		translation: 'no one, nobody',
		asked: false,
	},
	{
		word: 'nescio, nescire, nescivi',
		category: 'verb 4',
		translation: 'not know',
		asked: false,
	},
	{
		word: 'nihil',
		category: 'noun irreg',
		translation: 'nothing',
		asked: false,
	},
	{
		word: 'nisi',
		category: 'conjunction',
		translation: 'unless, if not, except',
		asked: false,
	},
	{
		word: 'nobilis, nobile',
		category: 'adj',
		translation: 'noble, famous',
		asked: false,
	},
	{
		word: 'noceo, nocere, nocui + dat',
		category: 'verb 2',
		translation: 'hurt, harm',
		asked: false,
	},
	{
		word: 'nolo, nolle, nolui',
		category: 'verb irreg',
		translation: 'not want, be unwilling, refuse',
		asked: false,
	},
	{
		word: 'nomen, nominis, n',
		category: 'noun 3',
		translation: 'name',
		asked: false,
	},
	{
		word: 'non',
		category: 'adverb',
		translation: 'not',
		asked: false,
	},
	{
		word: 'nondum',
		category: 'adverb',
		translation: 'not yet',
		asked: false,
	},
	{
		word: 'nonne?',
		category: 'adverb',
		translation: 'surely?',
		asked: false,
	},
	{
		word: 'nonnulli, nonnullae, nonnulla',
		category: 'adj',
		translation: 'some, several',
		asked: false,
	},
	{
		word: 'nos, nostrum / nostri',
		category: 'pron',
		translation: 'we, us',
		asked: false,
	},
	{
		word: 'noster, nostra, nostrum',
		category: 'pron',
		translation: 'our',
		asked: false,
	},
	{
		word: 'notus, nota, notum',
		category: 'adj',
		translation: 'known, well-known, famous',
		asked: false,
	},
	{
		word: 'novi, notus (perfect with present meaning)',
		category: 'verb 3',
		translation: 'know',
		asked: false,
	},
	{
		word: 'novus, nova, novum',
		category: 'adj',
		translation: 'new, fresh, recent',
		asked: false,
	},
	{
		word: 'nox, noctis, f',
		category: 'noun 3',
		translation: 'night',
		asked: false,
	},
	{
		word: 'noctu',
		category: null,
		translation: 'by night',
		asked: false,
	},
	{
		word: 'nullus, nulla, nullum',
		category: 'adj',
		translation: 'no, none, not any',
		asked: false,
	},
	{
		word: 'num',
		category: 'adverb',
		translation: 'surely…not, whether',
		asked: false,
	},
	{
		word: 'numerus, numeri, m',
		category: 'noun 2',
		translation: 'number',
		asked: false,
	},
	{
		word: 'numquam',
		category: 'adverb',
		translation: 'never',
		asked: false,
	},
	{
		word: 'nunc',
		category: 'adverb',
		translation: 'now',
		asked: false,
	},
	{
		word: 'nuntio, nuntiare, nuntiavi, nuntiatus',
		category: 'verb 1',
		translation: 'announce, report',
		asked: false,
	},
	{
		word: 'nuntius, nuntii, m',
		category: 'noun 2',
		translation: 'messenger, message, news',
		asked: false,
	},
	{
		word: 'ob + acc',
		category: 'prep',
		translation: 'because of, on account of',
		asked: false,
	},
	{
		word: 'obliviscor, oblivisci, oblitus sum',
		category: 'verb 3 dep',
		translation: 'forget',
		asked: false,
	},
	{
		word: 'obses, obsidis m and f',
		category: 'noun 3',
		translation: 'hostage',
		asked: false,
	},
	{
		word: 'obsideo, obsidere, obsedi, obsessus',
		category: 'verb 2',
		translation: 'besiege, blockade',
		asked: false,
	},
	{
		word: 'obviam eo, ire, i(v)i + dat',
		category: 'verb phrase',
		translation: 'meet, go to meet, oppose, resist',
		asked: false,
	},
	{
		word: 'occasio, occasionis, f',
		category: 'noun 3',
		translation: 'opportunity, occasion',
		asked: false,
	},
	{
		word: 'occido, occidere, occidi, occisus',
		category: 'verb 3',
		translation: 'kill',
		asked: false,
	},
	{
		word: 'occupo, occupare, occupavi, occupatus',
		category: 'verb 1',
		translation: 'seize, take possession of, occupy',
		asked: false,
	},
	{
		word: 'oculus, oculi, m',
		category: 'noun 2',
		translation: 'eye',
		asked: false,
	},
	{
		word: 'odi, odisse (perfect with present meaning)',
		category: 'verb irreg',
		translation: 'hate',
		asked: false,
	},
	{
		word: 'odium, odii, n',
		category: 'noun 2',
		translation: 'hatred',
		asked: false,
	},
	{
		word: 'odio est + dat',
		category: 'verb phrase',
		translation: 'be hated by',
		asked: false,
	},
	{
		word: 'offero, offerre, obtuli, oblatus',
		category: 'verb irreg',
		translation: 'present, offer',
		asked: false,
	},
	{
		word: 'officium, officii, n',
		category: 'noun 2',
		translation: 'duty, task, function',
		asked: false,
	},
	{
		word: 'olim',
		category: 'adverb',
		translation: 'once, formerly, one day',
		asked: false,
	},
	{
		word: 'omitto, omittere, omisi, omissus',
		category: 'verb 3',
		translation: 'neglect, disregard, make no mention of',
		asked: false,
	},
	{
		word: 'omnis, omne',
		category: 'adj',
		translation: 'all, every',
		asked: false,
	},
	{
		word: 'omnino',
		category: 'adverb',
		translation: 'altogether, at all, entirely',
		asked: false,
	},
	{
		word: 'onus, oneris, n',
		category: 'noun 3',
		translation: 'burden, load',
		asked: false,
	},
	{
		word: 'opera, operae, f',
		category: 'noun 1',
		translation: 'work, effort, attention, trouble',
		asked: false,
	},
	{
		word: 'operam do',
		category: 'verb phrase',
		translation: 'I take pains, give attention (to)',
		asked: false,
	},
	{
		word: 'oportet, oportere, oportuit',
		category: 'verb 2 impersonal',
		translation: 'be necessary, ought, must',
		asked: false,
	},
	{
		word: 'oppidum, oppidi, n',
		category: 'noun 2',
		translation: 'town',
		asked: false,
	},
	{
		word: 'opprimo, opprimere, oppressi, oppressus',
		category: 'verb 3',
		translation: 'overwhelm, crush, weigh down',
		asked: false,
	},
	{
		word: 'oppugno, oppugnare, oppugnavi, oppugnatus',
		category: 'verb 1',
		translation: 'attack',
		asked: false,
	},
	{
		word: '(ops), opis, f',
		category: 'noun 3',
		translation: 'help; (pl) resources, riches',
		asked: false,
	},
	{
		word: 'opus, operis, n',
		category: 'noun 3',
		translation: 'work, toil, construction',
		asked: false,
	},
	{
		word: 'opus est, esse, fuit + abl (impersonal)',
		category: 'verb phrase',
		translation: 'there is need (of)',
		asked: false,
	},
	{
		word: 'ora, orae, f',
		category: 'noun 1',
		translation: 'coast',
		asked: false,
	},
	{
		word: 'oratio, orationis, f',
		category: 'noun 3',
		translation: 'speech',
		asked: false,
	},
	{
		word: 'ordo, ordinis, m',
		category: 'noun 3',
		translation: 'rank, order, line',
		asked: false,
	},
	{
		word: 'orior, oriri, ortus sum',
		category: 'verb 4 dep',
		translation: 'rise, start, originate',
		asked: false,
	},
	{
		word: 'orno, ornare, ornavi, ornatus',
		category: 'verb 1',
		translation: 'adorn, decorate, provide, equip',
		asked: false,
	},
	{
		word: 'oro, orare, oravi, oratus',
		category: 'verb 1',
		translation: 'beg',
		asked: false,
	},
	{
		word: 'os, oris, n',
		category: 'noun 3',
		translation: 'mouth, face',
		asked: false,
	},
	{
		word: 'ostendo, ostendere, ostendi, ostentus',
		category: 'verb 3',
		translation: 'show, point out, indicate',
		asked: false,
	},
	{
		word: 'otium, otii, n',
		category: 'noun 2',
		translation: 'leisure, idleness, peace',
		asked: false,
	},
	{
		word: 'paene',
		category: 'adverb',
		translation: 'almost, nearly',
		asked: false,
	},
	{
		word: 'palam',
		category: 'adverb',
		translation: 'openly',
		asked: false,
	},
	{
		word: 'par, paris',
		category: 'adj',
		translation: 'equal',
		asked: false,
	},
	{
		word: 'parco, parcere, peperci + dat',
		category: 'verb 3',
		translation: 'spare',
		asked: false,
	},
	{
		word: 'parens, parentis, m and f',
		category: 'noun 3',
		translation: 'parent; (pl) relations',
		asked: false,
	},
	{
		word: 'pareo, parere, parui + dat',
		category: 'verb 2',
		translation: 'obey',
		asked: false,
	},
	{
		word: 'pario, parere, peperi, partus',
		category: 'verb 3',
		translation: 'bear (a child), win, acquire, gain, secure',
		asked: false,
	},
	{
		word: 'paro, parare, paravi, paratus',
		category: 'verb 1',
		translation: 'prepare, provide',
		asked: false,
	},
	{
		word: 'pars, partis, f',
		category: 'noun 3',
		translation: 'part, some, direction',
		asked: false,
	},
	{
		word: 'parvus, parva, parvum',
		category: 'adj',
		translation: 'small',
		asked: false,
	},
	{
		word: 'passim',
		category: 'adverb',
		translation: 'in all directions, far and wide, everywhere',
		asked: false,
	},
	{
		word: 'passus, passus, m',
		category: 'noun 4',
		translation: 'pace',
		asked: false,
	},
	{
		word: 'mille passus (pl milia passuum)',
		category: null,
		translation: 'mile',
		asked: false,
	},
	{
		word: 'pater, patris, m',
		category: 'noun 3',
		translation: 'father',
		asked: false,
	},
	{
		word: 'patior, pati, passus sum',
		category: 'verb 3 dep',
		translation: 'suffer, endure, allow',
		asked: false,
	},
	{
		word: 'patria, patriae, f',
		category: 'noun 1',
		translation: 'homeland, native land',
		asked: false,
	},
	{
		word: 'pauci, paucae, pauca',
		category: 'adj plural',
		translation: 'few, a few',
		asked: false,
	},
	{
		word: 'paulatim',
		category: 'adverb',
		translation: 'gradually, little by little',
		asked: false,
	},
	{
		word: 'paulisper',
		category: 'adverb',
		translation: 'for a short time',
		asked: false,
	},
	{
		word: 'paulum, paulo',
		category: 'adverb',
		translation: 'a little, somewhat',
		asked: false,
	},
	{
		word: 'pauper, pauperis',
		category: 'adj',
		translation: 'poor',
		asked: false,
	},
	{
		word: 'pax, pacis, f',
		category: 'noun 3',
		translation: 'peace',
		asked: false,
	},
	{
		word: 'pecunia, pecuniae, f',
		category: 'noun 1',
		translation: 'money',
		asked: false,
	},
	{
		word: 'pedes, peditis, m',
		category: 'noun 3',
		translation: 'infantry',
		asked: false,
	},
	{
		word: 'pello, pellere, pepuli, pulsus',
		category: 'verb 3',
		translation: 'push, drive, rout',
		asked: false,
	},
	{
		word: 'per + acc',
		category: 'prep',
		translation: 'through, throughout, along',
		asked: false,
	},
	{
		word: 'perdo, perdere, perdidi, perditus',
		category: 'verb 3',
		translation: 'destroy, lose',
		asked: false,
	},
	{
		word: 'pereo, perire, perii',
		category: 'verb irreg',
		translation: 'die, perish, be ruined',
		asked: false,
	},
	{
		word: 'perficio, perficere, perfeci, perfectus',
		category: 'verb 3',
		translation: 'bring about, complete, perfect',
		asked: false,
	},
	{
		word: 'periculum, periculi, n',
		category: 'noun 2',
		translation: 'danger',
		asked: false,
	},
	{
		word: 'peritus, perita, peritum + gen or abl',
		category: 'adj',
		translation: 'skilled (in)',
		asked: false,
	},
	{
		word: 'permitto, permittere, permisi, permissus',
		category: 'verb 3',
		translation: 'hand over, entrust, permit, allow',
		asked: false,
	},
	{
		word: 'persuadeo, persuadere, persuasi + dat',
		category: 'verb 2',
		translation: 'persuade, convince',
		asked: false,
	},
	{
		word: 'perterritus, perterrita, perterritum',
		category: 'adj',
		translation: 'very frightened, terrified',
		asked: false,
	},
	{
		word: 'pervenio, pervenire, perveni',
		category: 'verb 4',
		translation: 'reach, arrive',
		asked: false,
	},
	{
		word: 'pes, pedis, m',
		category: 'noun 3',
		translation: 'foot',
		asked: false,
	},
	{
		word: 'peto, petere, petivi, petitus',
		category: 'verb 3',
		translation: 'seek, ask for, make for, attack',
		asked: false,
	},
	{
		word: 'pilum, pili, n',
		category: 'noun 2',
		translation: 'javelin',
		asked: false,
	},
	{
		word: 'placet, placere, placuit + dat',
		category: 'verb 2 impersonal',
		translation: 'it pleases, suits, it is resolved',
		asked: false,
	},
	{
		word: 'plebs, plebis, f',
		category: 'noun 3',
		translation: 'the people, common people',
		asked: false,
	},
	{
		word: 'plenus, plena, plenum',
		category: 'adj',
		translation: 'full, filled',
		asked: false,
	},
	{
		word: 'plerique, pleraeque, pleraque',
		category: 'adj',
		translation: 'most, the majority',
		asked: false,
	},
	{
		word: 'poena, poenae, f',
		category: 'noun 1',
		translation: 'punishment, penalty',
		asked: false,
	},
	{
		word: 'poenas do',
		category: 'verb phrase',
		translation: 'pay the penalty, am punished',
		asked: false,
	},
	{
		word: 'polliceor, polliceri, pollicitus sum',
		category: 'verb 2 dep',
		translation: 'promise',
		asked: false,
	},
	{
		word: 'pono, ponere, posui, positus',
		category: 'verb 3',
		translation: 'put, place, set up (camp)',
		asked: false,
	},
	{
		word: 'pons, pontis, m',
		category: 'noun 3',
		translation: 'bridge',
		asked: false,
	},
	{
		word: 'populus, populi, m',
		category: 'noun 2',
		translation: 'people, nation',
		asked: false,
	},
	{
		word: 'porta, portae, f',
		category: 'noun 1',
		translation: 'gate',
		asked: false,
	},
	{
		word: 'porto, portare, portavi, portatus',
		category: 'verb 1',
		translation: 'carry, bear, take',
		asked: false,
	},
	{
		word: 'portus, portus, m',
		category: 'noun 4',
		translation: 'harbour, port',
		asked: false,
	},
	{
		word: 'posco, poscere, poposci',
		category: 'verb 3',
		translation: 'demand, ask for',
		asked: false,
	},
	{
		word: 'possum, posse, potui',
		category: 'verb irreg',
		translation: 'can, be able',
		asked: false,
	},
	{
		word: 'post + acc',
		category: 'prep',
		translation: 'behind, after',
		asked: false,
	},
	{
		word: 'post',
		category: 'adverb',
		translation: 'afterwards, next',
		asked: false,
	},
	{
		word: 'postea',
		category: 'adverb',
		translation: 'afterwards, then',
		asked: false,
	},
	{
		word: 'postquam',
		category: 'conjunction',
		translation: 'after, when',
		asked: false,
	},
	{
		word: 'postremus, postrema, postremum',
		category: 'adj',
		translation: 'last',
		asked: false,
	},
	{
		word: 'postridie',
		category: 'adverb',
		translation: 'on the next day',
		asked: false,
	},
	{
		word: 'postulo, postulare, postulavi, postulatus',
		category: 'verb 1',
		translation: 'demand, ask',
		asked: false,
	},
	{
		word: 'potens, potentis',
		category: 'adj',
		translation: 'powerful',
		asked: false,
	},
	{
		word: 'potestas, potestatis, f',
		category: 'noun 3',
		translation: 'power, authority, opportunity',
		asked: false,
	},
	{
		word: 'potior, potiri, potitus sum + gen or abl',
		category: 'verb 4',
		translation: 'seize, get possession of',
		asked: false,
	},
	{
		word: 'potius',
		category: 'adverb',
		translation: 'rather, more',
		asked: false,
	},
	{
		word: 'praebeo, praebere, praebui, praebitus',
		category: 'verb 2',
		translation: 'provide, give, show, offer',
		asked: false,
	},
	{
		word: 'praeda, praedae, f',
		category: 'noun 1',
		translation: 'booty, plunder',
		asked: false,
	},
	{
		word: 'praemium, praemii, n',
		category: 'noun 2',
		translation: 'prize, reward',
		asked: false,
	},
	{
		word: 'praeficio, praeficere, praefeci, praefectus',
		category: 'verb 3',
		translation: 'put in charge (of)',
		asked: false,
	},
	{
		word: 'praesidium, praesidii, n',
		category: 'noun 2',
		translation: 'protection, garrison, fortification',
		asked: false,
	},
	{
		word: 'praesum, praeesse, praefui + dat',
		category: 'verb irreg',
		translation: 'be in charge of',
		asked: false,
	},
	{
		word: 'praeter + acc',
		category: 'prep',
		translation: 'beyond, except, besides',
		asked: false,
	},
	{
		word: 'praeterea',
		category: 'adverb',
		translation: 'besides, moreover, in addition',
		asked: false,
	},
	{
		word: 'praetor, praetoris, m',
		category: 'noun 3',
		translation: 'praetor (acted as judge or governor)',
		asked: false,
	},
	{
		word: 'precor, precari, precatus sum',
		category: 'verb 1 dep',
		translation: 'pray, pray to, beg',
		asked: false,
	},
	{
		word: 'pretium, pretii, n',
		category: 'noun 2',
		translation: 'price, value',
		asked: false,
	},
	{
		word: 'primus, prima, primum',
		category: 'adj',
		translation: 'first, chief',
		asked: false,
	},
	{
		word: 'princeps, principis, m',
		category: 'noun 3',
		translation: 'emperor, chief, chieftain',
		asked: false,
	},
	{
		word: 'prior, prioris',
		category: 'adj',
		translation: 'previous, former',
		asked: false,
	},
	{
		word: 'prius',
		category: 'adverb',
		translation: 'before, previously',
		asked: false,
	},
	{
		word: 'priusquam',
		category: 'conjunction',
		translation: 'before, until',
		asked: false,
	},
	{
		word: 'pro + abl',
		category: 'prep',
		translation: 'in front of, for, on behalf of, in return for',
		asked: false,
	},
	{
		word: 'procedo, procedere, processi',
		category: 'verb 3',
		translation: 'advance, proceed',
		asked: false,
	},
	{
		word: 'procul',
		category: 'adverb',
		translation: 'far away, distant',
		asked: false,
	},
	{
		word: 'prodo, prodere, prodidi, proditus',
		category: 'verb 3',
		translation: 'betray, surrender',
		asked: false,
	},
	{
		word: 'proelium, proelii, n',
		category: 'noun 2',
		translation: 'battle',
		asked: false,
	},
	{
		word: 'proficiscor, proficisci, profectus sum',
		category: 'verb 3 dep',
		translation: 'set out, depart',
		asked: false,
	},
	{
		word: 'progredior, progredi, progressus sum',
		category: 'verb 3 dep',
		translation: 'advance, proceed',
		asked: false,
	},
	{
		word: 'promitto, promittere, promisi, promissus',
		category: 'verb 3',
		translation: 'promise',
		asked: false,
	},
	{
		word: 'prope + acc',
		category: 'prep',
		translation: 'near',
		asked: false,
	},
	{
		word: 'propter + acc',
		category: 'prep',
		translation: 'on account of, because of',
		asked: false,
	},
	{
		word: 'provincia, provinciae, f',
		category: 'noun 1',
		translation: 'province',
		asked: false,
	},
	{
		word: 'proximus, proxima, proximum',
		category: 'adj',
		translation: 'nearest, next, last',
		asked: false,
	},
	{
		word: 'publicus, publica, publicum',
		category: 'adj',
		translation: 'public, common',
		asked: false,
	},
	{
		word: 'pudor, pudoris, m',
		category: 'noun 3',
		translation: 'shame, modesty, honour, disgrace',
		asked: false,
	},
	{
		word: 'puella, puellae, f',
		category: 'noun 1',
		translation: 'girl',
		asked: false,
	},
	{
		word: 'puer, pueri, m',
		category: 'noun 2',
		translation: 'boy',
		asked: false,
	},
	{
		word: 'pugna, pugnae, f',
		category: 'noun 1',
		translation: 'fight, battle',
		asked: false,
	},
	{
		word: 'pugno, pugnare, pugnavi',
		category: 'verb 1',
		translation: 'fight',
		asked: false,
	},
	{
		word: 'punio, punire, punivi, punitus',
		category: 'verb 4',
		translation: 'punish',
		asked: false,
	},
	{
		word: 'puto, putare, putavi, putatus',
		category: 'verb 1',
		translation: 'think, consider, reckon',
		asked: false,
	},
	{
		word: 'quaero, quaerere, quaesivi, quaesitus',
		category: 'verb 3',
		translation: 'search for, ask for, ask, inquire',
		asked: false,
	},
	{
		word: 'qualis?, quale',
		category: 'adj',
		translation: 'what sort of?',
		asked: false,
	},
	{
		word: 'quam',
		category: 'adverb',
		translation: 'how, than, as',
		asked: false,
	},
	{
		word: 'quam + superlative',
		category: null,
		translation: 'as ... as possible',
		asked: false,
	},
	{
		word: 'quamquam',
		category: 'conjunction',
		translation: 'although',
		asked: false,
	},
	{
		word: 'quando?',
		category: 'adverb',
		translation: 'when?',
		asked: false,
	},
	{
		word: 'quantus?, quanta, quantum',
		category: 'adj',
		translation: 'how big? how much?',
		asked: false,
	},
	{
		word: 'quasi',
		category: 'adverb',
		translation: 'as if, just as, nearly',
		asked: false,
	},
	{
		word: '-que',
		category: 'conjunction',
		translation: 'and',
		asked: false,
	},
	{
		word: 'queror, queri, questus sum',
		category: 'verb 3 dep',
		translation: 'complain',
		asked: false,
	},
	{
		word: 'qui, quae, quod',
		category: 'pron',
		translation: 'who, which, that',
		asked: false,
	},
	{
		word: 'quia',
		category: 'conjunction',
		translation: 'because',
		asked: false,
	},
	{
		word: 'quidam, quaedam, quoddam',
		category: 'pron',
		translation: 'one, a certain, some',
		asked: false,
	},
	{
		word: 'quidem',
		category: 'adverb',
		translation: 'indeed, in fact, however',
		asked: false,
	},
	{
		word: 'ne ... quidem',
		category: 'adverb',
		translation: 'not ... even',
		asked: false,
	},
	{
		word: 'quies, quietis, f',
		category: 'noun 3',
		translation: 'rest, peace, quiet',
		asked: false,
	},
	{
		word: 'quis?, quid',
		category: 'pron',
		translation: 'who? what? any',
		asked: false,
	},
	{
		word: 'quisquam, quicquam',
		category: 'pron',
		translation: 'anyone, anything',
		asked: false,
	},
	{
		word: 'quisque, quaeque, quidque',
		category: 'pron',
		translation: 'each, each one, every',
		asked: false,
	},
	{
		word: 'quisquis, quicquid',
		category: 'pron',
		translation: 'whoever, whatever',
		asked: false,
	},
	{
		word: 'quo?',
		category: 'adverb',
		translation: 'where to?',
		asked: false,
	},
	{
		word: 'quoad',
		category: 'conjunction',
		translation: 'as long as, until',
		asked: false,
	},
	{
		word: 'quod',
		category: 'conjunction',
		translation: 'because, (as to) the fact that',
		asked: false,
	},
	{
		word: 'quod si',
		category: 'conjunction',
		translation: 'but if',
		asked: false,
	},
	{
		word: 'quomodo?',
		category: 'adverb',
		translation: 'how? in what way?',
		asked: false,
	},
	{
		word: 'quoniam',
		category: 'conjunction',
		translation: 'since',
		asked: false,
	},
	{
		word: 'quoque',
		category: 'conjunction',
		translation: 'also, too',
		asked: false,
	},
	{
		word: 'quot?',
		category: 'adj',
		translation: 'how many?',
		asked: false,
	},
	{
		word: 'quotiens?',
		category: 'adverb',
		translation: 'how often? as often as',
		asked: false,
	},
	{
		word: 'rapio, rapere, rapui, raptus',
		category: 'verb 3',
		translation: 'seize, grab, carry off, plunder',
		asked: false,
	},
	{
		word: 'ratio, rationis, f',
		category: 'noun 3',
		translation: 'account, reckoning, manner, reason',
		asked: false,
	},
	{
		word: 'recens, recentis',
		category: 'adj',
		translation: 'recent, fresh',
		asked: false,
	},
	{
		word: 'recipio, recipere, recepi, receptus',
		category: 'verb 3',
		translation: 'regain, receive, welcome',
		asked: false,
	},
	{
		word: 'me recipio',
		category: 'verb phrase',
		translation: 'retreat, withdraw',
		asked: false,
	},
	{
		word: 'recito, recitare, recitavi, recitatus',
		category: 'verb 1',
		translation: 'recite, read aloud',
		asked: false,
	},
	{
		word: 'rectus, recta, rectum',
		category: 'adj',
		translation: 'straight, direct, right, proper',
		asked: false,
	},
	{
		word: 'reddo, reddere, reddidi, redditus',
		category: 'verb 3',
		translation: 'give back, restore, hand over, make',
		asked: false,
	},
	{
		word: 'redeo, redire, redii',
		category: 'verb irreg',
		translation: 'return, go back, come back',
		asked: false,
	},
	{
		word: 'refero, referre, rettuli, relatus',
		category: 'verb irreg',
		translation: 'bring back, report, refer',
		asked: false,
	},
	{
		word: 'pedem/me refero',
		category: 'verb phrase',
		translation: 'retreat',
		asked: false,
	},
	{
		word: 'reficio, reficere, refeci, refectus',
		category: 'verb 3',
		translation: 'repair, restore, refresh',
		asked: false,
	},
	{
		word: 'regina, reginae, f',
		category: 'noun 1',
		translation: 'queen',
		asked: false,
	},
	{
		word: 'regnum, regni, n',
		category: 'noun 2',
		translation: 'kingdom, reign, rule',
		asked: false,
	},
	{
		word: 'rego, regere, rexi, rectus',
		category: 'verb 3',
		translation: 'rule, direct',
		asked: false,
	},
	{
		word: 'regredior, regredi, regressus sum',
		category: 'verb 3 dep',
		translation: 'go back, return',
		asked: false,
	},
	{
		word: 'relinquo, relinquere, reliqui, relictus',
		category: 'verb 3',
		translation: 'leave, leave behind, abandon',
		asked: false,
	},
	{
		word: 'reliquus, reliqua, reliquum',
		category: 'adj',
		translation: 'the rest of, the other',
		asked: false,
	},
	{
		word: 'repente',
		category: 'adverb',
		translation: 'suddenly',
		asked: false,
	},
	{
		word: 'res, rei, f',
		category: 'noun 5',
		translation: 'thing, affair, matter, business',
		asked: false,
	},
	{
		word: 'res publica, rei publicae, f',
		category: 'noun phrase',
		translation: 'state, republic',
		asked: false,
	},
	{
		word: 'resisto, resistere, restiti + dat',
		category: 'verb 3',
		translation: 'resist, oppose',
		asked: false,
	},
	{
		word: 'respondeo, respondere, respondi, responsus',
		category: 'verb 2',
		translation: 'answer, reply',
		asked: false,
	},
	{
		word: 'responsum, responsi, n',
		category: 'noun 2',
		translation: 'answer, reply',
		asked: false,
	},
	{
		word: 'retineo, retinere, retinui, retentus',
		category: 'verb 2',
		translation: 'hold back, restrain, keep',
		asked: false,
	},
	{
		word: 'rex, regis, m',
		category: 'noun 3',
		translation: 'king',
		asked: false,
	},
	{
		word: 'ripa, ripae, f',
		category: 'noun 1',
		translation: 'bank',
		asked: false,
	},
	{
		word: 'rogo, rogare, rogavi, rogatus',
		category: 'verb 1',
		translation: 'ask, ask for',
		asked: false,
	},
	{
		word: 'rumpo, rumpere, rupi, ruptus',
		category: 'verb 3',
		translation: 'break, burst, break through',
		asked: false,
	},
	{
		word: 'rursus',
		category: 'adverb',
		translation: 'back, again',
		asked: false,
	},
	{
		word: 'rus, ruris, n',
		category: 'noun 3',
		translation: 'country, countryside',
		asked: false,
	},
	{
		word: 'sacerdos, sacerdotis, m and f',
		category: 'noun 3',
		translation: 'priest, priestess',
		asked: false,
	},
	{
		word: 'saepe',
		category: 'adverb',
		translation: 'often',
		asked: false,
	},
	{
		word: 'saevus, saeva, saevum',
		category: 'adj',
		translation: 'savage, cruel',
		asked: false,
	},
	{
		word: 'salus, salutis, f',
		category: 'noun 3',
		translation: 'health, safety, greeting',
		asked: false,
	},
	{
		word: 'saluto, salutare, salutavi, salutatus',
		category: 'verb 1',
		translation: 'greet, salute',
		asked: false,
	},
	{
		word: 'sanguis, sanguinis, m',
		category: 'noun 3',
		translation: 'blood',
		asked: false,
	},
	{
		word: 'sapiens, sapientis',
		category: 'adj',
		translation: 'wise, sensible',
		asked: false,
	},
	{
		word: 'sapientia, sapientiae, f',
		category: 'noun 1',
		translation: 'wisdom, good sense',
		asked: false,
	},
	{
		word: 'satis',
		category: 'adj',
		translation: 'enough',
		asked: false,
	},
	{
		word: 'scelus, sceleris, n',
		category: 'noun 3',
		translation: 'crime, wickedness',
		asked: false,
	},
	{
		word: 'scio, scire, scivi, scitus',
		category: 'verb 4',
		translation: 'know',
		asked: false,
	},
	{
		word: 'scribo, scribere, scripsi, scriptus',
		category: 'verb 3',
		translation: 'write',
		asked: false,
	},
	{
		word: 'scutum, scuti, n',
		category: 'noun 2',
		translation: 'shield',
		asked: false,
	},
	{
		word: 'se, sui',
		category: 'pron',
		translation: 'himself, herself, itself, themselves',
		asked: false,
	},
	{
		word: 'secundus, secunda, secundum',
		category: 'adj',
		translation: 'following, next, second, favourable',
		asked: false,
	},
	{
		word: 'sed',
		category: 'conjunction',
		translation: 'but',
		asked: false,
	},
	{
		word: 'sedes, sedis, f',
		category: 'noun 3',
		translation: 'seat, temple, home',
		asked: false,
	},
	{
		word: 'semel',
		category: 'adverb',
		translation: 'once',
		asked: false,
	},
	{
		word: 'semper',
		category: 'adverb',
		translation: 'always',
		asked: false,
	},
	{
		word: 'senator, senatoris, m',
		category: 'noun 3',
		translation: 'senator',
		asked: false,
	},
	{
		word: 'senatus, senatus, m',
		category: 'noun 4',
		translation: 'senate',
		asked: false,
	},
	{
		word: 'senex, senis, m',
		category: 'noun 3',
		translation: 'old man',
		asked: false,
	},
	{
		word: 'sententia, sententiae, f',
		category: 'noun 1',
		translation: 'opinion, judgement, sentence',
		asked: false,
	},
	{
		word: 'sentio, sentire, sensi, sensus',
		category: 'verb 4',
		translation: 'feel, notice, hear, judge',
		asked: false,
	},
	{
		word: 'sequor, sequi, secutus sum',
		category: 'verb 3 dep',
		translation: 'follow, pursue, attend',
		asked: false,
	},
	{
		word: 'servo, servare, servavi, servatus',
		category: 'verb 1',
		translation: 'save, protect, keep',
		asked: false,
	},
	{
		word: 'servus, servi, m',
		category: 'noun 2',
		translation: 'slave',
		asked: false,
	},
	{
		word: 'si',
		category: 'conjunction',
		translation: 'if',
		asked: false,
	},
	{
		word: 'sic',
		category: 'adverb',
		translation: 'thus, in this way',
		asked: false,
	},
	{
		word: 'sicut',
		category: 'adverb',
		translation: 'just as, like, as, as if',
		asked: false,
	},
	{
		word: 'signum, signi, n',
		category: 'noun 2',
		translation: 'sign, signal, standard',
		asked: false,
	},
	{
		word: 'silentium, silentii, n',
		category: 'noun 2',
		translation: 'silence',
		asked: false,
	},
	{
		word: 'silva, silvae, f',
		category: 'noun 1',
		translation: 'wood, forest',
		asked: false,
	},
	{
		word: 'similis, simile',
		category: 'adj',
		translation: 'similar, like',
		asked: false,
	},
	{
		word: 'simul',
		category: 'adverb',
		translation: 'at the same time, together',
		asked: false,
	},
	{
		word: 'simulac, (simulatque) indeclinable',
		category: 'conjunction',
		translation: 'as soon as',
		asked: false,
	},
	{
		word: 'sine + abl',
		category: 'prep',
		translation: 'without',
		asked: false,
	},
	{
		word: 'sinister, sinistra, sinistrum',
		category: 'adj',
		translation: 'left, on the left, unfavourable',
		asked: false,
	},
	{
		word: 'sinistra, sinistrae, f',
		category: 'noun 1',
		translation: 'left hand, left side',
		asked: false,
	},
	{
		word: 'sino, sinere, sivi, situs',
		category: 'verb 3',
		translation: 'allow, permit',
		asked: false,
	},
	{
		word: 'sive, seu',
		category: 'conjunction',
		translation: 'or if, whether',
		asked: false,
	},
	{
		word: 'socius, socii, m',
		category: 'noun 2',
		translation: 'ally, comrade, companion',
		asked: false,
	},
	{
		word: 'sol, solis, m',
		category: 'noun 3',
		translation: 'sun, sunlight',
		asked: false,
	},
	{
		word: 'soleo, solere, solitus sum',
		category: 'verb 2 semidep',
		translation: 'be accustomed',
		asked: false,
	},
	{
		word: 'solum',
		category: 'adverb',
		translation: 'only',
		asked: false,
	},
	{
		word: 'solus, sola, solum',
		category: 'adj',
		translation: 'alone, only, lonely, single',
		asked: false,
	},
	{
		word: 'solvo, solvere, solvi, solutus',
		category: 'verb 3',
		translation: 'loose, pay',
		asked: false,
	},
	{
		word: 'navem solvo',
		category: 'verb phrase',
		translation: 'set sail',
		asked: false,
	},
	{
		word: 'somnus, somni, m',
		category: 'noun 2',
		translation: 'sleep',
		asked: false,
	},
	{
		word: 'sonus, soni, m',
		category: 'noun 2',
		translation: 'noise, sound',
		asked: false,
	},
	{
		word: 'soror, sororis, f',
		category: 'noun 3',
		translation: 'sister',
		asked: false,
	},
	{
		word: 'spatium, spatii, n',
		category: 'noun 2',
		translation: 'interval, space, distance',
		asked: false,
	},
	{
		word: 'specto, spectare, spectavi, spectatus',
		category: 'verb 1',
		translation: 'look at, watch',
		asked: false,
	},
	{
		word: 'sperno, spernere, sprevi, spretus',
		category: 'verb 3',
		translation: 'despise, reject, scorn',
		asked: false,
	},
	{
		word: 'spero, sperare, speravi, speratus',
		category: 'verb 1',
		translation: 'hope, expect',
		asked: false,
	},
	{
		word: 'spes, spei, f',
		category: 'noun 5',
		translation: 'hope',
		asked: false,
	},
	{
		word: 'spolium, spolii, n',
		category: 'noun 2',
		translation: 'booty, spoil(s)',
		asked: false,
	},
	{
		word: 'statim',
		category: 'adverb',
		translation: 'at once, immediately',
		asked: false,
	},
	{
		word: 'statuo, statuere, statui, statutus',
		category: 'verb 3',
		translation: 'fix, determine, decide, arrange',
		asked: false,
	},
	{
		word: 'sto, stare, steti',
		category: 'verb 1',
		translation: 'stand, stand firm',
		asked: false,
	},
	{
		word: 'studium, studii, n',
		category: 'noun 2',
		translation: 'eagerness, study, devotion',
		asked: false,
	},
	{
		word: 'stultus, stulta, stultum',
		category: 'adj',
		translation: 'stupid, foolish',
		asked: false,
	},
	{
		word: 'sub + abl or + acc',
		category: 'prep',
		translation: 'under, beneath; up to',
		asked: false,
	},
	{
		word: 'subito',
		category: 'adverb',
		translation: 'suddenly',
		asked: false,
	},
	{
		word: 'sum, esse, fui',
		category: 'verb irreg',
		translation: 'be',
		asked: false,
	},
	{
		word: 'summus, summa, summum',
		category: 'adj',
		translation: 'highest, greatest, top (of)',
		asked: false,
	},
	{
		word: 'sumo, sumere, sumpsi, sumptus',
		category: 'verb 3',
		translation: 'take, take up',
		asked: false,
	},
	{
		word: 'supero, superare, superavi, superatus',
		category: 'verb 1',
		translation: 'overcome, overpower',
		asked: false,
	},
	{
		word: 'supersum, superesse, superfui',
		category: 'verb irreg',
		translation: 'be left, remain, survive',
		asked: false,
	},
	{
		word: 'superus, supera, superum',
		category: 'adj',
		translation: 'upper, higher',
		asked: false,
	},
	{
		word: 'surgo, surgere, surrexi',
		category: 'verb 3',
		translation: 'get up, stand up, rise',
		asked: false,
	},
	{
		word: 'suscipio, suscipere, suscepi, susceptus',
		category: 'verb 3',
		translation: 'take up, undertake, begin, bear',
		asked: false,
	},
	{
		word: 'suspicor, suspicari, suspicatus sum',
		category: 'verb 1 dep',
		translation: 'mistrust, suspect',
		asked: false,
	},
	{
		word: 'suus, sua, suum',
		category: 'pron',
		translation: 'his (own), her (own), its (own), their (own)',
		asked: false,
	},
	{
		word: 'taberna, tabernae, f',
		category: 'noun 1',
		translation: 'shop, inn',
		asked: false,
	},
	{
		word: 'tacitus, tacita, tacitum',
		category: 'adj',
		translation: 'quiet, silent, in silence',
		asked: false,
	},
	{
		word: 'talis, tale',
		category: 'adj',
		translation: 'such',
		asked: false,
	},
	{
		word: 'tam',
		category: 'adverb',
		translation: 'so',
		asked: false,
	},
	{
		word: 'tamen',
		category: 'adverb',
		translation: 'however, nevertheless, yet',
		asked: false,
	},
	{
		word: 'tandem',
		category: 'adverb',
		translation: 'at last, finally',
		asked: false,
	},
	{
		word: 'tango, tangere, tetigi, tactus',
		category: 'verb 3',
		translation: 'touch',
		asked: false,
	},
	{
		word: 'tantum',
		category: 'adverb',
		translation: 'only',
		asked: false,
	},
	{
		word: 'tantus, tanta, tantum',
		category: 'adj',
		translation: 'so great, such a great, so much',
		asked: false,
	},
	{
		word: 'tectum, tecti, n',
		category: 'noun 2',
		translation: 'roof, house',
		asked: false,
	},
	{
		word: 'tego, tegere, texi, tectus',
		category: 'verb 3',
		translation: 'cover, protect, hide',
		asked: false,
	},
	{
		word: 'telum, teli, n',
		category: 'noun 2',
		translation: 'weapon, javelin, missile',
		asked: false,
	},
	{
		word: 'tempestas, tempestatis, f',
		category: 'noun 3',
		translation: 'weather, storm, time',
		asked: false,
	},
	{
		word: 'templum, templi, n',
		category: 'noun 2',
		translation: 'temple',
		asked: false,
	},
	{
		word: 'tempus, temporis, n',
		category: 'noun 3',
		translation: 'time',
		asked: false,
	},
	{
		word: 'teneo, tenere, tenui, tentus',
		category: 'verb 2',
		translation: 'hold, keep, maintain',
		asked: false,
	},
	{
		word: 'tergum, tergi, n',
		category: 'noun 2',
		translation: 'back, rear',
		asked: false,
	},
	{
		word: 'terra, terrae, f',
		category: 'noun 1',
		translation: 'ground, land, earth',
		asked: false,
	},
	{
		word: 'terreo, terrere, terrui, territus',
		category: 'verb 2',
		translation: 'frighten',
		asked: false,
	},
	{
		word: 'terror, terroris, m',
		category: 'noun 3',
		translation: 'terror, panic',
		asked: false,
	},
	{
		word: 'timeo, timere, timui',
		category: 'verb 2',
		translation: 'fear, be afraid',
		asked: false,
	},
	{
		word: 'timor, timoris, m',
		category: 'noun 3',
		translation: 'fear, anxiety',
		asked: false,
	},
	{
		word: 'tollo, tollere, sustuli, sublatus',
		category: 'verb 3',
		translation: 'raise, lift up, remove, destroy',
		asked: false,
	},
	{
		word: 'tot',
		category: 'adj',
		translation: 'so many',
		asked: false,
	},
	{
		word: 'totus, tota, totum',
		category: 'adj',
		translation: 'the whole, entire, all',
		asked: false,
	},
	{
		word: 'trado, tradere, tradidi, traditus',
		category: 'verb 3',
		translation: 'hand over, entrust, hand down, surrender',
		asked: false,
	},
	{
		word: 'traho, trahere, traxi, tractus',
		category: 'verb 3',
		translation: 'pull, drag, draw',
		asked: false,
	},
	{
		word: 'trans + acc',
		category: 'prep',
		translation: 'across, over',
		asked: false,
	},
	{
		word: 'tristis, triste',
		category: 'adj',
		translation: 'sad, gloomy, grim',
		asked: false,
	},
	{
		word: 'tu, tui',
		category: 'pron',
		translation: 'you (singular)',
		asked: false,
	},
	{
		word: 'tum',
		category: 'adverb',
		translation: 'then, next',
		asked: false,
	},
	{
		word: 'tumultus, tumultus, m',
		category: 'noun 4',
		translation: 'uproar, disturbance, civil war',
		asked: false,
	},
	{
		word: 'turba, turbae, f',
		category: 'noun 1',
		translation: 'crowd, mob, disturbance, multitude',
		asked: false,
	},
	{
		word: 'tutus, tuta, tutum',
		category: 'adj',
		translation: 'safe',
		asked: false,
	},
	{
		word: 'tuus, tua, tuum',
		category: 'pron',
		translation: 'your (singular)',
		asked: false,
	},
	{
		word: 'ubi',
		category: 'adverb',
		translation: 'where? where, when',
		asked: false,
	},
	{
		word: 'ubique',
		category: 'adverb',
		translation: 'everywhere',
		asked: false,
	},
	{
		word: 'ullus, ulla, ullum',
		category: 'adj',
		translation: 'any',
		asked: false,
	},
	{
		word: 'ultimus, ultima, ultimum',
		category: 'adj',
		translation: 'furthest, last, utmost',
		asked: false,
	},
	{
		word: 'umquam',
		category: 'adverb',
		translation: 'ever',
		asked: false,
	},
	{
		word: 'una',
		category: 'adverb',
		translation: 'together',
		asked: false,
	},
	{
		word: 'unda, undae, f',
		category: 'noun 1',
		translation: 'wave',
		asked: false,
	},
	{
		word: 'unde',
		category: 'adverb',
		translation: 'from where, whence',
		asked: false,
	},
	{
		word: 'undique',
		category: 'adverb',
		translation: 'from all sides, on all sides',
		asked: false,
	},
	{
		word: 'urbs, urbis, f',
		category: 'noun 3',
		translation: 'city, town, Rome',
		asked: false,
	},
	{
		word: 'usque',
		category: 'adverb',
		translation: 'all the way, right up to, continuously',
		asked: false,
	},
	{
		word: 'usus, usus, m',
		category: 'noun 4',
		translation: 'use, experience, practice',
		asked: false,
	},
	{
		word: 'usui est',
		category: 'verb phrase',
		translation: 'it is useful',
		asked: false,
	},
	{
		word: 'ut, indeclinable + indic.',
		category: 'conjunction',
		translation: 'as, where, when, how',
		asked: false,
	},
	{
		word: 'ut, indeclinable + subjunc.',
		category: 'conjunction',
		translation: 'that, so that, to',
		asked: false,
	},
	{
		word: 'uter?, utra, utrum',
		category: 'pron',
		translation: 'which (of two)?',
		asked: false,
	},
	{
		word: 'uterque, utraque, utrumque',
		category: 'pron',
		translation: 'each (of two), both',
		asked: false,
	},
	{
		word: 'utrum',
		category: 'adverb',
		translation: 'whether',
		asked: false,
	},
	{
		word: 'utor, uti, usus sum + abl',
		category: 'verb 3 dep',
		translation: 'use, enjoy',
		asked: false,
	},
	{
		word: 'uxor, uxoris, f',
		category: 'noun 3',
		translation: 'wife',
		asked: false,
	},
	{
		word: 'valeo, valere, valui',
		category: 'verb 2',
		translation: 'be strong, have influence',
		asked: false,
	},
	{
		word: 'validus, valida, validum',
		category: 'adj',
		translation: 'strong, powerful',
		asked: false,
	},
	{
		word: '-ve',
		category: 'conjunction',
		translation: 'or',
		asked: false,
	},
	{
		word: 'vehementer',
		category: 'adverb',
		translation: 'violently, loudly, strongly',
		asked: false,
	},
	{
		word: 'veho, vehere, vexi, vectus',
		category: 'verb 3',
		translation: 'carry, bear, convey',
		asked: false,
	},
	{
		word: 'vel',
		category: 'conjunction',
		translation: 'or, either',
		asked: false,
	},
	{
		word: 'velut',
		category: 'adverb',
		translation: 'just as, like, as, as if',
		asked: false,
	},
	{
		word: 'venio, venire, veni',
		category: 'verb 4',
		translation: 'come',
		asked: false,
	},
	{
		word: 'ventus, venti, m',
		category: 'noun 2',
		translation: 'wind',
		asked: false,
	},
	{
		word: 'verbum, verbi, n',
		category: 'noun 2',
		translation: 'word',
		asked: false,
	},
	{
		word: 'vereor, vereri, veritus sum',
		category: 'verb 2 dep',
		translation: 'fear, be afraid',
		asked: false,
	},
	{
		word: 'vero',
		category: 'adverb',
		translation: 'indeed, in fact, however',
		asked: false,
	},
	{
		word: 'verto, vertere, verti, versus',
		category: 'verb 3',
		translation: 'turn',
		asked: false,
	},
	{
		word: 'verus, vera, verum',
		category: 'adj',
		translation: 'true, real',
		asked: false,
	},
	{
		word: 'vesper, vesperis or vesperi, m',
		category: 'noun 3 or 2',
		translation: 'evening',
		asked: false,
	},
	{
		word: 'vester, vestra, vestrum',
		category: 'pron',
		translation: 'your (pl)',
		asked: false,
	},
	{
		word: 'vestis, vestis, f',
		category: 'noun 3',
		translation: 'clothes',
		asked: false,
	},
	{
		word: 'veto, vetare, vetui, vetitus',
		category: 'verb 1',
		translation: 'forbid, order…not',
		asked: false,
	},
	{
		word: 'vetus, veteris',
		category: 'adj',
		translation: 'old',
		asked: false,
	},
	{
		word: 'via, viae, f',
		category: 'noun 1',
		translation: 'street, road, way, path',
		asked: false,
	},
	{
		word: 'victor, victoris, m',
		category: 'noun 3',
		translation: 'victor, conqueror',
		asked: false,
	},
	{
		word: 'victoria, victoriae, f',
		category: 'noun 1',
		translation: 'victory',
		asked: false,
	},
	{
		word: 'video, videre, vidi, visus',
		category: 'verb 2',
		translation: 'see',
		asked: false,
	},
	{
		word: 'videor, videri, visus sum',
		category: 'verb 2 dep',
		translation: 'seem, appear, be seen',
		asked: false,
	},
	{
		word: 'villa, villae, f',
		category: 'noun 1',
		translation: 'country-house, estate, farm',
		asked: false,
	},
	{
		word: 'vinco, vincere, vici, victus',
		category: 'verb 3',
		translation: 'conquer, defeat, win, be victorious',
		asked: false,
	},
	{
		word: 'vir, viri, m',
		category: 'noun 2',
		translation: 'man, husband',
		asked: false,
	},
	{
		word: 'virtus, virtutis, f',
		category: 'noun 3',
		translation: 'courage, virtue',
		asked: false,
	},
	{
		word: 'vis, pl vires, f',
		category: 'noun irreg',
		translation: 'force, violence; (pl) strength, forces',
		asked: false,
	},
	{
		word: 'vita, vitae, f',
		category: 'noun 1',
		translation: 'life',
		asked: false,
	},
	{
		word: 'vito, vitare, vitavi, vitatus',
		category: 'verb 1',
		translation: 'avoid',
		asked: false,
	},
	{
		word: 'vivo, vivere, vixi',
		category: 'verb 3',
		translation: 'live, be alive, (+ abl) live on',
		asked: false,
	},
	{
		word: 'vivus, viva, vivum',
		category: 'adj',
		translation: 'alive, living',
		asked: false,
	},
	{
		word: 'vix',
		category: 'adverb',
		translation: 'hardly, scarcely, with difficulty',
		asked: false,
	},
	{
		word: 'voco, vocare, vocavi, vocatus',
		category: 'verb 1',
		translation: 'call, summon, invite, name',
		asked: false,
	},
	{
		word: 'volo, velle, volui',
		category: 'verb irreg',
		translation: 'want, wish, be willing, intend',
		asked: false,
	},
	{
		word: 'vos, vestrum / vestri',
		category: 'pron',
		translation: 'you (plural)',
		asked: false,
	},
	{
		word: 'vox, vocis, f',
		category: 'noun 3',
		translation: 'voice, shout, word',
		asked: false,
	},
	{
		word: 'vulnero, vulnerare, vulneravi, vulneratus',
		category: 'verb 1',
		translation: 'wound, injure',
		asked: false,
	},
	{
		word: 'vulnus, vulneris, n',
		category: 'noun 3',
		translation: 'wound, injury',
		asked: false,
	},
	{
		word: 'vultus, vultus, m',
		category: 'noun 4',
		translation: 'face, expression',
		asked: false,
	},
];
