var vocabGCSEOCR = [
	{
		word: 'a, ab + ablative (also used as prefix with verbs)',
		category: 'preposition',
		translation: 'from, away from, by (as prefix = away)',
		asked: false,
	},
	{
		word: 'absum, abesse, afui',
		category: 'verb irreg',
		translation: 'be absent, be away, be distant from',
		asked: false,
	},
	{
		word: 'ac, atque',
		category: 'conjunction',
		translation: 'and',
		asked: false,
	},
	{
		word: 'accido, accidere, accidi',
		category: 'verb 3',
		translation: 'happen',
		asked: false,
	},
	{
		word: 'accipio, accipere, accepi, acceptus',
		category: 'verb 3',
		translation: 'accept, take in, receive',
		asked: false,
	},
	{
		word: 'ad + accusative (also used as prefix with verbs)',
		category: 'preposition',
		translation: 'to, towards, at',
		asked: false,
	},
	{
		word: 'adeo',
		category: 'adverb',
		translation: 'so much, so greatly, to such an extent',
		asked: false,
	},
	{
		word: 'adsum, adesse, adfui',
		category: 'verb irreg',
		translation: 'be here, be present',
		asked: false,
	},
	{
		word: 'advenio, advenire, adveni',
		category: 'verb 4',
		translation: 'arrive',
		asked: false,
	},
	{
		word: 'aedifico, aedificare, aedificavi, aedificatus',
		category: 'verb 1',
		translation: 'build',
		asked: false,
	},
	{
		word: 'ager, agri, m',
		category: 'noun 2',
		translation: 'field',
		asked: false,
		noms: 'ager',
		nomp: 'agri',
		gens: 'agri',
		genp: 'agrorum',
		dats: 'agro',
		datp: 'agris',
		accs: 'agrum',
		accp: 'agros',
		vocs: 'ager',
		vocp: 'agri',
		abls: 'agro',
		ablp: 'agris',
	},
	{
		word: 'ago, agere, egi, actus',
		category: 'verb 3',
		translation: 'do, act, drive',
		asked: false,
	},
	{
		word: 'alii...alii',
		category: 'pronoun',
		translation: 'some...others, some others',
		asked: false,
	},
	{
		word: 'alius, alia, aliud',
		category: 'pronoun',
		translation: 'other, another, else',
		asked: false,
	},
	{
		word: 'alter, altera, alterum',
		category: 'pronoun',
		translation: 'the other, another, one (of two), the second (of two)',
		asked: false,
	},
	{
		word: 'altus, alta, altum',
		category: 'adjective',
		translation: 'high, deep',
		asked: false,
	},
	{
		word: 'ambulo, ambulare, ambulavi',
		category: 'verb 1',
		translation: 'walk',
		asked: false,
	},
	{
		word: 'amicus, amici, m',
		category: 'noun 2',
		translation: 'friend',
		asked: false,
		noms: 'amicus',
		nomp: 'amici',
		gens: 'amici',
		genp: 'amicorum',
		dats: 'amico',
		datp: 'amicis',
		accs: 'amicum',
		accp: 'amicos',
		vocs: 'amice',
		vocp: 'amici',
		abls: 'amico',
		ablp: 'amicis',
	},
	{
		word: 'amo, amare, amavi, amatus',
		category: 'verb 1',
		translation: 'love, like',
		asked: false,
	},
	{
		word: 'amor, amoris, m',
		category: 'noun 3',
		translation: 'love',
		asked: false,
		noms: 'amor',
		nomp: 'amores',
		gens: 'amoris',
		genp: 'amorum',
		dats: 'amori',
		datp: 'amoribus',
		accs: 'amorem',
		accp: 'amores',
		vocs: 'amor',
		vocp: 'amores',
		abls: 'amore',
		ablp: 'amoribus',
	},
	{
		word: 'ancilla, ancillae, f',
		category: 'noun 1',
		translation: 'slave-girl, slave-woman, maid',
		asked: false,
		noms: 'ancilla',
		nomp: 'ancillae',
		gens: 'ancillae',
		genp: 'ancillarum',
		dats: 'ancillae',
		datp: 'ancillis',
		accs: 'ancillam',
		accp: 'ancillas',
		vocs: 'ancilla',
		vocp: 'ancillae',
		abls: 'ancilla',
		ablp: 'ancillis',
	},
	{
		word: 'animus, animi, m',
		category: 'noun 2',
		translation: 'spirit, soul, mind',
		asked: false,
		noms: 'animus',
		nomp: 'animi',
		gens: 'animi',
		genp: 'animorum',
		dats: 'animo',
		datp: 'animis',
		accs: 'animum',
		accp: 'animos',
		vocs: 'anime',
		vocp: 'animi',
		abls: 'animo',
		ablp: 'animis',
	},
	{
		word: 'annus, anni, m',
		category: 'noun 2',
		translation: 'year',
		asked: false,
		noms: 'annus',
		nomp: 'anni',
		gens: 'anni',
		genp: 'annorum',
		dats: 'anno',
		datp: 'annis',
		accs: 'annum',
		accp: 'annos',
		vocs: 'anne',
		vocp: 'anni',
		abls: 'anno',
		ablp: 'annis',
	},
	{
		word: 'antea',
		category: 'adverb',
		translation: 'before',
		asked: false,
	},
	{
		word: 'appropinquo, appropinquare, appropinquavi + dative',
		category: 'verb 1',
		translation: 'approach, come near to',
		asked: false,
	},
	{
		word: 'aqua, aquae, f',
		category: 'noun 1',
		translation: 'water',
		asked: false,
		noms: 'aqua',
		nomp: 'aquae',
		gens: 'aquae',
		genp: 'aquarum',
		dats: 'aquae',
		datp: 'aquis',
		accs: 'aquam',
		accp: 'aquas',
		vocs: 'aqua',
		vocp: 'aquae',
		abls: 'aqua',
		ablp: 'aquis',
	},
	{
		word: 'arma, armorum, n plural',
		category: 'noun 2 plural',
		translation: 'arms, weapons',
		asked: false,
		noms: 'armum',
		nomp: 'arma',
		gens: 'armi',
		genp: 'armorum',
		dats: 'armo',
		datp: 'armis',
		accs: 'armum',
		accp: 'arma',
		vocs: 'armum',
		vocp: 'arma',
		abls: 'armo',
		ablp: 'armis',
	},
	{
		word: 'ars, artis, f',
		category: 'noun 3',
		translation: 'art, skill',
		asked: false,
		noms: 'ars',
		nomp: 'artes',
		gens: 'artis',
		genp: 'artium',
		dats: 'arti',
		datp: 'artibus',
		accs: 'artem',
		accp: 'artes',
		vocs: 'ars',
		vocp: 'artes',
		abls: 'arte',
		ablp: 'artibus',
	},
	{
		word: 'ascendo, ascendere, ascendi, ascensus',
		category: 'verb 3',
		translation: 'climb',
		asked: false,
	},
	{
		word: 'audax, audacis',
		category: 'adjective',
		translation: 'bold, daring',
		asked: false,
	},
	{
		word: 'audeo, audere, ausus sum',
		category: 'verb 2',
		translation: 'dare',
		asked: false,
	},
	{
		word: 'audio, audire, audivi, auditus',
		category: 'verb 4',
		translation: 'hear, listen to',
		asked: false,
	},
	{
		word: 'aufero, auferre, abstuli, ablatus',
		category: 'verb irreg',
		translation: 'take away, carry off, steal',
		asked: false,
	},
	{
		word: 'auxilium, auxilii, n',
		category: 'noun 2',
		translation: 'help',
		asked: false,
		noms: 'auxilium',
		nomp: 'auxilia',
		gens: 'auxilii',
		genp: 'auxiliorum',
		dats: 'auxilio',
		datp: 'auxiliis',
		accs: 'auxilium',
		accp: 'auxilia',
		vocs: 'auxilium',
		vocp: 'auxilia',
		abls: 'auxilio',
		ablp: 'auxiliis',
	},
	{
		word: 'bellum, belli, n',
		category: 'noun 2',
		translation: 'war',
		asked: false,
		noms: 'bellum',
		nomp: 'bella',
		gens: 'belli',
		genp: 'bellorum',
		dats: 'bello',
		datp: 'bellis',
		accs: 'bellum',
		accp: 'bella',
		vocs: 'bellum',
		vocp: 'bella',
		abls: 'bello',
		ablp: 'bellis',
	},
	{
		word: 'bene',
		category: 'adverb',
		translation: 'well',
		asked: false,
	},
	{
		word: 'bibo, bibere, bibi',
		category: 'verb 3',
		translation: 'drink',
		asked: false,
	},
	{
		word: 'bonus, bona, bonum',
		category: 'adjective',
		translation: 'good',
		asked: false,
	},
	{
		word: 'brevis, breve',
		category: 'adjective',
		translation: 'short, brief',
		asked: false,
	},
	{
		word: 'cado, cadere, cecidi, casus',
		category: 'verb 3',
		translation: 'fall',
		asked: false,
	},
	{
		word: 'caelum, caeli, n',
		category: 'noun 2',
		translation: 'sky, heaven',
		asked: false,
		noms: 'caelum',
		nomp: 'caela',
		gens: 'caeli',
		genp: 'caelorum',
		dats: 'caelo',
		datp: 'caelis',
		accs: 'caelum',
		accp: 'caela',
		vocs: 'caelum',
		vocp: 'caela',
		abls: 'caelo',
		ablp: 'caelis',
	},
	{
		word: 'capio, capere, cepi, captus',
		category: 'verb 3',
		translation: 'take, catch, capture, make (a plan)',
		asked: false,
	},
	{
		word: 'captivus, captivi, m',
		category: 'noun 2',
		translation: 'captive, prisoner',
		asked: false,
		noms: 'captivus',
		nomp: 'captivi',
		gens: 'captivi',
		genp: 'captivorum',
		dats: 'captivo',
		datp: 'captivis',
		accs: 'captivum',
		accp: 'captivos',
		vocs: 'captive',
		vocp: 'captivi',
		abls: 'captivo',
		ablp: 'captivis',
	},
	{
		word: 'caput, capitis, n',
		category: 'noun 3',
		translation: 'head',
		asked: false,
		noms: 'caput',
		nomp: 'capita',
		gens: 'capitis',
		genp: 'capitum',
		dats: 'capiti',
		datp: 'capitibus',
		accs: 'caput',
		accp: 'capita',
		vocs: 'caput',
		vocp: 'capita',
		abls: 'capite',
		ablp: 'capitibus',
	},
	{
		word: 'castra, castrorum, n plural',
		category: 'noun 2',
		translation: 'camp',
		asked: false,
		noms: 'castrum',
		nomp: 'castra',
		gens: 'castri',
		genp: 'castrorum',
		dats: 'castro',
		datp: 'castris',
		accs: 'castrum',
		accp: 'castra',
		vocs: 'castrum',
		vocp: 'castra',
		abls: 'castro',
		ablp: 'castris',
	},
	{
		word: 'celer, celeris, celere',
		category: 'adjective',
		translation: 'quick, fast',
		asked: false,
	},
	{
		word: 'celo, celare, celavi, celatus',
		category: 'verb 1',
		translation: 'hide',
		asked: false,
	},
	{
		word: 'cena, cenae, f',
		category: 'noun 1',
		translation: 'dinner, meal',
		asked: false,
		noms: 'cena',
		nomp: 'cenae',
		gens: 'cenae',
		genp: 'cenarum',
		dats: 'cenae',
		datp: 'cenis',
		accs: 'cenam',
		accp: 'cenas',
		vocs: 'cena',
		vocp: 'cenae',
		abls: 'cena',
		ablp: 'cenis',
	},
	{
		word: 'ceteri, ceterae, cetera',
		category: 'adjective',
		translation: 'the rest, the others',
		asked: false,
	},
	{
		word: 'cibus, cibi, m',
		category: 'noun 2',
		translation: 'food',
		asked: false,
		noms: 'cibus',
		nomp: 'cibi',
		gens: 'cibi',
		genp: 'ciborum',
		dats: 'cibo',
		datp: 'cibis',
		accs: 'cibum',
		accp: 'cibos',
		vocs: 'cibe',
		vocp: 'cibi',
		abls: 'cibo',
		ablp: 'cibis',
	},
	{
		word: 'circum + accusative',
		category: 'preposition',
		translation: 'around',
		asked: false,
	},
	{
		word: 'civis, civis, m and f',
		category: 'noun 3',
		translation: 'citizen',
		asked: false,
		noms: 'civis',
		nomp: 'cives',
		gens: 'civis',
		genp: 'civium',
		dats: 'civi',
		datp: 'civibus',
		accs: 'civem',
		accp: 'cives',
		vocs: 'civis',
		vocp: 'cives',
		abls: 'cive',
		ablp: 'civibus',
	},
	{
		word: 'clamo, clamare, clamavi, clamatus',
		category: 'verb 1',
		translation: 'shout',
		asked: false,
	},
	{
		word: 'clamor, clamoris, m',
		category: 'noun 3',
		translation: 'shout, shouting, noise',
		asked: false,
		noms: 'clamor',
		nomp: 'clamores',
		gens: 'clamoris',
		genp: 'clamorum',
		dats: 'clamori',
		datp: 'clamoribus',
		accs: 'clamorem',
		accp: 'clamores',
		vocs: 'clamor',
		vocp: 'clamores',
		abls: 'clamore',
		ablp: 'clamoribus',
	},
	{
		word: 'clarus, clara, clarum',
		category: 'adjective',
		translation: 'famous, clear',
		asked: false,
	},
	{
		word: 'coepi, coepisse',
		category: 'verb irreg',
		translation: 'began',
		asked: false,
	},
	{
		word: 'cogito, cogitare, cogitavi, cogitatus',
		category: 'verb 1',
		translation: 'think, consider',
		asked: false,
	},
	{
		word: 'cognosco, cognoscere, cognovi, cognitus',
		category: 'verb 3',
		translation: 'get to know, find out',
		asked: false,
	},
	{
		word: 'cogo, cogere, coegi, coactus',
		category: 'verb 3',
		translation: 'force, compel',
		asked: false,
	},
	{
		word: 'comes, comitis, m and f',
		category: 'noun 3',
		translation: 'comrade, companion',
		asked: false,
		noms: 'comes',
		nomp: 'comites',
		gens: 'comitis',
		genp: 'comitum',
		dats: 'comiti',
		datp: 'comitibus',
		accs: 'comitem',
		accp: 'comites',
		vocs: 'comes',
		vocp: 'comites',
		abls: 'comite',
		ablp: 'comitibus',
	},
	{
		word: 'conficio, conficere, confeci, confectus',
		category: 'verb 3',
		translation: 'finish, wear out',
		asked: false,
	},
	{
		word: 'conor, conari, conatus sum',
		category: 'verb 1 deponent',
		translation: 'try',
		asked: false,
	},
	{
		word: 'consilium, consilii, n',
		category: 'noun 2',
		translation: 'plan, idea, advice',
		asked: false,
		noms: 'consilium',
		nomp: 'consilia',
		gens: 'consilii',
		genp: 'consiliorum',
		dats: 'consilio',
		datp: 'consiliis',
		accs: 'consilium',
		accp: 'consilia',
		vocs: 'consilium',
		vocp: 'consilia',
		abls: 'consilio',
		ablp: 'consiliis',
	},
	{
		word: 'conspicio, conspicere, conspexi, conspectus',
		category: 'verb 3',
		translation: 'catch sight of, notice',
		asked: false,
	},
	{
		word: 'constituo, constituere, constitui, constitutus',
		category: 'verb 3',
		translation: 'decide',
		asked: false,
	},
	{
		word: 'consul, consulis, m',
		category: 'noun 3',
		translation: 'consul',
		asked: false,
		noms: 'consul',
		nomp: 'consules',
		gens: 'consulis',
		genp: 'consulum',
		dats: 'consuli',
		datp: 'consulibus',
		accs: 'consulem',
		accp: 'consules',
		vocs: 'consul',
		vocp: 'consules',
		abls: 'consule',
		ablp: 'consulibus',
	},
	{
		word: 'consumo, consumere, consumpsi, consumptus',
		category: 'verb 3',
		translation: 'eat',
		asked: false,
	},
	{
		word: 'contra + accusative',
		category: 'preposition',
		translation: 'against',
		asked: false,
	},
	{
		word: 'convenio, convenire, conveni',
		category: 'verb 4',
		translation: 'come together, gather, meet',
		asked: false,
	},
	{
		word: 'copiae, copiarum, f plural',
		category: 'noun 1 plural',
		translation: 'forces, troops',
		asked: false,
		noms: 'copia',
		nomp: 'copiae',
		gens: 'copiae',
		genp: 'copiarum',
		dats: 'copiae',
		datp: 'copiis',
		accs: 'copiam',
		accp: 'copias',
		vocs: 'copia',
		vocp: 'copiae',
		abls: 'copia',
		ablp: 'copiis',
	},
	{
		word: 'corpus, corporis, n',
		category: 'noun 3',
		translation: 'body',
		asked: false,
		noms: 'corpus',
		nomp: 'corpora',
		gens: 'corporis',
		genp: 'corporum',
		dats: 'corpori',
		datp: 'corporibus',
		accs: 'corpus',
		accp: 'corpora',
		vocs: 'corpus',
		vocp: 'corpora',
		abls: 'corpore',
		ablp: 'corporibus',
	},
	{
		word: 'cras',
		category: 'adverb',
		translation: 'tomorrow',
		asked: false,
	},
	{
		word: 'credo, credere, credidi, creditus + dative',
		category: 'verb 3',
		translation: 'believe, trust',
		asked: false,
	},
	{
		word: 'crudelis, crudele',
		category: 'adjective',
		translation: 'cruel',
		asked: false,
	},
	{
		word: 'cum + ablative',
		category: 'preposition',
		translation: 'with',
		asked: false,
	},
	{
		word: 'cum',
		category: 'conjunction',
		translation: 'when, since',
		asked: false,
	},
	{
		word: 'cupio, cupere, cupivi, cupitus',
		category: 'verb 3',
		translation: 'want, desire',
		asked: false,
	},
	{
		word: 'cur?',
		category: 'adverb',
		translation: 'why?',
		asked: false,
	},
	{
		word: 'cura, curae, f',
		category: 'noun 1',
		translation: 'care, worry',
		asked: false,
		noms: 'cura',
		nomp: 'curae',
		gens: 'curae',
		genp: 'curarum',
		dats: 'curae',
		datp: 'curis',
		accs: 'curam',
		accp: 'curas',
		vocs: 'cura',
		vocp: 'curae',
		abls: 'cura',
		ablp: 'curis',
	},
	{
		word: 'curro, currere, cucurri, cursus',
		category: 'verb 3',
		translation: 'run',
		asked: false,
	},
	{
		word: 'custodio, custodire, custodivi, custoditus',
		category: 'verb 4',
		translation: 'guard',
		asked: false,
	},
	{
		word: 'custos, custodis, m and f',
		category: 'noun 3',
		translation: 'guard',
		asked: false,
		noms: 'custos',
		nomp: 'custodes',
		gens: 'custodis',
		genp: 'custodum',
		dats: 'custodi',
		datp: 'custodibus',
		accs: 'custodem',
		accp: 'custodes',
		vocs: 'custos',
		vocp: 'custodes',
		abls: 'custode',
		ablp: 'custodibus',
	},
	{
		word: 'de + ablative',
		category: 'preposition',
		translation: 'from, down from, about',
		asked: false,
	},
	{
		word: 'dea, deae, f',
		category: 'noun 1',
		translation: 'goddess',
		asked: false,
		noms: 'dea',
		nomp: 'deae',
		gens: 'deae',
		genp: 'dearum',
		dats: 'deae',
		datp: 'deis',
		accs: 'deam',
		accp: 'deas',
		vocs: 'dea',
		vocp: 'deae',
		abls: 'dea',
		ablp: 'deis',
	},
	{
		word: 'debeo, debere, debui, debitus',
		category: 'verb 2',
		translation: 'owe, ought, should, must',
		asked: false,
	},
	{
		word: 'defendo, defendere, defendi, defensus',
		category: 'verb 3',
		translation: 'defend',
		asked: false,
	},
	{
		word: 'deinde',
		category: 'adverb',
		translation: 'then',
		asked: false,
	},
	{
		word: 'deleo, delere, delevi, deletus',
		category: 'verb 2',
		translation: 'destroy',
		asked: false,
	},
	{
		word: 'descendo, descendere, descendi, descensus',
		category: 'verb 3',
		translation: 'go down, come down',
		asked: false,
	},
	{
		word: 'deus, dei, m',
		category: 'noun 2',
		translation: 'god',
		asked: false,
		noms: 'deus',
		nomp: 'dei',
		gens: 'dei',
		genp: 'deorum',
		dats: 'deo',
		datp: 'deisdeibus',
		accs: 'deum',
		accp: 'deos',
		vocs: 'deus',
		vocp: 'dei',
		abls: 'deo',
		ablp: 'deisdeibus',
	},
	{
		word: 'dico, dicere, dixi, dictus',
		category: 'verb 3',
		translation: 'say, speak, tell',
		asked: false,
	},
	{
		word: 'dies, diei, m',
		category: 'noun 5',
		translation: 'day',
		asked: false,
		noms: 'dies',
		nomp: 'dies',
		gens: 'diei',
		genp: 'dierum',
		dats: 'diei',
		datp: 'diebus',
		accs: 'diem',
		accp: 'dies',
		vocs: 'dies',
		vocp: 'dies',
		abls: 'die',
		ablp: 'diebus',
	},
	{
		word: 'difficilis, difficile',
		category: 'adjective',
		translation: 'difficult',
		asked: false,
	},
	{
		word: 'diligens, diligentis',
		category: 'adjective',
		translation: 'careful',
		asked: false,
	},
	{
		word: 'dirus, dira, dirum',
		category: 'adjective',
		translation: 'dreadful',
		asked: false,
	},
	{
		word: 'discedo, discedere, discessi',
		category: 'verb 3',
		translation: 'depart, leave',
		asked: false,
	},
	{
		word: 'diu',
		category: 'adverb',
		translation: 'for a long time',
		asked: false,
	},
	{
		word: 'do, dare, dedi, datus',
		category: 'verb 1',
		translation: 'give',
		asked: false,
	},
	{
		word: 'doceo, docere, docui, doctus',
		category: 'verb 2',
		translation: 'teach',
		asked: false,
	},
	{
		word: 'domina, dominae, f',
		category: 'noun 1',
		translation: 'mistress',
		asked: false,
		noms: 'domina',
		nomp: 'dominae',
		gens: 'dominae',
		genp: 'dominarum',
		dats: 'dominae',
		datp: 'dominis',
		accs: 'dominam',
		accp: 'dominas',
		vocs: 'domina',
		vocp: 'dominae',
		abls: 'domina',
		ablp: 'dominabus',
	},
	{
		word: 'dominus, domini, m',
		category: 'noun 2',
		translation: 'master',
		asked: false,
		noms: 'dominus',
		nomp: 'domini',
		gens: 'domini',
		genp: 'dominorum',
		dats: 'domino',
		datp: 'dominis',
		accs: 'dominum',
		accp: 'dominos',
		vocs: 'domine',
		vocp: 'domini',
		abls: 'domino',
		ablp: 'dominis',
	},
	{
		word: 'domus, domus, f (domi = at home)',
		category: 'noun 4',
		translation: 'home',
		asked: false,
		noms: 'domus',
		nomp: 'domus',
		gens: 'domus',
		genp: 'domuumdomorum',
		dats: 'domui',
		datp: 'domibus',
		accs: 'domum',
		accp: 'domusdomos',
		vocs: 'domus',
		vocp: 'domus',
		abls: 'domo (domu)  domi',
		ablp: 'domibus',
	},
	{
		word: 'donum, doni, n',
		category: 'noun 2',
		translation: 'gift, present',
		asked: false,
		noms: 'donum',
		nomp: 'dona',
		gens: 'doni',
		genp: 'donorum',
		dats: 'dono',
		datp: 'donis',
		accs: 'donum',
		accp: 'dona',
		vocs: 'donum',
		vocp: 'dona',
		abls: 'dono',
		ablp: 'donis',
	},
	{
		word: 'dormio, dormire, dormivi',
		category: 'verb 4',
		translation: 'sleep',
		asked: false,
	},
	{
		word: 'duco, ducere, duxi, ductus',
		category: 'verb 3',
		translation: 'lead, take',
		asked: false,
	},
	{
		word: 'dum',
		category: 'conjunction',
		translation: 'while, until',
		asked: false,
	},
	{
		word: 'dux, ducis, m',
		category: 'noun 3',
		translation: 'leader',
		asked: false,
		noms: 'dux',
		nomp: 'duces',
		gens: 'ducis',
		genp: 'ducum',
		dats: 'duci',
		datp: 'ducibus',
		accs: 'ducem',
		accp: 'duces',
		vocs: 'ducem',
		vocp: 'duces',
		abls: 'duce',
		ablp: 'ducibus',
	},
	{
		word: 'e, ex + ablative (also used as prefix with verbs)',
		category: 'preposition',
		translation: 'from, out of, out',
		asked: false,
	},
	{
		word: 'ecce!',
		category: 'adverb',
		translation: 'look!',
		asked: false,
	},
	{
		word: 'effugio, effugere, effugi',
		category: 'verb 3',
		translation: 'escape',
		asked: false,
	},
	{
		word: 'ego, mei',
		category: 'pronoun',
		translation: 'I, me',
		asked: false,
	},
	{
		word: 'egredior, egredi, egressus sum',
		category: 'verb 3 deponent',
		translation: 'go out',
		asked: false,
	},
	{
		word: 'emo, emere, emi, emptus',
		category: 'verb 3',
		translation: 'buy',
		asked: false,
	},
	{
		word: 'enim',
		category: 'conjunction',
		translation: 'for',
		asked: false,
	},
	{
		word: 'eo, ire, i(v)i',
		category: 'verb irreg',
		translation: 'go',
		asked: false,
	},
	{
		word: 'epistula, epistulae, f',
		category: 'noun 1',
		translation: 'letter',
		asked: false,
		noms: 'epistula',
		nomp: 'epistulae',
		gens: 'epistulae',
		genp: 'epistularum',
		dats: 'epistulae',
		datp: 'epistulis',
		accs: 'epistulam',
		accp: 'epistulas',
		vocs: 'epistula',
		vocp: 'epistulae',
		abls: 'epistula',
		ablp: 'epistulis',
	},
	{
		word: 'equus, equi, m',
		category: 'noun 2',
		translation: 'horse',
		asked: false,
		noms: 'equus',
		nomp: 'equi',
		gens: 'equi',
		genp: 'equorum',
		dats: 'equo',
		datp: 'equis',
		accs: 'equum',
		accp: 'equos',
		vocs: 'eque',
		vocp: 'equi',
		abls: 'equo',
		ablp: 'equis',
	},
	{
		word: 'et',
		category: 'conjunction',
		translation: 'and, even',
		asked: false,
	},
	{
		word: 'et ... et',
		category: 'conjunction',
		translation: 'both ... and',
		asked: false,
	},
	{
		word: 'etiam',
		category: 'adverb',
		translation: 'also, even',
		asked: false,
	},
	{
		word: 'exercitus, exercitus, m',
		category: 'noun 4',
		translation: 'army',
		asked: false,
		noms: 'exercitus',
		nomp: 'exercitus',
		gens: 'exercitus',
		genp: 'exercituum',
		dats: 'exercitui',
		datp: 'exercitibus',
		accs: 'exercitum',
		accp: 'exercitus',
		vocs: 'exercitus',
		vocp: 'exercitus',
		abls: 'exercitu',
		ablp: 'exercitibus',
	},
	{
		word: 'exspecto, exspectare, exspectavi, exspectatus',
		category: 'verb 1',
		translation: 'wait for, expect',
		asked: false,
	},
	{
		word: 'facilis, facile',
		category: 'adjective',
		translation: 'easy',
		asked: false,
	},
	{
		word: 'facio, facere, feci, factus',
		category: 'verb 3',
		translation: 'make, do',
		asked: false,
	},
	{
		word: 'faveo, favere, favi, fautus + dative',
		category: 'verb 2',
		translation: 'favour, support',
		asked: false,
	},
	{
		word: 'felix, felicis',
		category: 'adjective',
		translation: 'fortunate, happy',
		asked: false,
	},
	{
		word: 'femina, feminae, f',
		category: 'noun 1',
		translation: 'woman',
		asked: false,
		noms: 'femina',
		nomp: 'feminae',
		gens: 'feminae',
		genp: 'feminarum',
		dats: 'feminae',
		datp: 'feminis',
		accs: 'feminam',
		accp: 'feminas',
		vocs: 'femina',
		vocp: 'feminae',
		abls: 'femina',
		ablp: 'feminis',
	},
	{
		word: 'fero, ferre, tuli, latus',
		category: 'verb irreg',
		translation: 'bring, carry, bear',
		asked: false,
	},
	{
		word: 'ferox, ferocis',
		category: 'adjective',
		translation: 'fierce, ferocious',
		asked: false,
	},
	{
		word: 'festino, festinare, festinavi',
		category: 'verb 1',
		translation: 'hurry',
		asked: false,
	},
	{
		word: 'fidelis, fidele',
		category: 'adjective',
		translation: 'faithful, loyal',
		asked: false,
	},
	{
		word: 'filia, filiae, f',
		category: 'noun 1',
		translation: 'daughter',
		asked: false,
		noms: 'filia',
		nomp: 'filiae',
		gens: 'filiae',
		genp: 'filiarum',
		dats: 'filiae',
		datp: 'filiis',
		accs: 'filiam',
		accp: 'filias',
		vocs: 'filia',
		vocp: 'filiae',
		abls: 'filia',
		ablp: 'filiis',
	},
	{
		word: 'filius, filii, m',
		category: 'noun 2',
		translation: 'son',
		asked: false,
		noms: 'filius',
		nomp: 'filii',
		gens: 'filii',
		genp: 'filiorum',
		dats: 'filio',
		datp: 'filiis',
		accs: 'filium',
		accp: 'filios',
		vocs: 'fili',
		vocp: 'filii',
		abls: 'filio',
		ablp: 'filiis',
	},
	{
		word: 'flumen, fluminis, n',
		category: 'noun 3',
		translation: 'river',
		asked: false,
		noms: 'flumen',
		nomp: 'flumina',
		gens: 'fluminis',
		genp: 'fluminum',
		dats: 'flumini',
		datp: 'fluminibus',
		accs: 'flumen',
		accp: 'flumina',
		vocs: 'flumen',
		vocp: 'flumina',
		abls: 'flumine',
		ablp: 'fluminibus',
	},
	{
		word: 'forte',
		category: 'adverb',
		translation: 'by chance',
		asked: false,
	},
	{
		word: 'fortis, forte',
		category: 'adjective',
		translation: 'brave',
		asked: false,
	},
	{
		word: 'forum, fori, n',
		category: 'noun 2',
		translation: 'forum, market place',
		asked: false,
		noms: 'forum',
		nomp: 'fora',
		gens: 'fori',
		genp: 'fororum',
		dats: 'foro',
		datp: 'foris',
		accs: 'forum',
		accp: 'fora',
		vocs: 'forum',
		vocp: 'fora',
		abls: 'foro',
		ablp: 'foris',
	},
	{
		word: 'frater, fratris, m',
		category: 'noun 3',
		translation: 'brother',
		asked: false,
		noms: 'frater',
		nomp: 'fratres',
		gens: 'fratris',
		genp: 'fratrum',
		dats: 'fratri',
		datp: 'fratribus',
		accs: 'fratrem',
		accp: 'fratres',
		vocs: 'frater',
		vocp: 'fratres',
		abls: 'fratre',
		ablp: 'fratribus',
	},
	{
		word: 'frustra',
		category: 'adverb',
		translation: 'in vain',
		asked: false,
	},
	{
		word: 'fugio, fugere, fugi',
		category: 'verb 3',
		translation: 'run away, flee',
		asked: false,
	},
	{
		word: 'gaudeo, gaudere, gavisus sum',
		category: 'verb 2',
		translation: 'be pleased, rejoice',
		asked: false,
	},
	{
		word: 'gaudium, gaudii, n',
		category: 'noun 2',
		translation: 'joy, pleasure',
		asked: false,
		noms: 'gaudium',
		nomp: 'gaudia',
		gens: 'gaudii',
		genp: 'gaudiorum',
		dats: 'gaudio',
		datp: 'gaudiis',
		accs: 'gaudium',
		accp: 'gaudia',
		vocs: 'gaudium',
		vocp: 'gaudia',
		abls: 'gaudio',
		ablp: 'gaudiis',
	},
	{
		word: 'gens, gentis, f',
		category: 'noun 3',
		translation: 'family, tribe, race, people',
		asked: false,
	},
	{
		word: 'gero, gerere, gessi, gestus',
		category: 'verb 3',
		translation: 'wear (clothes), wage (war)',
		asked: false,
	},
	{
		word: 'gladius, gladii, m',
		category: 'noun 2',
		translation: 'sword',
		asked: false,
		noms: 'gladius',
		nomp: 'gladii',
		gens: 'gladii',
		genp: 'gladiorum',
		dats: 'gladio',
		datp: 'gladiis',
		accs: 'gladium',
		accp: 'gladios',
		vocs: 'gladie',
		vocp: 'gladii',
		abls: 'gladio',
		ablp: 'gladiis',
	},
	{
		word: 'gravis, grave',
		category: 'adjective',
		translation: 'heavy, serious',
		asked: false,
	},
	{
		word: 'habeo, habere, habui, habitus',
		category: 'verb 2',
		translation: 'have, hold',
		asked: false,
	},
	{
		word: 'habito, habitare, habitavi, habitatus',
		category: 'verb 1',
		translation: 'live',
		asked: false,
	},
	{
		word: 'heri',
		category: 'adverb',
		translation: 'yesterday',
		asked: false,
	},
	{
		word: 'hic, haec, hoc',
		category: 'pronoun',
		translation: 'this, he, she, it',
		asked: false,
	},
	{
		word: 'hodie',
		category: 'adverb',
		translation: 'today',
		asked: false,
	},
	{
		word: 'homo, hominis, m',
		category: 'noun 3',
		translation: 'man, human being',
		asked: false,
		noms: 'homo',
		nomp: 'homines',
		gens: 'hominis',
		genp: 'hominum',
		dats: 'homini',
		datp: 'hominibus',
		accs: 'hominem',
		accp: 'homines',
		vocs: 'homo',
		vocp: 'homines',
		abls: 'homine',
		ablp: 'hominibus',
	},
	{
		word: 'hora, horae, f',
		category: 'noun 1',
		translation: 'hour',
		asked: false,
		noms: 'hora',
		nomp: 'horae',
		gens: 'horae',
		genp: 'horarum',
		dats: 'horae',
		datp: 'horis',
		accs: 'horam',
		accp: 'horas',
		vocs: 'hora',
		vocp: 'horae',
		abls: 'hora',
		ablp: 'horis',
	},
	{
		word: 'hortor, hortari, hortatus sum',
		category: 'verb 1 deponent',
		translation: 'encourage, urge',
		asked: false,
	},
	{
		word: 'hortus, horti, m',
		category: 'noun 2',
		translation: 'garden',
		asked: false,
		noms: 'hortus',
		nomp: 'horti',
		gens: 'horti',
		genp: 'hortorum',
		dats: 'horto',
		datp: 'hortis',
		accs: 'hortum',
		accp: 'hortos',
		vocs: 'horte',
		vocp: 'horti',
		abls: 'horto',
		ablp: 'hortis',
	},
	{
		word: 'hostis, hostis, m',
		category: 'noun 3',
		translation: 'enemy',
		asked: false,
		noms: 'hostis',
		nomp: 'hostes',
		gens: 'hostis',
		genp: 'hostium',
		dats: 'hosti',
		datp: 'hostibus',
		accs: 'hostem',
		accp: 'hostes',
		vocs: 'hostis',
		vocp: 'hostes',
		abls: 'hoste',
		ablp: 'hostibus',
	},
	{
		word: 'iaceo, iacere, iacui',
		category: 'verb 2',
		translation: 'lie',
		asked: false,
	},
	{
		word: 'iacio, iacere, ieci, iactus (in compounds -icio)',
		category: 'verb 3',
		translation: 'throw',
		asked: false,
	},
	{
		word: 'iam',
		category: 'adverb',
		translation: 'now, already',
		asked: false,
	},
	{
		word: 'ianua, ianuae, f',
		category: 'noun 1',
		translation: 'door',
		asked: false,
		noms: 'ianua',
		nomp: 'ianuae',
		gens: 'ianuae',
		genp: 'ianuarum',
		dats: 'ianuae',
		datp: 'ianuis',
		accs: 'ianuam',
		accp: 'ianuas',
		vocs: 'ianua',
		vocp: 'ianuae',
		abls: 'ianua',
		ablp: 'ianuis',
	},
	{
		word: 'ibi',
		category: 'adverb',
		translation: 'there',
		asked: false,
	},
	{
		word: 'idem, eadem, idem',
		category: 'pronoun',
		translation: 'the same',
		asked: false,
	},
	{
		word: 'igitur',
		category: 'adverb',
		translation: 'therefore, and so',
		asked: false,
	},
	{
		word: 'ille, ilIa, illud',
		category: 'pronoun',
		translation: 'that, he, she, it',
		asked: false,
	},
	{
		word: 'imperator, imperatoris, m',
		category: 'noun 3',
		translation: 'emperor, general, leader',
		asked: false,
		noms: 'imperator',
		nomp: 'imperatores',
		gens: 'imperatoris',
		genp: 'imperatorum',
		dats: 'imperatori',
		datp: 'imperatoribus',
		accs: 'imperatorem',
		accp: 'imperatores',
		vocs: 'imperator',
		vocp: 'imperatores',
		abls: 'imperatore',
		ablp: 'imperatoribus',
	},
	{
		word: 'imperium, imperii, n',
		category: 'noun 2',
		translation: 'empire, power, command',
		asked: false,
		noms: 'imperium',
		nomp: 'imperia',
		gens: 'imperii',
		genp: 'imperiorum',
		dats: 'imperio',
		datp: 'imperiis',
		accs: 'imperium',
		accp: 'imperia',
		vocs: 'imperium',
		vocp: 'imperia',
		abls: 'imperio',
		ablp: 'imperiis',
	},
	{
		word: 'impero, imperare, imperavi, imperatus + dative',
		category: 'verb 1',
		translation: 'order, command',
		asked: false,
	},
	{
		word: 'in + ablative (also used as prefix with verbs)',
		category: 'preposition',
		translation: 'in, on',
		asked: false,
	},
	{
		word: 'in + accusative (also used as prefix with verbs)',
		category: 'preposition',
		translation: 'into, onto',
		asked: false,
	},
	{
		word: 'incendo, incendere, incendi, incensus',
		category: 'verb 3',
		translation: 'burn, set on fire',
		asked: false,
	},
	{
		word: 'infelix, infelicis',
		category: 'adjective',
		translation: 'unlucky, unhappy',
		asked: false,
	},
	{
		word: 'ingens, ingentis',
		category: 'adjective',
		translation: 'huge',
		asked: false,
	},
	{
		word: 'ingredior, ingredi, ingressus sum',
		category: 'verb 3 deponent',
		translation: 'enter',
		asked: false,
	},
	{
		word: 'inimicus, inimici, m',
		category: 'noun 2',
		translation: 'enemy',
		asked: false,
		noms: 'inimicus',
		nomp: 'inimici',
		gens: 'inimici',
		genp: 'inimicorum',
		dats: 'inimico',
		datp: 'inimicis',
		accs: 'inimicum',
		accp: 'inimicos',
		vocs: 'inimice',
		vocp: 'inimici',
		abls: 'inimico',
		ablp: 'inimicis',
	},
	{
		word: 'inquit',
		category: 'verb irreg',
		translation: 'he/she says, he/she said',
		asked: false,
	},
	{
		word: 'insula, insulae, f',
		category: 'noun 1',
		translation: 'island, block of flats',
		asked: false,
		noms: 'insula',
		nomp: 'insulae',
		gens: 'insulae',
		genp: 'insularum',
		dats: 'insulae',
		datp: 'insulis',
		accs: 'insulam',
		accp: 'insulas',
		vocs: 'insula',
		vocp: 'insulae',
		abls: 'insula',
		ablp: 'insulis',
	},
	{
		word: 'intellego, intellegere, intellexi, intellectus',
		category: 'verb 3',
		translation: 'understand, realise',
		asked: false,
	},
	{
		word: 'inter + accusative',
		category: 'preposition',
		translation: 'among, between',
		asked: false,
	},
	{
		word: 'interea',
		category: 'adverb',
		translation: 'meanwhile',
		asked: false,
	},
	{
		word: 'interficio, interficere, interfeci, interfectus',
		category: 'verb 3',
		translation: 'kill',
		asked: false,
	},
	{
		word: 'intro, intrare, intravi, intratus',
		category: 'verb 1',
		translation: 'enter',
		asked: false,
	},
	{
		word: 'invenio, invenire, inveni, inventus',
		category: 'verb 4',
		translation: 'find',
		asked: false,
	},
	{
		word: 'invito, invitare, invitavi, invitatus',
		category: 'verb 1',
		translation: 'invite',
		asked: false,
	},
	{
		word: 'ipse, ipsa, ipsum',
		category: 'pronoun',
		translation: 'himself, herself, itself, themselves',
		asked: false,
	},
	{
		word: 'ira, irae, f',
		category: 'noun 1',
		translation: 'anger',
		asked: false,
		noms: 'ira',
		nomp: 'irae',
		gens: 'irae',
		genp: 'irarum',
		dats: 'irae',
		datp: 'iris',
		accs: 'iram',
		accp: 'iras',
		vocs: 'ira',
		vocp: 'irae',
		abls: 'ira',
		ablp: 'iris',
	},
	{
		word: 'iratus, irata, iratum',
		category: 'adjective',
		translation: 'angry',
		asked: false,
	},
	{
		word: 'is, ea, id',
		category: 'pronoun',
		translation: 'this, that, he, she, it, them',
		asked: false,
	},
	{
		word: 'ita',
		category: 'adverb',
		translation: 'in this way, to such an extent, so',
		asked: false,
	},
	{
		word: 'itaque',
		category: 'adverb',
		translation: 'and so, therefore',
		asked: false,
	},
	{
		word: 'iter, itineris, n',
		category: 'noun 3',
		translation: 'journey',
		asked: false,
		noms: 'iter',
		nomp: 'itinera',
		gens: 'itineris',
		genp: 'itinerum',
		dats: 'itineri',
		datp: 'itineribus',
		accs: 'iter',
		accp: 'itinera',
		vocs: 'iter',
		vocp: 'itinera',
		abls: 'itinere',
		ablp: 'itineribus',
	},
	{
		word: 'iterum',
		category: 'adverb',
		translation: 'again',
		asked: false,
	},
	{
		word: 'iubeo, iubere, iussi, iussus',
		category: 'verb 2',
		translation: 'order',
		asked: false,
	},
	{
		word: 'iuvenis, iuvenis, m',
		category: 'noun 3',
		translation: 'young man',
		asked: false,
		noms: 'iuvenis',
		nomp: 'iuvenes',
		gens: 'iuvenis',
		genp: 'iuvenum',
		dats: 'iuveni',
		datp: 'iuvenibus',
		accs: 'iuvenem',
		accp: 'iuvenes',
		vocs: 'iuvenis',
		vocp: 'iuvenes',
		abls: 'iuvene',
		ablp: 'iuvenibus',
	},
	{
		word: 'labor, laboris, m',
		category: 'noun 3',
		translation: 'work, toil',
		asked: false,
		noms: 'labor',
		nomp: 'labores',
		gens: 'laboris',
		genp: 'laborum',
		dats: 'labori',
		datp: 'laboribus',
		accs: 'laborem',
		accp: 'labores',
		vocs: 'labor',
		vocp: 'labores',
		abls: 'labore',
		ablp: 'laboribus',
	},
	{
		word: 'laboro, laborare, laboravi',
		category: 'verb 1',
		translation: 'work, toil',
		asked: false,
	},
	{
		word: 'lacrimo, lacrimare, lacrimavi',
		category: 'verb 1',
		translation: 'weep, cry',
		asked: false,
	},
	{
		word: 'laetus, laeta, laetum',
		category: 'adjective',
		translation: 'happy',
		asked: false,
	},
	{
		word: 'laudo, laudare, laudavi, laudatus',
		category: 'verb 1',
		translation: 'praise',
		asked: false,
	},
	{
		word: 'legio, legionis, f',
		category: 'noun 3',
		translation: 'legion',
		asked: false,
		noms: 'legio',
		nomp: 'legiones',
		gens: 'legionis',
		genp: 'legionum',
		dats: 'legioni',
		datp: 'legionibus',
		accs: 'legionem',
		accp: 'legiones',
		vocs: 'legio',
		vocp: 'legiones',
		abls: 'legione',
		ablp: 'legionibus',
	},
	{
		word: 'lego, legere, legi, lectus',
		category: 'verb 3',
		translation: 'read, choose',
		asked: false,
	},
	{
		word: 'lentus, lenta, lentum',
		category: 'adjective',
		translation: 'slow',
		asked: false,
	},
	{
		word: 'libenter',
		category: 'adverb',
		translation: 'willingly, gladly',
		asked: false,
	},
	{
		word: 'liber, libri, m',
		category: 'noun 2',
		translation: 'book',
		asked: false,
		noms: 'liber',
		nomp: 'libri',
		gens: 'libri',
		genp: 'librorum',
		dats: 'libro',
		datp: 'libris',
		accs: 'librum',
		accp: 'libros',
		vocs: 'liber',
		vocp: 'libri',
		abls: 'libro',
		ablp: 'libris',
	},
	{
		word: 'liberi, liberorum, m plural',
		category: 'noun 2',
		translation: 'children',
		asked: false,
		noms: 'liberus',
		nomp: 'liberi',
		gens: 'liberi',
		genp: 'liberorum',
		dats: 'libero',
		datp: 'liberis',
		accs: 'liberum',
		accp: 'liberos',
		vocs: 'libere',
		vocp: 'liberi',
		abls: 'libero',
		ablp: 'liberis',
	},
	{
		word: 'libero, liberare, liberavi, liberatus',
		category: 'verb 1',
		translation: 'set free',
		asked: false,
	},
	{
		word: 'libertus, liberti, m',
		category: 'noun 2',
		translation: 'freedman, ex-slave',
		asked: false,
		noms: 'libertus',
		nomp: 'liberti',
		gens: 'liberti',
		genp: 'libertorum',
		dats: 'liberto',
		datp: 'libertis',
		accs: 'libertum',
		accp: 'libertos',
		vocs: 'liberte',
		vocp: 'liberti',
		abls: 'liberto',
		ablp: 'libertis',
	},
	{
		word: 'locus, loci, m',
		category: 'noun 2',
		translation: 'place',
		asked: false,
		noms: 'locus',
		nomp: 'loci',
		gens: 'loci',
		genp: 'locorum',
		dats: 'loco',
		datp: 'locis',
		accs: 'locum',
		accp: 'locos',
		vocs: 'loce',
		vocp: 'loci',
		abls: 'loco',
		ablp: 'locis',
	},
	{
		word: 'longus, longa, longum',
		category: 'adjective',
		translation: 'long',
		asked: false,
	},
	{
		word: 'loquor, loqui, locutus sum',
		category: 'verb 3 deponent',
		translation: 'speak, talk',
		asked: false,
	},
	{
		word: 'lux, lucis, f',
		category: 'noun 3',
		translation: 'light, daylight',
		asked: false,
		noms: 'lux',
		nomp: 'luces',
		gens: 'lucis',
		genp: 'lucum',
		dats: 'luci',
		datp: 'lucibus',
		accs: 'lucem',
		accp: 'luces',
		vocs: 'lux',
		vocp: 'luces',
		abls: 'luce',
		ablp: 'lucibus',
	},
	{
		word: 'magnus, magna, magnum',
		category: 'adjective',
		translation: 'big, large, great',
		asked: false,
	},
	{
		word: 'malo, malle, malui',
		category: 'verb irreg',
		translation: 'prefer',
		asked: false,
	},
	{
		word: 'malus, mala, malum',
		category: 'adjective',
		translation: 'evil, bad',
		asked: false,
	},
	{
		word: 'maneo, manere, mansi',
		category: 'verb 2',
		translation: 'remain, stay',
		asked: false,
	},
	{
		word: 'manus, manus, f',
		category: 'noun 4',
		translation: 'hand, group of people',
		asked: false,
		noms: 'manus',
		nomp: 'manus',
		gens: 'manus',
		genp: 'manuum',
		dats: 'manui',
		datp: 'manibus',
		accs: 'manum',
		accp: 'manus',
		vocs: 'manus',
		vocp: 'manus',
		abls: 'manu',
		ablp: 'manibus',
	},
	{
		word: 'mare, maris, n',
		category: 'noun 3',
		translation: 'sea',
		asked: false,
		noms: 'mare',
		nomp: 'maria',
		gens: 'maris',
		genp: 'marium',
		dats: 'mari',
		datp: 'maribus',
		accs: 'mare',
		accp: 'maria',
		vocs: 'mare',
		vocp: 'maria',
		abls: 'mari',
		ablp: 'maribus',
	},
	{
		word: 'maritus, mariti, m',
		category: 'noun 2',
		translation: 'husband',
		asked: false,
		noms: 'maritus',
		nomp: 'mariti',
		gens: 'mariti',
		genp: 'maritorum',
		dats: 'marito',
		datp: 'maritis',
		accs: 'maritum',
		accp: 'maritos',
		vocs: 'marite',
		vocp: 'mariti',
		abls: 'marito',
		ablp: 'maritis',
	},
	{
		word: 'mater, matris, f',
		category: 'noun 3',
		translation: 'mother',
		asked: false,
		noms: 'mater',
		nomp: 'matres',
		gens: 'matris',
		genp: 'matrium',
		dats: 'matri',
		datp: 'matribus',
		accs: 'matrem',
		accp: 'matres',
		vocs: 'mater',
		vocp: 'matres',
		abls: 'matre',
		ablp: 'matribus',
	},
	{
		word: 'maxime',
		category: 'adverb',
		translation: 'very greatly',
		asked: false,
	},
	{
		word: 'medius, media, medium',
		category: 'adjective',
		translation: 'middle',
		asked: false,
	},
	{
		word: 'meus, mea, meum',
		category: 'pronoun',
		translation: 'my',
		asked: false,
	},
	{
		word: 'miles, militis, m',
		category: 'noun 3',
		translation: 'soldier',
		asked: false,
		noms: 'miles',
		nomp: 'milites',
		gens: 'militis',
		genp: 'militum',
		dats: 'militi',
		datp: 'militibus',
		accs: 'militem',
		accp: 'milites',
		vocs: 'miles',
		vocp: 'milites',
		abls: 'milite',
		ablp: 'militibus',
	},
	{
		word: 'minime',
		category: 'adverb',
		translation: 'very little, least, no',
		asked: false,
	},
	{
		word: 'miror, mirari, miratus sum',
		category: 'verb 1 deponent',
		translation: 'wonder at, admire',
		asked: false,
	},
	{
		word: 'miser, misera, miserum',
		category: 'adjective',
		translation: 'miserable, wretched, sad',
		asked: false,
	},
	{
		word: 'mitto, mittere, misi, missus',
		category: 'verb 3',
		translation: 'send',
		asked: false,
	},
	{
		word: 'modus, modi, m',
		category: 'noun 2',
		translation: 'manner, way, kind',
		asked: false,
		noms: 'modus',
		nomp: 'modi',
		gens: 'modi',
		genp: 'modorum',
		dats: 'modo',
		datp: 'modis',
		accs: 'modum',
		accp: 'modos',
		vocs: 'mode',
		vocp: 'modi',
		abls: 'modo',
		ablp: 'modis',
	},
	{
		word: 'moneo, monere, monui, monitus',
		category: 'verb 2',
		translation: 'warn, advise',
		asked: false,
	},
	{
		word: 'mons, montis, m',
		category: 'noun 3',
		translation: 'mountain',
		asked: false,
		noms: 'mons',
		nomp: 'montes',
		gens: 'montis',
		genp: 'montium',
		dats: 'monti',
		datp: 'montibus',
		accs: 'montem',
		accp: 'montes',
		vocs: 'mons',
		vocp: 'montes',
		abls: 'monte',
		ablp: 'montibus',
	},
	{
		word: 'morior, mori, mortuus sum',
		category: 'verb 3 deponent',
		translation: 'die',
		asked: false,
	},
	{
		word: 'mors, mortis, f',
		category: 'noun 3',
		translation: 'death',
		asked: false,
		noms: 'mors',
		nomp: 'mortes',
		gens: 'mortis',
		genp: 'mortum',
		dats: 'morti',
		datp: 'mortibus',
		accs: 'mortem',
		accp: 'mortes',
		vocs: 'mors',
		vocp: 'mortes',
		abls: 'morte',
		ablp: 'mortibus',
	},
	{
		word: 'moveo, movere, movi, motus',
		category: 'verb 2',
		translation: 'move',
		asked: false,
	},
	{
		word: 'mox',
		category: 'adverb',
		translation: 'soon',
		asked: false,
	},
	{
		word: 'multo',
		category: 'adverb',
		translation: 'much',
		asked: false,
	},
	{
		word: 'multus, multa, multum',
		category: 'adjective',
		translation: 'much, many',
		asked: false,
	},
	{
		word: 'murus, muri, m',
		category: 'noun 2',
		translation: 'wall',
		asked: false,
		noms: 'murus',
		nomp: 'muri',
		gens: 'muri',
		genp: 'murorum',
		dats: 'muro',
		datp: 'muris',
		accs: 'murum',
		accp: 'muros',
		vocs: 'mure',
		vocp: 'muri',
		abls: 'muro',
		ablp: 'muris',
	},
	{
		word: 'nam',
		category: 'conjunction',
		translation: 'for',
		asked: false,
	},
	{
		word: 'narro, narrare, narravi, narratus',
		category: 'verb 1',
		translation: 'tell, relate',
		asked: false,
	},
	{
		word: 'nauta, nautae, m',
		category: 'noun 1',
		translation: 'sailor',
		asked: false,
		noms: 'nauta',
		nomp: 'nautae',
		gens: 'nautae',
		genp: 'nautarum',
		dats: 'nautae',
		datp: 'nautis',
		accs: 'nautam',
		accp: 'nautas',
		vocs: 'nauta',
		vocp: 'nautae',
		abls: 'nauta',
		ablp: 'nautis',
	},
	{
		word: 'navigo, navigare, navigavi',
		category: 'verb 1',
		translation: 'sail',
		asked: false,
	},
	{
		word: 'navis, navis, f',
		category: 'noun 3',
		translation: 'ship',
		asked: false,
		noms: 'navis',
		nomp: 'naves',
		gens: 'navis',
		genp: 'navium',
		dats: 'navi',
		datp: 'navibus',
		accs: 'navem',
		accp: 'naves',
		vocs: 'navis',
		vocp: 'naves',
		abls: 'nave',
		ablp: 'navibus',
	},
	{
		word: '-ne',
		category: 'particle',
		translation: '(introduces question)',
		asked: false,
	},
	{
		word: 'ne, indeclinable + subjunctive',
		category: 'conjunction',
		translation: 'that ... not, so that ... not, that, lest',
		asked: false,
	},
	{
		word: 'nec, neque',
		category: 'conjunction',
		translation: 'and not, nor, neither',
		asked: false,
	},
	{
		word: 'neco, necare, necavi, necatus',
		category: 'verb 1',
		translation: 'kill',
		asked: false,
	},
	{
		word: 'nemo, nullius',
		category: 'noun irreg',
		translation: 'no one, nobody',
		asked: false,
	},
	{
		word: 'nescio, nescire, nescivi',
		category: 'verb 4',
		translation: 'not know',
		asked: false,
	},
	{
		word: 'nihil',
		category: 'noun irreg',
		translation: 'nothing',
		asked: false,
	},
	{
		word: 'nisi',
		category: 'conjunction',
		translation: 'unless, except',
		asked: false,
	},
	{
		word: 'nolo, nolle, nolui',
		category: 'verb irreg',
		translation: 'not want, refuse',
		asked: false,
	},
	{
		word: 'nomen, nominis, n',
		category: 'noun 3',
		translation: 'name',
		asked: false,
	},
	{
		word: 'non',
		category: 'adverb',
		translation: 'not',
		asked: false,
	},
	{
		word: 'nonne?',
		category: 'adverb',
		translation: 'surely, surely?, surely...?',
		asked: false,
	},
	{
		word: 'nonnulli, nonnullae, nonnulla',
		category: 'adjective',
		translation: 'some, several',
		asked: false,
	},
	{
		word: 'nos, nostrum',
		category: 'pronoun',
		translation: 'we, us',
		asked: false,
	},
	{
		word: 'noster, nostra, nostrum',
		category: 'pronoun',
		translation: 'our',
		asked: false,
	},
	{
		word: 'novus, nova, novum',
		category: 'adjective',
		translation: 'new',
		asked: false,
	},
	{
		word: 'nox, noctis, f',
		category: 'noun 3',
		translation: 'night',
		asked: false,
		noms: 'nox',
		nomp: 'noctes',
		gens: 'noctis',
		genp: 'noctium',
		dats: 'nocti',
		datp: 'noctibus',
		accs: 'noctem',
		accp: 'noctes',
		vocs: 'nox',
		vocp: 'noctes',
		abls: 'nocte',
		ablp: 'noctibus',
	},
	{
		word: 'nullus, nulla, nullum',
		category: 'adjective',
		translation: 'not any, no',
		asked: false,
	},
	{
		word: 'num',
		category: 'particle',
		translation: 'whether',
		asked: false,
	},
	{
		word: 'num ... ?',
		category: 'particle',
		translation: 'surely...not?, surely not, surely not?',
		asked: false,
	},
	{
		word: 'numquam',
		category: 'adverb',
		translation: 'never',
		asked: false,
	},
	{
		word: 'nunc',
		category: 'adverb',
		translation: 'now',
		asked: false,
	},
	{
		word: 'nuntio, nuntiare, nuntiavi, nuntiatus',
		category: 'verb 1',
		translation: 'announce, report',
		asked: false,
	},
	{
		word: 'nuntius, nuntii, m',
		category: 'noun 2',
		translation: 'messenger, message, news',
		asked: false,
		noms: 'nuntius',
		nomp: 'nuntii',
		gens: 'nuntii',
		genp: 'nuntiorum',
		dats: 'nuntio',
		datp: 'nuntiis',
		accs: 'nuntium',
		accp: 'nuntios',
		vocs: 'nunti',
		vocp: 'nuntii',
		abls: 'nuntio',
		ablp: 'nuntiis',
	},
	{
		word: 'occido, occidere, occidi, occisus',
		category: 'verb 3',
		translation: 'kill',
		asked: false,
	},
	{
		word: 'offero, offerre, obtuli, oblatus',
		category: 'verb irreg',
		translation: 'offer',
		asked: false,
	},
	{
		word: 'olim',
		category: 'adverb',
		translation: 'once, some time ago',
		asked: false,
	},
	{
		word: 'omnis, omne',
		category: 'adjective',
		translation: 'all, every',
		asked: false,
	},
	{
		word: 'opprimo, opprimere, oppressi, oppressus',
		category: 'verb 3',
		translation: 'crush, overwhelm',
		asked: false,
	},
	{
		word: 'oppugno, oppugnare, oppugnavi, oppugnatus',
		category: 'verb 1',
		translation: 'attack',
		asked: false,
	},
	{
		word: 'oro, orare, oravi, oratus',
		category: 'verb 1',
		translation: 'beg',
		asked: false,
	},
	{
		word: 'ostendo, ostendere, ostendi, ostentus',
		category: 'verb 3',
		translation: 'show',
		asked: false,
	},
	{
		word: 'paene',
		category: 'adverb',
		translation: 'almost, nearly',
		asked: false,
	},
	{
		word: 'paro, parare, paravi, paratus',
		category: 'verb 1',
		translation: 'prepare, provide',
		asked: false,
	},
	{
		word: 'pars, partis, f',
		category: 'noun 3',
		translation: 'part',
		asked: false,
		noms: 'pars',
		nomp: 'partes',
		gens: 'partis',
		genp: 'partium',
		dats: 'parti',
		datp: 'partibus',
		accs: 'partem',
		accp: 'partes',
		vocs: 'pars',
		vocp: 'partes',
		abls: 'parte',
		ablp: 'partibus',
	},
	{
		word: 'parvus, parva, parvum',
		category: 'adjective',
		translation: 'small',
		asked: false,
	},
	{
		word: 'pater, patris, m',
		category: 'noun 3',
		translation: 'father',
		asked: false,
		noms: 'pater',
		nomp: 'patres',
		gens: 'patris',
		genp: 'patrum',
		dats: 'patri',
		datp: 'patribus',
		accs: 'patrem',
		accp: 'patres',
		vocs: 'pater',
		vocp: 'patres',
		abls: 'patre',
		ablp: 'patribus',
	},
	{
		word: 'patior, pati, passus sum',
		category: 'verb 3 deponent',
		translation: 'suffer, endure',
		asked: false,
	},
	{
		word: 'patria, patriae, f',
		category: 'noun 1',
		translation: 'country, homeland',
		asked: false,
		noms: 'patria',
		nomp: 'patriae',
		gens: 'patriae',
		genp: 'patriarum',
		dats: 'patriae',
		datp: 'patriis',
		accs: 'patriam',
		accp: 'patrias',
		vocs: 'patria',
		vocp: 'patriae',
		abls: 'patria',
		ablp: 'patriis',
	},
	{
		word: 'pauci, paucae, pauca',
		category: 'adjective plural',
		translation: 'few, a few',
		asked: false,
	},
	{
		word: 'pax, pacis, f',
		category: 'noun 3',
		translation: 'peace',
		asked: false,
		noms: 'pax',
		nomp: 'paces',
		gens: 'pacis',
		genp: 'pacum',
		dats: 'paci',
		datp: 'pacibus',
		accs: 'pacem',
		accp: 'paces',
		vocs: 'pax',
		vocp: 'paces',
		abls: 'pace',
		ablp: 'pacibus',
	},
	{
		word: 'pecunia, pecuniae, f',
		category: 'noun 1',
		translation: 'money',
		asked: false,
		noms: 'pecunia',
		nomp: 'pecuniae',
		gens: 'pecuniae',
		genp: 'pecuniarum',
		dats: 'pecuniae',
		datp: 'pecuniis',
		accs: 'pecuniam',
		accp: 'pecunias',
		vocs: 'pecunia',
		vocp: 'pecuniae',
		abls: 'pecunia',
		ablp: 'pecuniis',
	},
	{
		word: 'pello, pellere, pepuli, pulsus',
		category: 'verb 3',
		translation: 'drive',
		asked: false,
	},
	{
		word: 'per + accusative',
		category: 'preposition',
		translation: 'through, along',
		asked: false,
	},
	{
		word: 'pereo, perire, perii',
		category: 'verb irreg',
		translation: 'die, perish',
		asked: false,
	},
	{
		word: 'periculum, periculi, n',
		category: 'noun 2',
		translation: 'danger',
		asked: false,
		noms: 'periculum',
		nomp: 'pericula',
		gens: 'periculi',
		genp: 'periculorum',
		dats: 'periculo',
		datp: 'periculis',
		accs: 'periculum',
		accp: 'pericula',
		vocs: 'periculum',
		vocp: 'pericula',
		abls: 'periculo',
		ablp: 'periculis',
	},
	{
		word: 'persuadeo, persuadere, persuasi + dative',
		category: 'verb 2',
		translation: 'persuade',
		asked: false,
	},
	{
		word: 'perterritus, perterrita, perterritum',
		category: 'adjective',
		translation: 'terrified',
		asked: false,
	},
	{
		word: 'pes, pedis, m',
		category: 'noun 3',
		translation: 'foot',
		asked: false,
		noms: 'pes',
		nomp: 'pedes',
		gens: 'pedis',
		genp: 'pedum',
		dats: 'pedi',
		datp: 'pedibus',
		accs: 'pedem',
		accp: 'pedes',
		vocs: 'pes',
		vocp: 'pedes',
		abls: 'pede',
		ablp: 'pedibus',
	},
	{
		word: 'peto, petere, petivi, petitus',
		category: 'verb 3',
		translation: 'make for, seek, beg/ask for',
		asked: false,
	},
	{
		word: 'poena, poenae, f',
		category: 'noun 1',
		translation: 'punishment',
		asked: false,
		noms: 'poena',
		nomp: 'poenae',
		gens: 'poenae',
		genp: 'poenarum',
		dats: 'poenae',
		datp: 'poenis',
		accs: 'poenam',
		accp: 'poenas',
		vocs: 'poena',
		vocp: 'poenae',
		abls: 'poena',
		ablp: 'poenis',
	},
	{
		word: 'poenas do',
		translation: 'pay the penalty, be punished',
		asked: false,
	},
	{
		word: 'pono, ponere, posui, positus',
		category: 'verb 3',
		translation: 'put, place, set up',
		asked: false,
	},
	{
		word: 'porta, portae, f',
		category: 'noun 1',
		translation: 'gate',
		asked: false,
		noms: 'porta',
		nomp: 'portae',
		gens: 'portae',
		genp: 'portarum',
		dats: 'portae',
		datp: 'portis',
		accs: 'portam',
		accp: 'portas',
		vocs: 'porta',
		vocp: 'portae',
		abls: 'porta',
		ablp: 'portis',
	},
	{
		word: 'porto, portare, portavi, portatus',
		category: 'verb 1',
		translation: 'carry, bear, take',
		asked: false,
	},
	{
		word: 'possum, posse, potui',
		category: 'verb irreg',
		translation: 'can, be able',
		asked: false,
	},
	{
		word: 'post + accusative',
		category: 'preposition',
		translation: 'after, behind',
		asked: false,
	},
	{
		word: 'postea',
		category: 'adverb',
		translation: 'afterwards',
		asked: false,
	},
	{
		word: 'postquam',
		category: 'conjunction',
		translation: 'after, when',
		asked: false,
	},
	{
		word: 'postridie',
		category: 'adverb',
		translation: 'on the next day',
		asked: false,
	},
	{
		word: 'praemium, praemii, n',
		category: 'noun 2',
		translation: 'prize, reward, profit',
		asked: false,
		noms: 'praemium',
		nomp: 'praemia',
		gens: 'praemii',
		genp: 'praemiorum',
		dats: 'praemio',
		datp: 'praemiis',
		accs: 'praemium',
		accp: 'praemia',
		vocs: 'praemium',
		vocp: 'praemia',
		abls: 'praemio',
		ablp: 'praemiis',
	},
	{
		word: 'primo',
		category: 'adverb',
		translation: 'at first',
		asked: false,
	},
	{
		word: 'primus, prima, primum',
		category: 'adjective',
		translation: 'first',
		asked: false,
	},
	{
		word: 'princeps, principis, m',
		category: 'noun 3',
		translation: 'chief, emperor',
		asked: false,
		noms: 'princeps',
		nomp: 'principes',
		gens: 'principis',
		genp: 'principum',
		dats: 'principi',
		datp: 'principibus',
		accs: 'principem',
		accp: 'principes',
		vocs: 'princeps',
		vocp: 'principes',
		abls: 'principe',
		ablp: 'principibus',
	},
	{
		word: 'pro + ablative',
		category: 'preposition',
		translation: 'in front of, for, in return for',
		asked: false,
	},
	{
		word: 'procedo, procedere, processi',
		category: 'verb 3',
		translation: 'advance, proceed',
		asked: false,
	},
	{
		word: 'proelium, proelii, n',
		category: 'noun 2',
		translation: 'battle',
		asked: false,
		noms: 'proelium',
		nomp: 'proelia',
		gens: 'proelii',
		genp: 'proeliorum',
		dats: 'proelio',
		datp: 'proeliis',
		accs: 'proelium',
		accp: 'proelia',
		vocs: 'proelium',
		vocp: 'proelia',
		abls: 'proelio',
		ablp: 'proeliis',
	},
	{
		word: 'proficiscor, proficisci, profectus sum',
		category: 'verb 3 deponent',
		translation: 'set out',
		asked: false,
	},
	{
		word: 'progredior, progredi, progressus sum',
		category: 'verb 3 deponent',
		translation: 'advance',
		asked: false,
	},
	{
		word: 'promitto, promittere, promisi, promissus',
		category: 'verb 3',
		translation: 'promise',
		asked: false,
	},
	{
		word: 'prope + accusative',
		category: 'preposition',
		translation: 'near',
		asked: false,
	},
	{
		word: 'propter + accusative',
		category: 'preposition',
		translation: 'on account of, because of',
		asked: false,
	},
	{
		word: 'proximus, proxima, proximum',
		category: 'adjective',
		translation: 'nearest, next to',
		asked: false,
	},
	{
		word: 'puella, puellae, f',
		category: 'noun 1',
		translation: 'girl',
		asked: false,
		noms: 'puella',
		nomp: 'puellae',
		gens: 'puellae',
		genp: 'puellarum',
		dats: 'puellae',
		datp: 'puellis',
		accs: 'puellam',
		accp: 'puellas',
		vocs: 'puella',
		vocp: 'puellae',
		abls: 'puella',
		ablp: 'puellis',
	},
	{
		word: 'puer, pueri, m',
		category: 'noun 2',
		translation: 'boy',
		asked: false,
		noms: 'puer',
		nomp: 'pueri',
		gens: 'pueri',
		genp: 'puerorum',
		dats: 'puero',
		datp: 'pueris',
		accs: 'puerum',
		accp: 'pueros',
		vocs: 'puer',
		vocp: 'pueri',
		abls: 'puero',
		ablp: 'pueris',
	},
	{
		word: 'pugno, pugnare, pugnavi',
		category: 'verb 1',
		translation: 'fight',
		asked: false,
	},
	{
		word: 'pulcher, pulchra, pulchrum',
		category: 'adjective',
		translation: 'beautiful, handsome',
		asked: false,
	},
	{
		word: 'punio, punire, punivi, punitus',
		category: 'verb 4',
		translation: 'punish',
		asked: false,
	},
	{
		word: 'puto, putare, putavi, putatus',
		category: 'verb 1',
		translation: 'think',
		asked: false,
	},
	{
		word: 'quaero, quaerere, quaesivi, quaesitus',
		category: 'verb 3',
		translation: 'search for, look for, ask',
		asked: false,
	},
	{
		word: 'qualis?, quale',
		category: 'adjective',
		translation: 'what sort of?',
		asked: false,
	},
	{
		word: 'quam + superlative adverb',
		category: 'conjunction',
		translation: 'as â€¦ as possible',
		asked: false,
	},
	{
		word: 'quam',
		category: 'adverb',
		translation: 'than, how â€¦ ? how â€¦ !',
		asked: false,
	},
	{
		word: 'quamquam',
		category: 'conjunction',
		translation: 'although',
		asked: false,
	},
	{
		word: 'quando?',
		category: 'adverb',
		translation: 'when?',
		asked: false,
	},
	{
		word: 'quantus?, quanta? quantum?',
		category: 'adjective',
		translation: 'how big? how much?',
		asked: false,
	},
	{
		word: '-que',
		category: 'conjunction',
		translation: 'and',
		asked: false,
	},
	{
		word: 'qui, quae, quod',
		category: 'pronoun',
		translation: 'who, which',
		asked: false,
	},
	{
		word: 'quidam, quaedam, quoddam',
		category: 'pronoun',
		translation: 'one, a certain, some',
		asked: false,
	},
	{
		word: 'quis?, quid?',
		category: 'pronoun',
		translation: 'who? what?',
		asked: false,
	},
	{
		word: 'quo?',
		category: 'adverb',
		translation: 'to where?',
		asked: false,
	},
	{
		word: 'quod',
		category: 'conjunction',
		translation: 'because',
		asked: false,
	},
	{
		word: 'quomodo?',
		category: 'adverb',
		translation: 'how?',
		asked: false,
	},
	{
		word: 'quoque',
		category: 'conjunction',
		translation: 'also, too',
		asked: false,
	},
	{
		word: 'quot?',
		category: 'adjective',
		translation: 'how many?',
		asked: false,
	},
	{
		word: 'rapio, rapere, rapui, raptus',
		category: 'verb 3',
		translation: 'seize, grab',
		asked: false,
	},
	{
		word: 're-, (prefix used with verbs)',
		category: 'prefix',
		translation: 'back',
		asked: false,
	},
	{
		word: 'reddo, reddere, reddidi, redditus',
		category: 'verb 3',
		translation: 'give back, restore',
		asked: false,
	},
	{
		word: 'redeo, redire, redii',
		category: 'verb irreg',
		translation: 'go back, come back, return',
		asked: false,
	},
	{
		word: 'refero, referre, rettuli, relatus',
		category: 'verb irreg',
		translation: 'bring/carry back, report, tell',
		asked: false,
	},
	{
		word: 'regina, reginae, f',
		category: 'noun 1',
		translation: 'queen',
		asked: false,
		noms: 'regina',
		nomp: 'reginae',
		gens: 'reginae',
		genp: 'reginarum',
		dats: 'reginae',
		datp: 'reginis',
		accs: 'reginam',
		accp: 'reginas',
		vocs: 'regina',
		vocp: 'reginae',
		abls: 'regina',
		ablp: 'reginis',
	},
	{
		word: 'regnum, regni, n',
		category: 'noun 2',
		translation: 'kingdom',
		asked: false,
		noms: 'regnum',
		nomp: 'regna',
		gens: 'regni',
		genp: 'regnorum',
		dats: 'regno',
		datp: 'regnis',
		accs: 'regnum',
		accp: 'regna',
		vocs: 'regnum',
		vocp: 'regna',
		abls: 'regno',
		ablp: 'regnis',
	},
	{
		word: 'rego, regere, rexi, rectus',
		category: 'verb 3',
		translation: 'rule',
		asked: false,
	},
	{
		word: 'regredior, regredi, regressus sum',
		category: 'verb 3 deponent',
		translation: 'go back, return',
		asked: false,
	},
	{
		word: 'relinquo, relinquere, reliqui, relictus',
		category: 'verb 3',
		translation: 'leave, leave behind',
		asked: false,
	},
	{
		word: 'res, rei, f',
		category: 'noun 5',
		translation: 'thing, matter, event',
		asked: false,
		noms: 'res',
		nomp: 'res',
		gens: 'rei',
		genp: 'rerum',
		dats: 'rei',
		datp: 'rebus',
		accs: 'rem',
		accp: 'res',
		vocs: 'res',
		vocp: 'res',
		abls: 're',
		ablp: 'rebus',
	},
	{
		word: 'resisto, resistere, restiti + dative',
		category: 'verb 3',
		translation: 'resist',
		asked: false,
	},
	{
		word: 'respondeo, respondere, respondi, responsus',
		category: 'verb 2',
		translation: 'reply',
		asked: false,
	},
	{
		word: 'rex, regis, m',
		category: 'noun 3',
		translation: 'king',
		asked: false,
		noms: 'rex',
		nomp: 'reges',
		gens: 'regis',
		genp: 'regum',
		dats: 'regi',
		datp: 'regibus',
		accs: 'regem',
		accp: 'reges',
		vocs: 'rex',
		vocp: 'reges',
		abls: 'rege',
		ablp: 'regibus',
	},
	{
		word: 'rideo, ridere, risi',
		category: 'verb 2',
		translation: 'laugh, smile',
		asked: false,
	},
	{
		word: 'rogo, rogare, rogavi, rogatus',
		category: 'verb 1',
		translation: 'ask, ask for',
		asked: false,
	},
	{
		word: 'Roma, Romae, f',
		category: 'noun 1',
		translation: 'Rome',
		asked: false,
	},
	{
		word: 'Romanus, Romana, Romanum',
		category: 'adjective',
		translation: 'Roman',
		asked: false,
	},
	{
		word: 'sacer, sacra, sacrum',
		category: 'adjective',
		translation: 'sacred',
		asked: false,
	},
	{
		word: 'saepe',
		category: 'adverb',
		translation: 'often',
		asked: false,
	},
	{
		word: 'saevus, saeva, saevum',
		category: 'adjective',
		translation: 'savage, cruel',
		asked: false,
	},
	{
		word: 'saluto, salutare, salutavi, salutatus',
		category: 'verb 1',
		translation: 'greet',
		asked: false,
	},
	{
		word: 'sanguis, sanguinis, m',
		category: 'noun 3',
		translation: 'blood',
		asked: false,
		noms: 'sanguis',
		nomp: 'sanguines',
		gens: 'sanguinis',
		genp: 'sanguinum',
		dats: 'sanguini',
		datp: 'sanguinibus',
		accs: 'sanguinem',
		accp: 'sanguines',
		vocs: 'sanguis',
		vocp: 'sanguines',
		abls: 'sanguine',
		ablp: 'sanguinibus',
	},
	{
		word: 'scelestus, scelesta, scelestum',
		category: 'adjective',
		translation: 'wicked',
		asked: false,
	},
	{
		word: 'scelus, sceleris, n',
		category: 'noun 3',
		translation: 'crime',
		asked: false,
		noms: 'scelus',
		nomp: 'scelera',
		gens: 'sceleris',
		genp: 'scelerum',
		dats: 'sceleri',
		datp: 'sceleribus',
		accs: 'scelus',
		accp: 'scelera',
		vocs: 'scelus',
		vocp: 'scelera',
		abls: 'scelere',
		ablp: 'sceleribus',
	},
	{
		word: 'scio, scire, scivi, scitus',
		category: 'verb 4',
		translation: 'know',
		asked: false,
	},
	{
		word: 'scribo, scribere, scripsi, scriptus',
		category: 'verb 3',
		translation: 'write',
		asked: false,
	},
	{
		word: 'se, sui',
		category: 'pronoun',
		translation: 'himself, herself, itself, themselves',
		asked: false,
	},
	{
		word: 'sed',
		category: 'conjunction',
		translation: 'but',
		asked: false,
	},
	{
		word: 'sedeo, sedere, sedi',
		category: 'verb 2',
		translation: 'sit',
		asked: false,
	},
	{
		word: 'semper',
		category: 'adverb',
		translation: 'always',
		asked: false,
	},
	{
		word: 'senator, senatoris, m',
		category: 'noun 3',
		translation: 'senator',
		asked: false,
		noms: 'senator',
		nomp: 'senatores',
		gens: 'senatoris',
		genp: 'senatorum',
		dats: 'senatori',
		datp: 'senatoribus',
		accs: 'senatorem',
		accp: 'senatores',
		vocs: 'senator',
		vocp: 'senatores',
		abls: 'senatore',
		ablp: 'senatoribus',
	},
	{
		word: 'senex, senis, m',
		category: 'noun 3',
		translation: 'old man',
		asked: false,
		noms: 'senex',
		nomp: 'senes',
		gens: 'senis',
		genp: 'senum',
		dats: 'seni',
		datp: 'senibus',
		accs: 'senem',
		accp: 'senes',
		vocs: 'senex',
		vocp: 'senes',
		abls: 'sene',
		ablp: 'senibus',
	},
	{
		word: 'sentio, sentire, sensi, sensus',
		category: 'verb 4',
		translation: 'feel, notice',
		asked: false,
	},
	{
		word: 'sequor, sequi, secutus sum',
		category: 'verb 3 deponent',
		translation: 'follow',
		asked: false,
	},
	{
		word: 'servo, servare, servavi, servatus',
		category: 'verb 1',
		translation: 'save, protect, keep',
		asked: false,
	},
	{
		word: 'servus, servi, m',
		category: 'noun 2',
		translation: 'slave',
		asked: false,
		noms: 'servus',
		nomp: 'servi',
		gens: 'servi',
		genp: 'servorum',
		dats: 'servo',
		datp: 'servis',
		accs: 'servum',
		accp: 'servos',
		vocs: 'serve',
		vocp: 'servi',
		abls: 'servo',
		ablp: 'servis',
	},
	{
		word: 'si',
		category: 'conjunction',
		translation: 'if',
		asked: false,
	},
	{
		word: 'sic',
		category: 'adverb',
		translation: 'thus, in this way',
		asked: false,
	},
	{
		word: 'silva, silvae, f',
		category: 'noun 1',
		translation: 'wood',
		asked: false,
		noms: 'silva',
		nomp: 'silvae',
		gens: 'silvae',
		genp: 'silvarum',
		dats: 'silvae',
		datp: 'silvis',
		accs: 'silvam',
		accp: 'silvas',
		vocs: 'silva',
		vocp: 'silvae',
		abls: 'silva',
		ablp: 'silvis',
	},
	{
		word: 'simul',
		category: 'adverb',
		translation: 'at the same time',
		asked: false,
	},
	{
		word: 'simulac, simulatque',
		category: 'conjunction',
		translation: 'as soon as',
		asked: false,
	},
	{
		word: 'sine + ablative',
		category: 'preposition',
		translation: 'without',
		asked: false,
	},
	{
		word: 'soleo, solere, solitus sum',
		category: 'verb 2',
		translation: 'be accustomed',
		asked: false,
	},
	{
		word: 'solus, sola, solum',
		category: 'adjective',
		translation: "alone, lonely, only, on one's own",
		asked: false,
	},
	{
		word: 'specto, spectare, spectavi, spectatus',
		category: 'verb 1',
		translation: 'look at, watch',
		asked: false,
	},
	{
		word: 'spero, sperare, speravi, speratus',
		category: 'verb 1',
		translation: 'hope, expect',
		asked: false,
	},
	{
		word: 'spes, spei, f',
		category: 'noun 5',
		translation: 'hope',
		asked: false,
		noms: 'spes',
		nomp: 'spes',
		gens: 'spei',
		genp: 'sperum',
		dats: 'spei',
		datp: 'spebus',
		accs: 'spem',
		accp: 'spes',
		vocs: 'spes',
		vocp: 'spes',
		abls: 'spe',
		ablp: 'spebus',
	},
	{
		word: 'statim',
		category: 'adverb',
		translation: 'at once, immediately',
		asked: false,
	},
	{
		word: 'sto, stare, steti',
		category: 'verb 1',
		translation: 'stand',
		asked: false,
	},
	{
		word: 'stultus, stulta, stultum',
		category: 'adjective',
		translation: 'stupid, foolish',
		asked: false,
	},
	{
		word: 'sub + accusative/ablative',
		category: 'preposition',
		translation: 'under, beneath',
		asked: false,
	},
	{
		word: 'subito',
		category: 'adverb',
		translation: 'suddenly',
		asked: false,
	},
	{
		word: 'sum, esse, fui',
		category: 'verb irreg',
		translation: 'be',
		asked: false,
	},
	{
		word: 'summus, summa, summum',
		category: 'adjective',
		translation: 'highest, greatest, top (of)',
		asked: false,
	},
	{
		word: 'supero, superare, superavi, superatus',
		category: 'verb 1',
		translation: 'overcome, overpower',
		asked: false,
	},
	{
		word: 'surgo, surgere, surrexi',
		category: 'verb 3',
		translation: 'get up, stand up, rise',
		asked: false,
	},
	{
		word: 'suus, sua, suum',
		category: 'pronoun',
		translation: 'his, her, its, their (own)',
		asked: false,
	},
	{
		word: 'taberna, tabernae, f',
		category: 'noun 1',
		translation: 'shop, inn',
		asked: false,
		noms: 'taberna',
		nomp: 'tabernae',
		gens: 'tabernae',
		genp: 'tabernarum',
		dats: 'tabernae',
		datp: 'tabernis',
		accs: 'tabernam',
		accp: 'tabernas',
		vocs: 'taberna',
		vocp: 'tabernae',
		abls: 'taberna',
		ablp: 'tabernis',
	},
	{
		word: 'taceo, tacere, tacui, tacitus',
		category: 'verb 2',
		translation: 'be silent, be quiet',
		asked: false,
	},
	{
		word: 'talis, tale',
		category: 'adjective',
		translation: 'such, of such a kind',
		asked: false,
	},
	{
		word: 'tam',
		category: 'adverb',
		translation: 'so',
		asked: false,
	},
	{
		word: 'tamen',
		category: 'adverb',
		translation: 'however',
		asked: false,
	},
	{
		word: 'tandem',
		category: 'adverb',
		translation: 'at last, finally',
		asked: false,
	},
	{
		word: 'tantus, tanta, tantum',
		category: 'adjective',
		translation: 'so great, such a great',
		asked: false,
	},
	{
		word: 'tempestas, tempestatis, f',
		category: 'noun 3',
		translation: 'storm',
		asked: false,
		noms: 'tempestas',
		nomp: 'tempestates',
		gens: 'tempestatis',
		genp: 'tempestatum',
		dats: 'tempestati',
		datp: 'tempestatibus',
		accs: 'tempestatem',
		accp: 'tempestates',
		vocs: 'tempestas',
		vocp: 'tempestates',
		abls: 'tempestate',
		ablp: 'tempestatibus',
	},
	{
		word: 'templum, templi, n',
		category: 'noun 2',
		translation: 'temple',
		asked: false,
		noms: 'templum',
		nomp: 'templa',
		gens: 'templi',
		genp: 'templorum',
		dats: 'templo',
		datp: 'templis',
		accs: 'templum',
		accp: 'templa',
		vocs: 'templum',
		vocp: 'templa',
		abls: 'templo',
		ablp: 'templis',
	},
	{
		word: 'tempus, temporis, n',
		category: 'noun 3',
		translation: 'time',
		asked: false,
		noms: 'tempus',
		nomp: 'tempora',
		gens: 'temporis',
		genp: 'temporum',
		dats: 'tempori',
		datp: 'temporibus',
		accs: 'tempus',
		accp: 'tempora',
		vocs: 'tempus',
		vocp: 'tempora',
		abls: 'tempore',
		ablp: 'temporibus',
	},
	{
		word: 'teneo, tenere, tenui, tentus',
		category: 'verb 2',
		translation: 'hold',
		asked: false,
	},
	{
		word: 'terra, terrae, f',
		category: 'noun 1',
		translation: 'ground, land, country',
		asked: false,
		noms: 'terra',
		nomp: 'terrae',
		gens: 'terrae',
		genp: 'terrarum',
		dats: 'terrae',
		datp: 'terris',
		accs: 'terram',
		accp: 'terras',
		vocs: 'terra',
		vocp: 'terrae',
		abls: 'terra',
		ablp: 'terris',
	},
	{
		word: 'terreo, terrere, terrui, territus',
		category: 'verb 2',
		translation: 'frighten',
		asked: false,
	},
	{
		word: 'timeo, timere, timui',
		category: 'verb 2',
		translation: 'fear, be afraid',
		asked: false,
	},
	{
		word: 'tollo, tollere, sustuli, sublatus',
		category: 'verb 3',
		translation: 'raise, lift up, hold up',
		asked: false,
	},
	{
		word: 'tot',
		category: 'adjective',
		translation: 'so many',
		asked: false,
	},
	{
		word: 'totus, tota, totum',
		category: 'adjective',
		translation: 'whole',
		asked: false,
	},
	{
		word: 'trado, tradere, tradidi, traditus',
		category: 'verb 3',
		translation: 'hand over, hand down',
		asked: false,
	},
	{
		word: 'traho, trahere, traxi, tractus',
		category: 'verb 3',
		translation: 'drag',
		asked: false,
	},
	{
		word: 'trans + accusative (also used as prefix with verbs)',
		category: 'preposition',
		translation: 'across',
		asked: false,
	},
	{
		word: 'tristis, triste',
		category: 'adjective',
		translation: 'sad',
		asked: false,
	},
	{
		word: 'tu, tui',
		category: 'pronoun',
		translation: 'you (singular)',
		asked: false,
	},
	{
		word: 'tum',
		category: 'adverb',
		translation: 'then',
		asked: false,
	},
	{
		word: 'turba, turbae, f',
		category: 'noun 1',
		translation: 'crowd',
		asked: false,
		noms: 'turba',
		nomp: 'turbae',
		gens: 'turbae',
		genp: 'turbarum',
		dats: 'turbae',
		datp: 'turbis',
		accs: 'turbam',
		accp: 'turbas',
		vocs: 'turba',
		vocp: 'turbae',
		abls: 'turba',
		ablp: 'turbis',
	},
	{
		word: 'tuus, tua, tuum',
		category: 'pronoun',
		translation: 'your (singular), yours',
		asked: false,
	},
	{
		word: 'ubi',
		category: 'adverb',
		translation: 'where? where, when',
		asked: false,
	},
	{
		word: 'umquam',
		category: 'adverb',
		translation: 'ever',
		asked: false,
	},
	{
		word: 'unde?',
		category: 'adverb',
		translation: 'from where?',
		asked: false,
	},
	{
		word: 'urbs, urbis, f',
		category: 'noun 3',
		translation: 'city',
		asked: false,
		noms: 'urbs',
		nomp: 'urbes',
		gens: 'urbis',
		genp: 'urbium',
		dats: 'urbi',
		datp: 'urbibus',
		accs: 'urbem',
		accp: 'urbes',
		vocs: 'urbs',
		vocp: 'urbes',
		abls: 'urbe',
		ablp: 'urbibus',
	},
	{
		word: 'ut, indeclinable + subjunctive',
		category: 'conjunction',
		translation: 'that, so that, in order that',
		asked: false,
	},
	{
		word: 'ut, indeclinable + indicative',
		category: 'conjunction',
		translation: 'as, when',
		asked: false,
	},
	{
		word: 'uxor, uxoris, f',
		category: 'noun 3',
		translation: 'wife',
		asked: false,
		noms: 'uxor',
		nomp: 'uxores',
		gens: 'uxoris',
		genp: 'uxorum',
		dats: 'uxori',
		datp: 'uxoribus',
		accs: 'uxorem',
		accp: 'uxores',
		vocs: 'uxor',
		vocp: 'uxores',
		abls: 'uxore',
		ablp: 'uxoribus',
	},
	{
		word: 'validus, valida, validum',
		category: 'adjective',
		translation: 'strong',
		asked: false,
	},
	{
		word: 'vehementer',
		category: 'adverb',
		translation: 'violently, loudly',
		asked: false,
	},
	{
		word: 'vendo, vendere, vendidi, venditus',
		category: 'verb 3',
		translation: 'sell',
		asked: false,
	},
	{
		word: 'venio, venire, veni',
		category: 'verb 4',
		translation: 'come',
		asked: false,
	},
	{
		word: 'verbum, verbi, n',
		category: 'noun 2',
		translation: 'word',
		asked: false,
		noms: 'verbum',
		nomp: 'verba',
		gens: 'verbi',
		genp: 'verborum',
		dats: 'verbo',
		datp: 'verbis',
		accs: 'verbum',
		accp: 'verba',
		vocs: 'verbum',
		vocp: 'verba',
		abls: 'verbo',
		ablp: 'verbis',
	},
	{
		word: 'verto, vertere, verti, versus',
		category: 'verb 3',
		translation: 'turn',
		asked: false,
	},
	{
		word: 'vester, vestra, vestrum',
		category: 'pronoun',
		translation: 'your (plural), yours',
		asked: false,
	},
	{
		word: 'via, viae, f',
		category: 'noun 1',
		translation: 'street, road, way',
		asked: false,
		noms: 'via',
		nomp: 'viae',
		gens: 'viae',
		genp: 'viarum',
		dats: 'viae',
		datp: 'viis',
		accs: 'viam',
		accp: 'vias',
		vocs: 'via',
		vocp: 'viae',
		abls: 'via',
		ablp: 'viis',
	},
	{
		word: 'victoria, victoriae, f',
		category: 'noun 1',
		translation: 'victory',
		asked: false,
		noms: 'victoria',
		nomp: 'victoriae',
		gens: 'victoriae',
		genp: 'victoriarum',
		dats: 'victoriae',
		datp: 'victoriis',
		accs: 'victoriam',
		accp: 'victorias',
		vocs: 'victoria',
		vocp: 'victoriae',
		abls: 'victoria',
		ablp: 'victoriis',
	},
	{
		word: 'video, videre, vidi, visus',
		category: 'verb 2',
		translation: 'see',
		asked: false,
	},
	{
		word: 'videor, videri, visus sum',
		category: 'verb 2 deponent',
		translation: 'seem, appear',
		asked: false,
	},
	{
		word: 'villa, villae, f',
		category: 'noun 1',
		translation: 'house, country villa',
		asked: false,
		noms: 'villa',
		nomp: 'villae',
		gens: 'villae',
		genp: 'villarum',
		dats: 'villae',
		datp: 'villis',
		accs: 'villam',
		accp: 'villas',
		vocs: 'villa',
		vocp: 'villae',
		abls: 'villa',
		ablp: 'villis',
	},
	{
		word: 'vinco, vincere, vici, victus',
		category: 'verb 3',
		translation: 'conquer, win, be victorious',
		asked: false,
	},
	{
		word: 'vinum, vini, n',
		category: 'noun 2',
		translation: 'wine',
		asked: false,
		noms: 'vinum',
		nomp: 'vina',
		gens: 'vini',
		genp: 'vinorum',
		dats: 'vino',
		datp: 'vinis',
		accs: 'vinum',
		accp: 'vina',
		vocs: 'vinum',
		vocp: 'vina',
		abls: 'vino',
		ablp: 'vinis',
	},
	{
		word: 'vir, viri, m',
		category: 'noun 2',
		translation: 'man',
		asked: false,
		noms: 'vir',
		nomp: 'viri',
		gens: 'viri',
		genp: 'virorum',
		dats: 'viro',
		datp: 'viris',
		accs: 'virum',
		accp: 'viros',
		vocs: 'viri',
		vocp: 'viri',
		abls: 'viro',
		ablp: 'viris',
	},
	{
		word: 'virtus, virtutis, f',
		category: 'noun 3',
		translation: 'courage, virtue',
		asked: false,
		noms: 'virtus',
		nomp: 'virtutes',
		gens: 'virtutis',
		genp: 'virtutum',
		dats: 'virtuti',
		datp: 'virtutibus',
		accs: 'virtutem',
		accp: 'virtutes',
		vocs: 'virtus',
		vocp: 'virtutes',
		abls: 'virtute',
		ablp: 'virtutibus',
	},
	{
		word: 'vita, vitae, f',
		category: 'noun 1',
		translation: 'life',
		asked: false,
		noms: 'vita',
		nomp: 'vitae',
		gens: 'vitae',
		genp: 'vitarum',
		dats: 'vitae',
		datp: 'vitis',
		accs: 'vitam',
		accp: 'vitas',
		vocs: 'vita',
		vocp: 'vitae',
		abls: 'vita',
		ablp: 'vitis',
	},
	{
		word: 'vivo, vivere, vixi',
		category: 'verb 3',
		translation: 'live, be alive',
		asked: false,
	},
	{
		word: 'voco, vocare, vocavi, vocatus',
		category: 'verb 1',
		translation: 'call',
		asked: false,
	},
	{
		word: 'volo, velle, volui',
		category: 'verb irreg',
		translation: 'want, wish, be willing',
		asked: false,
	},
	{
		word: 'vos, vestrum',
		category: 'pronoun',
		translation: 'you (plural)',
		asked: false,
	},
	{
		word: 'vox, vocis, f',
		category: 'noun 3',
		translation: 'voice, shout',
		asked: false,
	},
	{
		word: 'vulnero, vulnerare, vulneravi, vulneratus',
		category: 'verb 1',
		translation: 'wound, injure',
		asked: false,
	},
	{
		word: 'vulnus, vulneris, n',
		category: 'noun 3',
		translation: 'wound',
		asked: false,
		noms: 'vulnus',
		nomp: 'vulnera',
		gens: 'vulneris',
		genp: 'vulnerum',
		dats: 'vulneri',
		datp: 'vulneribus',
		accs: 'vulnus',
		accp: 'vulnera',
		vocs: 'vulnus',
		vocp: 'vulnera',
		abls: 'vulnere',
		ablp: 'vulneribus',
	},
];
