var vocabGCSEEduqas = [
	{
		word: 'a, ab + abl (also used as prefix with verbs)',
		category: 21,
		translation: 'from, by (as prefix = away)',
		asked: false,
	},
	{
		word: 'absum, abesse',
		category: 6,
		translation: 'be out, be absent, be away',
		asked: false,
	},
	{
		word: 'ac, atque (indecl.)',
		category: 28,
		translation: 'and',
		asked: false,
	},
	{
		word: 'accido, accidere, accidi',
		category: 25,
		translation: 'happen',
		asked: false,
	},
	{
		word: 'accipio, accipere, accepi, acceptus',
		category: 10,
		translation: 'accept, take in, receive',
		asked: false,
	},
	{
		word: 'ad + acc (also used as prefix with verbs)',
		category: 3,
		translation: 'to, towards, at',
		asked: false,
	},
	{
		word: 'adeo (indecl.)',
		category: 27,
		translation: 'so much, so greatly',
		asked: false,
	},
	{
		word: 'adiuvo, adiuvare, adiuvi, adiutus',
		category: 21,
		translation: 'help',
		asked: false,
	},
	{
		word: 'adsum, adesse',
		category: 5,
		translation: 'be here, be present',
		asked: false,
	},
	{
		word: 'advenio, advenire, adveni',
		category: 13,
		translation: 'arrive',
		asked: false,
	},
	{
		word: 'ago, agere, egi, actus',
		category: 4,
		translation: 'do, act, drive',
		asked: false,
	},
	{
		word: 'aliquis, aliquid',
		category: 14,
		translation: 'someone, something',
		asked: false,
	},
	{
		word: 'alius, alia, aliud',
		category: 15,
		translation: 'other, another, else',
		asked: false,
		noms: 'alium',
		nomp: 'alia',
		gens: 'alii',
		genp: 'aliorum',
		dats: 'alio',
		datp: 'aliis',
		accs: 'alium',
		accp: 'alia',
		vocs: 'alium',
		vocp: 'alia',
		abls: 'alio',
		ablp: 'aliis',
	},
	{
		word: 'alter, altera, alterum',
		category: 13,
		translation: 'the other, another, the second of two',
		asked: false,
	},
	{
		word: 'altus, alta, altum',
		category: 31,
		translation: 'high, deep',
		asked: false,
	},
	{
		word: 'ambulo, ambulare, ambulavi',
		category: 5,
		translation: 'walk',
		asked: false,
	},
	{
		word: 'amicus, amici, m.',
		category: 2,
		translation: 'friend',
		asked: false,
		noms: 'amicus',
		nomp: 'amici',
		gens: 'amici',
		genp: 'amicorum',
		dats: 'amico',
		datp: 'amicis',
		accs: 'amicum',
		accp: 'amicos',
		vocs: 'amice',
		vocp: 'amici',
		abls: 'amico',
		ablp: 'amicis',
	},
	{
		word: 'amo, amare, amavi, amatus',
		category: 19,
		translation: 'love, like',
		asked: false,
	},
	{
		word: 'amor, amoris, m.',
		category: 22,
		translation: 'love',
		asked: false,
		noms: 'amor',
		nomp: 'amores',
		gens: 'amoris',
		genp: 'amorum',
		dats: 'amori',
		datp: 'amoribus',
		accs: 'amorem',
		accp: 'amores',
		vocs: 'amor',
		vocp: 'amores',
		abls: 'amore',
		ablp: 'amoribus',
	},
	{
		word: 'ancilla, ancillae, f.',
		category: 2,
		translation: 'slave-girl, maid',
		asked: false,
		noms: 'ancilla',
		nomp: 'ancillae',
		gens: 'ancillae',
		genp: 'ancillarum',
		dats: 'ancillae',
		datp: 'ancillis',
		accs: 'ancillam',
		accp: 'ancillas',
		vocs: 'ancilla',
		vocp: 'ancillae',
		abls: 'ancilla',
		ablp: 'ancillis',
	},
	{
		word: 'animus, animi, m.',
		category: 17,
		translation: 'spirit, soul, mind',
		asked: false,
		noms: 'animus',
		nomp: 'animi',
		gens: 'animi',
		genp: 'animorum',
		dats: 'animo',
		datp: 'animis',
		accs: 'animum',
		accp: 'animos',
		vocs: 'anime',
		vocp: 'animi',
		abls: 'animo',
		ablp: 'animis',
	},
	{
		word: 'annus, anni, m.',
		category: 21,
		translation: 'year',
		asked: false,
		noms: 'annus',
		nomp: 'anni',
		gens: 'anni',
		genp: 'annorum',
		dats: 'anno',
		datp: 'annis',
		accs: 'annum',
		accp: 'annos',
		vocs: 'anne',
		vocp: 'anni',
		abls: 'anno',
		ablp: 'annis',
	},
	{
		word: 'ante + acc',
		category: 31,
		translation: 'before, in front of',
		asked: false,
	},
	{
		word: 'antea (indecl.)',
		category: 27,
		translation: 'before',
		asked: false,
	},
	{
		word: 'aperio, aperire, aperui, apertus',
		category: 25,
		translation: 'open',
		asked: false,
	},
	{
		word: 'appareo, apparere, apparui',
		category: 27,
		translation: 'appear',
		asked: false,
	},
	{
		word: 'appropinquo, appropinquare, appropinquavi + dat',
		category: 17,
		translation: 'approach, come near to',
		asked: false,
	},
	{
		word: 'apud + acc',
		category: 14,
		translation: 'among, with, at the house of',
		asked: false,
	},
	{
		word: 'aqua, aquae, f.',
		category: 15,
		translation: 'water',
		asked: false,
		noms: 'aqua',
		nomp: 'aquae',
		gens: 'aquae',
		genp: 'aquarum',
		dats: 'aquae',
		datp: 'aquis',
		accs: 'aquam',
		accp: 'aquas',
		vocs: 'aqua',
		vocp: 'aquae',
		abls: 'aqua',
		ablp: 'aquis',
	},
	{
		word: 'audax, audacis',
		category: 24,
		translation: 'bold, daring',
		asked: false,
		noms: 'audacia',
		nomp: 'audacae',
		gens: 'audacae',
		genp: 'audacarum',
		dats: 'audacae',
		datp: 'audacis',
		accs: 'audacam',
		accp: 'audacas',
		vocs: 'audacia',
		vocp: 'audacae',
		abls: 'audaca',
		ablp: 'audacis',
	},
	{
		word: 'audio, audire, audivi, auditus',
		category: 5,
		translation: 'hear, listen to',
		asked: false,
	},
	{
		word: 'aufero, auferre, abstuli, ablatus',
		category: 26,
		translation: 'take away, carry off, steal',
		asked: false,
	},
	{
		word: 'aut ... aut (indecl.)',
		category: 39,
		translation: 'either ... or ...',
		asked: false,
	},
	{
		word: 'bellum, belli, n.',
		category: 26,
		translation: 'war',
		asked: false,
		noms: 'bellum',
		nomp: 'bella',
		gens: 'belli',
		genp: 'bellorum',
		dats: 'bello',
		datp: 'bellis',
		accs: 'bellum',
		accp: 'bella',
		vocs: 'bellum',
		vocp: 'bella',
		abls: 'bello',
		ablp: 'bellis',
	},
	{
		word: 'bene (indecl.)',
		category: 17,
		translation: 'well',
		asked: false,
	},
	{
		word: 'benignus, benigna, benignum',
		category: 17,
		translation: 'kind, generous',
		asked: false,
	},
	{
		word: 'bibo, bibere, bibi',
		category: 3,
		translation: 'drink',
		asked: false,
	},
	{
		word: 'bonus, bona, bonum',
		category: 16,
		translation: 'good',
		asked: false,
		noms: 'bona',
		nomp: 'bonae',
		gens: 'bonae',
		genp: 'bonarum',
		dats: 'bonae',
		datp: 'bonis',
		accs: 'bonam',
		accp: 'bonas',
		vocs: 'bona',
		vocp: 'bonae',
		abls: 'bona',
		ablp: 'bonis',
	},
	{
		word: 'brevis, breve',
		category: 'other',
		translation: 'short, brief',
		asked: false,
	},
	{
		word: 'cado, cadere, cecidi, casus',
		category: 39,
		translation: 'fall',
		asked: false,
	},
	{
		word: 'caelum, caeli, n.',
		category: 22,
		translation: 'sky, heaven',
		asked: false,
		noms: 'caelum',
		nomp: 'caela',
		gens: 'caeli',
		genp: 'caelorum',
		dats: 'caelo',
		datp: 'caelis',
		accs: 'caelum',
		accp: 'caela',
		vocs: 'caelum',
		vocp: 'caela',
		abls: 'caelo',
		ablp: 'caelis',
	},
	{
		word: 'canis, canis, m.',
		category: 1,
		translation: 'dog',
		asked: false,
		noms: 'canis',
		nomp: 'canes',
		gens: 'canis',
		genp: 'canum',
		dats: 'cani',
		datp: 'canibus',
		accs: 'canem',
		accp: 'canes',
		vocs: 'canis',
		vocp: 'canes',
		abls: 'cane',
		ablp: 'canibus',
	},
	{
		word: 'capio, capere, cepi, captus',
		category: 11,
		translation: 'take, catch, capture, adopt (a plan)',
		asked: false,
	},
	{
		word: 'caput, capitis, n.',
		category: 18,
		translation: 'head',
		asked: false,
		noms: 'caput',
		nomp: 'capita',
		gens: 'capitis',
		genp: 'capitum',
		dats: 'capiti',
		datp: 'capitibus',
		accs: 'caput',
		accp: 'capita',
		vocs: 'caput',
		vocp: 'capita',
		abls: 'capite',
		ablp: 'capitibus',
	},
	{
		word: 'carus, cara, carum',
		category: 19,
		translation: 'dear',
		asked: false,
	},
	{
		word: 'celer, celere',
		category: 9,
		translation: 'quick, fast',
		asked: false,
		noms: 'celer',
		nomp: 'celeres',
		gens: 'celeris',
		genp: 'celerum',
		dats: 'celeri',
		datp: 'celeribus',
		accs: 'celerem',
		accp: 'celeres',
		vocs: 'celer',
		vocp: 'celeres',
		abls: 'celere',
		ablp: 'celeribus',
	},
	{
		word: 'celo, celare, celavi, celatus',
		category: 21,
		translation: 'hide',
		asked: false,
	},
	{
		word: 'cena, cenae, f.',
		category: 2,
		translation: 'dinner, meal',
		asked: false,
		noms: 'cena',
		nomp: 'cenae',
		gens: 'cenae',
		genp: 'cenarum',
		dats: 'cenae',
		datp: 'cenis',
		accs: 'cenam',
		accp: 'cenas',
		vocs: 'cena',
		vocp: 'cenae',
		abls: 'cena',
		ablp: 'cenis',
	},
	{
		word: 'centum (indecl.)',
		category: 28,
		translation: 'a hundred',
		asked: false,
	},
	{
		word: 'ceteri, ceterae, cetera',
		category: 13,
		translation: 'the rest, the others',
		asked: false,
	},
	{
		word: 'cibus, cibi, m.',
		category: 2,
		translation: 'food',
		asked: false,
		noms: 'cibus',
		nomp: 'cibi',
		gens: 'cibi',
		genp: 'ciborum',
		dats: 'cibo',
		datp: 'cibis',
		accs: 'cibum',
		accp: 'cibos',
		vocs: 'cibe',
		vocp: 'cibi',
		abls: 'cibo',
		ablp: 'cibis',
	},
	{
		word: 'circum + acc',
		category: 21,
		translation: 'around',
		asked: false,
	},
	{
		word: 'civis, civis, m.f.',
		category: 11,
		translation: 'citizen',
		asked: false,
		noms: 'civis',
		nomp: 'cives',
		gens: 'civis',
		genp: 'civium',
		dats: 'civi',
		datp: 'civibus',
		accs: 'civem',
		accp: 'cives',
		vocs: 'civis',
		vocp: 'cives',
		abls: 'cive',
		ablp: 'civibus',
	},
	{
		word: 'clamo, clamare, clamavi, clamatus',
		category: 3,
		translation: 'shout',
		asked: false,
	},
	{
		word: 'clamor, clamoris, m.',
		category: 5,
		translation: 'shout, shouting, noise',
		asked: false,
		noms: 'clamor',
		nomp: 'clamores',
		gens: 'clamoris',
		genp: 'clamorum',
		dats: 'clamori',
		datp: 'clamoribus',
		accs: 'clamorem',
		accp: 'clamores',
		vocs: 'clamor',
		vocp: 'clamores',
		abls: 'clamore',
		ablp: 'clamoribus',
	},
	{
		word: 'coepi, coepisse, coeptus',
		category: 18,
		translation: 'began (past tenses only)',
		asked: false,
	},
	{
		word: 'cogito, cogitare, cogitavi, cogitatus',
		category: 19,
		translation: 'think, consider',
		asked: false,
	},
	{
		word: 'cognosco, cognoscere, cognovi, cognitus',
		category: 18,
		translation: 'get to know, find out, learn',
		asked: false,
	},
	{
		word: 'cogo, cogere, coegi, coactus',
		category: 25,
		translation: 'force, compel',
		asked: false,
	},
	{
		word: 'comes, comitis, m.f.',
		category: 27,
		translation: 'comrade, companion',
		asked: false,
		noms: 'comes',
		nomp: 'comites',
		gens: 'comitis',
		genp: 'comitum',
		dats: 'comiti',
		datp: 'comitibus',
		accs: 'comitem',
		accp: 'comites',
		vocs: 'comes',
		vocp: 'comites',
		abls: 'comite',
		ablp: 'comitibus',
	},
	{
		word: 'conficio, conficere, confeci, confectus',
		category: 19,
		translation: 'finish; wear out, exhaust',
		asked: false,
	},
	{
		word: 'conor, conari, conatus sum',
		category: 34,
		translation: 'try',
		asked: false,
	},
	{
		word: 'consilium, consilii, n.',
		category: 16,
		translation: 'plan, idea, advice',
		asked: false,
		noms: 'consilium',
		nomp: 'consilia',
		gens: 'consilii',
		genp: 'consiliorum',
		dats: 'consilio',
		datp: 'consiliis',
		accs: 'consilium',
		accp: 'consilia',
		vocs: 'consilium',
		vocp: 'consilia',
		abls: 'consilio',
		ablp: 'consiliis',
	},
	{
		word: 'conspicio, conspicere, conspexi, conspectus',
		category: 7,
		translation: 'catch sight of, notice',
		asked: false,
	},
	{
		word: 'constituo, constituere, constitui, constitutus',
		category: 28,
		translation: 'decide',
		asked: false,
	},
	{
		word: 'consumo, consumere, consumpsi, consumptus',
		category: 8,
		translation: 'eat',
		asked: false,
	},
	{
		word: 'contra + acc',
		category: 33,
		translation: 'against',
		asked: false,
	},
	{
		word: 'corpus, corporis, n.',
		category: 28,
		translation: 'body',
		asked: false,
		noms: 'corpus',
		nomp: 'corpora',
		gens: 'corporis',
		genp: 'corporum',
		dats: 'corpori',
		datp: 'corporibus',
		accs: 'corpus',
		accp: 'corpora',
		vocs: 'corpus',
		vocp: 'corpora',
		abls: 'corpore',
		ablp: 'corporibus',
	},
	{
		word: 'credo, credere, credidi, creditus + dat',
		category: 11,
		translation: 'believe, trust, have faith in',
		asked: false,
	},
	{
		word: 'crudelis, crudele',
		category: 20,
		translation: 'cruel',
		asked: false,
	},
	{
		word: 'cum + abl (as prefix col- / com- / con- / cor-)',
		category: 7,
		translation: 'with (as prefix = together)',
		asked: false,
	},
	{
		word: 'cum (indecl.)',
		category: 24,
		translation: 'when, since',
		asked: false,
	},
	{
		word: 'cupio, cupere, cupivi',
		category: 9,
		translation: 'want, desire',
		asked: false,
	},
	{
		word: 'cur? (indecl.)',
		category: 4,
		translation: 'why?',
		asked: false,
	},
	{
		word: 'cura, curae, f.',
		category: 23,
		translation: 'care, worry',
		asked: false,
		noms: 'cura',
		nomp: 'curae',
		gens: 'curae',
		genp: 'curarum',
		dats: 'curae',
		datp: 'curis',
		accs: 'curam',
		accp: 'curas',
		vocs: 'cura',
		vocp: 'curae',
		abls: 'cura',
		ablp: 'curis',
	},
	{
		word: 'curo, curare, curavi, curatus',
		category: 19,
		translation: 'look after, care for, supervise',
		asked: false,
	},
	{
		word: 'curro, currere, cucurri, cursus',
		category: 5,
		translation: 'run',
		asked: false,
	},
	{
		word: 'custos, custodis, m.f.',
		category: 13,
		translation: 'guard',
		asked: false,
		noms: 'custos',
		nomp: 'custodes',
		gens: 'custodis',
		genp: 'custodum',
		dats: 'custodi',
		datp: 'custodibus',
		accs: 'custodem',
		accp: 'custodes',
		vocs: 'custos',
		vocp: 'custodes',
		abls: 'custode',
		ablp: 'custodibus',
	},
	{
		word: 'de + abl (also used as prefix with verbs)',
		category: 11,
		translation: 'from, down from; about (as prefix = down)',
		asked: false,
	},
	{
		word: 'dea, deae, f.',
		category: 18,
		translation: 'goddess',
		asked: false,
		noms: 'dea',
		nomp: 'deae',
		gens: 'deae',
		genp: 'dearum',
		dats: 'deae',
		datp: 'deis',
		accs: 'deam',
		accp: 'deas',
		vocs: 'dea',
		vocp: 'deae',
		abls: 'dea',
		ablp: 'deis',
	},
	{
		word: 'debeo, debere, debui, debitus',
		category: 15,
		translation: 'owe, ought, should, must',
		asked: false,
	},
	{
		word: 'decem (indecl.)',
		category: 20,
		translation: 'ten',
		asked: false,
	},
	{
		word: 'deinde (indecl.)',
		category: 16,
		translation: 'then',
		asked: false,
	},
	{
		word: 'deleo, delere, delevi, deletus',
		category: 14,
		translation: 'destroy',
		asked: false,
	},
	{
		word: 'despero, desperare, desperavi, desperatus',
		category: 20,
		translation: 'despair',
		asked: false,
	},
	{
		word: 'deus, dei, m.',
		category: 14,
		translation: 'god',
		asked: false,
	},
	{
		word: 'dico, dicere, dixi, dictus',
		category: 13,
		translation: 'say',
		asked: false,
	},
	{
		word: 'dies, diei, m.',
		category: 9,
		translation: 'day',
		asked: false,
		noms: 'dies',
		nomp: 'dies',
		gens: 'diei',
		genp: 'dierum',
		dats: 'diei',
		datp: 'diebus',
		accs: 'diem',
		accp: 'dies',
		vocs: 'dies',
		vocp: 'dies',
		abls: 'die',
		ablp: 'diebus',
	},
	{
		word: 'difficilis, difficile',
		category: 14,
		translation: 'difficult',
		asked: false,
	},
	{
		word: 'dirus, dira, dirum',
		category: 'other',
		translation: 'dreadful',
		asked: false,
		noms: 'dira',
		nomp: 'dirae',
		gens: 'dirae',
		genp: 'dirarum',
		dats: 'dirae',
		datp: 'diris',
		accs: 'diram',
		accp: 'diras',
		vocs: 'dira',
		vocp: 'dirae',
		abls: 'dira',
		ablp: 'diris',
	},
	{
		word: 'discedo, discedere, discessi',
		category: 18,
		translation: 'depart, leave',
		asked: false,
	},
	{
		word: 'diu (indecl.)',
		category: 17,
		translation: 'for a long time',
		asked: false,
	},
	{
		word: 'dives, divitis',
		category: 30,
		translation: 'rich',
		asked: false,
		noms: 'dives',
		nomp: 'divites',
		gens: 'divitis',
		genp: 'divitum',
		dats: 'diviti',
		datp: 'divitibus',
		accs: 'divitem',
		accp: 'divites',
		vocs: 'dives',
		vocp: 'divites',
		abls: 'divite',
		ablp: 'divitibus',
	},
	{
		word: 'do, dare, dedi, datus',
		category: 9,
		translation: 'give',
		asked: false,
	},
	{
		word: 'domi',
		category: 'other',
		translation: 'at home',
		asked: false,
	},
	{
		word: 'domina, dominae, f.',
		category: 14,
		translation: 'mistress',
		asked: false,
		noms: 'domina',
		nomp: 'dominae',
		gens: 'dominae',
		genp: 'dominarum',
		dats: 'dominae',
		datp: 'dominis',
		accs: 'dominam',
		accp: 'dominas',
		vocs: 'domina',
		vocp: 'dominae',
		abls: 'domina',
		ablp: 'dominabus',
	},
	{
		word: 'dominus, domini, m.',
		category: 2,
		translation: 'master',
		asked: false,
		noms: 'dominus',
		nomp: 'domini',
		gens: 'domini',
		genp: 'dominorum',
		dats: 'domino',
		datp: 'dominis',
		accs: 'dominum',
		accp: 'dominos',
		vocs: 'domine',
		vocp: 'domini',
		abls: 'domino',
		ablp: 'dominis',
	},
	{
		word: 'domus, domus, f.',
		category: 20,
		translation: 'home, house',
		asked: false,
		noms: 'domus',
		nomp: 'domi',
		gens: 'domi',
		genp: 'domorum',
		dats: 'domo',
		datp: 'domis',
		accs: 'domum',
		accp: 'domos',
		vocs: 'dome',
		vocp: 'domi',
		abls: 'domo',
		ablp: 'domis',
	},
	{
		word: 'donum, doni, n.',
		category: 14,
		translation: 'gift, present',
		asked: false,
		noms: 'donum',
		nomp: 'dona',
		gens: 'doni',
		genp: 'donorum',
		dats: 'dono',
		datp: 'donis',
		accs: 'donum',
		accp: 'dona',
		vocs: 'donum',
		vocp: 'dona',
		abls: 'dono',
		ablp: 'donis',
	},
	{
		word: 'dormio, dormire, dormivi',
		category: 2,
		translation: 'sleep',
		asked: false,
	},
	{
		word: 'duco, ducere, duxi, ductus',
		category: 8,
		translation: 'lead, take',
		asked: false,
	},
	{
		word: 'dum',
		category: 34,
		translation: 'while',
		asked: false,
	},
	{
		word: 'duo, duae, duo',
		category: 12,
		translation: 'two',
		asked: false,
	},
	{
		word: 'durus, dura, durum',
		category: 21,
		translation: 'hard, harsh',
		asked: false,
	},
	{
		word: 'dux, ducis, m.',
		category: 'other',
		translation: 'leader',
		asked: false,
		noms: 'dux',
		nomp: 'duces',
		gens: 'ducis',
		genp: 'ducum',
		dats: 'duci',
		datp: 'ducibus',
		accs: 'ducem',
		accp: 'duces',
		vocs: 'ducem',
		vocp: 'duces',
		abls: 'duce',
		ablp: 'ducibus',
	},
	{
		word: 'e, ex + abl (also used as prefix with verbs)',
		category: 4,
		translation: 'from, out of (as prefix = out, away)',
		asked: false,
	},
	{
		word: 'effugio, effugere, effugi',
		category: 16,
		translation: 'escape',
		asked: false,
	},
	{
		word: 'ego, mei',
		category: 4,
		translation: 'I, me',
		asked: false,
	},
	{
		word: 'egredior, egredi, egressus sum',
		category: 34,
		translation: 'go out',
		asked: false,
	},
	{
		word: 'emo, emere, emi, emptus',
		category: 6,
		translation: 'buy',
		asked: false,
	},
	{
		word: 'enim (indecl.)',
		category: 23,
		translation: 'for',
		asked: false,
	},
	{
		word: 'eo, ire, ii',
		category: 11,
		translation: 'go',
		asked: false,
	},
	{
		word: 'epistula, epistulae, f.',
		category: 12,
		translation: 'letter',
		asked: false,
		noms: 'epistula',
		nomp: 'epistulae',
		gens: 'epistulae',
		genp: 'epistularum',
		dats: 'epistulae',
		datp: 'epistulis',
		accs: 'epistulam',
		accp: 'epistulas',
		vocs: 'epistula',
		vocp: 'epistulae',
		abls: 'epistula',
		ablp: 'epistulis',
	},
	{
		word: 'equus, equi, m.',
		category: 15,
		translation: 'horse',
		asked: false,
		noms: 'equus',
		nomp: 'equi',
		gens: 'equi',
		genp: 'equorum',
		dats: 'equo',
		datp: 'equis',
		accs: 'equum',
		accp: 'equos',
		vocs: 'eque',
		vocp: 'equi',
		abls: 'equo',
		ablp: 'equis',
	},
	{
		word: 'et (indecl.)',
		category: 3,
		translation: 'and',
		asked: false,
	},
	{
		word: 'etiam (indecl.)',
		category: 15,
		translation: 'also, even',
		asked: false,
	},
	{
		word: 'exspecto, exspectare, exspectavi, exspectatus',
		category: 3,
		translation: 'wait for',
		asked: false,
	},
	{
		word: 'facilis, facile',
		category: 17,
		translation: 'easy',
		asked: false,
	},
	{
		word: 'facio, facere, feci, factus',
		category: 7,
		translation: 'make, do',
		asked: false,
	},
	{
		word: 'femina, feminae, f.',
		category: 5,
		translation: 'woman',
		asked: false,
		noms: 'femina',
		nomp: 'feminae',
		gens: 'feminae',
		genp: 'feminarum',
		dats: 'feminae',
		datp: 'feminis',
		accs: 'feminam',
		accp: 'feminas',
		vocs: 'femina',
		vocp: 'feminae',
		abls: 'femina',
		ablp: 'feminis',
	},
	{
		word: 'fero, ferre, tuli, latus',
		category: 9,
		translation: 'bring, carry, bear',
		asked: false,
	},
	{
		word: 'ferox, ferocis',
		category: 8,
		translation: 'fierce, ferocious',
		asked: false,
	},
	{
		word: 'festino, festinare, festinavi',
		category: 6,
		translation: 'hurry',
		asked: false,
	},
	{
		word: 'fidelis, fidele',
		category: 14,
		translation: 'faithful, loyal',
		asked: false,
	},
	{
		word: 'filia, filiae, f.',
		category: 19,
		translation: 'daughter',
		asked: false,
		noms: 'filia',
		nomp: 'filiae',
		gens: 'filiae',
		genp: 'filiarum',
		dats: 'filiae',
		datp: 'filiis',
		accs: 'filiam',
		accp: 'filias',
		vocs: 'filia',
		vocp: 'filiae',
		abls: 'filia',
		ablp: 'filiis',
	},
	{
		word: 'filius, filii, m.',
		category: 1,
		translation: 'son',
		asked: false,
		noms: 'filius',
		nomp: 'filii',
		gens: 'filii',
		genp: 'filiorum',
		dats: 'filio',
		datp: 'filiis',
		accs: 'filium',
		accp: 'filios',
		vocs: 'fili',
		vocp: 'filii',
		abls: 'filio',
		ablp: 'filiis',
	},
	{
		word: 'flumen, fluminis, n.',
		category: 24,
		translation: 'river',
		asked: false,
		noms: 'flumen',
		nomp: 'flumina',
		gens: 'fluminis',
		genp: 'fluminum',
		dats: 'flumini',
		datp: 'fluminibus',
		accs: 'flumen',
		accp: 'flumina',
		vocs: 'flumen',
		vocp: 'flumina',
		abls: 'flumine',
		ablp: 'fluminibus',
	},
	{
		word: 'forte (indecl.)',
		category: 19,
		translation: 'by chance',
		asked: false,
	},
	{
		word: 'fortis, forte',
		category: 6,
		translation: 'brave',
		asked: false,
	},
	{
		word: 'forum, fori, n.',
		category: 'other',
		translation: 'forum, market place',
		asked: false,
		noms: 'forum',
		nomp: 'fora',
		gens: 'fori',
		genp: 'fororum',
		dats: 'foro',
		datp: 'foris',
		accs: 'forum',
		accp: 'fora',
		vocs: 'forum',
		vocp: 'fora',
		abls: 'foro',
		ablp: 'foris',
	},
	{
		word: 'frango, frangere, fregi, fractus',
		category: 34,
		translation: 'break',
		asked: false,
	},
	{
		word: 'frater, fratris, m.',
		category: 10,
		translation: 'brother',
		asked: false,
		noms: 'frater',
		nomp: 'fratres',
		gens: 'fratris',
		genp: 'fratrum',
		dats: 'fratri',
		datp: 'fratribus',
		accs: 'fratrem',
		accp: 'fratres',
		vocs: 'frater',
		vocp: 'fratres',
		abls: 'fratre',
		ablp: 'fratribus',
	},
	{
		word: 'frustra (indecl.)',
		category: 12,
		translation: 'in vain',
		asked: false,
	},
	{
		word: 'fugio, fugere, fugi',
		category: 12,
		translation: 'run away, flee',
		asked: false,
	},
	{
		word: 'gero, gerere, gessi, gestus',
		category: 23,
		translation: 'wear (clothes), wage (war)',
		asked: false,
	},
	{
		word: 'gladius, gladii, m.',
		category: 8,
		translation: 'sword',
		asked: false,
		noms: 'gladius',
		nomp: 'gladii',
		gens: 'gladii',
		genp: 'gladiorum',
		dats: 'gladio',
		datp: 'gladiis',
		accs: 'gladium',
		accp: 'gladios',
		vocs: 'gladie',
		vocp: 'gladii',
		abls: 'gladio',
		ablp: 'gladiis',
	},
	{
		word: 'gravis, grave',
		category: 21,
		translation: 'heavy, serious',
		asked: false,
	},
	{
		word: 'habeo, habere, habui, habitus',
		category: 4,
		translation: 'have',
		asked: false,
	},
	{
		word: 'habito, habitare, habitavi, habitatus',
		category: 10,
		translation: 'live',
		asked: false,
	},
	{
		word: 'heri (indecl.)',
		category: 7,
		translation: 'yesterday',
		asked: false,
	},
	{
		word: 'hic (indecl.)',
		category: 33,
		translation: 'here',
		asked: false,
	},
	{
		word: 'hic, haec, hoc',
		category: 8,
		translation: 'this',
		asked: false,
	},
	{
		word: 'hodie (indecl.)',
		category: 5,
		translation: 'today',
		asked: false,
	},
	{
		word: 'homo, hominis, m.',
		category: 9,
		translation: 'man, human being, person',
		asked: false,
		noms: 'homo',
		nomp: 'homines',
		gens: 'hominis',
		genp: 'hominum',
		dats: 'homini',
		datp: 'hominibus',
		accs: 'hominem',
		accp: 'homines',
		vocs: 'homo',
		vocp: 'homines',
		abls: 'homine',
		ablp: 'hominibus',
	},
	{
		word: 'hora, horae, f.',
		category: 21,
		translation: 'hour',
		asked: false,
		noms: 'hora',
		nomp: 'horae',
		gens: 'horae',
		genp: 'horarum',
		dats: 'horae',
		datp: 'horis',
		accs: 'horam',
		accp: 'horas',
		vocs: 'hora',
		vocp: 'horae',
		abls: 'hora',
		ablp: 'horis',
	},
	{
		word: 'hortus, horti, m.',
		category: 1,
		translation: 'garden',
		asked: false,
		noms: 'hortus',
		nomp: 'horti',
		gens: 'horti',
		genp: 'hortorum',
		dats: 'horto',
		datp: 'hortis',
		accs: 'hortum',
		accp: 'hortos',
		vocs: 'horte',
		vocp: 'horti',
		abls: 'horto',
		ablp: 'hortis',
	},
	{
		word: 'hostis, hostis, m.',
		category: 22,
		translation: 'enemy',
		asked: false,
		noms: 'hostis',
		nomp: 'hostes',
		gens: 'hostis',
		genp: 'hostium',
		dats: 'hosti',
		datp: 'hostibus',
		accs: 'hostem',
		accp: 'hostes',
		vocs: 'hostis',
		vocp: 'hostes',
		abls: 'hoste',
		ablp: 'hostibus',
	},
	{
		word: 'iaceo, iacere, iacui',
		category: 12,
		translation: 'lie (positional)',
		asked: false,
	},
	{
		word: 'iacio, iacere, ieci, iactus',
		category: 23,
		translation: 'throw',
		asked: false,
	},
	{
		word: 'iam (indecl.)',
		category: 12,
		translation: 'now, already',
		asked: false,
	},
	{
		word: 'ianua, ianuae, f.',
		category: 3,
		translation: 'door',
		asked: false,
		noms: 'ianua',
		nomp: 'ianuae',
		gens: 'ianuae',
		genp: 'ianuarum',
		dats: 'ianuae',
		datp: 'ianuis',
		accs: 'ianuam',
		accp: 'ianuas',
		vocs: 'ianua',
		vocp: 'ianuae',
		abls: 'ianua',
		ablp: 'ianuis',
	},
	{
		word: 'ibi (indecl.)',
		category: 18,
		translation: 'there',
		asked: false,
	},
	{
		word: 'igitur (indecl.)',
		category: 12,
		translation: 'therefore, and so',
		asked: false,
	},
	{
		word: 'ignis, ignis, m.',
		category: 36,
		translation: 'fire',
		asked: false,
		noms: 'ignis',
		nomp: 'ignes',
		gens: 'ignis',
		genp: 'ignium',
		dats: 'igni',
		datp: 'ignibus',
		accs: 'ignem',
		accp: 'ignes',
		vocs: 'ignis',
		vocp: 'ignes',
		abls: 'igne',
		ablp: 'ignibus',
	},
	{
		word: 'ille, illa, illud',
		category: 9,
		translation: 'that, he, she, it',
		asked: false,
	},
	{
		word: 'imperator, imperatoris, m.',
		category: 16,
		translation: 'emperor, commander, general',
		asked: false,
		noms: 'imperator',
		nomp: 'imperatores',
		gens: 'imperatoris',
		genp: 'imperatorum',
		dats: 'imperatori',
		datp: 'imperatoribus',
		accs: 'imperatorem',
		accp: 'imperatores',
		vocs: 'imperator',
		vocp: 'imperatores',
		abls: 'imperatore',
		ablp: 'imperatoribus',
	},
	{
		word: 'imperium, imperii, n.',
		category: 10,
		translation: 'empire, power, command',
		asked: false,
		noms: 'imperium',
		nomp: 'imperia',
		gens: 'imperii',
		genp: 'imperiorum',
		dats: 'imperio',
		datp: 'imperiis',
		accs: 'imperium',
		accp: 'imperia',
		vocs: 'imperium',
		vocp: 'imperia',
		abls: 'imperio',
		ablp: 'imperiis',
	},
	{
		word: 'impero, imperare, imperavi, imperatus + dat',
		category: 27,
		translation: 'order, command',
		asked: false,
	},
	{
		word: 'in + acc (also used as prefix with verbs)',
		category: 1,
		translation: 'into, onto',
		asked: false,
	},
	{
		word: 'in + abl (also used as prefix with verbs)',
		category: 1,
		translation: 'in, on',
		asked: false,
	},
	{
		word: 'incendo, incendere, incendi, incensus',
		category: 27,
		translation: 'burn, set on fire',
		asked: false,
	},
	{
		word: 'infelix, infelicis',
		category: 21,
		translation: 'unlucky, unhappy',
		asked: false,
	},
	{
		word: 'ingens, ingentis',
		category: 7,
		translation: 'huge',
		asked: false,
	},
	{
		word: 'ingredior, ingredi, ingressus sum',
		category: 34,
		translation: 'enter',
		asked: false,
	},
	{
		word: 'inquit',
		category: 4,
		translation: 'say, said',
		asked: false,
	},
	{
		word: 'insula, insulae, f.',
		category: 17,
		translation: 'island, block of flats',
		asked: false,
		noms: 'insula',
		nomp: 'insulae',
		gens: 'insulae',
		genp: 'insularum',
		dats: 'insulae',
		datp: 'insulis',
		accs: 'insulam',
		accp: 'insulas',
		vocs: 'insula',
		vocp: 'insulae',
		abls: 'insula',
		ablp: 'insulis',
	},
	{
		word: 'intellego, intellegere, intellexi, intellectus',
		category: 7,
		translation: 'understand, realise',
		asked: false,
	},
	{
		word: 'inter + acc',
		category: 16,
		translation: 'among, between',
		asked: false,
	},
	{
		word: 'interea (indecl.)',
		category: 24,
		translation: 'meanwhile',
		asked: false,
	},
	{
		word: 'intro, intrare, intravi, intratus',
		category: 2,
		translation: 'enter',
		asked: false,
	},
	{
		word: 'invenio, invenire, inveni, inventus',
		category: 10,
		translation: 'find',
		asked: false,
	},
	{
		word: 'ira, irae, f.',
		category: 28,
		translation: 'anger',
		asked: false,
		noms: 'ira',
		nomp: 'irae',
		gens: 'irae',
		genp: 'irarum',
		dats: 'irae',
		datp: 'iris',
		accs: 'iram',
		accp: 'iras',
		vocs: 'ira',
		vocp: 'irae',
		abls: 'ira',
		ablp: 'iris',
	},
	{
		word: 'iratus, irata, iratum',
		category: 3,
		translation: 'angry',
		asked: false,
	},
	{
		word: 'is, ea, id',
		category: 8,
		translation: 'this, that, he, she, it, them',
		asked: false,
	},
	{
		word: 'ita (indecl.)',
		category: 16,
		translation: 'in this way, so',
		asked: false,
	},
	{
		word: 'ita vero (indecl.)',
		category: 13,
		translation: 'yes',
		asked: false,
	},
	{
		word: 'itaque (indecl.)',
		category: 17,
		translation: 'and so, therefore',
		asked: false,
	},
	{
		word: 'iter, itineris, n.',
		category: 19,
		translation: 'journey, route, way',
		asked: false,
		noms: 'iter',
		nomp: 'itinera',
		gens: 'itineris',
		genp: 'itinerum',
		dats: 'itineri',
		datp: 'itineribus',
		accs: 'iter',
		accp: 'itinera',
		vocs: 'iter',
		vocp: 'itinera',
		abls: 'itinere',
		ablp: 'itineribus',
	},
	{
		word: 'iterum (indecl.)',
		category: 9,
		translation: 'again',
		asked: false,
	},
	{
		word: 'iubeo, iubere, iussi, iussus',
		category: 21,
		translation: 'order',
		asked: false,
	},
	{
		word: 'iuvenis, iuvenis (m.)',
		category: 5,
		translation: 'young, young man',
		asked: false,
	},
	{
		word: 'labor, laboris, m.',
		category: 'other',
		translation: 'work',
		asked: false,
		noms: 'labor',
		nomp: 'labores',
		gens: 'laboris',
		genp: 'laborum',
		dats: 'labori',
		datp: 'laboribus',
		accs: 'laborem',
		accp: 'labores',
		vocs: 'labor',
		vocp: 'labores',
		abls: 'labore',
		ablp: 'laboribus',
	},
	{
		word: 'laboro, laborare, laboravi',
		category: 1,
		translation: 'work',
		asked: false,
	},
	{
		word: 'lacrimo, lacrimare, lacrimavi',
		category: 7,
		translation: 'weep, cry',
		asked: false,
	},
	{
		word: 'laetus, laeta, laetum',
		category: 2,
		translation: 'happy',
		asked: false,
	},
	{
		word: 'latus, lata, latum',
		category: 'other',
		translation: 'wide',
		asked: false,
	},
	{
		word: 'laudo, laudare, laudavi, laudatus',
		category: 2,
		translation: 'praise',
		asked: false,
	},
	{
		word: 'legatus, legati, m.',
		category: 26,
		translation: 'commander',
		asked: false,
		noms: 'legatus',
		nomp: 'legati',
		gens: 'legati',
		genp: 'legatorum',
		dats: 'legato',
		datp: 'legatis',
		accs: 'legatum',
		accp: 'legatos',
		vocs: 'legate',
		vocp: 'legati',
		abls: 'legato',
		ablp: 'legatis',
	},
	{
		word: 'legio, legionis, f.',
		category: 26,
		translation: 'legion',
		asked: false,
		noms: 'legio',
		nomp: 'legiones',
		gens: 'legionis',
		genp: 'legionum',
		dats: 'legioni',
		datp: 'legionibus',
		accs: 'legionem',
		accp: 'legiones',
		vocs: 'legio',
		vocp: 'legiones',
		abls: 'legione',
		ablp: 'legionibus',
	},
	{
		word: 'lego, legere, legi, lectus',
		category: 11,
		translation: 'read, choose',
		asked: false,
	},
	{
		word: 'lente (indecl.)',
		category: 15,
		translation: 'slowly',
		asked: false,
	},
	{
		word: 'libenter (indecl.)',
		category: 18,
		translation: 'willingly, gladly',
		asked: false,
	},
	{
		word: 'liberi, liberorum, m.pl.',
		category: 29,
		translation: 'children',
		asked: false,
		noms: 'liberus',
		nomp: 'liberi',
		gens: 'liberi',
		genp: 'liberorum',
		dats: 'libero',
		datp: 'liberis',
		accs: 'liberum',
		accp: 'liberos',
		vocs: 'libere',
		vocp: 'liberi',
		abls: 'libero',
		ablp: 'liberis',
	},
	{
		word: 'libero, liberare, liberavi, liberatus',
		category: 20,
		translation: 'free, set free',
		asked: false,
	},
	{
		word: 'libertus, liberti, m.',
		category: 6,
		translation: 'freedman, ex-slave',
		asked: false,
		noms: 'libertus',
		nomp: 'liberti',
		gens: 'liberti',
		genp: 'libertorum',
		dats: 'liberto',
		datp: 'libertis',
		accs: 'libertum',
		accp: 'libertos',
		vocs: 'liberte',
		vocp: 'liberti',
		abls: 'liberto',
		ablp: 'libertis',
	},
	{
		word: 'locus, loci, m.',
		category: 19,
		translation: 'place',
		asked: false,
		noms: 'locus',
		nomp: 'loci',
		gens: 'loci',
		genp: 'locorum',
		dats: 'loco',
		datp: 'locis',
		accs: 'locum',
		accp: 'locos',
		vocs: 'loce',
		vocp: 'loci',
		abls: 'loco',
		ablp: 'locis',
	},
	{
		word: 'longus, longa, longum',
		category: 'other',
		translation: 'long',
		asked: false,
	},
	{
		word: 'loquor, loqui, locutus sum',
		category: 34,
		translation: 'speak',
		asked: false,
	},
	{
		word: 'lux, lucis, f.',
		category: 'other',
		translation: 'light, daylight',
		asked: false,
		noms: 'lux',
		nomp: 'luces',
		gens: 'lucis',
		genp: 'lucum',
		dats: 'luci',
		datp: 'lucibus',
		accs: 'lucem',
		accp: 'luces',
		vocs: 'lux',
		vocp: 'luces',
		abls: 'luce',
		ablp: 'lucibus',
	},
	{
		word: 'magnopere (indecl.)',
		category: 30,
		translation: 'greatly, very much',
		asked: false,
	},
	{
		word: 'magnus, magna, magnum',
		category: 3,
		translation: 'big, large, great',
		asked: false,
	},
	{
		word: 'maior, maius (irregular comparative)',
		category: 'other',
		translation: 'bigger, larger, greater',
		asked: false,
	},
	{
		word: 'malus, mala, malum',
		category: 28,
		translation: 'evil, bad',
		asked: false,
	},
	{
		word: 'maneo, manere, mansi',
		category: 9,
		translation: 'remain, stay',
		asked: false,
	},
	{
		word: 'manus, manus, f.',
		category: 18,
		translation: 'hand, group of people',
		asked: false,
		noms: 'manus',
		nomp: 'manus',
		gens: 'manus',
		genp: 'manuum',
		dats: 'manui',
		datp: 'manibus',
		accs: 'manum',
		accp: 'manus',
		vocs: 'manus',
		vocp: 'manus',
		abls: 'manu',
		ablp: 'manibus',
	},
	{
		word: 'mare, maris, n.',
		category: 15,
		translation: 'sea',
		asked: false,
		noms: 'mare',
		nomp: 'maria',
		gens: 'maris',
		genp: 'marium',
		dats: 'mari',
		datp: 'maribus',
		accs: 'mare',
		accp: 'maria',
		vocs: 'mare',
		vocp: 'maria',
		abls: 'mari',
		ablp: 'maribus',
	},
	{
		word: 'maritus, mariti, m.',
		category: 14,
		translation: 'husband',
		asked: false,
		noms: 'maritus',
		nomp: 'mariti',
		gens: 'mariti',
		genp: 'maritorum',
		dats: 'marito',
		datp: 'maritis',
		accs: 'maritum',
		accp: 'maritos',
		vocs: 'marite',
		vocp: 'mariti',
		abls: 'marito',
		ablp: 'maritis',
	},
	{
		word: 'mater, matris, f.',
		category: 1,
		translation: 'mother',
		asked: false,
		noms: 'mater',
		nomp: 'matres',
		gens: 'matris',
		genp: 'matrium',
		dats: 'matri',
		datp: 'matribus',
		accs: 'matrem',
		accp: 'matres',
		vocs: 'mater',
		vocp: 'matres',
		abls: 'matre',
		ablp: 'matribus',
	},
	{
		word: 'maximus, maxima, maximum',
		category: 17,
		translation: 'the biggest, the greatest, very big, very great',
		asked: false,
	},
	{
		word: 'medius, media, medium',
		category: 9,
		translation: 'middle, middle of',
		asked: false,
		noms: 'medium',
		nomp: 'media',
		gens: 'medii',
		genp: 'mediorum',
		dats: 'medio',
		datp: 'mediis',
		accs: 'medium',
		accp: 'media',
		vocs: 'medium',
		vocp: 'media',
		abls: 'medio',
		ablp: 'mediis',
	},
	{
		word: 'melior, melius (irregular comparative)',
		category: 16,
		translation: 'better',
		asked: false,
	},
	{
		word: 'meus, mea, meum',
		category: 5,
		translation: 'my',
		asked: false,
	},
	{
		word: 'miles, militis, m.',
		category: 18,
		translation: 'soldier',
		asked: false,
		noms: 'miles',
		nomp: 'milites',
		gens: 'militis',
		genp: 'militum',
		dats: 'militi',
		datp: 'militibus',
		accs: 'militem',
		accp: 'milites',
		vocs: 'miles',
		vocp: 'milites',
		abls: 'milite',
		ablp: 'militibus',
	},
	{
		word: 'mille, pl. milia',
		category: 28,
		translation: 'thousand',
		asked: false,
	},
	{
		word: 'minime (indecl.)',
		category: 11,
		translation: 'very little, least, no',
		asked: false,
	},
	{
		word: 'minimus, minima, minimum',
		category: 22,
		translation: 'very little, very small',
		asked: false,
	},
	{
		word: 'minor, minus (irregular comparative)',
		category: 'other',
		translation: 'smaller, less',
		asked: false,
	},
	{
		word: 'miser, misera, miserum',
		category: 15,
		translation: 'miserable, wretched, sad',
		asked: false,
	},
	{
		word: 'mitto, mittere, misi, missus',
		category: 12,
		translation: 'send',
		asked: false,
	},
	{
		word: 'modus, modi, m.',
		category: 23,
		translation: 'manner, way, kind',
		asked: false,
		noms: 'modus',
		nomp: 'modi',
		gens: 'modi',
		genp: 'modorum',
		dats: 'modo',
		datp: 'modis',
		accs: 'modum',
		accp: 'modos',
		vocs: 'mode',
		vocp: 'modi',
		abls: 'modo',
		ablp: 'modis',
	},
	{
		word: 'mons, montis, m.',
		category: 12,
		translation: 'mountain',
		asked: false,
		noms: 'mons',
		nomp: 'montes',
		gens: 'montis',
		genp: 'montium',
		dats: 'monti',
		datp: 'montibus',
		accs: 'montem',
		accp: 'montes',
		vocs: 'mons',
		vocp: 'montes',
		abls: 'monte',
		ablp: 'montibus',
	},
	{
		word: 'morior, mori, mortuus sum',
		category: 34,
		translation: 'die',
		asked: false,
		noms: 'mos',
		nomp: 'mores',
		gens: 'moris',
		genp: 'morum',
		dats: 'mori',
		datp: 'moribus',
		accs: 'morem',
		accp: 'mores',
		vocs: 'mos',
		vocp: 'mores',
		abls: 'more',
		ablp: 'moribus',
	},
	{
		word: 'mors, mortis, f.',
		category: 20,
		translation: 'death',
		asked: false,
		noms: 'mors',
		nomp: 'mortes',
		gens: 'mortis',
		genp: 'mortum',
		dats: 'morti',
		datp: 'mortibus',
		accs: 'mortem',
		accp: 'mortes',
		vocs: 'mors',
		vocp: 'mortes',
		abls: 'morte',
		ablp: 'mortibus',
	},
	{
		word: 'mox (indecl.)',
		category: 9,
		translation: 'soon',
		asked: false,
	},
	{
		word: 'multo, multum (indecl.)',
		category: 'other',
		translation: 'much',
		asked: false,
	},
	{
		word: 'multus, multa, multum',
		category: 5,
		translation: 'much, many',
		asked: false,
		noms: 'multa',
		nomp: 'multae',
		gens: 'multae',
		genp: 'multarum',
		dats: 'multae',
		datp: 'multis',
		accs: 'multam',
		accp: 'multas',
		vocs: 'multa',
		vocp: 'multae',
		abls: 'multa',
		ablp: 'multis',
	},
	{
		word: 'murus, muri, m.',
		category: 11,
		translation: 'wall',
		asked: false,
		noms: 'murus',
		nomp: 'muri',
		gens: 'muri',
		genp: 'murorum',
		dats: 'muro',
		datp: 'muris',
		accs: 'murum',
		accp: 'muros',
		vocs: 'mure',
		vocp: 'muri',
		abls: 'muro',
		ablp: 'muris',
	},
	{
		word: 'nam (indecl.)',
		category: 18,
		translation: 'for',
		asked: false,
	},
	{
		word: 'narro, narrare, narravi, narratus',
		category: 7,
		translation: 'tell, relate',
		asked: false,
	},
	{
		word: 'nauta, nautae, m.',
		category: 15,
		translation: 'sailor',
		asked: false,
		noms: 'nauta',
		nomp: 'nautae',
		gens: 'nautae',
		genp: 'nautarum',
		dats: 'nautae',
		datp: 'nautis',
		accs: 'nautam',
		accp: 'nautas',
		vocs: 'nauta',
		vocp: 'nautae',
		abls: 'nauta',
		ablp: 'nautis',
	},
	{
		word: 'navigo, navigare, navigavi',
		category: 16,
		translation: 'sail',
		asked: false,
	},
	{
		word: 'navis, navis, f.',
		category: 3,
		translation: 'ship',
		asked: false,
		noms: 'navis',
		nomp: 'naves',
		gens: 'navis',
		genp: 'navium',
		dats: 'navi',
		datp: 'navibus',
		accs: 'navem',
		accp: 'naves',
		vocs: 'navis',
		vocp: 'naves',
		abls: 'nave',
		ablp: 'navibus',
	},
	{
		word: 'ne (indecl.)',
		category: 31,
		translation: 'that...not, so that...not, that not',
		asked: false,
	},
	{
		word: '-ne (indecl.)',
		category: 'other',
		translation: 'introduces question',
		asked: false,
	},
	{
		word: 'nec ... nec, neque ... neque (indecl.)',
		category: 'other',
		translation: 'neither, nor, neither...nor,',
		asked: false,
	},
	{
		word: 'necesse (indecl.)',
		category: 14,
		translation: 'necessary',
		asked: false,
	},
	{
		word: 'neco, necare, necavi, necatus',
		category: 7,
		translation: 'kill',
		asked: false,
	},
	{
		word: 'nemo, neminis',
		category: 18,
		translation: 'no one, nobody',
		asked: false,
		noms: 'nemo',
		nomp: 'nemines',
		gens: 'neminis',
		genp: 'neminum',
		dats: 'nemini',
		datp: 'neminibus',
		accs: 'neminem',
		accp: 'nemines',
		vocs: 'nemo',
		vocp: 'nemines',
		abls: 'nemine',
		ablp: 'neminibus',
	},
	{
		word: 'nescio, nescire, nescivi',
		category: 25,
		translation: 'not know',
		asked: false,
	},
	{
		word: 'nihil (indecl.)',
		category: 7,
		translation: 'nothing',
		asked: false,
	},
	{
		word: 'nolo, nolle, nolui',
		category: 13,
		translation: 'not want',
		asked: false,
	},
	{
		word: 'nomen, nominis, n.',
		category: 25,
		translation: 'name',
		asked: false,
	},
	{
		word: 'non (indecl.)',
		category: 3,
		translation: 'not',
		asked: false,
	},
	{
		word: 'nonne? (indecl.)',
		category: 16,
		translation: 'surely?',
		asked: false,
	},
	{
		word: 'nos, nostrum',
		category: 10,
		translation: 'we, us',
		asked: false,
	},
	{
		word: 'noster, nostra, nostrum',
		category: 11,
		translation: 'our',
		asked: false,
	},
	{
		word: 'novem (indecl.)',
		category: 20,
		translation: 'nine',
		asked: false,
	},
	{
		word: 'novus, nova, novum',
		category: 13,
		translation: 'new',
		asked: false,
	},
	{
		word: 'nox, noctis, f.',
		category: 22,
		translation: 'night',
		asked: false,
		noms: 'nox',
		nomp: 'noctes',
		gens: 'noctis',
		genp: 'noctium',
		dats: 'nocti',
		datp: 'noctibus',
		accs: 'noctem',
		accp: 'noctes',
		vocs: 'nox',
		vocp: 'noctes',
		abls: 'nocte',
		ablp: 'noctibus',
	},
	{
		word: 'nullus, nulla, nullum',
		category: 13,
		translation: 'not any, no',
		asked: false,
	},
	{
		word: 'num (indecl.)',
		category: 26,
		translation: 'whether',
		asked: false,
	},
	{
		word: 'num ... ? (indecl.)',
		category: 14,
		translation: 'surely not?',
		asked: false,
	},
	{
		word: 'numquam (indecl.)',
		category: 17,
		translation: 'never',
		asked: false,
	},
	{
		word: 'nunc (indecl.)',
		category: 11,
		translation: 'now',
		asked: false,
	},
	{
		word: 'nuntio, nuntiare, nuntiavi, nuntiatus',
		category: 10,
		translation: 'announce, report',
		asked: false,
	},
	{
		word: 'nuntius, nuntii, m.',
		category: 8,
		translation: 'messenger, message, news',
		asked: false,
		noms: 'nuntius',
		nomp: 'nuntii',
		gens: 'nuntii',
		genp: 'nuntiorum',
		dats: 'nuntio',
		datp: 'nuntiis',
		accs: 'nuntium',
		accp: 'nuntios',
		vocs: 'nunti',
		vocp: 'nuntii',
		abls: 'nuntio',
		ablp: 'nuntiis',
	},
	{
		word: 'occido, occidere, occidi, occisus',
		category: 28,
		translation: 'kill',
		asked: false,
	},
	{
		word: 'octo (indecl.)',
		category: 20,
		translation: 'eight',
		asked: false,
	},
	{
		word: 'offero, offerre, obtuli, oblatus',
		category: 9,
		translation: 'offer',
		asked: false,
	},
	{
		word: 'olim (indecl.)',
		category: 6,
		translation: 'once, some time ago',
		asked: false,
	},
	{
		word: 'omnis, omne',
		category: 7,
		translation: 'all, every',
		asked: false,
		noms: 'omne',
		nomp: 'omnes',
		gens: 'omnis',
		genp: 'omnium',
		dats: 'omni',
		datp: 'omnibus',
		accs: 'omne',
		accp: 'omnes',
		vocs: 'omne',
		vocp: 'omnes',
		abls: 'omne',
		ablp: 'omnibus',
	},
	{
		word: 'oppugno, oppugnare, oppugnavi, oppugnatus',
		category: 24,
		translation: 'attack',
		asked: false,
	},
	{
		word: 'optimus, optima, optimum',
		category: 5,
		translation: 'the best, very good, excellent',
		asked: false,
	},
	{
		word: 'oro, orare, oravi, oratus',
		category: 'other',
		translation: 'beg, beg for',
		asked: false,
	},
	{
		word: 'ostendo, ostendere, ostendi, ostentus',
		category: 9,
		translation: 'show',
		asked: false,
	},
	{
		word: 'paene (indecl.)',
		category: 12,
		translation: 'almost, nearly',
		asked: false,
	},
	{
		word: 'pareo, parere, parui + dat',
		category: 23,
		translation: 'obey',
		asked: false,
	},
	{
		word: 'paro, parare, paravi, paratus',
		category: 7,
		translation: 'prepare',
		asked: false,
	},
	{
		word: 'pars, partis, f.',
		category: 18,
		translation: 'part',
		asked: false,
		noms: 'pars',
		nomp: 'partes',
		gens: 'partis',
		genp: 'partium',
		dats: 'parti',
		datp: 'partibus',
		accs: 'partem',
		accp: 'partes',
		vocs: 'pars',
		vocp: 'partes',
		abls: 'parte',
		ablp: 'partibus',
	},
	{
		word: 'parvus, parva, parvum',
		category: 6,
		translation: 'small',
		asked: false,
	},
	{
		word: 'pater, patris, m.',
		category: 1,
		translation: 'father',
		asked: false,
		noms: 'pater',
		nomp: 'patres',
		gens: 'patris',
		genp: 'patrum',
		dats: 'patri',
		datp: 'patribus',
		accs: 'patrem',
		accp: 'patres',
		vocs: 'pater',
		vocp: 'patres',
		abls: 'patre',
		ablp: 'patribus',
	},
	{
		word: 'pauci, paucae, pauca',
		category: 17,
		translation: 'few, a few',
		asked: false,
	},
	{
		word: 'pax, pacis, f.',
		category: 10,
		translation: 'peace',
		asked: false,
		noms: 'pax',
		nomp: 'paces',
		gens: 'pacis',
		genp: 'pacum',
		dats: 'paci',
		datp: 'pacibus',
		accs: 'pacem',
		accp: 'paces',
		vocs: 'pax',
		vocp: 'paces',
		abls: 'pace',
		ablp: 'pacibus',
	},
	{
		word: 'pecunia, pecuniae, f.',
		category: 4,
		translation: 'money',
		asked: false,
		noms: 'pecunia',
		nomp: 'pecuniae',
		gens: 'pecuniae',
		genp: 'pecuniarum',
		dats: 'pecuniae',
		datp: 'pecuniis',
		accs: 'pecuniam',
		accp: 'pecunias',
		vocs: 'pecunia',
		vocp: 'pecuniae',
		abls: 'pecunia',
		ablp: 'pecuniis',
	},
	{
		word: 'peior, peius (irregular comparative)',
		category: 'other',
		translation: 'worse',
		asked: false,
	},
	{
		word: 'per + acc (also used as prefix with verbs)',
		category: 6,
		translation: 'through, along',
		asked: false,
	},
	{
		word: 'pereo, perire, perii',
		category: 16,
		translation: 'die, perish',
		asked: false,
	},
	{
		word: 'periculum, periculi, n.',
		category: 19,
		translation: 'danger',
		asked: false,
		noms: 'periculum',
		nomp: 'pericula',
		gens: 'periculi',
		genp: 'periculorum',
		dats: 'periculo',
		datp: 'periculis',
		accs: 'periculum',
		accp: 'pericula',
		vocs: 'periculum',
		vocp: 'pericula',
		abls: 'periculo',
		ablp: 'periculis',
	},
	{
		word: 'persuadeo, persuadere, persuasi + dat',
		category: 20,
		translation: 'persuade',
		asked: false,
	},
	{
		word: 'perterritus, perterrita, perterritum',
		category: 4,
		translation: 'terrified',
		asked: false,
	},
	{
		word: 'pes, pedis, m.',
		category: 8,
		translation: 'foot, paw',
		asked: false,
		noms: 'pedum',
		nomp: 'peda',
		gens: 'pedi',
		genp: 'pedorum',
		dats: 'pedo',
		datp: 'pedis',
		accs: 'pedum',
		accp: 'peda',
		vocs: 'pedum',
		vocp: 'peda',
		abls: 'pedo',
		ablp: 'pedis',
	},
	{
		word: 'pessimus, pessima, pessimum',
		category: 20,
		translation: 'the worst, very bad',
		asked: false,
	},
	{
		word: 'peto, petere, petivi, petitus',
		category: 5,
		translation: 'make for, attack, seek, beg, ask for',
		asked: false,
	},
	{
		word: 'placeo, placere, placui + dat',
		category: 11,
		translation: 'please',
		asked: false,
	},
	{
		word: 'plenus, plena, plenum',
		category: 21,
		translation: 'full',
		asked: false,
	},
	{
		word: 'plus, pluris (irregular comparative)',
		category: 21,
		translation: 'more',
		asked: false,
	},
	{
		word: 'poena, poenae, f.',
		category: 25,
		translation: 'punishment',
		asked: false,
		noms: 'poena',
		nomp: 'poenae',
		gens: 'poenae',
		genp: 'poenarum',
		dats: 'poenae',
		datp: 'poenis',
		accs: 'poenam',
		accp: 'poenas',
		vocs: 'poena',
		vocp: 'poenae',
		abls: 'poena',
		ablp: 'poenis',
	},
	{
		word: 'poenas do, dare, dedi, datus',
		category: 25,
		translation: 'pay the penalty, be punished',
		asked: false,
	},
	{
		word: 'pono, ponere, posui, positus',
		category: 16,
		translation: 'put, place, put up',
		asked: false,
	},
	{
		word: 'porta, portae, f.',
		category: 8,
		translation: 'gate',
		asked: false,
		noms: 'porta',
		nomp: 'portae',
		gens: 'portae',
		genp: 'portarum',
		dats: 'portae',
		datp: 'portis',
		accs: 'portam',
		accp: 'portas',
		vocs: 'porta',
		vocp: 'portae',
		abls: 'porta',
		ablp: 'portis',
	},
	{
		word: 'porto, portare, portavi, portatus',
		category: 3,
		translation: 'carry',
		asked: false,
	},
	{
		word: 'possum, posse',
		category: 13,
		translation: 'can, be able',
		asked: false,
	},
	{
		word: 'post + acc',
		category: 9,
		translation: 'after, behind',
		asked: false,
	},
	{
		word: 'postea (indecl.)',
		category: 18,
		translation: 'afterwards',
		asked: false,
	},
	{
		word: 'postquam (indecl.)',
		category: 6,
		translation: 'after, when',
		asked: false,
	},
	{
		word: 'postridie (indecl.)',
		category: 16,
		translation: 'on the next day',
		asked: false,
	},
	{
		word: 'postulo, postulare, postulavi, postulatus',
		category: 8,
		translation: 'demand',
		asked: false,
	},
	{
		word: 'praebeo, praebere, praebui, praebitus',
		category: 26,
		translation: 'provide',
		asked: false,
	},
	{
		word: 'praemium, praemii, n.',
		category: 27,
		translation: 'prize, reward, profit',
		asked: false,
		noms: 'praemium',
		nomp: 'praemia',
		gens: 'praemii',
		genp: 'praemiorum',
		dats: 'praemio',
		datp: 'praemiis',
		accs: 'praemium',
		accp: 'praemia',
		vocs: 'praemium',
		vocp: 'praemia',
		abls: 'praemio',
		ablp: 'praemiis',
	},
	{
		word: 'primus, prima, primum',
		category: 11,
		translation: 'first',
		asked: false,
	},
	{
		word: 'princeps, principis, m.',
		category: 15,
		translation: 'chief, chieftain, emperor',
		asked: false,
		noms: 'princeps',
		nomp: 'principes',
		gens: 'principis',
		genp: 'principum',
		dats: 'principi',
		datp: 'principibus',
		accs: 'principem',
		accp: 'principes',
		vocs: 'princeps',
		vocp: 'principes',
		abls: 'principe',
		ablp: 'principibus',
	},
	{
		word: 'pro + abl (also used as prefix with verbs)',
		category: 18,
		translation: 'in front of, for, in return for (as prefix = forwards)',
		asked: false,
	},
	{
		word: 'procedo, procedere, processi',
		category: 9,
		translation: 'advance, proceed',
		asked: false,
	},
	{
		word: 'progredior, progredi, progressus sum',
		category: 34,
		translation: 'advance',
		asked: false,
	},
	{
		word: 'promitto, promittere, promisi, promissus',
		category: 11,
		translation: 'promise',
		asked: false,
	},
	{
		word: 'prope + acc',
		category: 7,
		translation: 'near',
		asked: false,
	},
	{
		word: 'propter + acc',
		category: 'other',
		translation: 'because of',
		asked: false,
	},
	{
		word: 'proximus, proxima, proximum',
		category: 27,
		translation: 'nearest, next to',
		asked: false,
	},
	{
		word: 'puella, puellae, f.',
		category: 5,
		translation: 'girl',
		asked: false,
		noms: 'puella',
		nomp: 'puellae',
		gens: 'puellae',
		genp: 'puellarum',
		dats: 'puellae',
		datp: 'puellis',
		accs: 'puellam',
		accp: 'puellas',
		vocs: 'puella',
		vocp: 'puellae',
		abls: 'puella',
		ablp: 'puellis',
	},
	{
		word: 'puer, pueri, m.',
		category: 8,
		translation: 'boy',
		asked: false,
		noms: 'puer',
		nomp: 'pueri',
		gens: 'pueri',
		genp: 'puerorum',
		dats: 'puero',
		datp: 'pueris',
		accs: 'puerum',
		accp: 'pueros',
		vocs: 'puer',
		vocp: 'pueri',
		abls: 'puero',
		ablp: 'pueris',
	},
	{
		word: 'pugno, pugnare, pugnavi',
		category: 8,
		translation: 'fight',
		asked: false,
	},
	{
		word: 'pulcher, pulchra, pulchrum',
		category: 9,
		translation: 'beautiful, handsome',
		asked: false,
	},
	{
		word: 'puto, putare, putavi, putatus',
		category: 'other',
		translation: 'think',
		asked: false,
	},
	{
		word: 'quaero, quaerere, quaesivi, quaesitus',
		category: 4,
		translation: 'search for, look for, ask',
		asked: false,
	},
	{
		word: 'qualis, quale?',
		category: 27,
		translation: 'what sort of?',
		asked: false,
	},
	{
		word: 'quam (indecl.)',
		category: 10,
		translation: 'than, how ... ? how ... !',
		asked: false,
	},
	{
		word: 'quamquam (indecl.)',
		category: 14,
		translation: 'although',
		asked: false,
	},
	{
		word: 'quantus, quanta, quantum?',
		category: 22,
		translation: 'how big? how much?',
		asked: false,
	},
	{
		word: 'quattuor (indecl.)',
		category: 20,
		translation: 'four',
		asked: false,
	},
	{
		word: '-que (indecl.) (added to end of a word)',
		category: 14,
		translation: 'and',
		asked: false,
	},
	{
		word: 'qui, quae, quod',
		category: 15,
		translation: 'who, which',
		asked: false,
	},
	{
		word: 'quinque (indecl.)',
		category: 20,
		translation: 'five',
		asked: false,
	},
	{
		word: 'quis, quid?',
		category: 4,
		translation: 'who? what?',
		asked: false,
	},
	{
		word: 'quo? (indecl.)',
		category: 18,
		translation: 'where to?',
		asked: false,
	},
	{
		word: 'quod (indecl.)',
		category: 6,
		translation: 'because',
		asked: false,
	},
	{
		word: 'quo modo? (indecl.)',
		category: 22,
		translation: 'how? in what way?',
		asked: false,
	},
	{
		word: 'quoque (indecl.)',
		category: 2,
		translation: 'also, too',
		asked: false,
	},
	{
		word: 'quot? (indecl.)',
		category: 26,
		translation: 'how many?',
		asked: false,
	},
	{
		word: 'rapio, rapere, rapui, raptus',
		category: 'other',
		translation: 'seize, grab',
		asked: false,
	},
	{
		word: 're- (prefix used with verbs)',
		category: 'other',
		translation: 'back',
		asked: false,
	},
	{
		word: 'reddo, reddere, reddidi, redditus',
		category: 4,
		translation: 'give back, restore',
		asked: false,
	},
	{
		word: 'redeo, redire, redii',
		category: 15,
		translation: 'go back, come back, return',
		asked: false,
	},
	{
		word: 'refero, referre, rettuli, relatus',
		category: 26,
		translation: 'bring, carry back, report, tell',
		asked: false,
	},
	{
		word: 'regina, reginae, f.',
		category: 33,
		translation: 'queen',
		asked: false,
		noms: 'regina',
		nomp: 'reginae',
		gens: 'reginae',
		genp: 'reginarum',
		dats: 'reginae',
		datp: 'reginis',
		accs: 'reginam',
		accp: 'reginas',
		vocs: 'regina',
		vocp: 'reginae',
		abls: 'regina',
		ablp: 'reginis',
	},
	{
		word: 'regredior, regredi, regressus sum',
		category: 34,
		translation: 'go back, return',
		asked: false,
	},
	{
		word: 'relinquo, relinquere, reliqui, relictus',
		category: 20,
		translation: 'leave, leave behind',
		asked: false,
	},
	{
		word: 'res, rei, f.',
		category: 6,
		translation: 'thing, business, matter',
		asked: false,
		noms: 'res',
		nomp: 'res',
		gens: 'rei',
		genp: 'rerum',
		dats: 'rei',
		datp: 'rebus',
		accs: 'rem',
		accp: 'res',
		vocs: 'res',
		vocp: 'res',
		abls: 're',
		ablp: 'rebus',
	},
	{
		word: 'resisto, resistere, restiti + dat',
		category: 17,
		translation: 'resist',
		asked: false,
	},
	{
		word: 'respondeo, respondere, respondi, responsus',
		category: 3,
		translation: 'reply',
		asked: false,
	},
	{
		word: 'rex, regis, m.',
		category: 14,
		translation: 'king',
		asked: false,
		noms: 'rex',
		nomp: 'reges',
		gens: 'regis',
		genp: 'regum',
		dats: 'regi',
		datp: 'regibus',
		accs: 'regem',
		accp: 'reges',
		vocs: 'rex',
		vocp: 'reges',
		abls: 'rege',
		ablp: 'regibus',
	},
	{
		word: 'rideo, ridere, risi',
		category: 3,
		translation: 'laugh, smile',
		asked: false,
	},
	{
		word: 'rogo, rogare, rogavi, rogatus',
		category: 7,
		translation: 'ask, ask for',
		asked: false,
	},
	{
		word: 'Roma, Romae, f.',
		category: 'other',
		translation: 'Rome',
		asked: false,
	},
	{
		word: 'Romae',
		category: 'other',
		translation: 'at/in Rome',
		asked: false,
	},
	{
		word: 'Romanus, Romana, Romanum',
		category: 'other',
		translation: 'Roman',
		asked: false,
		noms: 'romana',
		nomp: 'romanae',
		gens: 'romanae',
		genp: 'romanarum',
		dats: 'romanae',
		datp: 'romanis',
		accs: 'romanam',
		accp: 'romanas',
		vocs: 'romana',
		vocp: 'romanae',
		abls: 'romana',
		ablp: 'romanis',
	},
	{
		word: 'sacer, sacra, sacrum',
		category: 21,
		translation: 'sacred',
		asked: false,
	},
	{
		word: 'saepe (indecl.)',
		category: 8,
		translation: 'often',
		asked: false,
	},
	{
		word: 'saevus, saeva, saevum',
		category: 26,
		translation: 'savage, cruel',
		asked: false,
	},
	{
		word: 'saluto, salutare, salutavi, salutatus',
		category: 2,
		translation: 'greet',
		asked: false,
	},
	{
		word: 'sanguis, sanguinis, m.',
		category: 8,
		translation: 'blood',
		asked: false,
		noms: 'sanguis',
		nomp: 'sanguines',
		gens: 'sanguinis',
		genp: 'sanguinum',
		dats: 'sanguini',
		datp: 'sanguinibus',
		accs: 'sanguinem',
		accp: 'sanguines',
		vocs: 'sanguis',
		vocp: 'sanguines',
		abls: 'sanguine',
		ablp: 'sanguinibus',
	},
	{
		word: 'scio, scire, scivi, scitus',
		category: 23,
		translation: 'know',
		asked: false,
	},
	{
		word: 'scribo, scribere, scripsi, scriptus',
		category: 6,
		translation: 'write',
		asked: false,
	},
	{
		word: 'se, sui',
		category: 13,
		translation: 'himself, herself, itself, themselves',
		asked: false,
	},
	{
		word: 'sed (indecl.)',
		category: 4,
		translation: 'but',
		asked: false,
	},
	{
		word: 'sedeo, sedere, sedi',
		category: 1,
		translation: 'sit',
		asked: false,
	},
	{
		word: 'semper (indecl.)',
		category: 10,
		translation: 'always',
		asked: false,
	},
	{
		word: 'senator, senatoris, m.',
		category: 11,
		translation: 'senator',
		asked: false,
		noms: 'senator',
		nomp: 'senatores',
		gens: 'senatoris',
		genp: 'senatorum',
		dats: 'senatori',
		datp: 'senatoribus',
		accs: 'senatorem',
		accp: 'senatores',
		vocs: 'senator',
		vocp: 'senatores',
		abls: 'senatore',
		ablp: 'senatoribus',
	},
	{
		word: 'senex, senis (m.)',
		category: 5,
		translation: 'old, old man',
		asked: false,
	},
	{
		word: 'sentio, sentire, sensi, sensus',
		category: 12,
		translation: 'feel, notice',
		asked: false,
	},
	{
		word: 'septem (indecl.)',
		category: 20,
		translation: 'seven',
		asked: false,
	},
	{
		word: 'sequor, sequi, secutus sum',
		category: 34,
		translation: 'follow',
		asked: false,
	},
	{
		word: 'servo, servare, servavi, servatus',
		category: 10,
		translation: 'save, look after',
		asked: false,
	},
	{
		word: 'servus, servi, m.',
		category: 1,
		translation: 'slave',
		asked: false,
		noms: 'servus',
		nomp: 'servi',
		gens: 'servi',
		genp: 'servorum',
		dats: 'servo',
		datp: 'servis',
		accs: 'servum',
		accp: 'servos',
		vocs: 'serve',
		vocp: 'servi',
		abls: 'servo',
		ablp: 'servis',
	},
	{
		word: 'sex (indecl.)',
		category: 20,
		translation: 'six',
		asked: false,
	},
	{
		word: 'si (indecl.)',
		category: 26,
		translation: 'if',
		asked: false,
	},
	{
		word: 'sic (indecl.)',
		category: 28,
		translation: 'thus, in this way',
		asked: false,
	},
	{
		word: 'sicut (indecl.)',
		category: 20,
		translation: 'just as, like',
		asked: false,
	},
	{
		word: 'signum, signi, n.',
		category: 4,
		translation: 'sign, signal, seal',
		asked: false,
		noms: 'signum',
		nomp: 'signa',
		gens: 'signi',
		genp: 'signorum',
		dats: 'signo',
		datp: 'signis',
		accs: 'signum',
		accp: 'signa',
		vocs: 'signum',
		vocp: 'signa',
		abls: 'signo',
		ablp: 'signis',
	},
	{
		word: 'silva, silvae, f.',
		category: 8,
		translation: 'wood',
		asked: false,
		noms: 'silva',
		nomp: 'silvae',
		gens: 'silvae',
		genp: 'silvarum',
		dats: 'silvae',
		datp: 'silvis',
		accs: 'silvam',
		accp: 'silvas',
		vocs: 'silva',
		vocp: 'silvae',
		abls: 'silvÄ',
		ablp: 'silvis',
	},
	{
		word: 'simulac, simulatque',
		category: 16,
		translation: 'as soon as',
		asked: false,
	},
	{
		word: 'sine + abl',
		category: 'other',
		translation: 'without',
		asked: false,
	},
	{
		word: 'solus, sola, solum',
		category: 10,
		translation: 'alone, lonely, only, on oneâ€™s own',
		asked: false,
		noms: 'solum',
		nomp: 'sola',
		gens: 'soli',
		genp: 'solorum',
		dats: 'solo',
		datp: 'solis',
		accs: 'solum',
		accp: 'sola',
		vocs: 'solum',
		vocp: 'sola',
		abls: 'solo',
		ablp: 'solis',
	},
	{
		word: 'soror, sororis, f.',
		category: 30,
		translation: 'sister',
		asked: false,
		noms: 'soror',
		nomp: 'sorores',
		gens: 'sororis',
		genp: 'sororum',
		dats: 'sorori',
		datp: 'sororibus',
		accs: 'sororem',
		accp: 'sorores',
		vocs: 'soror',
		vocp: 'sorores',
		abls: 'sorore',
		ablp: 'sororibus',
	},
	{
		word: 'specto, spectare, spectavi, spectatus',
		category: 5,
		translation: 'look at, watch',
		asked: false,
	},
	{
		word: 'spes, spei, f.',
		category: 28,
		translation: 'hope',
		asked: false,
		noms: 'spes',
		nomp: 'spes',
		gens: 'spei',
		genp: 'sperum',
		dats: 'spei',
		datp: 'spebus',
		accs: 'spem',
		accp: 'spes',
		vocs: 'spes',
		vocp: 'spes',
		abls: 'spe',
		ablp: 'spebus',
	},
	{
		word: 'statim (indecl.)',
		category: 8,
		translation: 'at once, immediately',
		asked: false,
	},
	{
		word: 'sto, stare, steti',
		category: 5,
		translation: 'stand',
		asked: false,
	},
	{
		word: 'stultus, stulta, stultum',
		category: 11,
		translation: 'stupid, foolish',
		asked: false,
	},
	{
		word: 'sub + acc/abl (also used as prefix with verbs)',
		category: 27,
		translation: 'under, beneath (as prefix = under, up to)',
		asked: false,
	},
	{
		word: 'subito (indecl.)',
		category: 6,
		translation: 'suddenly',
		asked: false,
	},
	{
		word: 'sum, esse, fui',
		category: 1,
		translation: 'be',
		asked: false,
	},
	{
		word: 'summus, summa, summum',
		category: 16,
		translation: 'highest, greatest, top (of)',
		asked: false,
	},
	{
		word: 'supero, superare, superavi, superatus',
		category: 6,
		translation: 'overcome, overpower',
		asked: false,
	},
	{
		word: 'surgo, surgere, surrexi',
		category: 3,
		translation: 'get up, stand up, rise',
		asked: false,
	},
	{
		word: 'suus, sua, suum',
		category: 10,
		translation: 'his, her, its, their (own)',
		asked: false,
		noms: 'suum',
		nomp: 'sua',
		gens: 'sui',
		genp: 'suorum',
		dats: 'suo',
		datp: 'suis',
		accs: 'suum',
		accp: 'sua',
		vocs: 'suum',
		vocp: 'sua',
		abls: 'suo',
		ablp: 'suis',
	},
	{
		word: 'taberna, tabernae, f.',
		category: 3,
		translation: 'shop, inn',
		asked: false,
		noms: 'taberna',
		nomp: 'tabernae',
		gens: 'tabernae',
		genp: 'tabernarum',
		dats: 'tabernae',
		datp: 'tabernis',
		accs: 'tabernam',
		accp: 'tabernas',
		vocs: 'taberna',
		vocp: 'tabernae',
		abls: 'taberna',
		ablp: 'tabernis',
	},
	{
		word: 'taceo, tacere, tacui, tacitus',
		category: 10,
		translation: 'be silent, be quiet',
		asked: false,
	},
	{
		word: 'talis, tale',
		category: 23,
		translation: 'such',
		asked: false,
	},
	{
		word: 'tam (indecl.)',
		category: 20,
		translation: 'so',
		asked: false,
	},
	{
		word: 'tamen (indecl.)',
		category: 7,
		translation: 'however',
		asked: false,
	},
	{
		word: 'tandem (indecl.)',
		category: 12,
		translation: 'at last, finally',
		asked: false,
	},
	{
		word: 'tantus, tanta, tantum',
		category: 27,
		translation: 'so great, such a great, so much',
		asked: false,
	},
	{
		word: 'templum, templi, n.',
		category: 12,
		translation: 'temple',
		asked: false,
		noms: 'templum',
		nomp: 'templa',
		gens: 'templi',
		genp: 'templorum',
		dats: 'templo',
		datp: 'templis',
		accs: 'templum',
		accp: 'templa',
		vocs: 'templum',
		vocp: 'templa',
		abls: 'templo',
		ablp: 'templis',
	},
	{
		word: 'tempus, temporis, n.',
		category: 'other',
		translation: 'time',
		asked: false,
		noms: 'tempus',
		nomp: 'tempora',
		gens: 'temporis',
		genp: 'temporum',
		dats: 'tempori',
		datp: 'temporibus',
		accs: 'tempus',
		accp: 'tempora',
		vocs: 'tempus',
		vocp: 'tempora',
		abls: 'tempore',
		ablp: 'temporibus',
	},
	{
		word: 'teneo, tenere, tenui, tentus',
		category: 15,
		translation: 'hold, keep, possess',
		asked: false,
	},
	{
		word: 'terra, terrae, f.',
		category: 12,
		translation: 'ground, land',
		asked: false,
		noms: 'terra',
		nomp: 'terrae',
		gens: 'terrae',
		genp: 'terrarum',
		dats: 'terrae',
		datp: 'terris',
		accs: 'terram',
		accp: 'terras',
		vocs: 'terra',
		vocp: 'terrae',
		abls: 'terra',
		ablp: 'terris',
	},
	{
		word: 'terreo, terrere, terrui, territus',
		category: 7,
		translation: 'frighten',
		asked: false,
	},
	{
		word: 'timeo, timere, timui',
		category: 12,
		translation: 'fear, be afraid',
		asked: false,
	},
	{
		word: 'tollo, tollere, sustuli, sublatus',
		category: 16,
		translation: 'raise, lift up',
		asked: false,
	},
	{
		word: 'tot (indecl.)',
		category: 19,
		translation: 'so many',
		asked: false,
	},
	{
		word: 'totus, tota, totum',
		category: 8,
		translation: 'whole',
		asked: false,
	},
	{
		word: 'trado, tradere, tradidi, traditus',
		category: 9,
		translation: 'hand over',
		asked: false,
	},
	{
		word: 'traho, trahere, traxi, tractus',
		category: 13,
		translation: 'drag, draw, pull',
		asked: false,
	},
	{
		word: 'trans + acc (also used as prefix with verbs)',
		category: 'other',
		translation: 'across',
		asked: false,
	},
	{
		word: 'tres, tria',
		category: 12,
		translation: 'three',
		asked: false,
	},
	{
		word: 'tristis, triste',
		category: 24,
		translation: 'sad',
		asked: false,
	},
	{
		word: 'tu, tui',
		category: 4,
		translation: 'you (singular)',
		asked: false,
	},
	{
		word: 'tum (indecl.)',
		category: 6,
		translation: 'then',
		asked: false,
	},
	{
		word: 'turba, turbae, f.',
		category: 5,
		translation: 'crowd',
		asked: false,
		noms: 'turba',
		nomp: 'turbae',
		gens: 'turbae',
		genp: 'turbarum',
		dats: 'turbae',
		datp: 'turbis',
		accs: 'turbam',
		accp: 'turbas',
		vocs: 'turba',
		vocp: 'turbae',
		abls: 'turba',
		ablp: 'turbis',
	},
	{
		word: 'tutus, tuta, tutum',
		category: 22,
		translation: 'safe',
		asked: false,
	},
	{
		word: 'tuus, tua, tuum',
		category: 6,
		translation: 'your (singular), yours',
		asked: false,
	},
	{
		word: 'ubi (indecl.)',
		category: 5,
		translation: 'where, when, where?',
		asked: false,
	},
	{
		word: 'umquam (indecl.)',
		category: 23,
		translation: 'ever',
		asked: false,
	},
	{
		word: 'unde (indecl.)',
		category: 21,
		translation: 'from where',
		asked: false,
	},
	{
		word: 'unus, una, unum',
		category: 12,
		translation: 'one',
		asked: false,
	},
	{
		word: 'urbs, urbis, f.',
		category: 5,
		translation: 'city',
		asked: false,
		noms: 'urbs',
		nomp: 'urbes',
		gens: 'urbis',
		genp: 'urbium',
		dats: 'urbi',
		datp: 'urbibus',
		accs: 'urbem',
		accp: 'urbes',
		vocs: 'urbs',
		vocp: 'urbes',
		abls: 'urbe',
		ablp: 'urbibus',
	},
	{
		word: 'ut (indecl.) + subjunc.',
		category: 26,
		translation: 'that, so that, in order that',
		asked: false,
	},
	{
		word: 'ut (indecl.) + indic.',
		category: 28,
		translation: 'as',
		asked: false,
	},
	{
		word: 'uxor, uxoris, f.',
		category: 10,
		translation: 'wife',
		asked: false,
		noms: 'uxor',
		nomp: 'uxores',
		gens: 'uxoris',
		genp: 'uxorum',
		dats: 'uxori',
		datp: 'uxoribus',
		accs: 'uxorem',
		accp: 'uxores',
		vocs: 'uxor',
		vocp: 'uxores',
		abls: 'uxore',
		ablp: 'uxoribus',
	},
	{
		word: 'vehementer (indecl.)',
		category: 10,
		translation: 'violently, loudly, strongly',
		asked: false,
	},
	{
		word: 'vendo, vendere, vendidi, venditus',
		category: 6,
		translation: 'sell',
		asked: false,
	},
	{
		word: 'venio, venire, veni',
		category: 5,
		translation: 'come',
		asked: false,
	},
	{
		word: 'verbum, verbi, n.',
		category: 22,
		translation: 'word',
		asked: false,
		noms: 'verbum',
		nomp: 'verba',
		gens: 'verbi',
		genp: 'verborum',
		dats: 'verbo',
		datp: 'verbis',
		accs: 'verbum',
		accp: 'verba',
		vocs: 'verbum',
		vocp: 'verba',
		abls: 'verbo',
		ablp: 'verbis',
	},
	{
		word: 'verus, vera, verum',
		category: 33,
		translation: 'true, real',
		asked: false,
	},
	{
		word: 'vester, vestra, vestrum',
		category: 29,
		translation: 'your (plural), yours',
		asked: false,
	},
	{
		word: 'vestimenta, vestimentorum, n.pl.',
		category: 34,
		translation: 'clothes',
		asked: false,
		noms: 'vestimentum',
		nomp: 'vestimenta',
		gens: 'vestimenti',
		genp: 'vestimentorum',
		dats: 'vestimento',
		datp: 'vestimentis',
		accs: 'vestimentum',
		accp: 'vestimenta',
		vocs: 'vestimentum',
		vocp: 'vestimenta',
		abls: 'vestimento',
		ablp: 'vestimentis',
	},
	{
		word: 'via, viae, f.',
		category: 1,
		translation: 'street, road, way',
		asked: false,
		noms: 'via',
		nomp: 'viae',
		gens: 'viae',
		genp: 'viarum',
		dats: 'viae',
		datp: 'viis',
		accs: 'viam',
		accp: 'vias',
		vocs: 'via',
		vocp: 'viae',
		abls: 'via',
		ablp: 'viis',
	},
	{
		word: 'video, videre, vidi, visus',
		category: 3,
		translation: 'see',
		asked: false,
	},
	{
		word: 'villa, villae, f.',
		category: 'other',
		translation: 'house, country house',
		asked: false,
		noms: 'villa',
		nomp: 'villae',
		gens: 'villae',
		genp: 'villarum',
		dats: 'villae',
		datp: 'villis',
		accs: 'villam',
		accp: 'villas',
		vocs: 'villa',
		vocp: 'villae',
		abls: 'villa',
		ablp: 'villis',
	},
	{
		word: 'vinco, vincere, vici, victus',
		category: 15,
		translation: 'conquer, win, be victorious',
		asked: false,
	},
	{
		word: 'vinum, vini, n.',
		category: 3,
		translation: 'wine',
		asked: false,
		noms: 'vinum',
		nomp: 'vina',
		gens: 'vini',
		genp: 'vinorum',
		dats: 'vino',
		datp: 'vinis',
		accs: 'vinum',
		accp: 'vina',
		vocs: 'vinum',
		vocp: 'vina',
		abls: 'vino',
		ablp: 'vinis',
	},
	{
		word: 'vir, viri, m.',
		category: 11,
		translation: 'man',
		asked: false,
		noms: 'vir',
		nomp: 'viri',
		gens: 'viri',
		genp: 'virorum',
		dats: 'viro',
		datp: 'viris',
		accs: 'virum',
		accp: 'viros',
		vocs: 'viri',
		vocp: 'viri',
		abls: 'viro',
		ablp: 'viris',
	},
	{
		word: 'vita, vitae, f.',
		category: 13,
		translation: 'life',
		asked: false,
		noms: 'vita',
		nomp: 'vitae',
		gens: 'vitae',
		genp: 'vitarum',
		dats: 'vitae',
		datp: 'vitis',
		accs: 'vitam',
		accp: 'vitas',
		vocs: 'vita',
		vocp: 'vitae',
		abls: 'vita',
		ablp: 'vitis',
	},
	{
		word: 'vivo, vivere, vixi',
		category: 19,
		translation: 'live, be alive',
		asked: false,
	},
	{
		word: 'vivus, viva, vivum',
		category: 29,
		translation: 'alive, living',
		asked: false,
	},
	{
		word: 'vix (indecl.)',
		category: 19,
		translation: 'scarcely, hardly, with difficulty',
		asked: false,
	},
	{
		word: 'voco, vocare, vocavi, vocatus',
		category: 4,
		translation: 'call',
		asked: false,
	},
	{
		word: 'volo, velle, volui',
		category: 13,
		translation: 'want',
		asked: false,
	},
	{
		word: 'vos, vestrum',
		category: 10,
		translation: 'you (plural)',
		asked: false,
	},
	{
		word: 'vox, vocis, f.',
		category: 19,
		translation: 'voice, shout',
		asked: false,
	},
	{
		word: 'vulnus, vulneris, n.',
		category: 20,
		translation: 'wound',
		asked: false,
		noms: 'vulnus',
		nomp: 'vulnera',
		gens: 'vulneris',
		genp: 'vulnerum',
		dats: 'vulneri',
		datp: 'vulneribus',
		accs: 'vulnus',
		accp: 'vulnera',
		vocs: 'vulnus',
		vocp: 'vulnera',
		abls: 'vulnere',
		ablp: 'vulneribus',
	},
	{
		word: 'vultus, vultus, m.',
		category: 'other',
		translation: 'expression, face',
		asked: false,
		noms: 'vultus',
		nomp: 'vultus',
		gens: 'vultus',
		genp: 'vultuum',
		dats: 'vultui',
		datp: 'vultibus',
		accs: 'vultum',
		accp: 'vultus',
		vocs: 'vultus',
		vocp: 'vultus',
		abls: 'vultu',
		ablp: 'vultibus',
	},
];
